/* Common English idioms, roughly by familiarity. Same shape as words.js:
   { r:rank, w:idiom, c:Chinese meaning, e:English definition }. */
window.IDIOMS = [
{"r":1,"w":"break the ice","c":"打破僵局，破冰","e":"do or say something to relieve tension and start conversation"},
{"r":2,"w":"a piece of cake","c":"小菜一碟，轻而易举","e":"something very easy to do"},
{"r":3,"w":"under the weather","c":"身体不适","e":"feeling slightly ill"},
{"r":4,"w":"once in a blue moon","c":"千载难逢，难得","e":"very rarely"},
{"r":5,"w":"cost an arm and a leg","c":"价格昂贵","e":"be very expensive"},
{"r":6,"w":"hit the sack","c":"上床睡觉","e":"go to bed"},
{"r":7,"w":"let the cat out of the bag","c":"泄露秘密","e":"reveal a secret carelessly"},
{"r":8,"w":"spill the beans","c":"泄露秘密","e":"reveal secret information"},
{"r":9,"w":"break a leg","c":"祝你好运（演出前）","e":"good luck (said before a performance)"},
{"r":10,"w":"bite the bullet","c":"咬牙忍受，硬着头皮做","e":"force yourself to do something difficult"},
{"r":11,"w":"hit the nail on the head","c":"一针见血，说得正对","e":"describe exactly what is causing a situation"},
{"r":12,"w":"the ball is in your court","c":"该你做决定了","e":"it is now your turn to decide or act"},
{"r":13,"w":"beat around the bush","c":"拐弯抹角","e":"avoid getting to the main point"},
{"r":14,"w":"cut to the chase","c":"直奔主题","e":"get to the point without wasting time"},
{"r":15,"w":"on the same page","c":"看法一致","e":"in agreement; sharing the same understanding"},
{"r":16,"w":"call it a day","c":"收工，到此为止","e":"stop working on something"},
{"r":17,"w":"get out of hand","c":"失控","e":"become impossible to control"},
{"r":18,"w":"pull someone's leg","c":"开玩笑，逗某人","e":"tease or joke with someone"},
{"r":19,"w":"a blessing in disguise","c":"因祸得福","e":"a good thing that at first seemed bad"},
{"r":20,"w":"speak of the devil","c":"说曹操，曹操到","e":"the person we were talking about appears"},
{"r":21,"w":"the last straw","c":"最后一根稻草，忍无可忍","e":"the final problem that makes a situation unbearable"},
{"r":22,"w":"burn the midnight oil","c":"开夜车，熬夜","e":"work or study late into the night"},
{"r":23,"w":"throw in the towel","c":"认输，放弃","e":"give up; admit defeat"},
{"r":24,"w":"miss the boat","c":"错失良机","e":"miss an opportunity"},
{"r":25,"w":"on cloud nine","c":"欣喜若狂","e":"extremely happy"},
{"r":26,"w":"feeling blue","c":"情绪低落","e":"feeling sad or depressed"},
{"r":27,"w":"green with envy","c":"非常嫉妒","e":"very jealous"},
{"r":28,"w":"better late than never","c":"迟做总比不做好","e":"doing something late is better than not at all"},
{"r":29,"w":"actions speak louder than words","c":"行动胜于言辞","e":"what you do matters more than what you say"},
{"r":30,"w":"the best of both worlds","c":"两全其美","e":"an ideal situation combining two advantages"},
{"r":31,"w":"add insult to injury","c":"雪上加霜","e":"make a bad situation worse"},
{"r":32,"w":"barking up the wrong tree","c":"找错对象，弄错方向","e":"pursuing a mistaken line of thought or action"},
{"r":33,"w":"cry over spilt milk","c":"为已发生的事懊悔（无济于事）","e":"be upset about something that cannot be changed"},
{"r":34,"w":"every cloud has a silver lining","c":"黑暗中总有一线光明","e":"there is something good in every bad situation"},
{"r":35,"w":"give the benefit of the doubt","c":"姑且相信","e":"choose to believe someone despite doubts"},
{"r":36,"w":"go back to the drawing board","c":"从头再来","e":"start again after a failed attempt"},
{"r":37,"w":"hang in there","c":"坚持住，挺住","e":"don't give up despite difficulty"},
{"r":38,"w":"hit the books","c":"用功学习","e":"study hard"},
{"r":39,"w":"in hot water","c":"陷入困境，惹上麻烦","e":"in trouble"},
{"r":40,"w":"it's not rocket science","c":"这并不难","e":"it is not complicated or hard to understand"},
{"r":41,"w":"jump on the bandwagon","c":"随大流，赶时髦","e":"join an activity that has become popular"},
{"r":42,"w":"keep an eye on","c":"留意，照看","e":"watch carefully"},
{"r":43,"w":"kill two birds with one stone","c":"一石二鸟","e":"accomplish two things with a single action"},
{"r":44,"w":"leave no stone unturned","c":"想方设法，竭尽全力","e":"try every possible way to achieve something"},
{"r":45,"w":"let sleeping dogs lie","c":"别惹是非，别旧事重提","e":"avoid restarting an old conflict"},
{"r":46,"w":"to make a long story short","c":"长话短说","e":"tell something briefly"},
{"r":47,"w":"no pain, no gain","c":"不劳无获","e":"you must work hard to get results"},
{"r":48,"w":"off the hook","c":"摆脱困境，脱身","e":"no longer in trouble or under obligation"},
{"r":49,"w":"on the ball","c":"机敏，能干","e":"alert and quick to understand"},
{"r":50,"w":"out of the blue","c":"突然，出乎意料","e":"unexpectedly; without warning"},
{"r":51,"w":"pay through the nose","c":"花高价，被宰","e":"pay far too much for something"},
{"r":52,"w":"pull yourself together","c":"振作起来","e":"regain control of your emotions"},
{"r":53,"w":"rain on someone's parade","c":"扫兴，泼冷水","e":"spoil someone's plans or happiness"},
{"r":54,"w":"see eye to eye","c":"看法一致","e":"agree completely with someone"},
{"r":55,"w":"sit on the fence","c":"持观望态度，骑墙","e":"avoid making a decision"},
{"r":56,"w":"take it with a grain of salt","c":"半信半疑","e":"don't fully believe something"},
{"r":57,"w":"the tip of the iceberg","c":"冰山一角","e":"a small visible part of a much bigger problem"},
{"r":58,"w":"time flies","c":"光阴似箭","e":"time passes very quickly"},
{"r":59,"w":"up in the air","c":"悬而未决","e":"uncertain; not yet decided"},
{"r":60,"w":"when pigs fly","c":"绝不可能","e":"something that will never happen"},
{"r":61,"w":"you can say that again","c":"你说得太对了","e":"I completely agree"},
{"r":62,"w":"a dime a dozen","c":"多得很，不值钱","e":"very common and of little value"},
{"r":63,"w":"back to square one","c":"回到原点","e":"back to the very beginning"},
{"r":64,"w":"bend over backwards","c":"竭尽全力（帮忙）","e":"try very hard to help someone"},
{"r":65,"w":"blow off steam","c":"发泄情绪","e":"release anger or stress"},
{"r":66,"w":"by the skin of your teeth","c":"侥幸，险些","e":"only just; barely succeed"},
{"r":67,"w":"cut corners","c":"偷工减料，走捷径","e":"do something cheaply or carelessly to save effort"},
{"r":68,"w":"down to earth","c":"脚踏实地，务实","e":"practical and sensible"},
{"r":69,"w":"drive someone up the wall","c":"让某人抓狂","e":"annoy someone greatly"},
{"r":70,"w":"face the music","c":"承担后果","e":"accept the unpleasant consequences"},
{"r":71,"w":"get cold feet","c":"临阵退缩，胆怯","e":"become nervous and hesitant before an event"},
{"r":72,"w":"give someone a hand","c":"帮某人一把","e":"help someone"},
{"r":73,"w":"go the extra mile","c":"加倍努力","e":"make more effort than expected"},
{"r":74,"w":"hit the road","c":"出发，上路","e":"leave; begin a journey"},
{"r":75,"w":"in the same boat","c":"处境相同","e":"in the same difficult situation as others"},
{"r":76,"w":"jump the gun","c":"操之过急，抢先行动","e":"act too soon, before the right time"},
{"r":77,"w":"keep your chin up","c":"振作，别灰心","e":"stay cheerful in a difficult situation"},
{"r":78,"w":"on thin ice","c":"如履薄冰，处境危险","e":"in a risky or precarious situation"},
{"r":79,"w":"play it by ear","c":"见机行事，随机应变","e":"decide as you go rather than planning"},
{"r":80,"w":"pull strings","c":"走后门，动用关系","e":"use influence or connections to get something"},
{"r":81,"w":"put all your eggs in one basket","c":"孤注一掷","e":"risk everything on a single plan"},
{"r":82,"w":"raining cats and dogs","c":"倾盆大雨","e":"raining very heavily"},
{"r":83,"w":"read between the lines","c":"体会言外之意","e":"understand a hidden or implied meaning"},
{"r":84,"w":"ring a bell","c":"似曾相识，有点印象","e":"sound familiar"},
{"r":85,"w":"rule of thumb","c":"经验法则","e":"a practical, approximate guideline"},
{"r":86,"w":"so far so good","c":"目前为止还不错","e":"things are going well up to now"},
{"r":87,"w":"steal someone's thunder","c":"抢风头","e":"take attention or credit away from someone"},
{"r":88,"w":"take a rain check","c":"改天再约","e":"politely decline now but accept for a later time"},
{"r":89,"w":"twist someone's arm","c":"强迫/说服某人","e":"persuade someone to do something they're reluctant to"},
{"r":90,"w":"wrap your head around","c":"理解，弄懂","e":"manage to understand something difficult"}
];
