/* Common English idioms — curated idiom lists (baiango/english_idioms, ananddtyagi/idioms) matched to ECDICT (skywind3000/ECDICT) Chinese; literal phrases filtered out. { r, w, c:Chinese, e:English meaning }. */
window.IDIOMS = [
{"r": 1, "w": "break the ice", "c": "打破僵局，破冰", "e": "do or say something to relieve tension and start conversation"},
{"r": 2, "w": "a piece of cake", "c": "小菜一碟，轻而易举", "e": "something very easy to do"},
{"r": 3, "w": "under the weather", "c": "身体不适", "e": "feeling slightly ill"},
{"r": 4, "w": "once in a blue moon", "c": "千载难逢，难得", "e": "very rarely"},
{"r": 5, "w": "cost an arm and a leg", "c": "价格昂贵", "e": "be very expensive"},
{"r": 6, "w": "hit the sack", "c": "上床睡觉", "e": "go to bed"},
{"r": 7, "w": "let the cat out of the bag", "c": "泄露秘密", "e": "reveal a secret carelessly"},
{"r": 8, "w": "spill the beans", "c": "泄露秘密", "e": "reveal secret information"},
{"r": 9, "w": "break a leg", "c": "祝你好运（演出前）", "e": "good luck (said before a performance)"},
{"r": 10, "w": "bite the bullet", "c": "咬牙忍受，硬着头皮做", "e": "force yourself to do something difficult"},
{"r": 11, "w": "hit the nail on the head", "c": "一针见血，说得正对", "e": "describe exactly what is causing a situation"},
{"r": 12, "w": "the ball is in your court", "c": "该你做决定了", "e": "it is now your turn to decide or act"},
{"r": 13, "w": "beat around the bush", "c": "拐弯抹角", "e": "avoid getting to the main point"},
{"r": 14, "w": "cut to the chase", "c": "直奔主题", "e": "get to the point without wasting time"},
{"r": 15, "w": "on the same page", "c": "看法一致", "e": "in agreement; sharing the same understanding"},
{"r": 16, "w": "call it a day", "c": "收工，到此为止", "e": "stop working on something"},
{"r": 17, "w": "get out of hand", "c": "失控", "e": "become impossible to control"},
{"r": 18, "w": "pull someone's leg", "c": "开玩笑，逗某人", "e": "tease or joke with someone"},
{"r": 19, "w": "a blessing in disguise", "c": "因祸得福", "e": "a good thing that at first seemed bad"},
{"r": 20, "w": "speak of the devil", "c": "说曹操，曹操到", "e": "the person we were talking about appears"},
{"r": 21, "w": "the last straw", "c": "最后一根稻草，忍无可忍", "e": "the final problem that makes a situation unbearable"},
{"r": 22, "w": "burn the midnight oil", "c": "开夜车，熬夜", "e": "work or study late into the night"},
{"r": 23, "w": "throw in the towel", "c": "认输，放弃", "e": "give up; admit defeat"},
{"r": 24, "w": "miss the boat", "c": "错失良机", "e": "miss an opportunity"},
{"r": 25, "w": "on cloud nine", "c": "欣喜若狂", "e": "extremely happy"},
{"r": 26, "w": "feeling blue", "c": "情绪低落", "e": "feeling sad or depressed"},
{"r": 27, "w": "green with envy", "c": "非常嫉妒", "e": "very jealous"},
{"r": 28, "w": "better late than never", "c": "迟做总比不做好", "e": "doing something late is better than not at all"},
{"r": 29, "w": "actions speak louder than words", "c": "行动胜于言辞", "e": "what you do matters more than what you say"},
{"r": 30, "w": "the best of both worlds", "c": "两全其美", "e": "an ideal situation combining two advantages"},
{"r": 31, "w": "add insult to injury", "c": "雪上加霜", "e": "make a bad situation worse"},
{"r": 32, "w": "barking up the wrong tree", "c": "找错对象，弄错方向", "e": "pursuing a mistaken line of thought or action"},
{"r": 33, "w": "cry over spilt milk", "c": "为已发生的事懊悔（无济于事）", "e": "be upset about something that cannot be changed"},
{"r": 34, "w": "every cloud has a silver lining", "c": "黑暗中总有一线光明", "e": "there is something good in every bad situation"},
{"r": 35, "w": "give the benefit of the doubt", "c": "姑且相信", "e": "choose to believe someone despite doubts"},
{"r": 36, "w": "go back to the drawing board", "c": "从头再来", "e": "start again after a failed attempt"},
{"r": 37, "w": "hang in there", "c": "坚持住，挺住", "e": "don't give up despite difficulty"},
{"r": 38, "w": "hit the books", "c": "用功学习", "e": "study hard"},
{"r": 39, "w": "in hot water", "c": "陷入困境，惹上麻烦", "e": "in trouble"},
{"r": 40, "w": "it's not rocket science", "c": "这并不难", "e": "it is not complicated or hard to understand"},
{"r": 41, "w": "jump on the bandwagon", "c": "随大流，赶时髦", "e": "join an activity that has become popular"},
{"r": 42, "w": "keep an eye on", "c": "留意，照看", "e": "watch carefully"},
{"r": 43, "w": "kill two birds with one stone", "c": "一石二鸟", "e": "accomplish two things with a single action"},
{"r": 44, "w": "leave no stone unturned", "c": "想方设法，竭尽全力", "e": "try every possible way to achieve something"},
{"r": 45, "w": "let sleeping dogs lie", "c": "别惹是非，别旧事重提", "e": "avoid restarting an old conflict"},
{"r": 46, "w": "to make a long story short", "c": "长话短说", "e": "tell something briefly"},
{"r": 47, "w": "no pain, no gain", "c": "不劳无获", "e": "you must work hard to get results"},
{"r": 48, "w": "off the hook", "c": "摆脱困境，脱身", "e": "no longer in trouble or under obligation"},
{"r": 49, "w": "on the ball", "c": "机敏，能干", "e": "alert and quick to understand"},
{"r": 50, "w": "out of the blue", "c": "突然，出乎意料", "e": "unexpectedly; without warning"},
{"r": 51, "w": "pay through the nose", "c": "花高价，被宰", "e": "pay far too much for something"},
{"r": 52, "w": "pull yourself together", "c": "振作起来", "e": "regain control of your emotions"},
{"r": 53, "w": "rain on someone's parade", "c": "扫兴，泼冷水", "e": "spoil someone's plans or happiness"},
{"r": 54, "w": "see eye to eye", "c": "看法一致", "e": "agree completely with someone"},
{"r": 55, "w": "sit on the fence", "c": "持观望态度，骑墙", "e": "avoid making a decision"},
{"r": 56, "w": "take it with a grain of salt", "c": "半信半疑", "e": "don't fully believe something"},
{"r": 57, "w": "the tip of the iceberg", "c": "冰山一角", "e": "a small visible part of a much bigger problem"},
{"r": 58, "w": "time flies", "c": "光阴似箭", "e": "time passes very quickly"},
{"r": 59, "w": "up in the air", "c": "悬而未决", "e": "uncertain; not yet decided"},
{"r": 60, "w": "when pigs fly", "c": "绝不可能", "e": "something that will never happen"},
{"r": 61, "w": "you can say that again", "c": "你说得太对了", "e": "I completely agree"},
{"r": 62, "w": "a dime a dozen", "c": "多得很，不值钱", "e": "very common and of little value"},
{"r": 63, "w": "back to square one", "c": "回到原点", "e": "back to the very beginning"},
{"r": 64, "w": "bend over backwards", "c": "竭尽全力（帮忙）", "e": "try very hard to help someone"},
{"r": 65, "w": "blow off steam", "c": "发泄情绪", "e": "release anger or stress"},
{"r": 66, "w": "by the skin of your teeth", "c": "侥幸，险些", "e": "only just; barely succeed"},
{"r": 67, "w": "cut corners", "c": "偷工减料，走捷径", "e": "do something cheaply or carelessly to save effort"},
{"r": 68, "w": "down to earth", "c": "脚踏实地，务实", "e": "practical and sensible"},
{"r": 69, "w": "drive someone up the wall", "c": "让某人抓狂", "e": "annoy someone greatly"},
{"r": 70, "w": "face the music", "c": "承担后果", "e": "accept the unpleasant consequences"},
{"r": 71, "w": "get cold feet", "c": "临阵退缩，胆怯", "e": "become nervous and hesitant before an event"},
{"r": 72, "w": "give someone a hand", "c": "帮某人一把", "e": "help someone"},
{"r": 73, "w": "go the extra mile", "c": "加倍努力", "e": "make more effort than expected"},
{"r": 74, "w": "hit the road", "c": "出发，上路", "e": "leave; begin a journey"},
{"r": 75, "w": "in the same boat", "c": "处境相同", "e": "in the same difficult situation as others"},
{"r": 76, "w": "jump the gun", "c": "操之过急，抢先行动", "e": "act too soon, before the right time"},
{"r": 77, "w": "keep your chin up", "c": "振作，别灰心", "e": "stay cheerful in a difficult situation"},
{"r": 78, "w": "on thin ice", "c": "如履薄冰，处境危险", "e": "in a risky or precarious situation"},
{"r": 79, "w": "play it by ear", "c": "见机行事，随机应变", "e": "decide as you go rather than planning"},
{"r": 80, "w": "pull strings", "c": "走后门，动用关系", "e": "use influence or connections to get something"},
{"r": 81, "w": "put all your eggs in one basket", "c": "孤注一掷", "e": "risk everything on a single plan"},
{"r": 82, "w": "raining cats and dogs", "c": "倾盆大雨", "e": "raining very heavily"},
{"r": 83, "w": "read between the lines", "c": "体会言外之意", "e": "understand a hidden or implied meaning"},
{"r": 84, "w": "ring a bell", "c": "似曾相识，有点印象", "e": "sound familiar"},
{"r": 85, "w": "rule of thumb", "c": "经验法则", "e": "a practical, approximate guideline"},
{"r": 86, "w": "so far so good", "c": "目前为止还不错", "e": "things are going well up to now"},
{"r": 87, "w": "steal someone's thunder", "c": "抢风头", "e": "take attention or credit away from someone"},
{"r": 88, "w": "take a rain check", "c": "改天再约", "e": "politely decline now but accept for a later time"},
{"r": 89, "w": "twist someone's arm", "c": "强迫/说服某人", "e": "persuade someone to do something they're reluctant to"},
{"r": 90, "w": "wrap your head around", "c": "理解，弄懂", "e": "manage to understand something difficult"},
{"r": 91, "w": "out of this world", "c": "十全十美的, 极其动人的, 无比优秀的, 无比精彩的", "e": "Extraordinary."},
{"r": 92, "w": "bring the house down", "c": "博得满堂喝彩", "e": "Receive a loud applause."},
{"r": 93, "w": "high five", "c": "（尤指庆祝成功、表示致意等的）举手击掌", "e": "Slapping palms above each others heads as celebration gesture."},
{"r": 94, "w": "live and let live", "c": "自己活也让别人活, 待人宽容", "e": "Accept others' choices."},
{"r": 95, "w": "all set", "c": "一切准备就绪", "e": "Completely ready."},
{"r": 96, "w": "an eye for an eye", "c": "以眼还眼, 报复", "e": "Revenge."},
{"r": 97, "w": "by the book", "c": "按常规", "e": "Follow rules exactly."},
{"r": 98, "w": "few and far between", "c": "稀少", "e": "Rare."},
{"r": 99, "w": "around the world", "c": "全世界,遍及全世界,世界各地", "e": "Travel to various places."},
{"r": 100, "w": "carry the can", "c": "代人受过", "e": "Take responsibility."},
{"r": 101, "w": "last but not least", "c": "最后但并不是最不重要的(一点)", "e": "Last person is important."},
{"r": 102, "w": "open the door to", "c": "给...以机会, 导致...", "e": "Allow access or opportunity."},
{"r": 103, "w": "clear the air", "c": "使空气清新, 澄清事实, 消除误会", "e": "Remove misunderstanding."},
{"r": 104, "w": "draw the line", "c": "划一界线, 划定最后界限", "e": "Set a limit."},
{"r": 105, "w": "out on the town", "c": "寻欢作乐", "e": "To enjoy yourself by going out."},
{"r": 106, "w": "field day", "c": "野外实习日, 户外集会, 体育比赛日", "e": "An enjoyable day."},
{"r": 107, "w": "change of heart", "c": "变心", "e": "Change opinion."},
{"r": 108, "w": "break new ground", "c": "开创新局面", "e": "Do something innovative."},
{"r": 109, "w": "break the bank", "c": "耗尽资源", "e": "Be very expensive."},
{"r": 110, "w": "make a long story short", "c": "长话短说, 简而言之", "e": "Summarize."},
{"r": 111, "w": "red light", "c": "红灯, 危险信号", "e": "Stop or warning."},
{"r": 112, "w": "close the door on", "c": "拒之门外", "e": "End or refuse to consider."},
{"r": 113, "w": "party animal", "c": "超级爱玩的人", "e": "Enthusiastic partier."},
{"r": 114, "w": "get up on the wrong side of the bed", "c": "心情不佳", "e": "Someone who is having a horrible day."},
{"r": 115, "w": "on top of the world", "c": "幸福到极点, 处于最佳地位, 声名显赫", "e": "Feeling euphoric."},
{"r": 116, "w": "top of the line", "c": "极品", "e": "The best quality."},
{"r": 117, "w": "over the top", "c": "过火的， 不得当的", "e": "Very excessive."},
{"r": 118, "w": "achieve the goal", "c": "达到目的", "e": "Successfully attain the objective."},
{"r": 119, "w": "own goal", "c": "误中本队球门, 影响本身利益的错误行为; 乌龙球", "e": "To do something accidentally negative against yourself."},
{"r": 120, "w": "food for thought", "c": "值得思索的问题,耐人寻味的道理", "e": "Something to think about."},
{"r": 121, "w": "race against time", "c": "和时间赛跑,争分夺秒", "e": "Hurry to meet a deadline."},
{"r": 122, "w": "be in hot water", "c": "陷入困境", "e": "In trouble."},
{"r": 123, "w": "a cut above", "c": "高于...一等, 胜于", "e": "Better than others."},
{"r": 124, "w": "above board", "c": "公开地, 光明正大地", "e": "Honest and open."},
{"r": 125, "w": "make a scene", "c": "当众大吵一场", "e": "Cause a public disturbance."},
{"r": 126, "w": "black and blue", "c": "青肿的, 淤血的", "e": "Bruised."},
{"r": 127, "w": "an arm and a leg", "c": "代价昂贵的,贵得出奇,高昂的代价", "e": "Very expensive."},
{"r": 128, "w": "for a song", "c": "非常便宜地", "e": "Very cheaply."},
{"r": 129, "w": "dark horse", "c": "实力难测的竞争者,出人意料的获胜者", "e": "An unexpected winner."},
{"r": 130, "w": "rise with the sun", "c": "早起", "e": "Wake up early."},
{"r": 131, "w": "set in stone", "c": "一成不变", "e": "Unchangeable."},
{"r": 132, "w": "for good measure", "c": "作为额外增添, 另外", "e": "In addition."},
{"r": 133, "w": "green light", "c": "绿灯, 放行, 准许", "e": "Approval to proceed."},
{"r": 134, "w": "green room", "c": "演员化妆室", "e": "The waiting room especially for those who are about to go on a tv."},
{"r": 135, "w": "be on the ball", "c": "在精力充沛地行动, 知情, 内行", "e": "Be alert."},
{"r": 136, "w": "fly high", "c": "有雄心大志, 情绪高涨", "e": "Achieve great success."},
{"r": 137, "w": "like a fish out of water", "c": "如鱼出水,不适应环境,感到生疏", "e": "Uncomfortable."},
{"r": 138, "w": "give someone the cold shoulder", "c": "冷落某人,怠慢某人,躲避某人", "e": "Ignore someone."},
{"r": 139, "w": "cold shoulder", "c": "冷淡", "e": "Ignore."},
{"r": 140, "w": "in the bag", "c": "稳操胜券的, 十拿九稳的, 喝醉了的", "e": "To have something secured."},
{"r": 141, "w": "a shot in the dark", "c": "放黑枪;胡乱的猜测,瞎猜", "e": "Wild Guess"},
{"r": 142, "w": "a bird in the hand", "c": "到手的东西,定局的事情", "e": "Something certain."},
{"r": 143, "w": "second to none", "c": "首屈一指", "e": "The best"},
{"r": 144, "w": "get wind of", "c": "得到...的风声", "e": "Hear about."},
{"r": 145, "w": "hit the target", "c": "射中靶子", "e": "Achieve a specific goal or objective."},
{"r": 146, "w": "on target", "c": "击中要害的, 准确的：完全准确的、精确的或有效的", "e": "Accurate or focused."},
{"r": 147, "w": "fast food", "c": "速食; 快餐", "e": "Quick meal."},
{"r": 148, "w": "sleep on it", "c": "把问题留到第二天解决", "e": "Delay a decision until the next day."},
{"r": 149, "w": "bird brain", "c": "轻浮无知者,笨蛋", "e": "a person that is not too smart."},
{"r": 150, "w": "back seat driver", "c": "幕后指挥,喧宾夺主者,多管闲事的人", "e": "People who criticize from the sidelines much like someone giving unwanted advice from the back seat of a vehicle to the driver."},
{"r": 151, "w": "hit the spot", "c": "满口要求, 合口味", "e": "To be particularly pleasing."},
{"r": 152, "w": "cut no ice", "c": "不起作用, 无效", "e": "Fail to impress."},
{"r": 153, "w": "rock the boat", "c": "捣乱", "e": "Say something that will cause problems."},
{"r": 154, "w": "drink like a fish", "c": "大喝", "e": "To drink very heavily."},
{"r": 155, "w": "fly off the handle", "c": "冒火, 勃然大怒", "e": "Angry outburst."},
{"r": 156, "w": "rock and roll", "c": "摇滚乐", "e": "Live life with excitement and enthusiasm."},
{"r": 157, "w": "miss the mark", "c": "没打中目标, 没达到目的", "e": "Fail to achieve."},
{"r": 158, "w": "take flight", "c": "出奔；逃走；逃跑", "e": "Begin a journey or adventure."},
{"r": 159, "w": "bright and early", "c": "大清早", "e": "Early in the morning."},
{"r": 160, "w": "jump ship", "c": "弃船潜逃", "e": "Leave a activity suddenly."},
{"r": 161, "w": "look a gift horse in the mouth", "c": "对礼物吹毛求疵,过分挑剔礼物", "e": "To find fault with something that has been received as a gift."},
{"r": 162, "w": "blow hot and cold", "c": "摇摆不定", "e": "Be inconsistent."},
{"r": 163, "w": "water under the bridge", "c": "无法改变的事", "e": "Past and forgotten."},
{"r": 164, "w": "come hell or high water", "c": "不论有什么困难", "e": "No matter what."},
{"r": 165, "w": "as right as rain", "c": "非常健康", "e": "Perfectly fine."},
{"r": 166, "w": "right as rain", "c": "非常健康, 十分准确", "e": "Needed."},
{"r": 167, "w": "come full circle", "c": "兜了个圈回到原地", "e": "Return to start."},
{"r": 168, "w": "bottom line", "c": "概要, 账本底线", "e": "Essential point."},
{"r": 169, "w": "the bottom line", "c": "概要, 账本底线", "e": "The most important point."},
{"r": 170, "w": "come clean", "c": "全盘招供", "e": "Confess."},
{"r": 171, "w": "chicken out", "c": "临阵退缩", "e": "Withdraw due to fear."},
{"r": 172, "w": "paint the town red", "c": "狂欢庆祝, 饮酒作乐", "e": "Enjoy oneself extravagantly."},
{"r": 173, "w": "keep a straight face", "c": "板着脸", "e": "Hide emotion."},
{"r": 174, "w": "keep body and soul together", "c": "仅能维持生活", "e": "To earn a sufficient amount of money in order to keep yourself alive ."},
{"r": 175, "w": "feel under the weather", "c": "不舒服, 有点小病, 微恙, 不愉快", "e": "Feel ill."},
{"r": 176, "w": "feeling under the weather", "c": "不舒服, 有点小病, 微恙, 不愉快", "e": "Feeling ill."},
{"r": 177, "w": "weather the storm", "c": "战胜风暴,安然度过暴风雨", "e": "Endure difficulties."},
{"r": 178, "w": "a perfect storm", "c": "祸不单行；屋漏偏逢连夜雨", "e": "the worst possible situation"},
{"r": 179, "w": "through thick and thin", "c": "不畏艰险", "e": "In all situations."},
{"r": 180, "w": "sick as a dog", "c": "病得十分严重", "e": "To be very sick."},
{"r": 181, "w": "long in the tooth", "c": "年纪大, 老", "e": "Old people."},
{"r": 182, "w": "go with the flow", "c": "（非正式）顺应潮流，随波逐流，随大溜", "e": "Follow the majority."},
{"r": 183, "w": "steal the show", "c": "抢出风头", "e": "Be the center of attention."},
{"r": 184, "w": "a drop in the ocean", "c": "沧海一粟,九牛一毛,微不足道", "e": "A very small part of something much larger."},
{"r": 185, "w": "come out in the wash", "c": "暴露, 真相大白", "e": "Become known."},
{"r": 186, "w": "at the drop of a hat", "c": "一发出信号就…,立刻,毫不迟疑地", "e": "Immediately."},
{"r": 187, "w": "top hat", "c": "高顶黑色大礼帽", "e": "Formal attire."},
{"r": 188, "w": "break bread", "c": "共餐", "e": "Share a meal."},
{"r": 189, "w": "round the bend", "c": "有精神病的, 疯的", "e": "Crazy."},
{"r": 190, "w": "desert island", "c": "荒岛", "e": "Isolated place."},
{"r": 191, "w": "kick the habit", "c": "戒除嗜好", "e": "Stop engaging in a habitual practice."},
{"r": 192, "w": "a hot potato", "c": "棘手的问题", "e": "Controversial issue."},
{"r": 193, "w": "french kiss", "c": "法国式接吻", "e": "An open mouth kiss where tongues touch."},
{"r": 194, "w": "piece of cake", "c": "小菜一碟; 非常容易的事", "e": "Easy."},
{"r": 195, "w": "take the cake", "c": "成为最佳者, 得奖", "e": "To be especially good."},
{"r": 196, "w": "down to the wire", "c": "直到终点,直到最后期限;濒于破产", "e": "Last minute."},
{"r": 197, "w": "butter someone up", "c": "巴结, 讨好", "e": "Flatter for a favor."},
{"r": 198, "w": "pipe down", "c": "吹哨子通知下班, 停止说话, 安静下来, 不过于自信", "e": "To shut-up."},
{"r": 199, "w": "red flag", "c": "红旗", "e": "A warning sign of a problem."},
{"r": 200, "w": "over the moon", "c": "兴高采烈", "e": "Extremely happy."},
{"r": 201, "w": "cry for the moon", "c": "想做做不到的事", "e": "Desire the unattainable."},
{"r": 202, "w": "blue moon", "c": "不可能或稀有的时期或事情", "e": "A rare event."},
{"r": 203, "w": "no room to swing a cat", "c": "没有活动余地,地方狭小", "e": "An unusually small space."},
{"r": 204, "w": "pass the buck", "c": "推卸责任,推委", "e": "Avoid responsibility by giving it to someone else."},
{"r": 205, "w": "against the clock", "c": "抢在某一时刻之前", "e": "Rushed."},
{"r": 206, "w": "shoot from the hip", "c": "鲁莽地做事", "e": "Speak without thinking."},
{"r": 207, "w": "hit the ceiling", "c": "勃然大怒", "e": "To become enraged."},
{"r": 208, "w": "on the fence", "c": "抱观望态度, 保持中立", "e": "Undecided."},
{"r": 209, "w": "turn a blind eye", "c": "熟视无睹：拒绝正视, 装作没看见", "e": "Ignore something."},
{"r": 210, "w": "cheap as dirt", "c": "便宜极了,奇贱", "e": "Very inexpensive."},
{"r": 211, "w": "run out of steam", "c": "耗尽力气,精疲力竭;减慢速度,慢下来", "e": "Lose energy."},
{"r": 212, "w": "full steam ahead", "c": "开足马力,加油,全速前进", "e": "Proceeding with maximum effort and determination."},
{"r": 213, "w": "in the nick of time", "c": "恰好", "e": "Just in time."},
{"r": 214, "w": "sink or swim", "c": "不管成败如何, 沉浮全看自己", "e": "Fail or succeed."},
{"r": 215, "w": "at a loose end", "c": "闲着", "e": "Nothing specific to do."},
{"r": 216, "w": "rub off", "c": "擦掉, 使减色", "e": "Influence"},
{"r": 217, "w": "sail through", "c": "轻快地走过", "e": "Easily complete a task."},
{"r": 218, "w": "in the middle of nowhere", "c": "在偏僻的地方", "e": "A remote location."},
{"r": 219, "w": "crack someone up", "c": "吹捧某人", "e": "To make someone laugh."},
{"r": 220, "w": "pig out", "c": "狼吞虎咽, 大吃特吃", "e": "To eat alot and eat it quickly."},
{"r": 221, "w": "put pen to paper", "c": "落笔", "e": "Start writing or creating something."},
{"r": 222, "w": "flesh and blood", "c": "肉体, 情欲, 人类, 现实", "e": "Family or human nature."},
{"r": 223, "w": "hat trick", "c": "（板球）连中三柱, 使对方三击球手退场", "e": "When one player scores three goals in the same game."},
{"r": 224, "w": "smell a rat", "c": "感到不妙", "e": "To detect somone in the group is betraying the others."},
{"r": 225, "w": "bite the dust", "c": "大败", "e": "Fail or die."},
{"r": 226, "w": "a tough nut to crack", "c": "棘手的问题,难以对付的人", "e": "Hard to understand."},
{"r": 227, "w": "an old flame", "c": "旧情人", "e": "A past lover."},
{"r": 228, "w": "against the grain", "c": "格格不入", "e": "Contrary to norms."},
{"r": 229, "w": "cold turkey", "c": "突然完全停止使用毒品", "e": "Abrupt stop."},
{"r": 230, "w": "born on the wrong side of the blanket", "c": "私生的", "e": "Illegitimate birth."},
{"r": 231, "w": "cut from the same cloth", "c": "一路货", "e": "Very similar."},
{"r": 232, "w": "come rain or shine", "c": "风雨无阻, 不管发生什么情况", "e": "No matter what."},
{"r": 233, "w": "couch potato", "c": "花大量时间看电视的人, 电视迷; 美国人说整天看电视的人是“沙发土豆”", "e": "A lazy person."},
{"r": 234, "w": "sleep like a log", "c": "熟睡", "e": "Sleep soundly."},
{"r": 235, "w": "a leap in the dark", "c": "冒险的行动", "e": "A risky action."},
{"r": 236, "w": "look before you leap", "c": "三思而后行", "e": "Take only calculated risks"},
{"r": 237, "w": "a snake in the grass", "c": "潜伏的危险", "e": "Deceitful person."},
{"r": 238, "w": "as clear as mud", "c": "毫不清楚,令人迷惑不解", "e": "Confusing."},
{"r": 239, "w": "between the devil and the deep blue sea", "c": "进退两难,进退维谷,处于困境", "e": "In a dilemma."},
{"r": 240, "w": "fight tooth and nail", "c": "猛烈作战", "e": "Fight fiercely."},
{"r": 241, "w": "out on a limb", "c": "处于危险的境地, 孤立无援", "e": "When someone puts them self in a risky situation."},
{"r": 242, "w": "sing a different tune", "c": "改变调子, 转变态度", "e": "Change one's attitude."},
{"r": 243, "w": "change the tune", "c": "转变态度", "e": "Alter one's perspective."},
{"r": 244, "w": "call the tune", "c": "定调子, 发号施令, 操纵", "e": "Be in control."},
{"r": 245, "w": "green thumb", "c": "有特殊园艺才能", "e": "A talent for gardening."},
{"r": 246, "w": "nest egg", "c": "养老金, 储备金; 留窝鸡蛋", "e": "Savings set aside for future use."},
{"r": 247, "w": "burning the midnight oil", "c": "开夜车", "e": "Working late."},
{"r": 248, "w": "put the cart before the horse", "c": "前后颠倒,本末倒置", "e": "Do things in the wrong order."},
{"r": 249, "w": "a slap on the wrist", "c": "轻微的处罚", "e": "Minor punishment."},
{"r": 250, "w": "climb the ladder", "c": "上绞架,被处绞刑", "e": "Advance in a career."},
{"r": 251, "w": "cry wolf", "c": "发假警报", "e": "False alarm."},
{"r": 252, "w": "a bull in a china shop", "c": "公牛闯入瓷器店,鲁莽的", "e": "Someone who is very clumsy"},
{"r": 253, "w": "night owl", "c": "猫头鹰, 熬夜的人, 深夜不睡的人", "e": "A person who is active and alert during the night."},
{"r": 254, "w": "as busy as a bee", "c": "极忙碌", "e": "Very busy."},
{"r": 255, "w": "shoot the breeze", "c": "吹牛, 闲谈", "e": "To chat idly."},
{"r": 256, "w": "gut feeling", "c": "直觉", "e": "A personal intuition you get especially when feel something may not be right."},
{"r": 257, "w": "get the ball rolling", "c": "开个头,使开始,使展开", "e": "Start something."},
{"r": 258, "w": "last straw", "c": "压垮骆驼的最后一根稻草,导致失败的最后因素,导火线", "e": "Final problem."},
{"r": 259, "w": "draw a blank", "c": "抽空签", "e": "Find nothing."},
{"r": 260, "w": "drawing a blank", "c": "抽空签", "e": "Failing to remember."},
{"r": 261, "w": "pack a punch", "c": "击出兇勐的一拳;措词中肯有力;强劲有力", "e": "Strong effect."},
{"r": 262, "w": "kick the bucket", "c": "死掉", "e": "Die."},
{"r": 263, "w": "a drop in the bucket", "c": "沧海一粟", "e": "A very small part of something big."},
{"r": 264, "w": "a feather in one's cap", "c": "可夸耀的事, 卓越的成就", "e": "A notable achievement."},
{"r": 265, "w": "steer clear of", "c": "避开, 绕开", "e": "Avoid."},
{"r": 266, "w": "chew the fat", "c": "闲谈", "e": "Chat casually."},
{"r": 267, "w": "bite off more than one can chew", "c": "贪多嚼不烂", "e": "To take on more responsibility than one can manage."},
{"r": 268, "w": "start from scratch", "c": "从起跑线开始, 从头开始", "e": "To do it all over again from the beginning."},
{"r": 269, "w": "buy a pig in a poke", "c": "瞎买东西", "e": "Buy without full details."},
{"r": 270, "w": "blast off", "c": "点火起飞", "e": "Begin with great enthusiasm."},
{"r": 271, "w": "trip the light fantastic", "c": "跳舞", "e": "To dance"},
{"r": 272, "w": "ace in the hole", "c": "底牌,王牌,出奇制胜;应急法宝,锦囊妙计", "e": "A hidden advantage."},
{"r": 273, "w": "in a fog", "c": "困惑,迷惘,茫然,如坠五里雾中", "e": "Confused or unclear."},
{"r": 274, "w": "driving a hard bargain", "c": "精打细算,设法尽佔便宜,讨价还价", "e": "Negotiating firmly."},
{"r": 275, "w": "drive a hard bargain", "c": "精打细算,设法尽佔便宜,讨价还价", "e": "Negotiate firmly for a good deal."},
{"r": 276, "w": "all aboard", "c": "请上船(车、飞机)", "e": "Everyone is ready to go or participate."},
{"r": 277, "w": "carry the torch", "c": "开战, 奋斗, 单恋", "e": "Continue a tradition."},
{"r": 278, "w": "stab someone in the back", "c": "在某人背后刺上一刀,暗害某人", "e": "Betray someone close."},
{"r": 279, "w": "pull the plug", "c": "潜入水中", "e": "To stop something. To bring something to an end."},
{"r": 280, "w": "strike a chord", "c": "引起共鸣", "e": "Evoke emotion."},
{"r": 281, "w": "a different kettle of fish", "c": "两码事,另一回事", "e": "Completely different."},
{"r": 282, "w": "sleeping like a log", "c": "熟睡", "e": "Sleeping soundly."},
{"r": 283, "w": "eat humble pie", "c": "忍辱含垢", "e": "Admit error."},
{"r": 284, "w": "beating around the bush", "c": "转弯抹角, 旁敲侧击, 拖延谈及正题", "e": "Avoiding the main topic."},
{"r": 285, "w": "chalk up", "c": "记下, 得到", "e": "Attribute to."},
{"r": 286, "w": "off one's trolley", "c": "丧失理智", "e": "Senile."},
{"r": 287, "w": "bring home the bacon", "c": "成功, 谋生", "e": "Earn money."},
{"r": 288, "w": "cut the mustard", "c": "符合要求", "e": "Reach standard."},
{"r": 289, "w": "foam at the mouth", "c": "口吐泡沫, 非常愤怒", "e": "To be enraged and show it."},
{"r": 290, "w": "hit the hay", "c": "睡觉", "e": "Go to bed."},
{"r": 291, "w": "climbing the ladder", "c": "上绞架,被处绞刑", "e": "Advancing in a career."},
{"r": 292, "w": "no dice", "c": "不行,不成功,运气不佳", "e": "To not agree. To not accept a proposition."},
{"r": 293, "w": "at the eleventh hour", "c": "在最后时刻", "e": "Last moment."},
{"r": 294, "w": "wine and dine", "c": "吃喝", "e": "Enjoy a fancy meal and drinks."},
{"r": 295, "w": "rainy day", "c": "雨天, 穷困的日子", "e": "Financial hardship."},
{"r": 296, "w": "drop a dime", "c": "扔一枚硬币", "e": "Make a telephone call"},
{"r": 297, "w": "taking flight", "c": "出奔；逃走；逃跑", "e": "Beginning a new endeavor."},
{"r": 298, "w": "behind the times", "c": "过时", "e": "Outdated."},
{"r": 299, "w": "high on the hog", "c": "奢侈地,豪华地,养尊处优地", "e": "Living in Luxury."},
{"r": 300, "w": "elbow grease", "c": "使劲地擦磨;耗费体力的工作", "e": "Hard work."},
{"r": 301, "w": "as cool as a cucumber", "c": "极为冷静", "e": "Very calm and composed."},
{"r": 302, "w": "eating crow", "c": "做使自己丢脸的事", "e": "Admitting a mistake."},
{"r": 303, "w": "packing a punch", "c": "击出兇勐的一拳;措词中肯有力;强劲有力", "e": "Having a strong effect."},
{"r": 304, "w": "by hook or by crook", "c": "弯成钩形; 想方设法; 不择手段; 千方百计", "e": "Any means necessary."},
{"r": 305, "w": "call a spade a spade", "c": "直言不讳", "e": "Speak frankly."},
{"r": 306, "w": "fit as a fiddle", "c": "非常健康", "e": "Very healthy."},
{"r": 307, "w": "as fit as a fiddle", "c": "十分健康,精神饱满", "e": "Very healthy."},
{"r": 308, "w": "the pot calling the kettle black", "c": "锅嫌壶黑,五十步笑百步,半斤八两,无自知之明", "e": "Used when someone making an accusation is equally as guilty as those being accused."},
{"r": 309, "w": "off one's rocker", "c": "发疯", "e": "Crazy."},
{"r": 310, "w": "flea market", "c": "跳蚤市场", "e": "A swap meet. A place where people gather to buy and sell inexpensive goods."},
{"r": 311, "w": "hanging by a thread", "c": "千钧一发, 摇摇欲坠", "e": "In a very precarious situation."},
{"r": 312, "w": "notch up", "c": "创造,取得", "e": "Achieve something."},
{"r": 313, "w": "ethnic cleansing", "c": "种族清洗", "e": "Killing of a certain ethnic group on a massive scale."},
{"r": 314, "w": "once bitten twice shy", "c": "一次被咬下次胆小", "e": "You're more cautious when you've been hurt before"},
{"r": 315, "w": "a red herring", "c": "熏鲱, 转移注意力的话题", "e": "Misleading clue."},
{"r": 316, "w": "clam up", "c": "拒不开口", "e": "Stop talking."},
{"r": 317, "w": "go for broke", "c": "全力以赴", "e": "Risk everything."},
{"r": 318, "w": "going for broke", "c": "全力以赴", "e": "Risking everything."},
{"r": 319, "w": "skid row", "c": "城市贫民区,贫民窟", "e": "The rundown area of a city where the homeless and drug users live."},
{"r": 320, "w": "feeding frenzy", "c": "（鲨鱼等鱼群的）疯狂捕食", "e": "An aggressive attack on someone by a group."},
{"r": 321, "w": "backseat driver", "c": "指那些自己不在岗位上，但是却喜欢不断给在位的人提供别人不需要的意见或建议的人。", "e": "Someone who gives unwanted advice."},
{"r": 322, "w": "grasp the nettle", "c": "迎着困难上", "e": "Face a difficulty."},
{"r": 323, "w": "eager beaver", "c": "工作勤奋的人,干活卖力的人,巴结上司的人,野心勃勃者", "e": "Enthusiastic."},
{"r": 324, "w": "killing two birds with one stone", "c": "一箭双雕;一石二鸟", "e": "Solving two problems at once."},
{"r": 325, "w": "for the birds", "c": "荒唐可笑,无聊", "e": "Something that is not worth anything"},
{"r": 326, "w": "in the buff", "c": "用软物擦亮（金属）; 使皮革柔软; 减低（力量）; 减弱 / 作缓冲器, 缓冲", "e": "Nude."},
{"r": 327, "w": "as easy as abc", "c": "极其容易,十分简单", "e": "Very simple."},
{"r": 328, "w": "weathering the storm", "c": "战胜风暴,安然度过暴风雨", "e": "Surviving difficult times."},
{"r": 329, "w": "biting the bullet", "c": "硬着头皮,死撑硬顶", "e": "Enduring a painful experience."},
{"r": 330, "w": "apple of discord", "c": "争端,祸根", "e": "Anything causing trouble."},
{"r": 331, "w": "chewing the fat", "c": "闲谈", "e": "Chatting."},
{"r": 332, "w": "good samaritan", "c": "乐善好施者", "e": "Someone who helps others."},
{"r": 333, "w": "hitting the sack", "c": "就寝", "e": "Going to bed."},
{"r": 334, "w": "hitting the road", "c": "离开", "e": "Leaving or departing."},
{"r": 335, "w": "hitting the target", "c": "射中靶子", "e": "Achieving a goal."},
{"r": 336, "w": "in a nutshell", "c": "简括地说, 一句话", "e": "Briefly."},
{"r": 337, "w": "fly in the ointment", "c": "瑕疵，美中不足：有损大局的情况或细节，缺点", "e": "The one tiny drawback that ruins it."},
{"r": 338, "w": "a storm in a teacup", "c": "小事引起的大风波, 小题大做", "e": "An overreaction."},
{"r": 339, "w": "storm in a teacup", "c": "小事引起的大风波, 小题大做", "e": "Minor issue blown out of proportion."},
{"r": 340, "w": "bury the hatchet", "c": "和解, 停战", "e": "Make peace."},
{"r": 341, "w": "facing the music", "c": "勇于承担责任, 临危不惧", "e": "Accepting consequences."},
{"r": 342, "w": "dyed in the wool", "c": "原毛染色的, 彻底的", "e": "Set in one's ways."},
{"r": 343, "w": "hook line and sinker", "c": "完全地, 全部地", "e": "To be completely fooled by a deception."},
{"r": 344, "w": "come a cropper", "c": "猛摔一交, 遭到惨败", "e": "Fail badly."},
{"r": 345, "w": "bending over backwards", "c": "矫枉过正, 拼命", "e": "Trying very hard."},
{"r": 346, "w": "doggy bag", "c": "狗食袋（餐馆提供的食品袋, 用于顾客带走未吃完的食物）", "e": "A bag to take home leftovers from a restaurant"},
{"r": 347, "w": "alive and kicking", "c": "活蹦乱跳的", "e": "Still active."},
{"r": 348, "w": "kicking the bucket", "c": "死掉", "e": "Dying."},
{"r": 349, "w": "spitting image", "c": "简直一模一样的人", "e": "The exact likeness."},
{"r": 350, "w": "from a to z", "c": "彻底地, 从头到尾", "e": "Covering a complete range."},
{"r": 351, "w": "ignorance is bliss", "c": "无知便是福", "e": "Not knowing is better."},
{"r": 352, "w": "time is money", "c": "时间就是金钱", "e": "Work quickly"},
{"r": 353, "w": "crying over spilt milk", "c": "作无益的后悔", "e": "Regretting the unchangeable."},
{"r": 354, "w": "make a mountain out of a molehill", "c": "夸大其词,大惊小怪,庸人自扰,小题大作", "e": "Make something unimportant into a big deal"},
{"r": 355, "w": "bringing home the bacon", "c": "成功, 谋生", "e": "Earning a living or providing for the family."},
{"r": 356, "w": "a doubting thomas", "c": "怀疑一切的人", "e": "A skeptic who needs personal evidence in order to believe something."},
{"r": 357, "w": "as old as the hills", "c": "极古老", "e": "Very old."},
{"r": 358, "w": "peeping tom", "c": "好偷看的人（特指喜欢偷看裸体女人的好色之徒）", "e": "Someone who observes people in the nude people mainly for his own gratification."},
{"r": 359, "w": "call it quits", "c": "停止", "e": "Stop working or trying."},
{"r": 360, "w": "a little bird told me", "c": "有人私下告诉我,我听说", "e": "I heard something from a secret source."},
{"r": 361, "w": "easier said than done", "c": "说来容易做起来难", "e": "Hard to do."},
{"r": 362, "w": "hold your horses", "c": "不要着急，耐心一点", "e": "Be patient."},
{"r": 363, "w": "all ears", "c": "全神贯注地听", "e": "Listening closely."},
{"r": 364, "w": "roll with the punches", "c": "（拳击手）避让对方打击以减轻受打击的力", "e": "Adapt to challenges."},
{"r": 365, "w": "the early bird catches the worm", "c": "捷足先登;先下手为强", "e": "Early to succeed."},
{"r": 366, "w": "all thumbs", "c": "笨手笨脚的", "e": "Clumsy."},
{"r": 367, "w": "cold feet", "c": "害怕、胆怯", "e": "Nervous."},
{"r": 368, "w": "full of beans", "c": "精神旺盛的, 弄错的", "e": "Energetic."},
{"r": 369, "w": "get down to brass tacks", "c": "讨论重要问题,触及问题实质", "e": "Focus on essentials."},
{"r": 370, "w": "a stone's throw", "c": "短距离", "e": "Very close."},
{"r": 371, "w": "a watched pot never boils", "c": "心急水不开", "e": "Time slows when waiting."},
{"r": 372, "w": "blood is thicker than water", "c": "血浓于水", "e": "Family first."},
{"r": 373, "w": "burning the candle at both ends", "c": "过分地耗费精力,过分劳累", "e": "Overworking."},
{"r": 374, "w": "call the shots", "c": "控制事态, 操纵", "e": "Make decisions."},
{"r": 375, "w": "back to the salt mines", "c": "重回工作岗位,重操旧业,又要辛苦了", "e": "Return to work."},
{"r": 376, "w": "down and out", "c": "穷困潦倒", "e": "Without hope."},
{"r": 377, "w": "down in the dumps", "c": "十分沮丧的,颓丧的", "e": "Depressed."},
{"r": 378, "w": "dressed to the nines", "c": "盛装打扮（美国俚语）", "e": "Very dressed up."},
{"r": 379, "w": "every dog has his day", "c": "人皆有得意时", "e": "Everyone gets a chance."},
{"r": 380, "w": "fall on deaf ears", "c": "没有被听取", "e": "Ignored."},
{"r": 381, "w": "clutching at straws", "c": "姑且一试,明知不可为而为之", "e": "Desperate for a solution."},
{"r": 382, "w": "fits and starts", "c": "间歇的 / 断断续续的", "e": "Irregular bursts of activity."},
{"r": 383, "w": "for all intents and purposes", "c": "总而言之", "e": "Effectively."},
{"r": 384, "w": "getting up on the wrong side of the bed", "c": "心情不佳", "e": "Starting the day in a bad mood."},
{"r": 385, "w": "at sixes and sevens", "c": "乱七八糟, 不和", "e": "In confusion."},
{"r": 386, "w": "by leaps and bounds", "c": "非常迅速地", "e": "Rapidly."},
{"r": 387, "w": "come to grips with", "c": "与...搏斗", "e": "Understand and deal with."},
{"r": 388, "w": "chase rainbows", "c": "白日做梦,梦想获得不可能得到的东西", "e": "Pursue unlikely dreams."},
{"r": 389, "w": "clear the decks", "c": "清除障碍准备行动", "e": "Prepare for action."},
{"r": 390, "w": "come up trumps", "c": "令人满意, 对人有帮助, 慷慨大方, 交好运", "e": "Succeed unexpectedly."},
{"r": 391, "w": "at loggerheads", "c": "发生争执", "e": "In strong disagreement."},
{"r": 392, "w": "clutch at straws", "c": "姑且一试,明知不可为而为之", "e": "Desperate."},
{"r": 393, "w": "as the crow flies", "c": "笔直的", "e": "Straight line distance."},
{"r": 394, "w": "devil's advocate", "c": "唱反调的人; 故意唱反调的人", "e": "Contrarian"},
{"r": 395, "w": "skeletons in the closet", "c": "不可告人的秘密", "e": "Hidden secrets."},
{"r": 396, "w": "cast pearls before swine", "c": "明珠暗投", "e": "Offer value to the unappreciative."},
{"r": 397, "w": "crocodile tears", "c": "鳄鱼的眼泪, 假慈悲", "e": "Fake sadness."},
{"r": 398, "w": "a left-handed compliment", "c": "言不由衷(或挖苦人)的恭维话", "e": "Insult disguised as praise."},
{"r": 399, "w": "forty winks", "c": "打盹,小睡", "e": "Short nap."},
{"r": 400, "w": "up for grabs", "c": "供竞争,供竞买;容易到手", "e": "Available to anyone."},
{"r": 401, "w": "have the blues", "c": "闷闷不乐", "e": "Feel sad."},
{"r": 402, "w": "behind closed doors", "c": "与外界隔绝地, 秘密地", "e": "Done in private."},
{"r": 403, "w": "break someone's heart", "c": "使心碎", "e": "Cause emotional pain."},
{"r": 404, "w": "rub shoulders with", "c": "与…摩肩接踵,与…接近", "e": "Socialize with others."},
{"r": 405, "w": "let bygones be bygones", "c": "不咎既往；既往不究；既往不咎，忘掉旧嫌；宽大为怀", "e": "Forget past offenses and start anew."},
{"r": 406, "w": "sour grapes", "c": "酸葡萄", "e": "Disparaging something that is unattainable."},
{"r": 407, "w": "off the rails", "c": "出轨的, 混乱的, 神经错乱的", "e": "Going out of control."},
{"r": 408, "w": "make waves", "c": "兴风作浪", "e": "Create an impact."},
{"r": 409, "w": "the plot thickens", "c": "问题变得复杂了,情节复杂化了", "e": "The situation becomes more complex."},
{"r": 410, "w": "every dog has its day", "c": "人人都有得意之日", "e": "Everyone has a moment of success or achievement."},
{"r": 411, "w": "bird's eye view", "c": "鸟瞰；俯视", "e": "A broad perspective."},
{"r": 412, "w": "castles in the air", "c": "空中楼阁，白日梦，想入非非的计划", "e": "Unrealistic dreams."},
{"r": 413, "w": "spilling the beans", "c": "说漏嘴", "e": "Accidentally revealing a secret."},
{"r": 414, "w": "chasing rainbows", "c": "白日做梦,梦想获得不可能得到的东西", "e": "Pursuing something unattainable or unrealistic."},
{"r": 415, "w": "make hay while the sun shines", "c": "趁热打铁,抓紧时机", "e": "Take advantage of favorable conditions."},
{"r": 416, "w": "butterflies in the stomach", "c": "神经质的发抖", "e": "Feeling nervous or anxious."},
{"r": 417, "w": "to make matters worse", "c": "更糟糕的是", "e": "Make a problem worse"},
{"r": 418, "w": "familiarity breeds contempt", "c": "亲不尊熟生蔑", "e": "The better you know someone the less you like him"},
{"r": 419, "w": "snowed under", "c": "压倒的, 忙得不可开交的", "e": "Busy"},
{"r": 420, "w": "well begun is half done", "c": "好的开端是成功的一半", "e": "Getting a good start is important"},
{"r": 421, "w": "baker's dozen", "c": "十三", "e": "Thirteen."},
{"r": 422, "w": "head over heels", "c": "头朝下, 颠倒, 完全地", "e": "Very excited and joyful especially when in love."},
{"r": 423, "w": "know the ropes", "c": "知道内情", "e": "To understand the details."},
{"r": 424, "w": "on pins and needles", "c": "如坐针毡", "e": "Anxious especially in anticipation of something."},
{"r": 425, "w": "practice makes perfect", "c": "熟能生巧", "e": "By constantly practicing you will become better."},
{"r": 426, "w": "have mixed feelings", "c": "悲喜交加,百感交加", "e": "Be unsure of how you feel"},
{"r": 427, "w": "achilles' heel", "c": "唯一致命的弱点", "e": "A metaphor for a fatal weakness in spite of overall strength."},
{"r": 428, "w": "bed of roses", "c": "温床,安乐窝,安逸的生活环境", "e": "Easy and comfortable."},
{"r": 429, "w": "have at sb", "c": "扑向某人,袭击某人,对某人拳脚相加", "e": ""},
{"r": 430, "w": "have sb down", "c": "把某人请来作客", "e": ""},
{"r": 431, "w": "have sb over", "c": "把某人请到家里来", "e": ""},
{"r": 432, "w": "have sb up", "c": "把某人请来作客, 对某人起诉, 控告某人", "e": ""},
{"r": 433, "w": "have it in for sb", "c": "对某人怀有仇恨, 伺机想害某人, 对某人不怀好意", "e": ""},
{"r": 434, "w": "have it in one", "c": "有…的能力,善于…", "e": ""},
{"r": 435, "w": "have it on sb", "c": "胜过某人, 占某人的上风", "e": ""},
{"r": 436, "w": "have it out with sb", "c": "(与某人)斗一场解决争端, (与某人)决一雌雄, (同某人)讲个明白", "e": ""},
{"r": 437, "w": "have it over sb", "c": "胜过某人,超过某人,比某人强", "e": ""},
{"r": 438, "w": "do sb down", "c": "胜过某人;欺骗某人,中伤某人", "e": ""},
{"r": 439, "w": "get sb to do", "c": "让(某人)(做)...", "e": ""},
{"r": 440, "w": "have one's say", "c": "有发言机会, 有发言权", "e": ""},
{"r": 441, "w": "have the say", "c": "有最后决定权,有定论", "e": ""},
{"r": 442, "w": "say one's say", "c": "畅所欲言", "e": ""},
{"r": 443, "w": "one by one", "c": "一个接一个", "e": ""},
{"r": 444, "w": "this one or that one", "c": "这个还是那个", "e": ""},
{"r": 445, "w": "no one but", "c": "除了…谁也不", "e": ""},
{"r": 446, "w": "have one's will", "c": "达到自己的愿望", "e": ""},
{"r": 447, "w": "all in one", "c": "合为一体,整个的", "e": ""},
{"r": 448, "w": "all one can", "c": "力所能及,竭尽全力", "e": ""},
{"r": 449, "w": "all the go", "c": "非常流行,风行一时", "e": ""},
{"r": 450, "w": "be all one", "c": "都一样", "e": ""},
{"r": 451, "w": "be all over sb", "c": "讨好某人,巴结某人", "e": ""},
{"r": 452, "w": "have all the say", "c": "有决定一切的权力", "e": ""},
{"r": 453, "w": "have it all over sb", "c": "胜过某人", "e": ""},
{"r": 454, "w": "one and all", "c": "个个都, 全都", "e": ""},
{"r": 455, "w": "the all and the one", "c": "全部, 整体", "e": ""},
{"r": 456, "w": "as if as", "c": "至于;关于", "e": ""},
{"r": 457, "w": "make it up with sb", "c": "和某人讲和", "e": ""},
{"r": 458, "w": "make up to sb", "c": "接近, 巴结, 奉承, 向(女子)求爱, 企图得到...的欢心", "e": ""},
{"r": 459, "w": "all one know", "c": "力所能及的一切;尽全力地", "e": ""},
{"r": 460, "w": "see sb off", "c": "给某人送行", "e": ""},
{"r": 461, "w": "see with sb", "c": "同意某人的意见,和某人意见一致", "e": ""},
{"r": 462, "w": "all the time", "c": "始终", "e": ""},
{"r": 463, "w": "at no time", "c": "决不", "e": ""},
{"r": 464, "w": "at one time", "c": "同时, 曾经", "e": ""},
{"r": 465, "w": "in no time", "c": "立刻", "e": ""},
{"r": 466, "w": "in sb's time", "c": "在某人一生中, 当某人在某处工作的期间, 当某人在某处学习的期间", "e": ""},
{"r": 467, "w": "one at a time", "c": "一次一个人", "e": ""},
{"r": 468, "w": "take it out of sb", "c": "向(某人)报复, 以...来出气, 使(某人)筋疲力尽 / 疲乏", "e": ""},
{"r": 469, "w": "take it out on sb", "c": "向某人出气", "e": ""},
{"r": 470, "w": "take on sb", "c": "呈现, 具有(特征), 雇用, 招收, 增加, 接纳, 对付, 从事", "e": ""},
{"r": 471, "w": "take one's time", "c": "从容不迫", "e": ""},
{"r": 472, "w": "take one's time over", "c": "从容进行, 不慌不忙, 超过合理时间, 慢吞吞", "e": ""},
{"r": 473, "w": "take sb all his time", "c": "花费某人全部精力", "e": ""},
{"r": 474, "w": "take sb off", "c": "学...的样, 模仿", "e": ""},
{"r": 475, "w": "take sb out", "c": "拿出, 取出, 扣除, 除去, 带...出去, 发泄, 抵充, 取得(专利权), 获得, 领取(执照)", "e": ""},
{"r": 476, "w": "take sb up", "c": "接纳, 拘捕, 责备", "e": ""},
{"r": 477, "w": "take to one's", "c": "逃走, 溜走, 逃之夭夭", "e": ""},
{"r": 478, "w": "take to sb", "c": "喜欢, 亲近", "e": ""},
{"r": 479, "w": "take up with sb", "c": "与...亲密交往, 对...发生兴趣, 致力于", "e": ""},
{"r": 480, "w": "in the year one", "c": "很久以前", "e": ""},
{"r": 481, "w": "think about sb", "c": "考虑, 想, 回想, 想起, 认为", "e": ""},
{"r": 482, "w": "think of sb", "c": "考虑, 关心, 想, 想起, 记得, 想一想, 想象, 想出, 提出", "e": ""},
{"r": 483, "w": "one or two", "c": "一、二个, 很少的", "e": ""},
{"r": 484, "w": "go to the people", "c": "为争取人民对其政府或某计划的支持而举行公民投票", "e": ""},
{"r": 485, "w": "come over sb", "c": "支配, 左右, 攫住, 困扰", "e": ""},
{"r": 486, "w": "come to sb", "c": "突然进入脑海, 突然呈现", "e": ""},
{"r": 487, "w": "be just to sb", "c": "对某人公正", "e": ""},
{"r": 488, "w": "one or other", "c": "或者这个, 或者别个", "e": ""},
{"r": 489, "w": "this that and the other", "c": "形形色色, 诸如此类", "e": ""},
{"r": 490, "w": "this that or the other", "c": "形形色色, 诸如此类", "e": ""},
{"r": 491, "w": "one and only", "c": "唯一的", "e": ""},
{"r": 492, "w": "give it to sb", "c": "痛打某人,教训某人,斥责某人", "e": ""},
{"r": 493, "w": "give one his say", "c": "让某人把话讲出来", "e": ""},
{"r": 494, "w": "give over to sb", "c": "把...交付给某人", "e": ""},
{"r": 495, "w": "give sb time", "c": "给某人放宽时间", "e": ""},
{"r": 496, "w": "give sb up", "c": "认为(某人)没有救了, 宣告无法治好, 表示对...没有希望, 引渡罪犯, 投案", "e": ""},
{"r": 497, "w": "as good as", "c": "和...几乎一样, 实际上等于...", "e": ""},
{"r": 498, "w": "be up to no good", "c": "尽干坏事", "e": ""},
{"r": 499, "w": "come to no good", "c": "没有好结果", "e": ""},
{"r": 500, "w": "do sb good", "c": "对某人有益", "e": ""},
{"r": 501, "w": "in good with sb", "c": "讨某人喜欢,得到某人的好感,受到某人的宠爱", "e": ""},
{"r": 502, "w": "no other than", "c": "只有, 正是", "e": ""},
{"r": 503, "w": "up to no good", "c": "不怀好意", "e": ""},
{"r": 504, "w": "all the more", "c": "更加", "e": ""},
{"r": 505, "w": "as like as not", "c": "大概,多半,很可能", "e": ""},
{"r": 506, "w": "no more than", "c": "至多", "e": ""},
{"r": 507, "w": "which one would you like", "c": "你喜欢哪一个", "e": ""},
{"r": 508, "w": "for the first time", "c": "第一次", "e": ""},
{"r": 509, "w": "from the very first", "c": "从最初开始", "e": ""},
{"r": 510, "w": "be new with sb", "c": "对某人来说很新奇", "e": ""},
{"r": 511, "w": "by the look of it", "c": "看样子", "e": ""},
{"r": 512, "w": "give sb a look", "c": "对某人看了一眼", "e": ""},
{"r": 513, "w": "look about one", "c": "察看自己的情况", "e": ""},
{"r": 514, "w": "look sb up", "c": "(顺便)拜访, 探望", "e": ""},
{"r": 515, "w": "look sb up and down", "c": "上下打量某人", "e": ""},
{"r": 516, "w": "look up to sb", "c": "尊敬, 尊重, 折服, 敬仰", "e": ""},
{"r": 517, "w": "to look at sb", "c": "从某人的外表看来", "e": ""},
{"r": 518, "w": "all the way", "c": "从远道, 自始至终, 一路上", "e": ""},
{"r": 519, "w": "as well as", "c": "也, 又", "e": ""},
{"r": 520, "w": "be well with sb", "c": "与某人相处得好", "e": ""},
{"r": 521, "w": "do sb well", "c": "盛情款待,热情招待", "e": ""},
{"r": 522, "w": "get in the way", "c": "挡住去路,障碍,碍事", "e": ""},
{"r": 523, "w": "get out of the way", "c": "让路,避开;除去,完成", "e": ""},
{"r": 524, "w": "go all the way", "c": "完全一致", "e": ""},
{"r": 525, "w": "go one's way", "c": "出发, 动身", "e": ""},
{"r": 526, "w": "go out of one's way", "c": "特地, 不怕麻烦, 故意", "e": ""},
{"r": 527, "w": "go out of the way", "c": "不怕麻烦, 故意", "e": ""},
{"r": 528, "w": "in no way", "c": "决不", "e": ""},
{"r": 529, "w": "in one way", "c": "在某点上, 在某种程度上, 有几分, 稍微", "e": ""},
{"r": 530, "w": "in one's way", "c": "挡道的, 妨碍人的, 使人不便的, (英)近在咫尺, 在场", "e": ""},
{"r": 531, "w": "look the other way", "c": "故意朝另一边看", "e": ""},
{"r": 532, "w": "make one's way", "c": "前进, 行进, 成功, 发迹", "e": ""},
{"r": 533, "w": "on the way out", "c": "即将灭亡", "e": ""},
{"r": 534, "w": "over the way", "c": "在路对面", "e": ""},
{"r": 535, "w": "see one's way to do", "c": "有可能做某事, 有意做某事", "e": ""},
{"r": 536, "w": "think well of sb", "c": "认为某人好", "e": ""},
{"r": 537, "w": "of no use", "c": "无用", "e": ""},
{"r": 538, "w": "use sb well", "c": "待某人好", "e": ""},
{"r": 539, "w": "a day off", "c": "休息日", "e": ""},
{"r": 540, "w": "a year and a day", "c": "满一年, 一整年", "e": ""},
{"r": 541, "w": "all the day", "c": "整天地", "e": ""},
{"r": 542, "w": "give the time of day", "c": "问好", "e": ""},
{"r": 543, "w": "have one's day", "c": "走运", "e": ""},
{"r": 544, "w": "know the time of day", "c": "消息灵通, 机警", "e": ""},
{"r": 545, "w": "on one's day", "c": "在鼎盛时期", "e": ""},
{"r": 546, "w": "one of these day", "c": "日内,总有一天", "e": ""},
{"r": 547, "w": "this time of the day", "c": "每天的这个时候", "e": ""},
{"r": 548, "w": "as one man", "c": "一致地", "e": ""},
{"r": 549, "w": "make a man of sb", "c": "使某人成人, 使某人成器", "e": ""},
{"r": 550, "w": "one after the other", "c": "相继地", "e": ""},
{"r": 551, "w": "take after sb", "c": "象..., 像..., 与...相象, 学...的样", "e": ""},
{"r": 552, "w": "do one's thing", "c": "以自己独特的方式表现自己的性格", "e": ""},
{"r": 553, "w": "for one thing", "c": "首先", "e": ""},
{"r": 554, "w": "just the thing", "c": "正是想要的", "e": ""},
{"r": 555, "w": "as many as", "c": "和...一样多", "e": ""},
{"r": 556, "w": "tell on sb", "c": "(非正式)告发某人, (正式)起坏作用, 影响", "e": ""},
{"r": 557, "w": "tell sb off", "c": "数落, 责骂, 斥责, 责备, 向...透露消息", "e": ""},
{"r": 558, "w": "at sb's back", "c": "支持(某人), 给(某人)撑腰", "e": ""},
{"r": 559, "w": "be on one's back", "c": "仰卧, 生病卧床", "e": ""},
{"r": 560, "w": "be on sb's back", "c": "嘲笑 / 指责(某人), 打扰 / 惹恼(某人)", "e": ""},
{"r": 561, "w": "get back at sb", "c": "报复某人,向某人报仇", "e": ""},
{"r": 562, "w": "give sb the back", "c": "不再理睬某人", "e": ""},
{"r": 563, "w": "see sb back", "c": "送某人回去", "e": ""},
{"r": 564, "w": "see the back of sb", "c": "不理睬某人,摆脱某人", "e": ""},
{"r": 565, "w": "to get off sb's back", "c": "不再嘲笑 / 打扰(某人)", "e": ""},
{"r": 566, "w": "be even with sb", "c": "与(某人)扯平", "e": ""},
{"r": 567, "w": "even up on sb", "c": "向(某人)报复, 向(某人)报答", "e": ""},
{"r": 568, "w": "even with sb", "c": "与某人结清", "e": ""},
{"r": 569, "w": "get even with sb", "c": "与(某人)扯平, 跟(某人)算账, 向(某人)报复", "e": ""},
{"r": 570, "w": "all the year through", "c": "整年, 一年到头", "e": ""},
{"r": 571, "w": "be through with sb", "c": "与某人断绝关系", "e": ""},
{"r": 572, "w": "look sb through and through", "c": "仔细地打量某人", "e": ""},
{"r": 573, "w": "see sb through", "c": "帮助(某人)渡过...", "e": ""},
{"r": 574, "w": "as still as still", "c": "鸦雀无声,万籁俱寂", "e": ""},
{"r": 575, "w": "all one's life", "c": "一生", "e": ""},
{"r": 576, "w": "for the life of me", "c": "即使要我的命, 无论如何", "e": ""},
{"r": 577, "w": "the time of one's life", "c": "一生中最愉快的一段时期", "e": ""},
{"r": 578, "w": "one too many", "c": "多余的一个", "e": ""},
{"r": 579, "w": "put sb out of the way", "c": "除掉,监禁某人,消除某人的障碍", "e": ""},
{"r": 580, "w": "put sb through", "c": "替某人接通电话", "e": ""},
{"r": 581, "w": "go about one's work", "c": "着手工作", "e": ""},
{"r": 582, "w": "work sb up", "c": "激起, 引起...的情绪", "e": ""},
{"r": 583, "w": "be one's own man", "c": "不受他人控制", "e": ""},
{"r": 584, "w": "get one's own back", "c": "报复", "e": ""},
{"r": 585, "w": "get one's own way", "c": "独自行动, 自行其事, 一意孤行, 随心所欲, 为所欲为", "e": ""},
{"r": 586, "w": "go one's own way", "c": "一意孤行, 独自行动", "e": ""},
{"r": 587, "w": "have one's own way", "c": "独自行动, 自行其事, 一意孤行, 随心所欲, 为所欲为", "e": ""},
{"r": 588, "w": "in one's own good time", "c": "在方便的时候", "e": ""},
{"r": 589, "w": "make one's own way", "c": "成功, 发迹", "e": ""},
{"r": 590, "w": "of one's own", "c": "属于某人自己的", "e": ""},
{"r": 591, "w": "on one's own", "c": "独自地, 独立地, 主动地", "e": ""},
{"r": 592, "w": "on one's own time", "c": "在非工作时间", "e": ""},
{"r": 593, "w": "take one's own life", "c": "自杀", "e": ""},
{"r": 594, "w": "take one's own way", "c": "独自行动, 自行其事, 一意孤行, 随心所欲, 为所欲为", "e": ""},
{"r": 595, "w": "for the last time", "c": "最后一次", "e": ""},
{"r": 596, "w": "last but one", "c": "倒数第二", "e": ""},
{"r": 597, "w": "one last time", "c": "最后一次", "e": ""},
{"r": 598, "w": "to the very last", "c": "直至最后,至死,战斗到底", "e": ""},
{"r": 599, "w": "for the mean time", "c": "在此期间,暂时", "e": ""},
{"r": 600, "w": "in the mean time", "c": "同时;当其时,在其间", "e": ""},
{"r": 601, "w": "call sb up", "c": "打电话给某人", "e": ""},
{"r": 602, "w": "have the call", "c": "处于主要地位", "e": ""},
{"r": 603, "w": "all over the world", "c": "全世界", "e": ""},
{"r": 604, "w": "all the world", "c": "一切", "e": ""},
{"r": 605, "w": "all the world to sb", "c": "对某人最重要", "e": ""},
{"r": 606, "w": "come down in the world", "c": "落泊", "e": ""},
{"r": 607, "w": "come into the world", "c": "出生", "e": ""},
{"r": 608, "w": "come up in the world", "c": "(生活或社会地位)提高", "e": ""},
{"r": 609, "w": "for all the world", "c": "完全, 无论如何", "e": ""},
{"r": 610, "w": "for all the world like", "c": "完全像", "e": ""},
{"r": 611, "w": "give to the world", "c": "出版, 发表", "e": ""},
{"r": 612, "w": "man of the world", "c": "饱经世故者，爱享乐者", "e": ""},
{"r": 613, "w": "not for the world", "c": "无论如何不, 决不", "e": ""},
{"r": 614, "w": "out of the world", "c": "十全十美的, 极其动人的, 无比优秀的, 无比精彩的", "e": ""},
{"r": 615, "w": "see the world", "c": "见过世面,见多识广,通晓人情世故", "e": ""},
{"r": 616, "w": "tell the world", "c": "当众说, 断言", "e": ""},
{"r": 617, "w": "the way of the world", "c": "人情世故", "e": ""},
{"r": 618, "w": "the world over", "c": "全世界,遍及全球", "e": ""},
{"r": 619, "w": "go to school to sb", "c": "跟某人学, 模仿某人", "e": ""},
{"r": 620, "w": "go to the school", "c": "到学校去", "e": ""},
{"r": 621, "w": "the school year", "c": "学年", "e": ""},
{"r": 622, "w": "leave sb be", "c": "任他,别管他", "e": ""},
{"r": 623, "w": "leave sb to it", "c": "听任某人自由行事,不管某人", "e": ""},
{"r": 624, "w": "take one's leave", "c": "告辞", "e": ""},
{"r": 625, "w": "no great of a", "c": "没有什么了不起的,不大会,不是怎么样的…", "e": ""},
{"r": 626, "w": "the great and the mean", "c": "高贵者与卑贱者", "e": ""},
{"r": 627, "w": "ask for one's time", "c": "要求领取应得工资, 要求领取最后一次的工资", "e": ""},
{"r": 628, "w": "ask the way", "c": "问路", "e": ""},
{"r": 629, "w": "do one's need", "c": "解手", "e": ""},
{"r": 630, "w": "feel for sb", "c": "为某人感到惋惜, 怜悯", "e": ""},
{"r": 631, "w": "feel one's way", "c": "摸索着走, 谨慎行事", "e": ""},
{"r": 632, "w": "feel sb out", "c": "试探出某人的态度, 试探出某人的意向", "e": ""},
{"r": 633, "w": "have system in one's work", "c": "工作有条理", "e": ""},
{"r": 634, "w": "all the same", "c": "仍然", "e": ""},
{"r": 635, "w": "at the same time", "c": "同时, 但是", "e": ""},
{"r": 636, "w": "come to the same thing", "c": "结果相同", "e": ""},
{"r": 637, "w": "do the same", "c": "照办,採取同样的做法", "e": ""},
{"r": 638, "w": "feel the same to sb", "c": "对某人有同样的看法, 对某人的看法和过去一样", "e": ""},
{"r": 639, "w": "in the same way", "c": "同样地", "e": ""},
{"r": 640, "w": "in the same way as", "c": "如同…一样", "e": ""},
{"r": 641, "w": "just the same", "c": "完全一样, 还是", "e": ""},
{"r": 642, "w": "one and the same", "c": "同一个, 完全一样", "e": ""},
{"r": 643, "w": "the same to you", "c": "同样也祝你…", "e": ""},
{"r": 644, "w": "the very same", "c": "正是这个, 完全相同的", "e": ""},
{"r": 645, "w": "think the same of sb", "c": "对某人有同样的看法, 对某人的看法和过去一样", "e": ""},
{"r": 646, "w": "never a one", "c": "没有一个, 没有一个人", "e": ""},
{"r": 647, "w": "with all one's might", "c": "全力以赴地", "e": ""},
{"r": 648, "w": "give the case for sb", "c": "作出对某人有利的判决", "e": ""},
{"r": 649, "w": "in no case", "c": "决不", "e": ""},
{"r": 650, "w": "make out one's case", "c": "证明自己有理", "e": ""},
{"r": 651, "w": "put the case that", "c": "假设", "e": ""},
{"r": 652, "w": "do one's part", "c": "尽自己的职责", "e": ""},
{"r": 653, "w": "for one's part", "c": "对某人来说, 就个人来说", "e": ""},
{"r": 654, "w": "look the part", "c": "看起来适合这角色", "e": ""},
{"r": 655, "w": "have something on sb", "c": "掌握某人的一些事实", "e": ""},
{"r": 656, "w": "no mean something", "c": "很好的(东西)", "e": ""},
{"r": 657, "w": "see something of the world", "c": "见一些世面", "e": ""},
{"r": 658, "w": "get sb's number", "c": "发现某人的本质, 发现某人的动机", "e": ""},
{"r": 659, "w": "have sb's number", "c": "对某人的能力心中有数", "e": ""},
{"r": 660, "w": "for the most part", "c": "在极大程度上", "e": ""},
{"r": 661, "w": "most of the time", "c": "多数情况下，大多数时候", "e": ""},
{"r": 662, "w": "the most high", "c": "上帝", "e": ""},
{"r": 663, "w": "at one time or another", "c": "在某个时候", "e": ""},
{"r": 664, "w": "one time with another", "c": "前后合起来", "e": ""},
{"r": 665, "w": "one way and another", "c": "千方百计,以种种方法", "e": ""},
{"r": 666, "w": "one way or another", "c": "无论如何", "e": ""},
{"r": 667, "w": "take one thing with another", "c": "考虑各种情况", "e": ""},
{"r": 668, "w": "as much as", "c": "尽...那样多, 差不多", "e": ""},
{"r": 669, "w": "as much as to say", "c": "等于说", "e": ""},
{"r": 670, "w": "be with sb much", "c": "常和某人在一起", "e": ""},
{"r": 671, "w": "in as much as", "c": "既然,因为,由于…", "e": ""},
{"r": 672, "w": "much at one", "c": "几乎相等, 几乎等价", "e": ""},
{"r": 673, "w": "see much of the world", "c": "见过不少世面", "e": ""},
{"r": 674, "w": "so much the", "c": "那就更...了", "e": ""},
{"r": 675, "w": "show sb out", "c": "领(某人)出去", "e": ""},
{"r": 676, "w": "show sb the way", "c": "给某人指路 / 带路 / 引路, 给某人作示范, 为某人作指点", "e": ""},
{"r": 677, "w": "show sb up", "c": "使某人蒙羞, (非正式)大大胜过", "e": ""},
{"r": 678, "w": "show the way", "c": "做出样子来", "e": ""},
{"r": 679, "w": "woman of the house", "c": "女主人", "e": ""},
{"r": 680, "w": "all the while", "c": "一直, 始终", "e": ""},
{"r": 681, "w": "against one's will", "c": "违心地", "e": ""},
{"r": 682, "w": "give the case against sb", "c": "作出对某人不利的判决", "e": ""},
{"r": 683, "w": "as many again as", "c": "是…的两倍,比…多一倍", "e": ""},
{"r": 684, "w": "as much again as", "c": "比...多一倍", "e": ""},
{"r": 685, "w": "keep in with sb", "c": "与某人友好相处, 与某人结伙, 深得某人欢心", "e": ""},
{"r": 686, "w": "keep sb company", "c": "陪伴某人, 陪某人同走", "e": ""},
{"r": 687, "w": "keep the house", "c": "居家不外出", "e": ""},
{"r": 688, "w": "to keep on at sb", "c": "跟(某人)纠缠不休", "e": ""},
{"r": 689, "w": "the how and the why", "c": "方法和理由", "e": ""},
{"r": 690, "w": "let sb be", "c": "听任某人自由行事,不加干涉,随他去吧,听其自然", "e": ""},
{"r": 691, "w": "let sb have it", "c": "让某人吃顿苦头", "e": ""},
{"r": 692, "w": "let sb know", "c": "告诉, 通知", "e": ""},
{"r": 693, "w": "let sb off", "c": "让下车", "e": ""},
{"r": 694, "w": "let sb through", "c": "让某人通过", "e": ""},
{"r": 695, "w": "at sb's service", "c": "听候某人吩咐, 听凭某人使用", "e": ""},
{"r": 696, "w": "be in sb's service", "c": "在某人家帮佣", "e": ""},
{"r": 697, "w": "take sb into one's service", "c": "雇用某人", "e": ""},
{"r": 698, "w": "take the service", "c": "发球, 开球", "e": ""},
{"r": 699, "w": "all over the place", "c": "到处", "e": ""},
{"r": 700, "w": "as big as life", "c": "与原物一样大", "e": ""},
{"r": 701, "w": "in the first place", "c": "首先", "e": ""},
{"r": 702, "w": "in the last place", "c": "最后", "e": ""},
{"r": 703, "w": "know one's place", "c": "知趣", "e": ""},
{"r": 704, "w": "place sb as", "c": "任命某人为...", "e": ""},
{"r": 705, "w": "put sb in his place", "c": "使某人不敢越轨, 使某人安分, 使有所收敛, 使有一些自知之明", "e": ""},
{"r": 706, "w": "take one's place", "c": "就座", "e": ""},
{"r": 707, "w": "take the first place", "c": "居首位, 得第一", "e": ""},
{"r": 708, "w": "give one's hand to sb", "c": "(女子)答应和某人结婚", "e": ""},
{"r": 709, "w": "give sb a hand", "c": "给予(某人)帮助", "e": ""},
{"r": 710, "w": "hand it to sb", "c": "赞扬某人, 承认某人的长处", "e": ""},
{"r": 711, "w": "on one hand", "c": "一方面", "e": ""},
{"r": 712, "w": "on the one hand", "c": "在一方面", "e": ""},
{"r": 713, "w": "on the other hand", "c": "另一方面", "e": ""},
{"r": 714, "w": "show one's hand", "c": "摊牌", "e": ""},
{"r": 715, "w": "take sb by the hand", "c": "拉住某人的手", "e": ""},
{"r": 716, "w": "to one's hand", "c": "在手头", "e": ""},
{"r": 717, "w": "with the even hand", "c": "公平地", "e": ""},
{"r": 718, "w": "begin the world", "c": "开始自己谋生", "e": ""},
{"r": 719, "w": "help sb down", "c": "把某人搀扶下来", "e": ""},
{"r": 720, "w": "help sb into", "c": "搀扶某人进入...", "e": ""},
{"r": 721, "w": "help sb out", "c": "帮助某人解决难题, 帮助某人摆脱困境, 帮助某人完成工作", "e": ""},
{"r": 722, "w": "help sb over", "c": "帮某人越过..., 帮某人度过...", "e": ""},
{"r": 723, "w": "help sb up", "c": "把某人扶起, 扶某人攀登", "e": ""},
{"r": 724, "w": "if one can help it", "c": "如果有办法可想的话", "e": ""},
{"r": 725, "w": "look to sb for help", "c": "期待某人帮助", "e": ""},
{"r": 726, "w": "in the small of the back", "c": "在腰背部", "e": ""},
{"r": 727, "w": "talk at sb", "c": "影射某人, 指桑骂槐地讲某人", "e": ""},
{"r": 728, "w": "talk down to sb", "c": "用高人一等的口气对某人讲话, 对某人讲得简单", "e": ""},
{"r": 729, "w": "talk to sb", "c": "找某人谈话, (非正式)责备某人", "e": ""},
{"r": 730, "w": "the small of the back", "c": "腰背部", "e": ""},
{"r": 731, "w": "think small of sb", "c": "瞧不起某人", "e": ""},
{"r": 732, "w": "at the turn of the year", "c": "在旧的一年过去的时候", "e": ""},
{"r": 733, "w": "call the turn", "c": "言中", "e": ""},
{"r": 734, "w": "do sb a good turn", "c": "做一件有利于某人的事", "e": ""},
{"r": 735, "w": "give sb a turn", "c": "使某人大吃一惊,把某人吓一跳", "e": ""},
{"r": 736, "w": "in one's turn", "c": "轮到某人", "e": ""},
{"r": 737, "w": "in the turn of a hand", "c": "顷刻间", "e": ""},
{"r": 738, "w": "turn on sb", "c": "突然攻击, 反对, 对...发怒, 依靠, 依赖, 取决于", "e": ""},
{"r": 739, "w": "turn sb against sb", "c": "使某人与...作对, 使转而反对, 使与...为敌", "e": ""},
{"r": 740, "w": "turn sb down", "c": "关小, 调低, 拒绝, 摒弃, 翻下, 向下折转, 使面朝下", "e": ""},
{"r": 741, "w": "turn sb off", "c": "(使)厌烦, (使)讨厌, 使不感兴趣, 解雇, 把...绞死", "e": ""},
{"r": 742, "w": "turn sb over", "c": "交出, 上缴, 把...向里折, 告发, 交给警方, 出卖, 作出", "e": ""},
{"r": 743, "w": "turn the other way", "c": "转向另一侧", "e": ""},
{"r": 744, "w": "turn to sb", "c": "转向, 翻到(某页), 变成, 求教于, 讨教于, 致力于, 着手, 开始工作, 积极行动", "e": ""},
{"r": 745, "w": "turn to sb for help", "c": "求某人帮助", "e": ""},
{"r": 746, "w": "provide for sb", "c": "赡养, 提供生计", "e": ""},
{"r": 747, "w": "get the start of sb", "c": "比某人居先, 比某人占优势", "e": ""},
{"r": 748, "w": "have the start of sb", "c": "比某人居先, 比某人占优势", "e": ""},
{"r": 749, "w": "start after sb", "c": "开始追赶某人", "e": ""},
{"r": 750, "w": "start against sb", "c": "参加对某人的比赛, 参加对某人的竞争", "e": ""},
{"r": 751, "w": "a case in point", "c": "恰当的例子", "e": ""},
{"r": 752, "w": "come to the point", "c": "变尖锐, 到紧要关头, 说到要点, 扼要地说", "e": ""},
{"r": 753, "w": "keep to the point", "c": "扣住主题", "e": ""},
{"r": 754, "w": "off the point", "c": "离题", "e": ""},
{"r": 755, "w": "point to sb", "c": "指着某人", "e": ""},
{"r": 756, "w": "hold one's hand", "c": "迟迟不动手", "e": ""},
{"r": 757, "w": "hold one's own", "c": "坚持住", "e": ""},
{"r": 758, "w": "day of the week", "c": "礼拜", "e": ""},
{"r": 759, "w": "as large as life", "c": "与原物一样大小", "e": ""},
{"r": 760, "w": "be at the end", "c": "最终", "e": ""},
{"r": 761, "w": "end of the world", "c": "世界末日", "e": ""},
{"r": 762, "w": "keep one's end up", "c": "精神饱满地对付", "e": ""},
{"r": 763, "w": "keep up one's end", "c": "保持愉快和战斗的情绪, 精神饱满地对付", "e": ""},
{"r": 764, "w": "during the week", "c": "在一周的工作日内", "e": ""},
{"r": 765, "w": "be in the right", "c": "站在正义一边", "e": ""},
{"r": 766, "w": "do sb right", "c": "公平对侍某人", "e": ""},
{"r": 767, "w": "in one's own right", "c": "凭本身的头衔", "e": ""},
{"r": 768, "w": "in right of sb", "c": "依仗某人的头衔, 依仗某人的权利", "e": ""},
{"r": 769, "w": "one's right hand", "c": "右手, 得力助手, 右边", "e": ""},
{"r": 770, "w": "bring down the house", "c": "博得满堂喝彩", "e": ""},
{"r": 771, "w": "hear from sb", "c": "得到(某人)的消息, 接到(某人)的信, 受到...的批评", "e": ""},
{"r": 772, "w": "hear sb out", "c": "听某人把话说完", "e": ""},
{"r": 773, "w": "from the word go", "c": "从一开始", "e": ""},
{"r": 774, "w": "get the word", "c": "理解意思", "e": ""},
{"r": 775, "w": "give one's word", "c": "对某人说, 答允", "e": ""},
{"r": 776, "w": "give sb one's word", "c": "保证, 允诺, 对某人许下诺言", "e": ""},
{"r": 777, "w": "give the word", "c": "下命令", "e": ""},
{"r": 778, "w": "hold sb to his word", "c": "要某人遵守诺言", "e": ""},
{"r": 779, "w": "in one word", "c": "简言之, 总之, 一句话", "e": ""},
{"r": 780, "w": "keep one's word", "c": "守信", "e": ""},
{"r": 781, "w": "say the word", "c": "发命令", "e": ""},
{"r": 782, "w": "ask a question of sb", "c": "向某人提一个问题", "e": ""},
{"r": 783, "w": "ask sb a question", "c": "向某人提出一个问题", "e": ""},
{"r": 784, "w": "put a question to sb", "c": "向某人提问题", "e": ""},
{"r": 785, "w": "put sb to the question", "c": "拷问某人", "e": ""},
{"r": 786, "w": "put the question", "c": "提交表决", "e": ""},
{"r": 787, "w": "before one's time", "c": "提早, 在某人出生前, 过早", "e": ""},
{"r": 788, "w": "before the world", "c": "在全世界面前, 公然地", "e": ""},
{"r": 789, "w": "the year before last", "c": "前年", "e": ""},
{"r": 790, "w": "come to the next point", "c": "转入下一个话题", "e": ""},
{"r": 791, "w": "get next to sb", "c": "讨好某人, 与某人接近", "e": ""},
{"r": 792, "w": "in next to no time", "c": "立刻,马上,很快", "e": ""},
{"r": 793, "w": "in the next place", "c": "其次", "e": ""},
{"r": 794, "w": "next but one", "c": "下下一个", "e": ""},
{"r": 795, "w": "the next but one", "c": "下下一个", "e": ""},
{"r": 796, "w": "the week after next", "c": "下下星期", "e": ""},
{"r": 797, "w": "the year after next", "c": "后年", "e": ""},
{"r": 798, "w": "as good as a play", "c": "有趣", "e": ""},
{"r": 799, "w": "hold sb in play", "c": "牵制某人,使某人分心", "e": ""},
{"r": 800, "w": "play for one's own hand", "c": "为私利而干", "e": ""},
{"r": 801, "w": "play sb up", "c": "给...造成麻烦, 使痛苦", "e": ""},
{"r": 802, "w": "play the man", "c": "显示男子气概, 无所畏惧", "e": ""},
{"r": 803, "w": "play the woman", "c": "撒娇", "e": ""},
{"r": 804, "w": "run in the family", "c": "为一家人所共有,世代相传", "e": ""},
{"r": 805, "w": "run the show", "c": "主持演出, 主持, 操纵", "e": ""},
{"r": 806, "w": "feel not quite the thing", "c": "感到身体不适", "e": ""},
{"r": 807, "w": "look not quite the thing", "c": "看上去身体不适", "e": ""},
{"r": 808, "w": "quite the thing", "c": "很时髦", "e": ""},
{"r": 809, "w": "get on the move", "c": "开始行动,动身", "e": ""},
{"r": 810, "w": "be off of one's head", "c": "发疯, 神经错乱, 神志不清", "e": ""},
{"r": 811, "w": "be off one's head", "c": "神经错乱", "e": ""},
{"r": 812, "w": "be out of one's head", "c": "发疯, 神经错乱, 神志不清", "e": ""},
{"r": 813, "w": "be right in one's head", "c": "神志正常", "e": ""},
{"r": 814, "w": "go to sb's head", "c": "使兴奋, 使某人冲昏头脑, 使某人醉酒, 使某人狂妄, 使妄自尊大", "e": ""},
{"r": 815, "w": "head sb off", "c": "使转移方向", "e": ""},
{"r": 816, "w": "hold one's head high", "c": "趾高气扬, 扬眉吐气", "e": ""},
{"r": 817, "w": "in the still of night", "c": "更深夜静时", "e": ""},
{"r": 818, "w": "keep one's head", "c": "保持冷静", "e": ""},
{"r": 819, "w": "over sb's head", "c": "使某人不能理解", "e": ""},
{"r": 820, "w": "put a head on sb", "c": "击败某人", "e": ""},
{"r": 821, "w": "put up for the night", "c": "投宿,过夜,留过夜", "e": ""},
{"r": 822, "w": "run one's head off", "c": "狂奔不已", "e": ""},
{"r": 823, "w": "show one's head", "c": "到场", "e": ""},
{"r": 824, "w": "take into one's head", "c": "突然想到", "e": ""},
{"r": 825, "w": "talk sb's head off", "c": "对某人说个不停, 对某人唠叨不休", "e": ""},
{"r": 826, "w": "the night before last", "c": "前晚", "e": ""},
{"r": 827, "w": "turn sb's head", "c": "使某人感到骄傲, 使某人头脑发热", "e": ""},
{"r": 828, "w": "under the night", "c": "在黑夜的掩护下,趁黑夜", "e": ""},
{"r": 829, "w": "live the part", "c": "把角色演活了", "e": ""},
{"r": 830, "w": "go over the side", "c": "私自离开船只(或基地)", "e": ""},
{"r": 831, "w": "have no side", "c": "很谦虚", "e": ""},
{"r": 832, "w": "let the side down", "c": "有失众望", "e": ""},
{"r": 833, "w": "over the side", "c": "上船", "e": ""},
{"r": 834, "w": "take sb on one side", "c": "把某人拉到一边, 置某人于一旁", "e": ""},
{"r": 835, "w": "take the side of sb", "c": "同意某人, 支持某人, 袒护某人, 偏袒某人", "e": ""},
{"r": 836, "w": "set about one's work", "c": "开始工作", "e": ""},
{"r": 837, "w": "set sb down", "c": "(英)停车使(乘客)下车, 登记, (非正式)申斥, (非正式)责骂, 击败", "e": ""},
{"r": 838, "w": "a month or so", "c": "一个月左右", "e": ""},
{"r": 839, "w": "the month after next", "c": "再下一个月", "e": ""},
{"r": 840, "w": "the month before last", "c": "再上一个月", "e": ""},
{"r": 841, "w": "do the business", "c": "起作用,奏效,可以满足要求", "e": ""},
{"r": 842, "w": "have no business to do", "c": "无权(做)..., 没有权利(做)...", "e": ""},
{"r": 843, "w": "know one's business", "c": "精通自己一行", "e": ""},
{"r": 844, "w": "as long as", "c": "只要...", "e": ""},
{"r": 845, "w": "not long for the world", "c": "不久于人世,快要死", "e": ""},
{"r": 846, "w": "do sb in the eye", "c": "欺骗(某人), 愚弄(某人)", "e": ""},
{"r": 847, "w": "get the eye", "c": "引人注目;遭人白眼", "e": ""},
{"r": 848, "w": "give sb the eye", "c": "好奇地看着;冷眼看待,冷冷地望着", "e": ""},
{"r": 849, "w": "give the eye", "c": "注目, 给以白眼; 丢眼色", "e": ""},
{"r": 850, "w": "look sb in the eye", "c": "无愧于心地正视某人, 无所畏惧地正视某人", "e": ""},
{"r": 851, "w": "a home from home", "c": "象家里一样舒适的环境", "e": ""},
{"r": 852, "w": "bring home to sb", "c": "使某人深切地感到 / 清楚地认识到", "e": ""},
{"r": 853, "w": "come home to sb", "c": "打入某人的心中, 被某人所理解", "e": ""},
{"r": 854, "w": "make one's way home", "c": "回家去", "e": ""},
{"r": 855, "w": "on one's way home", "c": "在回家的路上", "e": ""},
{"r": 856, "w": "on the way back home", "c": "在回家的路上", "e": ""},
{"r": 857, "w": "on the way home", "c": "在回家途中", "e": ""},
{"r": 858, "w": "one in a million", "c": "百万分之一,极渺茫", "e": ""},
{"r": 859, "w": "one's long home", "c": "坟墓", "e": ""},
{"r": 860, "w": "see sb home", "c": "送某人回家", "e": ""},
{"r": 861, "w": "have sb in one's power", "c": "控制住某人, 能摆布某人", "e": ""},
{"r": 862, "w": "give sb change", "c": "给某人以相应的报答", "e": ""},
{"r": 863, "w": "of the first water", "c": "第一流的,最好的,上等的", "e": ""},
{"r": 864, "w": "put the change on sb", "c": "欺骗某人, 对某人隐瞒", "e": ""},
{"r": 865, "w": "take the water", "c": "下水, 上船, (美)(非正式)退却, (美)(非正式)打退堂鼓", "e": ""},
{"r": 866, "w": "in sb's room", "c": "处于某人的地位, 作为对某人的接替", "e": ""},
{"r": 867, "w": "in the room of sb", "c": "处于某人的地位, 作为对某人的接替", "e": ""},
{"r": 868, "w": "leave the room", "c": "离开房间;上厕所", "e": ""},
{"r": 869, "w": "make room for sb", "c": "让出空地方给某人", "e": ""},
{"r": 870, "w": "pay as one go", "c": "付钱购物,不赊帐", "e": ""},
{"r": 871, "w": "pay one's way", "c": "支付份内的费用, 支付生活费, 勉强维持", "e": ""},
{"r": 872, "w": "pay sb off", "c": "付清工资后解雇(某)人", "e": ""},
{"r": 873, "w": "be young at the work", "c": "对这工作还是新手", "e": ""},
{"r": 874, "w": "as often as", "c": "每当", "e": ""},
{"r": 875, "w": "as often as not", "c": "往往, 多半", "e": ""},
{"r": 876, "w": "make interest with sb", "c": "施加影响于某人", "e": ""},
{"r": 877, "w": "come into one's money", "c": "继承遗产", "e": ""},
{"r": 878, "w": "for one's money", "c": "依照本人的意见", "e": ""},
{"r": 879, "w": "out of the money", "c": "赌输", "e": ""},
{"r": 880, "w": "away from the point", "c": "离题", "e": ""},
{"r": 881, "w": "give sb away", "c": "无意中洩露,暴露", "e": ""},
{"r": 882, "w": "give the show away", "c": "露出马脚, 泄露内情", "e": ""},
{"r": 883, "w": "put sb away", "c": "把...送进监狱, 把...送进疯人院, 把...处死, 杀掉, 葬掉", "e": ""},
{"r": 884, "w": "turn sb away", "c": "把...打发走, 解雇, 拒绝接纳", "e": ""},
{"r": 885, "w": "while away the time", "c": "消磨时光,把时间白白浪费掉", "e": ""},
{"r": 886, "w": "find one's own level", "c": "找到相称的位置", "e": ""},
{"r": 887, "w": "give sb a level look", "c": "盯某人一眼", "e": ""},
{"r": 888, "w": "in the second place", "c": "其次, 第二点", "e": ""},
{"r": 889, "w": "a job lot", "c": "整批买卖的杂货", "e": ""},
{"r": 890, "w": "do a job on sb", "c": "毁了某人", "e": ""},
{"r": 891, "w": "just the job", "c": "正是需要的东西", "e": ""},
{"r": 892, "w": "try sb for a job", "c": "让某人试做某项工作, 试用某人", "e": ""},
{"r": 893, "w": "as early as", "c": "早在…", "e": ""},
{"r": 894, "w": "a back issue", "c": "过期期刊", "e": ""},
{"r": 895, "w": "have no issue", "c": "没有子女,无嗣", "e": ""},
{"r": 896, "w": "something of the kind", "c": "类似的事物", "e": ""},
{"r": 897, "w": "as far as", "c": "远到, 直到, 至于", "e": ""},
{"r": 898, "w": "as far as i can see", "c": "据我所知,在我看来", "e": ""},
{"r": 899, "w": "as far as i know", "c": "就我所知", "e": ""},
{"r": 900, "w": "as far back as", "c": "远在...", "e": ""},
{"r": 901, "w": "in as far as", "c": "在...的限度内, 在...的范围内, 到如此程度", "e": ""},
{"r": 902, "w": "as black as night", "c": "漆黑", "e": ""},
{"r": 903, "w": "be on the market", "c": "被供应出售", "e": ""},
{"r": 904, "w": "come into the market", "c": "上市", "e": ""},
{"r": 905, "w": "give sb a black look", "c": "恶狠狠地瞪(某人)一眼", "e": ""},
{"r": 906, "w": "take sb to court", "c": "把某人送上法庭,对某人起诉", "e": ""},
{"r": 907, "w": "a little while", "c": "一会儿,短时间", "e": ""},
{"r": 908, "w": "as early as possible", "c": "尽快地", "e": ""},
{"r": 909, "w": "as far as possible", "c": "尽可能, 尽量", "e": ""},
{"r": 910, "w": "as much as possible", "c": "尽可能", "e": ""},
{"r": 911, "w": "do one's possible", "c": "尽力", "e": ""},
{"r": 912, "w": "little or no", "c": "很少,几乎没有", "e": ""},
{"r": 913, "w": "have nothing in one", "c": "不足道, 不出众", "e": ""},
{"r": 914, "w": "have nothing of the", "c": "完全不像(是)...", "e": ""},
{"r": 915, "w": "have nothing on sb", "c": "对某人毫不占优势, 不拥有表明某人确有罪的证据", "e": ""},
{"r": 916, "w": "nothing of the kind", "c": "哪儿的话", "e": ""},
{"r": 917, "w": "meet one's end", "c": "死", "e": ""},
{"r": 918, "w": "meet the case", "c": "令人满意,合适", "e": ""},
{"r": 919, "w": "more than meet the eye", "c": "隐藏的事实, 看不到的困难或理由", "e": ""},
{"r": 920, "w": "be of no effect", "c": "无效", "e": ""},
{"r": 921, "w": "to no effect", "c": "无效", "e": ""},
{"r": 922, "w": "to the effect that", "c": "大意是, 以便", "e": ""},
{"r": 923, "w": "follow the lead of sb", "c": "效法(某人), 以(某人)为榜样", "e": ""},
{"r": 924, "w": "give sb a lead", "c": "给某人作出榜样,给某人起带头作用;提示某人", "e": ""},
{"r": 925, "w": "hold the lead", "c": "保持领先地位", "e": ""},
{"r": 926, "w": "lead sb a life", "c": "经常使某人不得安宁", "e": ""},
{"r": 927, "w": "lead the way", "c": "带路, 示范", "e": ""},
{"r": 928, "w": "take the lead", "c": "为首, 带头", "e": ""},
{"r": 929, "w": "all the year around", "c": "一年到头,整年", "e": ""},
{"r": 930, "w": "get the run around", "c": "有外遇,和异性鬼混", "e": ""},
{"r": 931, "w": "know one's way around", "c": "熟谙业务", "e": ""},
{"r": 932, "w": "show sb around", "c": "领某人参观", "e": ""},
{"r": 933, "w": "the other way around", "c": "从相反方向", "e": ""},
{"r": 934, "w": "with the result that", "c": "其结果是...", "e": ""},
{"r": 935, "w": "a friend in court", "c": "有势力的朋友", "e": ""},
{"r": 936, "w": "whether or no", "c": "不管怎样, 无论如何", "e": ""},
{"r": 937, "w": "father sb on sb", "c": "证明后者是前者的生父", "e": ""},
{"r": 938, "w": "have no idea", "c": "不知道，不了解; 没谱儿", "e": ""},
{"r": 939, "w": "sit on sb", "c": "责备, 压制", "e": ""},
{"r": 940, "w": "sit sb out", "c": "比...坐得久", "e": ""},
{"r": 941, "w": "call sb by name", "c": "叫某人名字", "e": ""},
{"r": 942, "w": "have one's name up", "c": "成名", "e": ""},
{"r": 943, "w": "in one's own name", "c": "以自己的名义", "e": ""},
{"r": 944, "w": "name the day", "c": "确定日期", "e": ""},
{"r": 945, "w": "to one's name", "c": "属于自己", "e": ""},
{"r": 946, "w": "a book stand", "c": "书摊", "e": ""},
{"r": 947, "w": "be off one's game", "c": "竞技状态不佳", "e": ""},
{"r": 948, "w": "be on one's game", "c": "竞技状态佳", "e": ""},
{"r": 949, "w": "give the game away", "c": "洩密,透露内幕,露出蛛丝马蹟", "e": ""},
{"r": 950, "w": "have a game with sb", "c": "企图作弄某人, 企图欺骗某人", "e": ""},
{"r": 951, "w": "one night stand", "c": "一夜情", "e": ""},
{"r": 952, "w": "play sb's game", "c": "做使(某人)获利的事, 帮(某人的)大忙", "e": ""},
{"r": 953, "w": "play the game", "c": "遵守比赛规则, 行动光明正大", "e": ""},
{"r": 954, "w": "stand by sb's side", "c": "站在某人旁边, 道义上支持某人", "e": ""},
{"r": 955, "w": "stand on one's right", "c": "坚持自己的权利", "e": ""},
{"r": 956, "w": "stand to one's word", "c": "遵守诺言, 守约", "e": ""},
{"r": 957, "w": "stand well with sb", "c": "得某人好感, 受某人宠爱", "e": ""},
{"r": 958, "w": "take the stand", "c": "站在证人席上作证", "e": ""},
{"r": 959, "w": "the name of the game", "c": "问题的关键,事情的实质,事物的本质", "e": ""},
{"r": 960, "w": "the body of a book", "c": "书籍正文", "e": ""},
{"r": 961, "w": "down the line", "c": "到处, 完全地", "e": ""},
{"r": 962, "w": "go up the line", "c": "上前线", "e": ""},
{"r": 963, "w": "hold the line", "c": "不挂断, 坚定不移", "e": ""},
{"r": 964, "w": "in sb's line", "c": "是某人擅长的", "e": ""},
{"r": 965, "w": "keep sb in line", "c": "控制住某人使他规规矩矩", "e": ""},
{"r": 966, "w": "line up with sb", "c": "跟某人过往甚密,与某人为伍", "e": ""},
{"r": 967, "w": "out of sb's line", "c": "非某人所擅长的", "e": ""},
{"r": 968, "w": "put on the line", "c": "冒险", "e": ""},
{"r": 969, "w": "take one's own line", "c": "干自己的本行", "e": ""},
{"r": 970, "w": "under the line", "c": "在赤道", "e": ""},
{"r": 971, "w": "give the law to sb", "c": "把自己的意志强加于某人", "e": ""},
{"r": 972, "w": "go to law against sb", "c": "跟某人打官司", "e": ""},
{"r": 973, "w": "have the law of sb", "c": "控告某人,对某人起诉", "e": ""},
{"r": 974, "w": "take the law of sb", "c": "控告某人,对某人起诉", "e": ""},
{"r": 975, "w": "a week later", "c": "一星期后", "e": ""},
{"r": 976, "w": "no later than", "c": "不迟于", "e": ""},
{"r": 977, "w": "at the first face", "c": "乍一看,初见", "e": ""},
{"r": 978, "w": "be in bad with sb", "c": "失宠于(某人)", "e": ""},
{"r": 979, "w": "black in the face", "c": "脸色发紫", "e": ""},
{"r": 980, "w": "do sb a bad turn", "c": "做一件有损于某人的事", "e": ""},
{"r": 981, "w": "face the fact", "c": "正视事实,勇敢地面对事实", "e": ""},
{"r": 982, "w": "go to the bad", "c": "变坏, 得病, 弄得没办法", "e": ""},
{"r": 983, "w": "in bad with sb", "c": "失宠于某人", "e": ""},
{"r": 984, "w": "in the face of day", "c": "公开地", "e": ""},
{"r": 985, "w": "look sb in the face", "c": "正视某人, 直视某人的脸", "e": ""},
{"r": 986, "w": "set one's face against", "c": "坚决反对, 抵制", "e": ""},
{"r": 987, "w": "show one's face", "c": "露面, 到场", "e": ""},
{"r": 988, "w": "to go to the bad", "c": "变坏, 堕落, 得病, 弄得毫无办法", "e": ""},
{"r": 989, "w": "to sb's face", "c": "当着某人的面, 坦白地, 公开地, 勇敢地", "e": ""},
{"r": 990, "w": "carry all before one", "c": "势如破竹,获巨大成功,万事如意", "e": ""},
{"r": 991, "w": "carry on with sb", "c": "与...调情", "e": ""},
{"r": 992, "w": "carry one's point", "c": "达到目的, 说服别人同意自己的观点", "e": ""},
{"r": 993, "w": "carry sb through", "c": "有效地帮助渡过疾病 / 困难时期 / 难关", "e": ""},
{"r": 994, "w": "carry the house", "c": "博得满堂喝采", "e": ""},
{"r": 995, "w": "carry the world before one", "c": "迅速全面成功", "e": ""},
{"r": 996, "w": "carry through to the end", "c": "将…进行到底", "e": ""},
{"r": 997, "w": "carry with one", "c": "记得", "e": ""},
{"r": 998, "w": "lose a move to sb", "c": "输某人一着", "e": ""},
{"r": 999, "w": "lose no time", "c": "不失时机,抓紧时间,立即", "e": ""},
{"r": 1000, "w": "lose one's form", "c": "竞技状态不好", "e": ""}
];
