/* Common English idioms — curated seeds + ECDICT (skywind3000/ECDICT, MIT/open). { r:rank, w:phrase, c:Chinese, e:English def }. */
window.IDIOMS = [
{"r": 1, "w": "break the ice", "c": "打破僵局，破冰", "e": "do or say something to relieve tension and start conversation"},
{"r": 2, "w": "a piece of cake", "c": "小菜一碟，轻而易举", "e": "something very easy to do"},
{"r": 3, "w": "under the weather", "c": "身体不适", "e": "feeling slightly ill"},
{"r": 4, "w": "once in a blue moon", "c": "千载难逢，难得", "e": "very rarely"},
{"r": 5, "w": "cost an arm and a leg", "c": "价格昂贵", "e": "be very expensive"},
{"r": 6, "w": "hit the sack", "c": "上床睡觉", "e": "go to bed"},
{"r": 7, "w": "let the cat out of the bag", "c": "泄露秘密", "e": "reveal a secret carelessly"},
{"r": 8, "w": "spill the beans", "c": "泄露秘密", "e": "reveal secret information"},
{"r": 9, "w": "break a leg", "c": "祝你好运（演出前）", "e": "good luck (said before a performance)"},
{"r": 10, "w": "bite the bullet", "c": "咬牙忍受，硬着头皮做", "e": "force yourself to do something difficult"},
{"r": 11, "w": "hit the nail on the head", "c": "一针见血，说得正对", "e": "describe exactly what is causing a situation"},
{"r": 12, "w": "the ball is in your court", "c": "该你做决定了", "e": "it is now your turn to decide or act"},
{"r": 13, "w": "beat around the bush", "c": "拐弯抹角", "e": "avoid getting to the main point"},
{"r": 14, "w": "cut to the chase", "c": "直奔主题", "e": "get to the point without wasting time"},
{"r": 15, "w": "on the same page", "c": "看法一致", "e": "in agreement; sharing the same understanding"},
{"r": 16, "w": "call it a day", "c": "收工，到此为止", "e": "stop working on something"},
{"r": 17, "w": "get out of hand", "c": "失控", "e": "become impossible to control"},
{"r": 18, "w": "pull someone's leg", "c": "开玩笑，逗某人", "e": "tease or joke with someone"},
{"r": 19, "w": "a blessing in disguise", "c": "因祸得福", "e": "a good thing that at first seemed bad"},
{"r": 20, "w": "speak of the devil", "c": "说曹操，曹操到", "e": "the person we were talking about appears"},
{"r": 21, "w": "the last straw", "c": "最后一根稻草，忍无可忍", "e": "the final problem that makes a situation unbearable"},
{"r": 22, "w": "burn the midnight oil", "c": "开夜车，熬夜", "e": "work or study late into the night"},
{"r": 23, "w": "throw in the towel", "c": "认输，放弃", "e": "give up; admit defeat"},
{"r": 24, "w": "miss the boat", "c": "错失良机", "e": "miss an opportunity"},
{"r": 25, "w": "on cloud nine", "c": "欣喜若狂", "e": "extremely happy"},
{"r": 26, "w": "feeling blue", "c": "情绪低落", "e": "feeling sad or depressed"},
{"r": 27, "w": "green with envy", "c": "非常嫉妒", "e": "very jealous"},
{"r": 28, "w": "better late than never", "c": "迟做总比不做好", "e": "doing something late is better than not at all"},
{"r": 29, "w": "actions speak louder than words", "c": "行动胜于言辞", "e": "what you do matters more than what you say"},
{"r": 30, "w": "the best of both worlds", "c": "两全其美", "e": "an ideal situation combining two advantages"},
{"r": 31, "w": "add insult to injury", "c": "雪上加霜", "e": "make a bad situation worse"},
{"r": 32, "w": "barking up the wrong tree", "c": "找错对象，弄错方向", "e": "pursuing a mistaken line of thought or action"},
{"r": 33, "w": "cry over spilt milk", "c": "为已发生的事懊悔（无济于事）", "e": "be upset about something that cannot be changed"},
{"r": 34, "w": "every cloud has a silver lining", "c": "黑暗中总有一线光明", "e": "there is something good in every bad situation"},
{"r": 35, "w": "give the benefit of the doubt", "c": "姑且相信", "e": "choose to believe someone despite doubts"},
{"r": 36, "w": "go back to the drawing board", "c": "从头再来", "e": "start again after a failed attempt"},
{"r": 37, "w": "hang in there", "c": "坚持住，挺住", "e": "don't give up despite difficulty"},
{"r": 38, "w": "hit the books", "c": "用功学习", "e": "study hard"},
{"r": 39, "w": "in hot water", "c": "陷入困境，惹上麻烦", "e": "in trouble"},
{"r": 40, "w": "it's not rocket science", "c": "这并不难", "e": "it is not complicated or hard to understand"},
{"r": 41, "w": "jump on the bandwagon", "c": "随大流，赶时髦", "e": "join an activity that has become popular"},
{"r": 42, "w": "keep an eye on", "c": "留意，照看", "e": "watch carefully"},
{"r": 43, "w": "kill two birds with one stone", "c": "一石二鸟", "e": "accomplish two things with a single action"},
{"r": 44, "w": "leave no stone unturned", "c": "想方设法，竭尽全力", "e": "try every possible way to achieve something"},
{"r": 45, "w": "let sleeping dogs lie", "c": "别惹是非，别旧事重提", "e": "avoid restarting an old conflict"},
{"r": 46, "w": "to make a long story short", "c": "长话短说", "e": "tell something briefly"},
{"r": 47, "w": "no pain, no gain", "c": "不劳无获", "e": "you must work hard to get results"},
{"r": 48, "w": "off the hook", "c": "摆脱困境，脱身", "e": "no longer in trouble or under obligation"},
{"r": 49, "w": "on the ball", "c": "机敏，能干", "e": "alert and quick to understand"},
{"r": 50, "w": "out of the blue", "c": "突然，出乎意料", "e": "unexpectedly; without warning"},
{"r": 51, "w": "pay through the nose", "c": "花高价，被宰", "e": "pay far too much for something"},
{"r": 52, "w": "pull yourself together", "c": "振作起来", "e": "regain control of your emotions"},
{"r": 53, "w": "rain on someone's parade", "c": "扫兴，泼冷水", "e": "spoil someone's plans or happiness"},
{"r": 54, "w": "see eye to eye", "c": "看法一致", "e": "agree completely with someone"},
{"r": 55, "w": "sit on the fence", "c": "持观望态度，骑墙", "e": "avoid making a decision"},
{"r": 56, "w": "take it with a grain of salt", "c": "半信半疑", "e": "don't fully believe something"},
{"r": 57, "w": "the tip of the iceberg", "c": "冰山一角", "e": "a small visible part of a much bigger problem"},
{"r": 58, "w": "time flies", "c": "光阴似箭", "e": "time passes very quickly"},
{"r": 59, "w": "up in the air", "c": "悬而未决", "e": "uncertain; not yet decided"},
{"r": 60, "w": "when pigs fly", "c": "绝不可能", "e": "something that will never happen"},
{"r": 61, "w": "you can say that again", "c": "你说得太对了", "e": "I completely agree"},
{"r": 62, "w": "a dime a dozen", "c": "多得很，不值钱", "e": "very common and of little value"},
{"r": 63, "w": "back to square one", "c": "回到原点", "e": "back to the very beginning"},
{"r": 64, "w": "bend over backwards", "c": "竭尽全力（帮忙）", "e": "try very hard to help someone"},
{"r": 65, "w": "blow off steam", "c": "发泄情绪", "e": "release anger or stress"},
{"r": 66, "w": "by the skin of your teeth", "c": "侥幸，险些", "e": "only just; barely succeed"},
{"r": 67, "w": "cut corners", "c": "偷工减料，走捷径", "e": "do something cheaply or carelessly to save effort"},
{"r": 68, "w": "down to earth", "c": "脚踏实地，务实", "e": "practical and sensible"},
{"r": 69, "w": "drive someone up the wall", "c": "让某人抓狂", "e": "annoy someone greatly"},
{"r": 70, "w": "face the music", "c": "承担后果", "e": "accept the unpleasant consequences"},
{"r": 71, "w": "get cold feet", "c": "临阵退缩，胆怯", "e": "become nervous and hesitant before an event"},
{"r": 72, "w": "give someone a hand", "c": "帮某人一把", "e": "help someone"},
{"r": 73, "w": "go the extra mile", "c": "加倍努力", "e": "make more effort than expected"},
{"r": 74, "w": "hit the road", "c": "出发，上路", "e": "leave; begin a journey"},
{"r": 75, "w": "in the same boat", "c": "处境相同", "e": "in the same difficult situation as others"},
{"r": 76, "w": "jump the gun", "c": "操之过急，抢先行动", "e": "act too soon, before the right time"},
{"r": 77, "w": "keep your chin up", "c": "振作，别灰心", "e": "stay cheerful in a difficult situation"},
{"r": 78, "w": "on thin ice", "c": "如履薄冰，处境危险", "e": "in a risky or precarious situation"},
{"r": 79, "w": "play it by ear", "c": "见机行事，随机应变", "e": "decide as you go rather than planning"},
{"r": 80, "w": "pull strings", "c": "走后门，动用关系", "e": "use influence or connections to get something"},
{"r": 81, "w": "put all your eggs in one basket", "c": "孤注一掷", "e": "risk everything on a single plan"},
{"r": 82, "w": "raining cats and dogs", "c": "倾盆大雨", "e": "raining very heavily"},
{"r": 83, "w": "read between the lines", "c": "体会言外之意", "e": "understand a hidden or implied meaning"},
{"r": 84, "w": "ring a bell", "c": "似曾相识，有点印象", "e": "sound familiar"},
{"r": 85, "w": "rule of thumb", "c": "经验法则", "e": "a practical, approximate guideline"},
{"r": 86, "w": "so far so good", "c": "目前为止还不错", "e": "things are going well up to now"},
{"r": 87, "w": "steal someone's thunder", "c": "抢风头", "e": "take attention or credit away from someone"},
{"r": 88, "w": "take a rain check", "c": "改天再约", "e": "politely decline now but accept for a later time"},
{"r": 89, "w": "twist someone's arm", "c": "强迫/说服某人", "e": "persuade someone to do something they're reluctant to"},
{"r": 90, "w": "wrap your head around", "c": "理解，弄懂", "e": "manage to understand something difficult"},
{"r": 91, "w": "have at sb", "c": "扑向某人,袭击某人,对某人拳脚相加", "e": ""},
{"r": 92, "w": "have sb down", "c": "把某人请来作客", "e": ""},
{"r": 93, "w": "have sb in", "c": "把某人叫进来, 请某人到屋里", "e": ""},
{"r": 94, "w": "have sb over", "c": "把某人请到家里来", "e": ""},
{"r": 95, "w": "have sb up", "c": "把某人请来作客, 对某人起诉, 控告某人", "e": ""},
{"r": 96, "w": "have it in for sb", "c": "对某人怀有仇恨, 伺机想害某人, 对某人不怀好意", "e": ""},
{"r": 97, "w": "have it in one", "c": "有…的能力,善于…", "e": ""},
{"r": 98, "w": "have it on sb", "c": "胜过某人, 占某人的上风", "e": ""},
{"r": 99, "w": "have it out with sb", "c": "(与某人)斗一场解决争端, (与某人)决一雌雄, (同某人)讲个明白", "e": ""},
{"r": 100, "w": "have it over sb", "c": "胜过某人,超过某人,比某人强", "e": ""},
{"r": 101, "w": "do sb down", "c": "胜过某人;欺骗某人,中伤某人", "e": ""},
{"r": 102, "w": "do sb in", "c": "杀害, 搞垮, 使累坏", "e": ""},
{"r": 103, "w": "get sb to do", "c": "让(某人)(做)...", "e": ""},
{"r": 104, "w": "have one's say", "c": "有发言机会, 有发言权", "e": ""},
{"r": 105, "w": "have the say", "c": "有最后决定权,有定论", "e": ""},
{"r": 106, "w": "say no to", "c": "拒绝,否认,不同意", "e": ""},
{"r": 107, "w": "say one's say", "c": "畅所欲言", "e": ""},
{"r": 108, "w": "one by one", "c": "一个接一个", "e": ""},
{"r": 109, "w": "this one or that one", "c": "这个还是那个", "e": ""},
{"r": 110, "w": "no one but", "c": "除了…谁也不", "e": ""},
{"r": 111, "w": "from the off", "c": "从头开始,从起点开始,从零开始", "e": ""},
{"r": 112, "w": "do the will of", "c": "服从...的意志", "e": ""},
{"r": 113, "w": "have one's will", "c": "达到自己的愿望", "e": ""},
{"r": 114, "w": "in the can", "c": "（影片等）摄制完成（准备上映）的", "e": ""},
{"r": 115, "w": "all in one", "c": "合为一体,整个的", "e": ""},
{"r": 116, "w": "all one can", "c": "力所能及,竭尽全力", "e": ""},
{"r": 117, "w": "all one to", "c": "对...来说都一样", "e": ""},
{"r": 118, "w": "all the go", "c": "非常流行,风行一时", "e": ""},
{"r": 119, "w": "be all one", "c": "都一样", "e": ""},
{"r": 120, "w": "be all over sb", "c": "讨好某人,巴结某人", "e": ""},
{"r": 121, "w": "have all the say", "c": "有决定一切的权力", "e": ""},
{"r": 122, "w": "have it all over sb", "c": "胜过某人", "e": ""},
{"r": 123, "w": "one and all", "c": "个个都, 全都", "e": ""},
{"r": 124, "w": "the all and the one", "c": "全部, 整体", "e": ""},
{"r": 125, "w": "as if as", "c": "至于;关于", "e": ""},
{"r": 126, "w": "make it up with sb", "c": "和某人讲和", "e": ""},
{"r": 127, "w": "make up to sb", "c": "接近, 巴结, 奉承, 向(女子)求爱, 企图得到...的欢心", "e": ""},
{"r": 128, "w": "on the make", "c": "在制作中, 野心勃勃", "e": ""},
{"r": 129, "w": "all one know", "c": "力所能及的一切;尽全力地", "e": ""},
{"r": 130, "w": "in the know", "c": "知道实情,掌握内幕", "e": ""},
{"r": 131, "w": "see sb off", "c": "给某人送行", "e": ""},
{"r": 132, "w": "see with sb", "c": "同意某人的意见,和某人意见一致", "e": ""},
{"r": 133, "w": "all the time", "c": "始终", "e": ""},
{"r": 134, "w": "at no time", "c": "决不", "e": ""},
{"r": 135, "w": "at one time", "c": "同时, 曾经", "e": ""},
{"r": 136, "w": "at the time", "c": "当时,那时", "e": ""},
{"r": 137, "w": "at the time of", "c": "在...的时候", "e": ""},
{"r": 138, "w": "by the time", "c": "到…的时候,截至", "e": ""},
{"r": 139, "w": "have no time for", "c": "讨厌, 不喜欢", "e": ""},
{"r": 140, "w": "in no time", "c": "立刻", "e": ""},
{"r": 141, "w": "in sb's time", "c": "在某人一生中, 当某人在某处工作的期间, 当某人在某处学习的期间", "e": ""},
{"r": 142, "w": "of the time", "c": "当时的, 当代的", "e": ""},
{"r": 143, "w": "one at a time", "c": "一次一个人", "e": ""},
{"r": 144, "w": "take it out of sb", "c": "向(某人)报复, 以...来出气, 使(某人)筋疲力尽 / 疲乏", "e": ""},
{"r": 145, "w": "take it out on sb", "c": "向某人出气", "e": ""},
{"r": 146, "w": "take on sb", "c": "呈现, 具有(特征), 雇用, 招收, 增加, 接纳, 对付, 从事", "e": ""},
{"r": 147, "w": "take one's time", "c": "从容不迫", "e": ""},
{"r": 148, "w": "take one's time over", "c": "从容进行, 不慌不忙, 超过合理时间, 慢吞吞", "e": ""},
{"r": 149, "w": "take sb all his time", "c": "花费某人全部精力", "e": ""},
{"r": 150, "w": "take sb in", "c": "陪同, 在家承接, 改小(衣服), (英)订阅, 观看, 把...尽收眼底, 注意到", "e": ""},
{"r": 151, "w": "take sb off", "c": "学...的样, 模仿", "e": ""},
{"r": 152, "w": "take sb on", "c": "同...较量, 迎战", "e": ""},
{"r": 153, "w": "take sb out", "c": "拿出, 取出, 扣除, 除去, 带...出去, 发泄, 抵充, 取得(专利权), 获得, 领取(执照)", "e": ""},
{"r": 154, "w": "take sb up", "c": "接纳, 拘捕, 责备", "e": ""},
{"r": 155, "w": "take to one's", "c": "逃走, 溜走, 逃之夭夭", "e": ""},
{"r": 156, "w": "take to sb", "c": "喜欢, 亲近", "e": ""},
{"r": 157, "w": "take up with sb", "c": "与...亲密交往, 对...发生兴趣, 致力于", "e": ""},
{"r": 158, "w": "in the year one", "c": "很久以前", "e": ""},
{"r": 159, "w": "think about sb", "c": "考虑, 想, 回想, 想起, 认为", "e": ""},
{"r": 160, "w": "think of sb", "c": "考虑, 关心, 想, 想起, 记得, 想一想, 想象, 想出, 提出", "e": ""},
{"r": 161, "w": "one or two", "c": "一、二个, 很少的", "e": ""},
{"r": 162, "w": "go to the people", "c": "为争取人民对其政府或某计划的支持而举行公民投票", "e": ""},
{"r": 163, "w": "come over sb", "c": "支配, 左右, 攫住, 困扰", "e": ""},
{"r": 164, "w": "come to sb", "c": "突然进入脑海, 突然呈现", "e": ""},
{"r": 165, "w": "be just to sb", "c": "对某人公正", "e": ""},
{"r": 166, "w": "one or other", "c": "或者这个, 或者别个", "e": ""},
{"r": 167, "w": "the other one", "c": "另一个", "e": ""},
{"r": 168, "w": "this that and the other", "c": "形形色色, 诸如此类", "e": ""},
{"r": 169, "w": "this that or the other", "c": "形形色色, 诸如此类", "e": ""},
{"r": 170, "w": "one and only", "c": "唯一的", "e": ""},
{"r": 171, "w": "give it to sb", "c": "痛打某人,教训某人,斥责某人", "e": ""},
{"r": 172, "w": "give one his say", "c": "让某人把话讲出来", "e": ""},
{"r": 173, "w": "give sb time", "c": "给某人放宽时间", "e": ""},
{"r": 174, "w": "give sb up", "c": "认为(某人)没有救了, 宣告无法治好, 表示对...没有希望, 引渡罪犯, 投案", "e": ""},
{"r": 175, "w": "give sb what for", "c": "责骂(某人), 痛打(某人)", "e": ""},
{"r": 176, "w": "a good time", "c": "一段美好时光", "e": ""},
{"r": 177, "w": "as good as", "c": "和...几乎一样, 实际上等于...", "e": ""},
{"r": 178, "w": "be up to no good", "c": "尽干坏事", "e": ""},
{"r": 179, "w": "come to no good", "c": "没有好结果", "e": ""},
{"r": 180, "w": "do sb good", "c": "对某人有益", "e": ""},
{"r": 181, "w": "for the good of", "c": "为了…好,为了…的利益", "e": ""},
{"r": 182, "w": "in good with sb", "c": "讨某人喜欢,得到某人的好感,受到某人的宠爱", "e": ""},
{"r": 183, "w": "no other than", "c": "只有, 正是", "e": ""},
{"r": 184, "w": "to the good", "c": "有好处, 净赚", "e": ""},
{"r": 185, "w": "up to no good", "c": "不怀好意", "e": ""},
{"r": 186, "w": "all the more", "c": "更加", "e": ""},
{"r": 187, "w": "as like as not", "c": "大概,多半,很可能", "e": ""},
{"r": 188, "w": "no more than", "c": "至多", "e": ""},
{"r": 189, "w": "which one would you like", "c": "你喜欢哪一个", "e": ""},
{"r": 190, "w": "for the first time", "c": "第一次", "e": ""},
{"r": 191, "w": "from the very first", "c": "从最初开始", "e": ""},
{"r": 192, "w": "be new with sb", "c": "对某人来说很新奇", "e": ""},
{"r": 193, "w": "by the look of it", "c": "看样子", "e": ""},
{"r": 194, "w": "give sb a look", "c": "对某人看了一眼", "e": ""},
{"r": 195, "w": "look about one", "c": "察看自己的情况", "e": ""},
{"r": 196, "w": "look sb up", "c": "(顺便)拜访, 探望", "e": ""},
{"r": 197, "w": "look sb up and down", "c": "上下打量某人", "e": ""},
{"r": 198, "w": "look up to sb", "c": "尊敬, 尊重, 折服, 敬仰", "e": ""},
{"r": 199, "w": "on the look out for", "c": "注意,寻找,寻觅", "e": ""},
{"r": 200, "w": "to look at sb", "c": "从某人的外表看来", "e": ""},
{"r": 201, "w": "all the way", "c": "从远道, 自始至终, 一路上", "e": ""},
{"r": 202, "w": "as well as", "c": "也, 又", "e": ""},
{"r": 203, "w": "be well with sb", "c": "与某人相处得好", "e": ""},
{"r": 204, "w": "by the way", "c": "在途中, 顺便", "e": ""},
{"r": 205, "w": "do sb well", "c": "盛情款待,热情招待", "e": ""},
{"r": 206, "w": "get in the way", "c": "挡住去路,障碍,碍事", "e": ""},
{"r": 207, "w": "get into the way of", "c": "变得习惯于", "e": ""},
{"r": 208, "w": "get out of the way", "c": "让路,避开;除去,完成", "e": ""},
{"r": 209, "w": "go all the way", "c": "完全一致", "e": ""},
{"r": 210, "w": "go all the way with", "c": "完全同意…的意见", "e": ""},
{"r": 211, "w": "go one's way", "c": "出发, 动身", "e": ""},
{"r": 212, "w": "go out of one's way", "c": "特地, 不怕麻烦, 故意", "e": ""},
{"r": 213, "w": "go out of the way", "c": "不怕麻烦, 故意", "e": ""},
{"r": 214, "w": "go the way of", "c": "走…的道路,重蹈…的覆辙", "e": ""},
{"r": 215, "w": "in no way", "c": "决不", "e": ""},
{"r": 216, "w": "in one way", "c": "在某点上, 在某种程度上, 有几分, 稍微", "e": ""},
{"r": 217, "w": "in one's way", "c": "挡道的, 妨碍人的, 使人不便的, (英)近在咫尺, 在场", "e": ""},
{"r": 218, "w": "in the way", "c": "挡道", "e": ""},
{"r": 219, "w": "in the way of", "c": "在…方面;在…过程中;作为…;阻碍…", "e": ""},
{"r": 220, "w": "look the other way", "c": "故意朝另一边看", "e": ""},
{"r": 221, "w": "make one's way", "c": "前进, 行进, 成功, 发迹", "e": ""},
{"r": 222, "w": "make one's way to", "c": "到...去", "e": ""},
{"r": 223, "w": "on the way out", "c": "即将灭亡", "e": ""},
{"r": 224, "w": "on the way to", "c": "在去...的路上", "e": ""},
{"r": 225, "w": "over the way", "c": "在路对面", "e": ""},
{"r": 226, "w": "see one's way to", "c": "觉得有可能", "e": ""},
{"r": 227, "w": "see one's way to do", "c": "有可能做某事, 有意做某事", "e": ""},
{"r": 228, "w": "take one's way to", "c": "向...走去", "e": ""},
{"r": 229, "w": "think well of sb", "c": "认为某人好", "e": ""},
{"r": 230, "w": "give the use of", "c": "给…使用权", "e": ""},
{"r": 231, "w": "have no use for", "c": "不需要, 厌恶", "e": ""},
{"r": 232, "w": "of no use", "c": "无用", "e": ""},
{"r": 233, "w": "use sb well", "c": "待某人好", "e": ""},
{"r": 234, "w": "a day off", "c": "休息日", "e": ""},
{"r": 235, "w": "a year and a day", "c": "满一年, 一整年", "e": ""},
{"r": 236, "w": "all the day", "c": "整天地", "e": ""},
{"r": 237, "w": "by the day", "c": "按日", "e": ""},
{"r": 238, "w": "give the time of day", "c": "问好", "e": ""},
{"r": 239, "w": "have one's day", "c": "走运", "e": ""},
{"r": 240, "w": "know the time of day", "c": "消息灵通, 机警", "e": ""},
{"r": 241, "w": "of the day", "c": "当时的", "e": ""},
{"r": 242, "w": "on one's day", "c": "在鼎盛时期", "e": ""},
{"r": 243, "w": "one of these day", "c": "日内,总有一天", "e": ""},
{"r": 244, "w": "the other day", "c": "不久前某一天", "e": ""},
{"r": 245, "w": "the time of day", "c": "时刻", "e": ""},
{"r": 246, "w": "this time of the day", "c": "每天的这个时候", "e": ""},
{"r": 247, "w": "as one man", "c": "一致地", "e": ""},
{"r": 248, "w": "make a man of sb", "c": "使某人成人, 使某人成器", "e": ""},
{"r": 249, "w": "find one's way to", "c": "设法到达", "e": ""},
{"r": 250, "w": "one after the other", "c": "相继地", "e": ""},
{"r": 251, "w": "take after sb", "c": "象..., 像..., 与...相象, 学...的样", "e": ""},
{"r": 252, "w": "do one's thing", "c": "以自己独特的方式表现自己的性格", "e": ""},
{"r": 253, "w": "for one thing", "c": "首先", "e": ""},
{"r": 254, "w": "just the thing", "c": "正是想要的", "e": ""},
{"r": 255, "w": "not know the first thing about", "c": "对…一无所知", "e": ""},
{"r": 256, "w": "the first thing", "c": "首先, 在尽可能早的时刻", "e": ""},
{"r": 257, "w": "a good many", "c": "很多", "e": ""},
{"r": 258, "w": "as many as", "c": "和...一样多", "e": ""},
{"r": 259, "w": "tell on sb", "c": "(非正式)告发某人, (正式)起坏作用, 影响", "e": ""},
{"r": 260, "w": "tell sb off", "c": "数落, 责骂, 斥责, 责备, 向...透露消息", "e": ""},
{"r": 261, "w": "at sb's back", "c": "支持(某人), 给(某人)撑腰", "e": ""},
{"r": 262, "w": "be on one's back", "c": "仰卧, 生病卧床", "e": ""},
{"r": 263, "w": "be on sb's back", "c": "嘲笑 / 指责(某人), 打扰 / 惹恼(某人)", "e": ""},
{"r": 264, "w": "get back at sb", "c": "报复某人,向某人报仇", "e": ""},
{"r": 265, "w": "give sb the back", "c": "不再理睬某人", "e": ""},
{"r": 266, "w": "in the back of", "c": "支持,主使", "e": ""},
{"r": 267, "w": "on the back of", "c": "紧随着…又…", "e": ""},
{"r": 268, "w": "see sb back", "c": "送某人回去", "e": ""},
{"r": 269, "w": "see the back of sb", "c": "不理睬某人,摆脱某人", "e": ""},
{"r": 270, "w": "to get off sb's back", "c": "不再嘲笑 / 打扰(某人)", "e": ""},
{"r": 271, "w": "be even with sb", "c": "与(某人)扯平", "e": ""},
{"r": 272, "w": "even up on sb", "c": "向(某人)报复, 向(某人)报答", "e": ""},
{"r": 273, "w": "get even with sb", "c": "与(某人)扯平, 跟(某人)算账, 向(某人)报复", "e": ""},
{"r": 274, "w": "all the year through", "c": "整年, 一年到头", "e": ""},
{"r": 275, "w": "be through with sb", "c": "与某人断绝关系", "e": ""},
{"r": 276, "w": "look sb through and through", "c": "仔细地打量某人", "e": ""},
{"r": 277, "w": "see sb through", "c": "帮助(某人)渡过...", "e": ""},
{"r": 278, "w": "as still as still", "c": "鸦雀无声,万籁俱寂", "e": ""},
{"r": 279, "w": "a good life", "c": "道德的生活, 活得到平均寿命的人, 好的生活", "e": ""},
{"r": 280, "w": "all one's life", "c": "一生", "e": ""},
{"r": 281, "w": "for the life of me", "c": "即使要我的命, 无论如何", "e": ""},
{"r": 282, "w": "not on your life", "c": "一点也不(喜欢)", "e": ""},
{"r": 283, "w": "on your life", "c": "在任何情况下, 无论如何", "e": ""},
{"r": 284, "w": "the other life", "c": "来生", "e": ""},
{"r": 285, "w": "the time of one's life", "c": "一生中最愉快的一段时期", "e": ""},
{"r": 286, "w": "to the life", "c": "逼真地", "e": ""},
{"r": 287, "w": "one too many", "c": "多余的一个", "e": ""},
{"r": 288, "w": "one too many for", "c": "对…来说是多余的,超过了…的能力", "e": ""},
{"r": 289, "w": "put sb on to", "c": "引某人对...注意起来", "e": ""},
{"r": 290, "w": "put sb out of the way", "c": "除掉,监禁某人,消除某人的障碍", "e": ""},
{"r": 291, "w": "put sb through", "c": "替某人接通电话", "e": ""},
{"r": 292, "w": "put sb through to", "c": "把(电话)接通", "e": ""},
{"r": 293, "w": "go about one's work", "c": "着手工作", "e": ""},
{"r": 294, "w": "work sb up", "c": "激起, 引起...的情绪", "e": ""},
{"r": 295, "w": "be one's own man", "c": "不受他人控制", "e": ""},
{"r": 296, "w": "get one's own back", "c": "报复", "e": ""},
{"r": 297, "w": "get one's own way", "c": "独自行动, 自行其事, 一意孤行, 随心所欲, 为所欲为", "e": ""},
{"r": 298, "w": "go one's own way", "c": "一意孤行, 独自行动", "e": ""},
{"r": 299, "w": "have one's own way", "c": "独自行动, 自行其事, 一意孤行, 随心所欲, 为所欲为", "e": ""},
{"r": 300, "w": "in one's own good time", "c": "在方便的时候", "e": ""},
{"r": 301, "w": "make one's own way", "c": "成功, 发迹", "e": ""},
{"r": 302, "w": "of one's own", "c": "属于某人自己的", "e": ""},
{"r": 303, "w": "on one's own", "c": "独自地, 独立地, 主动地", "e": ""},
{"r": 304, "w": "on one's own time", "c": "在非工作时间", "e": ""},
{"r": 305, "w": "on your own", "c": "独立地，自愿地", "e": ""},
{"r": 306, "w": "take one's own life", "c": "自杀", "e": ""},
{"r": 307, "w": "take one's own way", "c": "独自行动, 自行其事, 一意孤行, 随心所欲, 为所欲为", "e": ""},
{"r": 308, "w": "your very own", "c": "完全属你所有", "e": ""},
{"r": 309, "w": "for the last time", "c": "最后一次", "e": ""},
{"r": 310, "w": "last but one", "c": "倒数第二", "e": ""},
{"r": 311, "w": "look one's last at", "c": "朝...看最后一眼", "e": ""},
{"r": 312, "w": "one last time", "c": "最后一次", "e": ""},
{"r": 313, "w": "see the last of", "c": "最后一次看到..., 再也不见到...", "e": ""},
{"r": 314, "w": "the last day", "c": "最后审判日", "e": ""},
{"r": 315, "w": "the last thing", "c": "就寝前的最后一件事,最不愿做的事,万万想不到的事;最新式样", "e": ""},
{"r": 316, "w": "to the last", "c": "到底, 至终", "e": ""},
{"r": 317, "w": "to the very last", "c": "直至最后,至死,战斗到底", "e": ""},
{"r": 318, "w": "for the mean time", "c": "在此期间,暂时", "e": ""},
{"r": 319, "w": "in the mean", "c": "同时;当其时,在其间", "e": ""},
{"r": 320, "w": "in the mean time", "c": "同时;当其时,在其间", "e": ""},
{"r": 321, "w": "become one with", "c": "和….结成一体", "e": ""},
{"r": 322, "w": "call sb down for", "c": "为...责骂某人", "e": ""},
{"r": 323, "w": "call sb up", "c": "打电话给某人", "e": ""},
{"r": 324, "w": "have the call", "c": "处于主要地位", "e": ""},
{"r": 325, "w": "no call for", "c": "不需要", "e": ""},
{"r": 326, "w": "a man of the world", "c": "深通世故的人", "e": ""},
{"r": 327, "w": "a woman of the world", "c": "世故的女人", "e": ""},
{"r": 328, "w": "a world of", "c": "很多,大量", "e": ""},
{"r": 329, "w": "all over the world", "c": "全世界", "e": ""},
{"r": 330, "w": "all the world", "c": "一切", "e": ""},
{"r": 331, "w": "all the world to", "c": "对…来说比什么都重要", "e": ""},
{"r": 332, "w": "come down in the world", "c": "落泊", "e": ""},
{"r": 333, "w": "come into the world", "c": "出生", "e": ""},
{"r": 334, "w": "come up in the world", "c": "(生活或社会地位)提高", "e": ""},
{"r": 335, "w": "for all the world", "c": "完全, 无论如何", "e": ""},
{"r": 336, "w": "for all the world like", "c": "完全像", "e": ""},
{"r": 337, "w": "give the world to", "c": "不惜一切代价", "e": ""},
{"r": 338, "w": "give to the world", "c": "出版, 发表", "e": ""},
{"r": 339, "w": "in the world", "c": "在世界上", "e": ""},
{"r": 340, "w": "man of the world", "c": "饱经世故者，爱享乐者", "e": ""},
{"r": 341, "w": "not for the world", "c": "无论如何不, 决不", "e": ""},
{"r": 342, "w": "out of the world", "c": "十全十美的, 极其动人的, 无比优秀的, 无比精彩的", "e": ""},
{"r": 343, "w": "see the world", "c": "见过世面,见多识广,通晓人情世故", "e": ""},
{"r": 344, "w": "tell the world", "c": "当众说, 断言", "e": ""},
{"r": 345, "w": "the way of the world", "c": "人情世故", "e": ""},
{"r": 346, "w": "the world over", "c": "全世界,遍及全球", "e": ""},
{"r": 347, "w": "think all the world of", "c": "极其看重..., 极其渴望..., 极其热爱...", "e": ""},
{"r": 348, "w": "think the world of", "c": "钦佩, 尊重, 对…评价极高", "e": ""},
{"r": 349, "w": "to the world", "c": "极度地, 完全地", "e": ""},
{"r": 350, "w": "go to school to sb", "c": "跟某人学, 模仿某人", "e": ""},
{"r": 351, "w": "go to the school", "c": "到学校去", "e": ""},
{"r": 352, "w": "the school year", "c": "学年", "e": ""},
{"r": 353, "w": "leave sb be", "c": "任他,别管他", "e": ""},
{"r": 354, "w": "leave sb to it", "c": "听任某人自由行事,不管某人", "e": ""},
{"r": 355, "w": "take one's leave", "c": "告辞", "e": ""},
{"r": 356, "w": "a great many", "c": "许许多多", "e": ""},
{"r": 357, "w": "no great of a", "c": "没有什么了不起的,不大会,不是怎么样的…", "e": ""},
{"r": 358, "w": "the great and the mean", "c": "高贵者与卑贱者", "e": ""},
{"r": 359, "w": "ask for one's time", "c": "要求领取应得工资, 要求领取最后一次的工资", "e": ""},
{"r": 360, "w": "ask the way", "c": "问路", "e": ""},
{"r": 361, "w": "do one's need", "c": "解手", "e": ""},
{"r": 362, "w": "with no need for", "c": "不需要…", "e": ""},
{"r": 363, "w": "feel for sb", "c": "为某人感到惋惜, 怜悯", "e": ""},
{"r": 364, "w": "feel one's way", "c": "摸索着走, 谨慎行事", "e": ""},
{"r": 365, "w": "feel sb out", "c": "试探出某人的态度, 试探出某人的意向", "e": ""},
{"r": 366, "w": "get the feel of", "c": "获得感受,获得体会;熟悉,了解", "e": ""},
{"r": 367, "w": "to the feel", "c": "在触角上,摸起来", "e": ""},
{"r": 368, "w": "have system in one's work", "c": "工作有条理", "e": ""},
{"r": 369, "w": "all the same", "c": "仍然", "e": ""},
{"r": 370, "w": "at the same time", "c": "同时, 但是", "e": ""},
{"r": 371, "w": "be all the same to", "c": "对...无所谓", "e": ""},
{"r": 372, "w": "be the same with", "c": "也一样", "e": ""},
{"r": 373, "w": "come to the same thing", "c": "结果相同", "e": ""},
{"r": 374, "w": "do the same", "c": "照办,採取同样的做法", "e": ""},
{"r": 375, "w": "feel the same to sb", "c": "对某人有同样的看法, 对某人的看法和过去一样", "e": ""},
{"r": 376, "w": "in the same way", "c": "同样地", "e": ""},
{"r": 377, "w": "in the same way as", "c": "如同…一样", "e": ""},
{"r": 378, "w": "just the same", "c": "完全一样, 还是", "e": ""},
{"r": 379, "w": "one and the same", "c": "同一个, 完全一样", "e": ""},
{"r": 380, "w": "the same as", "c": "与...相同, 与...一致", "e": ""},
{"r": 381, "w": "the same to you", "c": "同样也祝你…", "e": ""},
{"r": 382, "w": "the same with", "c": "与……相同", "e": ""},
{"r": 383, "w": "the very same", "c": "正是这个, 完全相同的", "e": ""},
{"r": 384, "w": "think the same of sb", "c": "对某人有同样的看法, 对某人的看法和过去一样", "e": ""},
{"r": 385, "w": "never a one", "c": "没有一个, 没有一个人", "e": ""},
{"r": 386, "w": "with all one's might", "c": "全力以赴地", "e": ""},
{"r": 387, "w": "as in the case with", "c": "与...的情况一样", "e": ""},
{"r": 388, "w": "in no case", "c": "决不", "e": ""},
{"r": 389, "w": "in the case of", "c": "在...的情况", "e": ""},
{"r": 390, "w": "make out one's case", "c": "证明自己有理", "e": ""},
{"r": 391, "w": "put the case that", "c": "假设", "e": ""},
{"r": 392, "w": "a part of", "c": "部分", "e": ""},
{"r": 393, "w": "do one's part", "c": "尽自己的职责", "e": ""},
{"r": 394, "w": "for one's part", "c": "对某人来说, 就个人来说", "e": ""},
{"r": 395, "w": "look the part", "c": "看起来适合这角色", "e": ""},
{"r": 396, "w": "take the part of", "c": "与...站在一边, 袒护, 支持", "e": ""},
{"r": 397, "w": "take the part with", "c": "与...站在一边, 袒护, 支持", "e": ""},
{"r": 398, "w": "a group of", "c": "一组,一队,一群,一伙,一批…", "e": ""},
{"r": 399, "w": "have something on sb", "c": "掌握某人的一些事实", "e": ""},
{"r": 400, "w": "no mean something", "c": "很好的(东西)", "e": ""},
{"r": 401, "w": "see something of the world", "c": "见一些世面", "e": ""},
{"r": 402, "w": "a back number", "c": "过期的刊物, 过时的人", "e": ""},
{"r": 403, "w": "a great number of", "c": "许多", "e": ""},
{"r": 404, "w": "a number of", "c": "许多的", "e": ""},
{"r": 405, "w": "get sb's number", "c": "发现某人的本质, 发现某人的动机", "e": ""},
{"r": 406, "w": "have sb's number", "c": "对某人的能力心中有数", "e": ""},
{"r": 407, "w": "the number of", "c": "…的数目", "e": ""},
{"r": 408, "w": "to the number of", "c": "达到...的数目", "e": ""},
{"r": 409, "w": "at the most", "c": "至多, 最多, 不超过, 充其量", "e": ""},
{"r": 410, "w": "for the most part", "c": "在极大程度上", "e": ""},
{"r": 411, "w": "get the most out of", "c": "最充分地利用…", "e": ""},
{"r": 412, "w": "make the most of", "c": "尽量利用", "e": ""},
{"r": 413, "w": "most of the time", "c": "多数情况下，大多数时候", "e": ""},
{"r": 414, "w": "the most high", "c": "上帝", "e": ""},
{"r": 415, "w": "at one time or another", "c": "在某个时候", "e": ""},
{"r": 416, "w": "one time with another", "c": "前后合起来", "e": ""},
{"r": 417, "w": "one way and another", "c": "千方百计,以种种方法", "e": ""},
{"r": 418, "w": "one way or another", "c": "无论如何", "e": ""},
{"r": 419, "w": "take one thing with another", "c": "考虑各种情况", "e": ""},
{"r": 420, "w": "as much as", "c": "尽...那样多, 差不多", "e": ""},
{"r": 421, "w": "as much as to say", "c": "等于说", "e": ""},
{"r": 422, "w": "be with sb much", "c": "常和某人在一起", "e": ""},
{"r": 423, "w": "in as much as", "c": "既然,因为,由于…", "e": ""},
{"r": 424, "w": "much at one", "c": "几乎相等, 几乎等价", "e": ""},
{"r": 425, "w": "see much of the world", "c": "见过不少世面", "e": ""},
{"r": 426, "w": "a man of family", "c": "有家室者,有妻儿老小者;名门子弟", "e": ""},
{"r": 427, "w": "show sb in", "c": "领(某人)进来", "e": ""},
{"r": 428, "w": "show sb out", "c": "领(某人)出去", "e": ""},
{"r": 429, "w": "show sb the way", "c": "给某人指路 / 带路 / 引路, 给某人作示范, 为某人作指点", "e": ""},
{"r": 430, "w": "show sb up", "c": "使某人蒙羞, (非正式)大大胜过", "e": ""},
{"r": 431, "w": "show the way", "c": "做出样子来", "e": ""},
{"r": 432, "w": "a house of call", "c": "零工待雇处, 常去的场所", "e": ""},
{"r": 433, "w": "on the house", "c": "由店家出钱, 由酒馆老板付钱, 免费地", "e": ""},
{"r": 434, "w": "woman of the house", "c": "女主人", "e": ""},
{"r": 435, "w": "in the area of", "c": "在…方面", "e": ""},
{"r": 436, "w": "in the company of", "c": "在...陪同下", "e": ""},
{"r": 437, "w": "a good while", "c": "好些时候,很长时间", "e": ""},
{"r": 438, "w": "all the while", "c": "一直, 始终", "e": ""},
{"r": 439, "w": "against one's will", "c": "违心地", "e": ""},
{"r": 440, "w": "as many again as", "c": "是…的两倍,比…多一倍", "e": ""},
{"r": 441, "w": "keep in with sb", "c": "与某人友好相处, 与某人结伙, 深得某人欢心", "e": ""},
{"r": 442, "w": "keep sb company", "c": "陪伴某人, 陪某人同走", "e": ""},
{"r": 443, "w": "keep sb on", "c": "继续留下某人", "e": ""},
{"r": 444, "w": "keep the house", "c": "居家不外出", "e": ""},
{"r": 445, "w": "to keep on at sb", "c": "跟(某人)纠缠不休", "e": ""},
{"r": 446, "w": "the how and the why", "c": "方法和理由", "e": ""},
{"r": 447, "w": "let sb be", "c": "听任某人自由行事,不加干涉,随他去吧,听其自然", "e": ""},
{"r": 448, "w": "let sb have it", "c": "让某人吃顿苦头", "e": ""},
{"r": 449, "w": "let sb in for", "c": "使某人遭遇…", "e": ""},
{"r": 450, "w": "let sb in on", "c": "告诉某人有关…,向某人透露…", "e": ""},
{"r": 451, "w": "let sb know", "c": "告诉, 通知", "e": ""},
{"r": 452, "w": "let sb off", "c": "让下车", "e": ""},
{"r": 453, "w": "let sb through", "c": "让某人通过", "e": ""},
{"r": 454, "w": "at sb's service", "c": "听候某人吩咐, 听凭某人使用", "e": ""},
{"r": 455, "w": "at your service", "c": "听候吩咐", "e": ""},
{"r": 456, "w": "be in sb's service", "c": "在某人家帮佣", "e": ""},
{"r": 457, "w": "take sb into one's service", "c": "雇用某人", "e": ""},
{"r": 458, "w": "take the service", "c": "发球, 开球", "e": ""},
{"r": 459, "w": "a big number", "c": "要人,大亨", "e": ""},
{"r": 460, "w": "all over the place", "c": "到处", "e": ""},
{"r": 461, "w": "as big as life", "c": "与原物一样大", "e": ""},
{"r": 462, "w": "in the first place", "c": "首先", "e": ""},
{"r": 463, "w": "in the last place", "c": "最后", "e": ""},
{"r": 464, "w": "know one's place", "c": "知趣", "e": ""},
{"r": 465, "w": "put sb in his place", "c": "使某人不敢越轨, 使某人安分, 使有所收敛, 使有一些自知之明", "e": ""},
{"r": 466, "w": "take one's place", "c": "就座", "e": ""},
{"r": 467, "w": "take the first place", "c": "居首位, 得第一", "e": ""},
{"r": 468, "w": "get one's hand in", "c": "使熟悉工作", "e": ""},
{"r": 469, "w": "give one's hand to sb", "c": "(女子)答应和某人结婚", "e": ""},
{"r": 470, "w": "give sb a hand", "c": "给予(某人)帮助", "e": ""},
{"r": 471, "w": "hand it to sb", "c": "赞扬某人, 承认某人的长处", "e": ""},
{"r": 472, "w": "on one hand", "c": "一方面", "e": ""},
{"r": 473, "w": "on the one hand", "c": "在一方面", "e": ""},
{"r": 474, "w": "on the other hand", "c": "另一方面", "e": ""},
{"r": 475, "w": "show one's hand", "c": "摊牌", "e": ""},
{"r": 476, "w": "take sb by the hand", "c": "拉住某人的手", "e": ""},
{"r": 477, "w": "to one's hand", "c": "在手头", "e": ""},
{"r": 478, "w": "with the even hand", "c": "公平地", "e": ""},
{"r": 479, "w": "begin the world", "c": "开始自己谋生", "e": ""},
{"r": 480, "w": "in the country", "c": "在乡下", "e": ""},
{"r": 481, "w": "by the help of", "c": "借助于,通过", "e": ""},
{"r": 482, "w": "help sb down", "c": "把某人搀扶下来", "e": ""},
{"r": 483, "w": "help sb into", "c": "搀扶某人进入...", "e": ""},
{"r": 484, "w": "help sb off with", "c": "帮某人脱去...", "e": ""},
{"r": 485, "w": "help sb on with", "c": "帮某人穿上...", "e": ""},
{"r": 486, "w": "help sb out", "c": "帮助某人解决难题, 帮助某人摆脱困境, 帮助某人完成工作", "e": ""},
{"r": 487, "w": "help sb out of", "c": "搀扶某人走出...", "e": ""},
{"r": 488, "w": "help sb over", "c": "帮某人越过..., 帮某人度过...", "e": ""},
{"r": 489, "w": "help sb to", "c": "给某人进(食), 帮助某人得到, 帮助某人发现", "e": ""},
{"r": 490, "w": "help sb up", "c": "把某人扶起, 扶某人攀登", "e": ""},
{"r": 491, "w": "if one can help it", "c": "如果有办法可想的话", "e": ""},
{"r": 492, "w": "look to sb for help", "c": "期待某人帮助", "e": ""},
{"r": 493, "w": "with the help of", "c": "借助于…,在…的帮助下", "e": ""},
{"r": 494, "w": "a small number of", "c": "少量的...", "e": ""},
{"r": 495, "w": "in the small of the back", "c": "在腰背部", "e": ""},
{"r": 496, "w": "talk at sb", "c": "影射某人, 指桑骂槐地讲某人", "e": ""},
{"r": 497, "w": "talk down to sb", "c": "用高人一等的口气对某人讲话, 对某人讲得简单", "e": ""},
{"r": 498, "w": "talk one's way out of", "c": "通过交谈摆脱困境", "e": ""},
{"r": 499, "w": "talk to sb", "c": "找某人谈话, (非正式)责备某人", "e": ""},
{"r": 500, "w": "the small of the back", "c": "腰背部", "e": ""},
{"r": 501, "w": "think small of sb", "c": "瞧不起某人", "e": ""},
{"r": 502, "w": "a good turn", "c": "有利的举动", "e": ""},
{"r": 503, "w": "at the turn of the year", "c": "在旧的一年过去的时候", "e": ""},
{"r": 504, "w": "call the turn", "c": "言中", "e": ""},
{"r": 505, "w": "do sb a good turn", "c": "做一件有利于某人的事", "e": ""},
{"r": 506, "w": "give sb a turn", "c": "使某人大吃一惊,把某人吓一跳", "e": ""},
{"r": 507, "w": "in one's turn", "c": "轮到某人", "e": ""},
{"r": 508, "w": "in the turn of a hand", "c": "顷刻间", "e": ""},
{"r": 509, "w": "on the turn", "c": "在转变中, 在变质", "e": ""},
{"r": 510, "w": "the turn of life", "c": "更年期", "e": ""},
{"r": 511, "w": "turn on sb", "c": "突然攻击, 反对, 对...发怒, 依靠, 依赖, 取决于", "e": ""},
{"r": 512, "w": "turn one's back on", "c": "背弃, 抛弃", "e": ""},
{"r": 513, "w": "turn one's hand to", "c": "承担", "e": ""},
{"r": 514, "w": "turn sb against sb", "c": "使某人与...作对, 使转而反对, 使与...为敌", "e": ""},
{"r": 515, "w": "turn sb down", "c": "关小, 调低, 拒绝, 摒弃, 翻下, 向下折转, 使面朝下", "e": ""},
{"r": 516, "w": "turn sb in", "c": "交出, 上缴, 把...向里折, 告发, 交给警方, 出卖, 作出", "e": ""},
{"r": 517, "w": "turn sb off", "c": "(使)厌烦, (使)讨厌, 使不感兴趣, 解雇, 把...绞死", "e": ""},
{"r": 518, "w": "turn sb on", "c": "产生幻觉, 变得兴奋, 刺激, 激起, 使生快感, 使产生性快感", "e": ""},
{"r": 519, "w": "turn sb over", "c": "交出, 上缴, 把...向里折, 告发, 交给警方, 出卖, 作出", "e": ""},
{"r": 520, "w": "turn sb over to", "c": "移交, 让出, 交出, 交给", "e": ""},
{"r": 521, "w": "turn the other way", "c": "转向另一侧", "e": ""},
{"r": 522, "w": "turn to sb", "c": "转向, 翻到(某页), 变成, 求教于, 讨教于, 致力于, 着手, 开始工作, 积极行动", "e": ""},
{"r": 523, "w": "turn to sb for help", "c": "求某人帮助", "e": ""},
{"r": 524, "w": "provide for sb", "c": "赡养, 提供生计", "e": ""},
{"r": 525, "w": "at the start", "c": "开始, 起初", "e": ""},
{"r": 526, "w": "at the very start", "c": "一开始", "e": ""},
{"r": 527, "w": "get the start of sb", "c": "比某人居先, 比某人占优势", "e": ""},
{"r": 528, "w": "have the start of sb", "c": "比某人居先, 比某人占优势", "e": ""},
{"r": 529, "w": "start after sb", "c": "开始追赶某人", "e": ""},
{"r": 530, "w": "start against sb", "c": "参加对某人的比赛, 参加对某人的竞争", "e": ""},
{"r": 531, "w": "a case in point", "c": "恰当的例子", "e": ""},
{"r": 532, "w": "at the point of", "c": "靠近, 接近", "e": ""},
{"r": 533, "w": "come to the point", "c": "变尖锐, 到紧要关头, 说到要点, 扼要地说", "e": ""},
{"r": 534, "w": "keep to the point", "c": "扣住主题", "e": ""},
{"r": 535, "w": "off the point", "c": "离题", "e": ""},
{"r": 536, "w": "on the point of", "c": "正要...的时候", "e": ""},
{"r": 537, "w": "point to sb", "c": "指着某人", "e": ""},
{"r": 538, "w": "to the point", "c": "中肯, 扼要", "e": ""},
{"r": 539, "w": "to the point of", "c": "达到...的成度", "e": ""},
{"r": 540, "w": "hold one's hand", "c": "迟迟不动手", "e": ""},
{"r": 541, "w": "hold one's own", "c": "坚持住", "e": ""},
{"r": 542, "w": "hold sb from", "c": "使某人不做…", "e": ""},
{"r": 543, "w": "day of the week", "c": "礼拜", "e": ""},
{"r": 544, "w": "a large number of", "c": "大量的..., 许多...", "e": ""},
{"r": 545, "w": "as large as life", "c": "与原物一样大小", "e": ""},
{"r": 546, "w": "a few of", "c": "少数, 几个,一些", "e": ""},
{"r": 547, "w": "a good few", "c": "相当多", "e": ""},
{"r": 548, "w": "at the end", "c": "在…的末尾", "e": ""},
{"r": 549, "w": "at the end of", "c": "在…末尾,在…结束时", "e": ""},
{"r": 550, "w": "be at the end", "c": "最终", "e": ""},
{"r": 551, "w": "by the end of", "c": "到…结束的时候,到…末", "e": ""},
{"r": 552, "w": "end of the world", "c": "世界末日", "e": ""},
{"r": 553, "w": "in the end", "c": "最后, 终于", "e": ""},
{"r": 554, "w": "keep one's end up", "c": "精神饱满地对付", "e": ""},
{"r": 555, "w": "keep up one's end", "c": "保持愉快和战斗的情绪, 精神饱满地对付", "e": ""},
{"r": 556, "w": "no end of", "c": "无数, 非常", "e": ""},
{"r": 557, "w": "think no end of", "c": "极看重", "e": ""},
{"r": 558, "w": "to no end", "c": "无益地", "e": ""},
{"r": 559, "w": "to the end", "c": "到底", "e": ""},
{"r": 560, "w": "to the end of time", "c": "永远", "e": ""},
{"r": 561, "w": "to the end that", "c": "为…起见,以便", "e": ""},
{"r": 562, "w": "during the week", "c": "在一周的工作日内", "e": ""},
{"r": 563, "w": "be in the right", "c": "站在正义一边", "e": ""},
{"r": 564, "w": "do sb right", "c": "公平对侍某人", "e": ""},
{"r": 565, "w": "in one's own right", "c": "凭本身的头衔", "e": ""},
{"r": 566, "w": "in right of sb", "c": "依仗某人的头衔, 依仗某人的权利", "e": ""},
{"r": 567, "w": "in the right", "c": "站在正义的一边", "e": ""},
{"r": 568, "w": "one's right hand", "c": "右手, 得力助手, 右边", "e": ""},
{"r": 569, "w": "the right way", "c": "正路, 真相, 最正确的方法", "e": ""},
{"r": 570, "w": "bring down the house", "c": "博得满堂喝彩", "e": ""},
{"r": 571, "w": "bring sb to", "c": "使某人苏醒过来", "e": ""},
{"r": 572, "w": "bring the house down", "c": "博得满堂喝彩", "e": ""},
{"r": 573, "w": "hear from sb", "c": "得到(某人)的消息, 接到(某人)的信, 受到...的批评", "e": ""},
{"r": 574, "w": "hear sb out", "c": "听某人把话说完", "e": ""},
{"r": 575, "w": "hear the last of", "c": "最后一次听到", "e": ""},
{"r": 576, "w": "never hear the end of", "c": "听人无休无止地谈论,永为笑柄", "e": ""},
{"r": 577, "w": "a man of his word", "c": "恪守信用者,言之有信者", "e": ""},
{"r": 578, "w": "a man of one's word", "c": "守信的人", "e": ""},
{"r": 579, "w": "from the word go", "c": "从一开始", "e": ""},
{"r": 580, "w": "get the word", "c": "理解意思", "e": ""},
{"r": 581, "w": "give one's word", "c": "对某人说, 答允", "e": ""},
{"r": 582, "w": "give sb one's word", "c": "保证, 允诺, 对某人许下诺言", "e": ""},
{"r": 583, "w": "give the word", "c": "下命令", "e": ""},
{"r": 584, "w": "hold sb to his word", "c": "要某人遵守诺言", "e": ""},
{"r": 585, "w": "in one word", "c": "简言之, 总之, 一句话", "e": ""},
{"r": 586, "w": "keep one's word", "c": "守信", "e": ""},
{"r": 587, "w": "say the word", "c": "发命令", "e": ""},
{"r": 588, "w": "the last word", "c": "最后一句话,定论,最后决定权,最新品种", "e": ""},
{"r": 589, "w": "ask a question of sb", "c": "向某人提一个问题", "e": ""},
{"r": 590, "w": "ask sb a question", "c": "向某人提出一个问题", "e": ""},
{"r": 591, "w": "make no question of", "c": "承认, 不加怀疑", "e": ""},
{"r": 592, "w": "put a question to sb", "c": "向某人提问题", "e": ""},
{"r": 593, "w": "put sb to the question", "c": "拷问某人", "e": ""},
{"r": 594, "w": "put the question", "c": "提交表决", "e": ""},
{"r": 595, "w": "to the question", "c": "针对所讨论的题目, 对题", "e": ""},
{"r": 596, "w": "before one's time", "c": "提早, 在某人出生前, 过早", "e": ""},
{"r": 597, "w": "before the turn of", "c": "在旧的世纪结束、新的世纪开始之前", "e": ""},
{"r": 598, "w": "before the world", "c": "在全世界面前, 公然地", "e": ""},
{"r": 599, "w": "the year before last", "c": "前年", "e": ""},
{"r": 600, "w": "come to the next point", "c": "转入下一个话题", "e": ""},
{"r": 601, "w": "get next to sb", "c": "讨好某人, 与某人接近", "e": ""},
{"r": 602, "w": "in next to no time", "c": "立刻,马上,很快", "e": ""},
{"r": 603, "w": "in the next place", "c": "其次", "e": ""},
{"r": 604, "w": "next but one", "c": "下下一个", "e": ""},
{"r": 605, "w": "the next but one", "c": "下下一个", "e": ""},
{"r": 606, "w": "the next year", "c": "翌年, 第二年", "e": ""},
{"r": 607, "w": "the week after next", "c": "下下星期", "e": ""},
{"r": 608, "w": "the year after next", "c": "后年", "e": ""},
{"r": 609, "w": "as good as a play", "c": "有趣", "e": ""},
{"r": 610, "w": "hold sb in play", "c": "牵制某人,使某人分心", "e": ""},
{"r": 611, "w": "play for one's own hand", "c": "为私利而干", "e": ""},
{"r": 612, "w": "play sb up", "c": "给...造成麻烦, 使痛苦", "e": ""},
{"r": 613, "w": "play the man", "c": "显示男子气概, 无所畏惧", "e": ""},
{"r": 614, "w": "play the woman", "c": "撒娇", "e": ""},
{"r": 615, "w": "keep the run of", "c": "与...保持接触", "e": ""},
{"r": 616, "w": "run in the family", "c": "为一家人所共有,世代相传", "e": ""},
{"r": 617, "w": "run the show", "c": "主持演出, 主持, 操纵", "e": ""},
{"r": 618, "w": "feel not quite the thing", "c": "感到身体不适", "e": ""},
{"r": 619, "w": "look not quite the thing", "c": "看上去身体不适", "e": ""},
{"r": 620, "w": "quite the thing", "c": "很时髦", "e": ""},
{"r": 621, "w": "get on the move", "c": "开始行动,动身", "e": ""},
{"r": 622, "w": "move sb on", "c": "指挥某人朝前走, (命令)去别处, (向别处)前进", "e": ""},
{"r": 623, "w": "on the move", "c": "在活动中, 在发展, 活跃", "e": ""},
{"r": 624, "w": "at the head of", "c": "在...的最前面", "e": ""},
{"r": 625, "w": "be off of one's head", "c": "发疯, 神经错乱, 神志不清", "e": ""},
{"r": 626, "w": "be off one's head", "c": "神经错乱", "e": ""},
{"r": 627, "w": "be out of one's head", "c": "发疯, 神经错乱, 神志不清", "e": ""},
{"r": 628, "w": "be right in one's head", "c": "神志正常", "e": ""},
{"r": 629, "w": "go to sb's head", "c": "使兴奋, 使某人冲昏头脑, 使某人醉酒, 使某人狂妄, 使妄自尊大", "e": ""},
{"r": 630, "w": "head sb off", "c": "使转移方向", "e": ""},
{"r": 631, "w": "hold one's head high", "c": "趾高气扬, 扬眉吐气", "e": ""},
{"r": 632, "w": "in the head", "c": "脑海里", "e": ""},
{"r": 633, "w": "in the night", "c": "在夜里", "e": ""},
{"r": 634, "w": "in the still of night", "c": "更深夜静时", "e": ""},
{"r": 635, "w": "keep one's head", "c": "保持冷静", "e": ""},
{"r": 636, "w": "over sb's head", "c": "使某人不能理解", "e": ""},
{"r": 637, "w": "put a head on sb", "c": "击败某人", "e": ""},
{"r": 638, "w": "put up for the night", "c": "投宿,过夜,留过夜", "e": ""},
{"r": 639, "w": "run one's head off", "c": "狂奔不已", "e": ""},
{"r": 640, "w": "show one's head", "c": "到场", "e": ""},
{"r": 641, "w": "take into one's head", "c": "突然想到", "e": ""},
{"r": 642, "w": "talk sb's head off", "c": "对某人说个不停, 对某人唠叨不休", "e": ""},
{"r": 643, "w": "the night before last", "c": "前晚", "e": ""},
{"r": 644, "w": "the other night", "c": "不久前的一个夜晚", "e": ""},
{"r": 645, "w": "turn sb's head", "c": "使某人感到骄傲, 使某人头脑发热", "e": ""},
{"r": 646, "w": "under the night", "c": "在黑夜的掩护下,趁黑夜", "e": ""},
{"r": 647, "w": "live the part", "c": "把角色演活了", "e": ""},
{"r": 648, "w": "at the side of", "c": "在…旁边;与…相比", "e": ""},
{"r": 649, "w": "by the side of", "c": "在...附近, 和...一起比较", "e": ""},
{"r": 650, "w": "come down on the side of", "c": "站在…一边,决定支持", "e": ""},
{"r": 651, "w": "go over the side", "c": "私自离开船只(或基地)", "e": ""},
{"r": 652, "w": "have no side", "c": "很谦虚", "e": ""},
{"r": 653, "w": "let the side down", "c": "有失众望", "e": ""},
{"r": 654, "w": "on the high side", "c": "偏高", "e": ""},
{"r": 655, "w": "on the other side", "c": "另一方面", "e": ""},
{"r": 656, "w": "on the right side of", "c": "不到,不满", "e": ""},
{"r": 657, "w": "on the side", "c": "作为兼职, 另外", "e": ""},
{"r": 658, "w": "on the side of", "c": "站在…一边，赞助", "e": ""},
{"r": 659, "w": "on the small side", "c": "较小", "e": ""},
{"r": 660, "w": "over the side", "c": "上船", "e": ""},
{"r": 661, "w": "take sb on one side", "c": "把某人拉到一边, 置某人于一旁", "e": ""},
{"r": 662, "w": "take the side of sb", "c": "同意某人, 支持某人, 袒护某人, 偏袒某人", "e": ""},
{"r": 663, "w": "a set of", "c": "一组,一套,一副,一批,一连串", "e": ""},
{"r": 664, "w": "set about one's work", "c": "开始工作", "e": ""},
{"r": 665, "w": "set one's hand to", "c": "着手, 批准, 签字", "e": ""},
{"r": 666, "w": "set sb down", "c": "(英)停车使(乘客)下车, 登记, (非正式)申斥, (非正式)责骂, 击败", "e": ""},
{"r": 667, "w": "a month or so", "c": "一个月左右", "e": ""},
{"r": 668, "w": "the month after next", "c": "再下一个月", "e": ""},
{"r": 669, "w": "the month before last", "c": "再上一个月", "e": ""},
{"r": 670, "w": "a man of business", "c": "代理人", "e": ""},
{"r": 671, "w": "do the business", "c": "起作用,奏效,可以满足要求", "e": ""},
{"r": 672, "w": "have no business to do", "c": "无权(做)..., 没有权利(做)...", "e": ""},
{"r": 673, "w": "know one's business", "c": "精通自己一行", "e": ""},
{"r": 674, "w": "the business end", "c": "使用的一头,锐利的一头", "e": ""},
{"r": 675, "w": "a long way from", "c": "距离…遥远", "e": ""},
{"r": 676, "w": "a long word", "c": "很长的时间", "e": ""},
{"r": 677, "w": "as long as", "c": "只要...", "e": ""},
{"r": 678, "w": "in the long run", "c": "长远, 最后", "e": ""},
{"r": 679, "w": "not long for the world", "c": "不久于人世,快要死", "e": ""},
{"r": 680, "w": "an eye for an eye", "c": "以眼还眼, 报复", "e": ""},
{"r": 681, "w": "do sb in the eye", "c": "欺骗(某人), 愚弄(某人)", "e": ""},
{"r": 682, "w": "get the eye", "c": "引人注目;遭人白眼", "e": ""},
{"r": 683, "w": "give sb the eye", "c": "好奇地看着;冷眼看待,冷冷地望着", "e": ""},
{"r": 684, "w": "give the eye", "c": "注目, 给以白眼; 丢眼色", "e": ""},
{"r": 685, "w": "in the eye of", "c": "在…心目中,在…看来", "e": ""},
{"r": 686, "w": "look sb in the eye", "c": "无愧于心地正视某人, 无所畏惧地正视某人", "e": ""},
{"r": 687, "w": "the eye of day", "c": "太阳", "e": ""},
{"r": 688, "w": "to the eye", "c": "从表面上看来", "e": ""},
{"r": 689, "w": "a home from home", "c": "象家里一样舒适的环境", "e": ""},
{"r": 690, "w": "bring home to sb", "c": "使某人深切地感到 / 清楚地认识到", "e": ""},
{"r": 691, "w": "come home to sb", "c": "打入某人的心中, 被某人所理解", "e": ""},
{"r": 692, "w": "make one's way home", "c": "回家去", "e": ""},
{"r": 693, "w": "on one's way home", "c": "在回家的路上", "e": ""},
{"r": 694, "w": "on the way back home", "c": "在回家的路上", "e": ""},
{"r": 695, "w": "on the way home", "c": "在回家途中", "e": ""},
{"r": 696, "w": "one in a million", "c": "百万分之一,极渺茫", "e": ""},
{"r": 697, "w": "one's long home", "c": "坟墓", "e": ""},
{"r": 698, "w": "see sb home", "c": "送某人回家", "e": ""},
{"r": 699, "w": "a power of", "c": "极大的,很多", "e": ""},
{"r": 700, "w": "have sb in one's power", "c": "控制住某人, 能摆布某人", "e": ""},
{"r": 701, "w": "get no change out of", "c": "没有回应,得不到帮助", "e": ""},
{"r": 702, "w": "give sb change", "c": "给某人以相应的报答", "e": ""},
{"r": 703, "w": "of the first water", "c": "第一流的,最好的,上等的", "e": ""},
{"r": 704, "w": "on the water", "c": "在水上, 在船上", "e": ""},
{"r": 705, "w": "put the change on sb", "c": "欺骗某人, 对某人隐瞒", "e": ""},
{"r": 706, "w": "take the water", "c": "下水, 上船, (美)(非正式)退却, (美)(非正式)打退堂鼓", "e": ""},
{"r": 707, "w": "in sb's room", "c": "处于某人的地位, 作为对某人的接替", "e": ""},
{"r": 708, "w": "in the pay of", "c": "受...雇用", "e": ""},
{"r": 709, "w": "in the room of sb", "c": "处于某人的地位, 作为对某人的接替", "e": ""},
{"r": 710, "w": "leave the room", "c": "离开房间;上厕所", "e": ""},
{"r": 711, "w": "no room to turn in", "c": "没有活动余地", "e": ""},
{"r": 712, "w": "pay as one go", "c": "付钱购物,不赊帐", "e": ""},
{"r": 713, "w": "pay one's way", "c": "支付份内的费用, 支付生活费, 勉强维持", "e": ""},
{"r": 714, "w": "pay sb off", "c": "付清工资后解雇(某)人", "e": ""},
{"r": 715, "w": "a young child", "c": "幼童", "e": ""},
{"r": 716, "w": "a young country", "c": "新兴的国家", "e": ""},
{"r": 717, "w": "a young family", "c": "幼小子女", "e": ""},
{"r": 718, "w": "a young man", "c": "青年男子", "e": ""},
{"r": 719, "w": "a young state", "c": "年轻的国家", "e": ""},
{"r": 720, "w": "be young at the work", "c": "对这工作还是新手", "e": ""},
{"r": 721, "w": "as often as", "c": "每当", "e": ""},
{"r": 722, "w": "as often as not", "c": "往往, 多半", "e": ""},
{"r": 723, "w": "in the interest of", "c": "为了, 为了...的利益", "e": ""},
{"r": 724, "w": "a run for one's money", "c": "花钱得到的满足, 激烈的竞争", "e": ""},
{"r": 725, "w": "come into one's money", "c": "继承遗产", "e": ""},
{"r": 726, "w": "for one's money", "c": "依照本人的意见", "e": ""},
{"r": 727, "w": "out of the money", "c": "赌输", "e": ""},
{"r": 728, "w": "follow the development of", "c": "注视着…的发展", "e": ""},
{"r": 729, "w": "with the development of", "c": "随着…的发展", "e": ""},
{"r": 730, "w": "by the book", "c": "按常规", "e": ""},
{"r": 731, "w": "away from the point", "c": "离题", "e": ""},
{"r": 732, "w": "give sb away", "c": "无意中洩露,暴露", "e": ""},
{"r": 733, "w": "give the show away", "c": "露出马脚, 泄露内情", "e": ""},
{"r": 734, "w": "put sb away", "c": "把...送进监狱, 把...送进疯人院, 把...处死, 杀掉, 葬掉", "e": ""},
{"r": 735, "w": "turn sb away", "c": "把...打发走, 解雇, 拒绝接纳", "e": ""},
{"r": 736, "w": "while away the time", "c": "消磨时光,把时间白白浪费掉", "e": ""},
{"r": 737, "w": "a good lot", "c": "大量, 很, 非常", "e": ""},
{"r": 738, "w": "a great lot", "c": "大量", "e": ""},
{"r": 739, "w": "a lot of", "c": "许多的", "e": ""},
{"r": 740, "w": "after the form of", "c": "按照…的格式", "e": ""},
{"r": 741, "w": "in the form of", "c": "以…形式", "e": ""},
{"r": 742, "w": "take the form of", "c": "採取…形式,以…形式出现", "e": ""},
{"r": 743, "w": "at the level of", "c": "在…一级", "e": ""},
{"r": 744, "w": "find one's own level", "c": "找到相称的位置", "e": ""},
{"r": 745, "w": "give sb a level look", "c": "盯某人一眼", "e": ""},
{"r": 746, "w": "on the level", "c": "诚实的 / 地, 真实的 / 地, 公平地, 坦率地, 不耍花招", "e": ""},
{"r": 747, "w": "in the second place", "c": "其次, 第二点", "e": ""},
{"r": 748, "w": "a good job", "c": "幸运事", "e": ""},
{"r": 749, "w": "a job lot", "c": "整批买卖的杂货", "e": ""},
{"r": 750, "w": "just the job", "c": "正是需要的东西", "e": ""},
{"r": 751, "w": "on the job", "c": "工作着, 警惕着", "e": ""},
{"r": 752, "w": "try sb for a job", "c": "让某人试做某项工作, 试用某人", "e": ""},
{"r": 753, "w": "as early as", "c": "早在…", "e": ""},
{"r": 754, "w": "a back issue", "c": "过期期刊", "e": ""},
{"r": 755, "w": "have no issue", "c": "没有子女,无嗣", "e": ""},
{"r": 756, "w": "in the issue", "c": "结果", "e": ""},
{"r": 757, "w": "a kind of", "c": "一种,一类", "e": ""},
{"r": 758, "w": "something of the kind", "c": "类似的事物", "e": ""},
{"r": 759, "w": "the first of its kind", "c": "破天荒,首创", "e": ""},
{"r": 760, "w": "as far as", "c": "远到, 直到, 至于", "e": ""},
{"r": 761, "w": "as far as i can see", "c": "据我所知,在我看来", "e": ""},
{"r": 762, "w": "as far as i know", "c": "就我所知", "e": ""},
{"r": 763, "w": "in as far as", "c": "在...的限度内, 在...的范围内, 到如此程度", "e": ""},
{"r": 764, "w": "as black as night", "c": "漆黑", "e": ""},
{"r": 765, "w": "be on the market", "c": "被供应出售", "e": ""},
{"r": 766, "w": "come into the market", "c": "上市", "e": ""},
{"r": 767, "w": "give sb a black look", "c": "恶狠狠地瞪(某人)一眼", "e": ""},
{"r": 768, "w": "in the market", "c": "上市,待售", "e": ""},
{"r": 769, "w": "make one's market of", "c": "把...作为赚钱的机会, 把...作为赚钱的目的", "e": ""},
{"r": 770, "w": "on the market", "c": "在市场上,供出售,待售", "e": ""},
{"r": 771, "w": "the run of the market", "c": "市场行情", "e": ""},
{"r": 772, "w": "take sb to court", "c": "把某人送上法庭,对某人起诉", "e": ""},
{"r": 773, "w": "a little while", "c": "一会儿,短时间", "e": ""},
{"r": 774, "w": "as early as possible", "c": "尽快地", "e": ""},
{"r": 775, "w": "as far as possible", "c": "尽可能, 尽量", "e": ""},
{"r": 776, "w": "as much as possible", "c": "尽可能", "e": ""},
{"r": 777, "w": "do one's possible", "c": "尽力", "e": ""},
{"r": 778, "w": "little or no", "c": "很少,几乎没有", "e": ""},
{"r": 779, "w": "have nothing in one", "c": "不足道, 不出众", "e": ""},
{"r": 780, "w": "have nothing of the", "c": "完全不像(是)...", "e": ""},
{"r": 781, "w": "have nothing on sb", "c": "对某人毫不占优势, 不拥有表明某人确有罪的证据", "e": ""},
{"r": 782, "w": "nothing of the kind", "c": "哪儿的话", "e": ""},
{"r": 783, "w": "meet one's end", "c": "死", "e": ""},
{"r": 784, "w": "meet the case", "c": "令人满意,合适", "e": ""},
{"r": 785, "w": "more than meet the eye", "c": "隐藏的事实, 看不到的困难或理由", "e": ""},
{"r": 786, "w": "be of no effect", "c": "无效", "e": ""},
{"r": 787, "w": "to no effect", "c": "无效", "e": ""},
{"r": 788, "w": "to the effect that", "c": "大意是, 以便", "e": ""},
{"r": 789, "w": "follow the lead of sb", "c": "效法(某人), 以(某人)为榜样", "e": ""},
{"r": 790, "w": "give sb a lead", "c": "给某人作出榜样,给某人起带头作用;提示某人", "e": ""},
{"r": 791, "w": "hold the lead", "c": "保持领先地位", "e": ""},
{"r": 792, "w": "in the lead", "c": "领先", "e": ""},
{"r": 793, "w": "lead sb a life", "c": "经常使某人不得安宁", "e": ""},
{"r": 794, "w": "lead sb on", "c": "使误信, 率领 / 带领...继续前进", "e": ""},
{"r": 795, "w": "lead sb on to", "c": "诱使某人相信…", "e": ""},
{"r": 796, "w": "lead the way", "c": "带路, 示范", "e": ""},
{"r": 797, "w": "lead the way in", "c": "率先…;领路,带路", "e": ""},
{"r": 798, "w": "take the lead", "c": "为首, 带头", "e": ""},
{"r": 799, "w": "under the lead of", "c": "在…的领导下", "e": ""},
{"r": 800, "w": "all the year around", "c": "一年到头,整年", "e": ""},
{"r": 801, "w": "around the time of", "c": "在…前后,大约在…时候", "e": ""},
{"r": 802, "w": "around the world", "c": "全世界,遍及全世界,世界各地", "e": ""},
{"r": 803, "w": "get the run around", "c": "有外遇,和异性鬼混", "e": ""},
{"r": 804, "w": "in the result", "c": "后来,结果", "e": ""},
{"r": 805, "w": "know one's way around", "c": "熟谙业务", "e": ""},
{"r": 806, "w": "show sb around", "c": "领某人参观", "e": ""},
{"r": 807, "w": "the other way around", "c": "从相反方向", "e": ""},
{"r": 808, "w": "with the result that", "c": "其结果是...", "e": ""},
{"r": 809, "w": "a friend in court", "c": "有势力的朋友", "e": ""},
{"r": 810, "w": "whether or no", "c": "不管怎样, 无论如何", "e": ""},
{"r": 811, "w": "father sb on sb", "c": "证明后者是前者的生父", "e": ""},
{"r": 812, "w": "have no idea", "c": "不知道，不了解; 没谱儿", "e": ""},
{"r": 813, "w": "have no idea of", "c": "不知道..., 想象不到...", "e": ""},
{"r": 814, "w": "sit on sb", "c": "责备, 压制", "e": ""},
{"r": 815, "w": "sit sb out", "c": "比...坐得久", "e": ""},
{"r": 816, "w": "the big idea", "c": "计划,建议", "e": ""},
{"r": 817, "w": "by the name of", "c": "名叫...", "e": ""},
{"r": 818, "w": "call sb by name", "c": "叫某人名字", "e": ""},
{"r": 819, "w": "go by the name of", "c": "称为", "e": ""},
{"r": 820, "w": "have one's name up", "c": "成名", "e": ""},
{"r": 821, "w": "in one's own name", "c": "以自己的名义", "e": ""},
{"r": 822, "w": "name sb for", "c": "提名某人担任…", "e": ""},
{"r": 823, "w": "name the day", "c": "确定日期", "e": ""},
{"r": 824, "w": "of the name of", "c": "名叫...", "e": ""},
{"r": 825, "w": "put one's name down for", "c": "为...而报名", "e": ""},
{"r": 826, "w": "to one's name", "c": "属于自己", "e": ""},
{"r": 827, "w": "under the name of", "c": "名叫...", "e": ""},
{"r": 828, "w": "on the hour", "c": "准点地", "e": ""},
{"r": 829, "w": "a book stand", "c": "书摊", "e": ""},
{"r": 830, "w": "a game of", "c": "一场,一盘,一局", "e": ""},
{"r": 831, "w": "be off one's game", "c": "竞技状态不佳", "e": ""},
{"r": 832, "w": "be on one's game", "c": "竞技状态佳", "e": ""},
{"r": 833, "w": "give the game away", "c": "洩密,透露内幕,露出蛛丝马蹟", "e": ""},
{"r": 834, "w": "have a game with sb", "c": "企图作弄某人, 企图欺骗某人", "e": ""},
{"r": 835, "w": "one night stand", "c": "一夜情", "e": ""},
{"r": 836, "w": "play sb's game", "c": "做使(某人)获利的事, 帮(某人的)大忙", "e": ""},
{"r": 837, "w": "play the game", "c": "遵守比赛规则, 行动光明正大", "e": ""},
{"r": 838, "w": "stand by sb's side", "c": "站在某人旁边, 道义上支持某人", "e": ""},
{"r": 839, "w": "stand in the way of", "c": "阻碍,阻拦,妨碍", "e": ""},
{"r": 840, "w": "stand on one's right", "c": "坚持自己的权利", "e": ""},
{"r": 841, "w": "stand to one's word", "c": "遵守诺言, 守约", "e": ""},
{"r": 842, "w": "stand well with sb", "c": "得某人好感, 受某人宠爱", "e": ""},
{"r": 843, "w": "take the stand", "c": "站在证人席上作证", "e": ""},
{"r": 844, "w": "the name of the game", "c": "问题的关键,事情的实质,事物的本质", "e": ""},
{"r": 845, "w": "a large body of", "c": "一大堆,许多…", "e": ""},
{"r": 846, "w": "the body of a book", "c": "书籍正文", "e": ""},
{"r": 847, "w": "a line of", "c": "一行,一列,一排", "e": ""},
{"r": 848, "w": "down the line", "c": "到处, 完全地", "e": ""},
{"r": 849, "w": "give sb a line on", "c": "给某人一些…的情况", "e": ""},
{"r": 850, "w": "go down the line for", "c": "全力支持...", "e": ""},
{"r": 851, "w": "go up the line", "c": "上前线", "e": ""},
{"r": 852, "w": "hold the line", "c": "不挂断, 坚定不移", "e": ""},
{"r": 853, "w": "in sb's line", "c": "是某人擅长的", "e": ""},
{"r": 854, "w": "keep sb in line", "c": "控制住某人使他规规矩矩", "e": ""},
{"r": 855, "w": "line up with sb", "c": "跟某人过往甚密,与某人为伍", "e": ""},
{"r": 856, "w": "on the line", "c": "处于中间, 立即", "e": ""},
{"r": 857, "w": "out of sb's line", "c": "非某人所擅长的", "e": ""},
{"r": 858, "w": "put on the line", "c": "冒险", "e": ""},
{"r": 859, "w": "take one's own line", "c": "干自己的本行", "e": ""},
{"r": 860, "w": "under the line", "c": "在赤道", "e": ""},
{"r": 861, "w": "give the law to sb", "c": "把自己的意志强加于某人", "e": ""},
{"r": 862, "w": "go to law against sb", "c": "跟某人打官司", "e": ""},
{"r": 863, "w": "have the law of sb", "c": "控告某人,对某人起诉", "e": ""},
{"r": 864, "w": "take the law of sb", "c": "控告某人,对某人起诉", "e": ""},
{"r": 865, "w": "a week later", "c": "一星期后", "e": ""},
{"r": 866, "w": "no later than", "c": "不迟于", "e": ""},
{"r": 867, "w": "a bad job", "c": "白费力的事", "e": ""},
{"r": 868, "w": "a bad life", "c": "不道德的生活, 活不到平均寿命的人", "e": ""},
{"r": 869, "w": "a bad lot", "c": "一个坏蛋", "e": ""},
{"r": 870, "w": "a bad policy", "c": "不明智的政策,下策", "e": ""},
{"r": 871, "w": "a bad word", "c": "猥亵话", "e": ""},
{"r": 872, "w": "at the first face", "c": "乍一看,初见", "e": ""},
{"r": 873, "w": "be in bad with sb", "c": "失宠于(某人)", "e": ""},
{"r": 874, "w": "black in the face", "c": "脸色发紫", "e": ""},
{"r": 875, "w": "do sb a bad turn", "c": "做一件有损于某人的事", "e": ""},
{"r": 876, "w": "face the fact", "c": "正视事实,勇敢地面对事实", "e": ""},
{"r": 877, "w": "go to the bad", "c": "变坏, 得病, 弄得没办法", "e": ""},
{"r": 878, "w": "in the face of", "c": "面对", "e": ""},
{"r": 879, "w": "in the face of day", "c": "公开地", "e": ""},
{"r": 880, "w": "look sb in the face", "c": "正视某人, 直视某人的脸", "e": ""},
{"r": 881, "w": "set one's face against", "c": "坚决反对, 抵制", "e": ""},
{"r": 882, "w": "show one's face", "c": "露面, 到场", "e": ""},
{"r": 883, "w": "to go to the bad", "c": "变坏, 堕落, 得病, 弄得毫无办法", "e": ""},
{"r": 884, "w": "to sb's face", "c": "当着某人的面, 坦白地, 公开地, 勇敢地", "e": ""},
{"r": 885, "w": "to the bad", "c": "亏损", "e": ""},
{"r": 886, "w": "carry all before one", "c": "势如破竹,获巨大成功,万事如意", "e": ""},
{"r": 887, "w": "carry on with sb", "c": "与...调情", "e": ""},
{"r": 888, "w": "carry one's point", "c": "达到目的, 说服别人同意自己的观点", "e": ""},
{"r": 889, "w": "carry sb through", "c": "有效地帮助渡过疾病 / 困难时期 / 难关", "e": ""},
{"r": 890, "w": "carry the can", "c": "代人受过", "e": ""},
{"r": 891, "w": "carry the house", "c": "博得满堂喝采", "e": ""},
{"r": 892, "w": "carry the world before one", "c": "迅速全面成功", "e": ""},
{"r": 893, "w": "carry through to the end", "c": "将…进行到底", "e": ""},
{"r": 894, "w": "carry with one", "c": "记得", "e": ""},
{"r": 895, "w": "lose a move to sb", "c": "输某人一着", "e": ""},
{"r": 896, "w": "lose no time", "c": "不失时机,抓紧时间,立即", "e": ""},
{"r": 897, "w": "lose one's form", "c": "竞技状态不好", "e": ""},
{"r": 898, "w": "lose one's head", "c": "被砍头, 不知所措", "e": ""},
{"r": 899, "w": "lose one's way", "c": "迷路", "e": ""},
{"r": 900, "w": "lose the day", "c": "打败", "e": ""},
{"r": 901, "w": "lose the game", "c": "输了比赛,败北", "e": ""},
{"r": 902, "w": "lose the lead", "c": "失去领先地位,落后", "e": ""},
{"r": 903, "w": "lose the way", "c": "迷路", "e": ""},
{"r": 904, "w": "get out of the road", "c": "让路", "e": ""},
{"r": 905, "w": "get the show on the road", "c": "开始干,着手进行", "e": ""},
{"r": 906, "w": "give sb the road", "c": "让某人通过,给某人让路;把某人打发走,辞退某人", "e": ""},
{"r": 907, "w": "in the road", "c": "挡路", "e": ""},
{"r": 908, "w": "no through road", "c": "此路不通", "e": ""},
{"r": 909, "w": "on the road", "c": "在旅途中, 在...过程中", "e": ""},
{"r": 910, "w": "out of the road", "c": "越出常规,别开生面,不落俗套", "e": ""},
{"r": 911, "w": "put the show on the road", "c": "开始干起来", "e": ""},
{"r": 912, "w": "take the road", "c": "选择特定道路, 出发", "e": ""},
{"r": 913, "w": "take the road of", "c": "占先", "e": ""},
{"r": 914, "w": "take to the road", "c": "出发, 动身", "e": ""},
{"r": 915, "w": "on the authority of", "c": "根据,得到…的授权", "e": ""},
{"r": 916, "w": "leave sb to himself", "c": "听任某人自由行事,不管某人", "e": ""},
{"r": 917, "w": "six to one", "c": "六对一, 相差悬殊", "e": ""},
{"r": 918, "w": "minister to sb", "c": "伺候, 照顾", "e": ""},
{"r": 919, "w": "rate with sb", "c": "受某人好评", "e": ""},
{"r": 920, "w": "no late than", "c": "不迟于…", "e": ""},
{"r": 921, "w": "work late into the night", "c": "工作至深夜", "e": ""},
{"r": 922, "w": "be on the door", "c": "守门, 门口值勤", "e": ""},
{"r": 923, "w": "by the back door", "c": "用隐蔽或不正当的方法, 走后门", "e": ""},
{"r": 924, "w": "show sb the door", "c": "指着门要某人出去, 把某人赶走", "e": ""},
{"r": 925, "w": "show sb to the door", "c": "把某人送到门口", "e": ""},
{"r": 926, "w": "show the door", "c": "把（某人）撵走", "e": ""},
{"r": 927, "w": "a general thing", "c": "惯例", "e": ""},
{"r": 928, "w": "a white night", "c": "白夜, 失眠的夜晚", "e": ""},
{"r": 929, "w": "in the general", "c": "概括地,全面地,普遍地", "e": ""},
{"r": 930, "w": "in the white", "c": "处于尚未完工状态", "e": ""},
{"r": 931, "w": "at the least", "c": "至少, 起码, 无论如何", "e": ""},
{"r": 932, "w": "at the very least", "c": "至少, 起码, 无论如何", "e": ""},
{"r": 933, "w": "in the least", "c": "丝毫", "e": ""},
{"r": 934, "w": "not in the least", "c": "一点不怕", "e": ""},
{"r": 935, "w": "not the least", "c": "丝毫没有", "e": ""},
{"r": 936, "w": "to say the least", "c": "退一步说", "e": ""},
{"r": 937, "w": "to say the least of", "c": "至少可以说,退一步说", "e": ""},
{"r": 938, "w": "give sb the office", "c": "暗示某人", "e": ""},
{"r": 939, "w": "the president of a company", "c": "公司的董事长", "e": ""},
{"r": 940, "w": "the president of a court", "c": "法庭庭长", "e": ""},
{"r": 941, "w": "a general war", "c": "全面战争", "e": ""},
{"r": 942, "w": "world war one", "c": "第一次世界大战", "e": ""},
{"r": 943, "w": "the real thing", "c": "货真价实", "e": ""},
{"r": 944, "w": "a team of", "c": "一队,一组…", "e": ""},
{"r": 945, "w": "offer one's hand", "c": "伸出手(准备握手)", "e": ""},
{"r": 946, "w": "offer sb a hand", "c": "主动帮助某人,向某人求婚", "e": ""},
{"r": 947, "w": "on the team", "c": "是球队的队员", "e": ""},
{"r": 948, "w": "team up with sb", "c": "与某人合作, 与某人协力, 与某人勾结", "e": ""},
{"r": 949, "w": "a young person", "c": "年轻人", "e": ""},
{"r": 950, "w": "at the last minute", "c": "在最后一分钟,在最后的时刻", "e": ""},
{"r": 951, "w": "on the minute", "c": "一分中不差地,准时地", "e": ""},
{"r": 952, "w": "to the last minute", "c": "直至最后一分钟", "e": ""},
{"r": 953, "w": "to the minute", "c": "一分不差", "e": ""},
{"r": 954, "w": "until the last minute", "c": "直到最后时刻", "e": ""},
{"r": 955, "w": "up to the minute", "c": "最新的", "e": ""},
{"r": 956, "w": "a best man", "c": "男傧相", "e": ""},
{"r": 957, "w": "a full general", "c": "四星上将", "e": ""},
{"r": 958, "w": "a full team", "c": "有特别才能的人,身怀绝技者", "e": ""},
{"r": 959, "w": "as best as one can", "c": "尽最大努力", "e": ""},
{"r": 960, "w": "as best one can", "c": "尽最大努力", "e": ""},
{"r": 961, "w": "as best one may", "c": "尽最大努力", "e": ""},
{"r": 962, "w": "at one's best", "c": "处在最佳状态", "e": ""},
{"r": 963, "w": "at the best", "c": "至多, 充其量", "e": ""},
{"r": 964, "w": "at the full", "c": "在充满的时候", "e": ""},
{"r": 965, "w": "do one's best", "c": "尽全力", "e": ""},
{"r": 966, "w": "do one's level best", "c": "全力以赴", "e": ""},
{"r": 967, "w": "do the best one can", "c": "尽自己最大的努力,竭尽全力", "e": ""},
{"r": 968, "w": "for the best", "c": "出于好意", "e": ""},
{"r": 969, "w": "get the best of", "c": "战胜,胜过,佔了…的上风;克服,克制", "e": ""},
{"r": 970, "w": "give one's best", "c": "竭尽全力", "e": ""},
{"r": 971, "w": "give sb best", "c": "承认不如(某人), 向(某人)认输", "e": ""},
{"r": 972, "w": "have the best of", "c": "胜过", "e": ""},
{"r": 973, "w": "in one's best", "c": "穿着节日盛装", "e": ""},
{"r": 974, "w": "make the best of", "c": "充分利用", "e": ""},
{"r": 975, "w": "one's level best", "c": "最大努力, 全力", "e": ""},
{"r": 976, "w": "the best part", "c": "最大的部分", "e": ""},
{"r": 977, "w": "the best people", "c": "上流社会人士", "e": ""},
{"r": 978, "w": "the best policy", "c": "上策", "e": ""},
{"r": 979, "w": "the next best", "c": "仅次于最好的", "e": ""},
{"r": 980, "w": "the next best thing", "c": "次上策,次最好的办法,不得已而为之的办法", "e": ""},
{"r": 981, "w": "to look one's best", "c": "看上去处于最佳状态", "e": ""},
{"r": 982, "w": "to the full", "c": "完全地, 充分地", "e": ""},
{"r": 983, "w": "try one's best", "c": "尽力", "e": ""},
{"r": 984, "w": "with the best", "c": "跟任何人一样好, 不比任何人差", "e": ""},
{"r": 985, "w": "bring sb to reason", "c": "说服某人变得明智些, 使某人讲道理", "e": ""},
{"r": 986, "w": "for no other reason than that", "c": "只是因为", "e": ""},
{"r": 987, "w": "reason with sb against", "c": "与...评理, 用道理劝说, 为了反对...和某人评理", "e": ""},
{"r": 988, "w": "reason with sb for", "c": "为了赞成...和某人评理", "e": ""},
{"r": 989, "w": "a point of view", "c": "观点", "e": ""},
{"r": 990, "w": "hold the view", "c": "持这种看法,认为…", "e": ""},
{"r": 991, "w": "in the view of", "c": "认为", "e": ""},
{"r": 992, "w": "take the long view", "c": "从长远着想,从长计议", "e": ""},
{"r": 993, "w": "to the view", "c": "公开地", "e": ""},
{"r": 994, "w": "a little while ago", "c": "方才", "e": ""},
{"r": 995, "w": "a long time ago", "c": "很久以前", "e": ""},
{"r": 996, "w": "a long while ago", "c": "很长时间以前", "e": ""},
{"r": 997, "w": "in the long term", "c": "长远地", "e": ""},
{"r": 998, "w": "make the first move towards", "c": "朝…迈出第一步", "e": ""},
{"r": 999, "w": "towards the end of", "c": "在…即将结束的时候", "e": ""},
{"r": 1000, "w": "bring sb low", "c": "贬抑,使屈辱,使穷困潦倒", "e": ""}
];
