/* Most common English phrasal verbs, roughly by frequency. Same shape as
   words.js: { r:rank, w:phrase, c:Chinese meaning, e:English definition }. */
window.PHRASAL = [
{"r":1,"w":"give up","c":"放弃；戒掉","e":"stop trying to do something; quit a habit"},
{"r":2,"w":"find out","c":"查明，发现","e":"discover information"},
{"r":3,"w":"look for","c":"寻找","e":"try to find something or someone"},
{"r":4,"w":"go on","c":"继续；发生","e":"continue; happen"},
{"r":5,"w":"come back","c":"回来","e":"return to a place"},
{"r":6,"w":"pick up","c":"捡起；（开车）接某人；学会","e":"lift; collect someone; learn casually"},
{"r":7,"w":"turn on","c":"打开（电器、灯）","e":"start a device or light working"},
{"r":8,"w":"turn off","c":"关闭（电器、灯）","e":"stop a device or light working"},
{"r":9,"w":"get up","c":"起床；站起来","e":"rise from bed; stand up"},
{"r":10,"w":"put on","c":"穿上；戴上","e":"dress in; wear"},
{"r":11,"w":"take off","c":"脱下；（飞机）起飞","e":"remove clothing; (of a plane) leave the ground"},
{"r":12,"w":"wake up","c":"醒来；叫醒","e":"stop sleeping; rouse someone"},
{"r":13,"w":"grow up","c":"长大，成长","e":"become an adult"},
{"r":14,"w":"set up","c":"建立；设置，搭建","e":"establish; arrange or assemble"},
{"r":15,"w":"carry on","c":"继续","e":"continue doing something"},
{"r":16,"w":"break down","c":"（机器）故障；（情绪）崩溃","e":"stop working; lose emotional control"},
{"r":17,"w":"work out","c":"锻炼；解决；想出","e":"exercise; solve; figure out"},
{"r":18,"w":"look after","c":"照顾","e":"take care of someone or something"},
{"r":19,"w":"look forward to","c":"期待","e":"anticipate with pleasure"},
{"r":20,"w":"give in","c":"屈服，让步","e":"stop resisting; yield"},
{"r":21,"w":"go out","c":"出去（社交）；（火、灯）熄灭","e":"leave home for fun; (of fire/light) stop burning"},
{"r":22,"w":"come in","c":"进来","e":"enter a place"},
{"r":23,"w":"get back","c":"返回；取回","e":"return; recover something"},
{"r":24,"w":"take care of","c":"照顾；处理","e":"look after; handle"},
{"r":25,"w":"put off","c":"推迟","e":"postpone"},
{"r":26,"w":"call off","c":"取消","e":"cancel something planned"},
{"r":27,"w":"run out of","c":"用完，耗尽","e":"have no more of something left"},
{"r":28,"w":"bring up","c":"抚养；提出（话题）","e":"raise a child; mention a topic"},
{"r":29,"w":"check out","c":"查看；结账退房","e":"examine; pay and leave a hotel"},
{"r":30,"w":"check in","c":"登记入住；办理登机","e":"register at a hotel or airport"},
{"r":31,"w":"fill out","c":"填写（表格）","e":"complete a form"},
{"r":32,"w":"hold on","c":"等一下；坚持","e":"wait; persevere"},
{"r":33,"w":"hang up","c":"挂断电话","e":"end a phone call"},
{"r":34,"w":"get along","c":"和睦相处","e":"have a friendly relationship"},
{"r":35,"w":"get on","c":"上（车、飞机）；进展","e":"board a vehicle; make progress"},
{"r":36,"w":"get off","c":"下（车）","e":"leave a vehicle"},
{"r":37,"w":"show up","c":"出现，露面","e":"appear; arrive"},
{"r":38,"w":"turn up","c":"出现；调高（音量）","e":"appear unexpectedly; increase volume"},
{"r":39,"w":"turn down","c":"拒绝；调低（音量）","e":"reject; lower volume"},
{"r":40,"w":"put up with","c":"容忍，忍受","e":"tolerate something unpleasant"},
{"r":41,"w":"look up","c":"查阅；向上看","e":"search for information; raise the eyes"},
{"r":42,"w":"look down on","c":"看不起，轻视","e":"regard as inferior"},
{"r":43,"w":"point out","c":"指出","e":"draw attention to a fact"},
{"r":44,"w":"figure out","c":"弄清楚，想出","e":"understand or solve by thinking"},
{"r":45,"w":"come up with","c":"想出，提出","e":"produce an idea or plan"},
{"r":46,"w":"end up","c":"最终成为，结果是","e":"eventually be or do something"},
{"r":47,"w":"set off","c":"出发；引发，触发","e":"start a journey; trigger something"},
{"r":48,"w":"take over","c":"接管，接手","e":"take control of something"},
{"r":49,"w":"take up","c":"开始从事；占用（时间、空间）","e":"start a hobby; occupy time or space"},
{"r":50,"w":"give back","c":"归还","e":"return something to its owner"},
{"r":51,"w":"throw away","c":"扔掉，丢弃","e":"discard"},
{"r":52,"w":"put away","c":"收起来，放好","e":"store something in its place"},
{"r":53,"w":"put down","c":"放下；镇压；贬低","e":"set down; suppress; criticize"},
{"r":54,"w":"break up","c":"分手；解散，拆散","e":"end a relationship; disperse"},
{"r":55,"w":"make up","c":"编造；和好；化妆","e":"invent; reconcile; apply cosmetics"},
{"r":56,"w":"catch up","c":"赶上","e":"reach the same level or point"},
{"r":57,"w":"cut down on","c":"减少","e":"reduce the amount of something"},
{"r":58,"w":"cut off","c":"切断；隔绝","e":"disconnect; isolate"},
{"r":59,"w":"drop off","c":"（开车）送某人；睡着","e":"deliver someone; fall asleep"},
{"r":60,"w":"get rid of","c":"摆脱，去掉","e":"remove or dispose of"},
{"r":61,"w":"go back","c":"回去，返回","e":"return to a place or topic"},
{"r":62,"w":"go ahead","c":"继续，开始（吧）","e":"proceed; begin"},
{"r":63,"w":"hold up","c":"举起；耽误；持械抢劫","e":"raise; delay; rob"},
{"r":64,"w":"keep on","c":"继续","e":"continue doing something"},
{"r":65,"w":"keep up with","c":"跟上","e":"maintain the same pace as"},
{"r":66,"w":"let down","c":"使失望","e":"fail to meet someone's hopes"},
{"r":67,"w":"move on","c":"继续前进；翻篇","e":"progress to something new"},
{"r":68,"w":"pass away","c":"去世","e":"die (polite term)"},
{"r":69,"w":"pay back","c":"偿还；报复","e":"repay; take revenge"},
{"r":70,"w":"run into","c":"偶遇；撞上","e":"meet by chance; collide with"},
{"r":71,"w":"set out","c":"出发；着手","e":"begin a journey; start a task"},
{"r":72,"w":"sort out","c":"解决；整理","e":"resolve; organize"},
{"r":73,"w":"stand out","c":"突出，显眼","e":"be clearly noticeable"},
{"r":74,"w":"stand up","c":"站起来","e":"rise to one's feet"},
{"r":75,"w":"take back","c":"收回（话）；退回","e":"retract a statement; return goods"},
{"r":76,"w":"take down","c":"记下；拆下","e":"write down; dismantle"},
{"r":77,"w":"try on","c":"试穿","e":"put on clothing to test the fit"},
{"r":78,"w":"turn into","c":"变成","e":"become something different"},
{"r":79,"w":"turn out","c":"结果是，原来是","e":"prove to be the case"},
{"r":80,"w":"warm up","c":"热身；变暖","e":"prepare with light exercise; become warmer"},
{"r":81,"w":"work on","c":"致力于，改进","e":"try to improve or repair"},
{"r":82,"w":"account for","c":"解释；（数量上）占","e":"explain; make up a proportion of"},
{"r":83,"w":"back up","c":"支持；备份；倒车","e":"support; make a copy; reverse a vehicle"},
{"r":84,"w":"blow up","c":"爆炸；充气；放大","e":"explode; inflate; enlarge"},
{"r":85,"w":"bring back","c":"带回；使想起","e":"return; evoke a memory"},
{"r":86,"w":"bring about","c":"带来，导致","e":"cause something to happen"},
{"r":87,"w":"call back","c":"回电话","e":"return a phone call"},
{"r":88,"w":"calm down","c":"冷静下来","e":"become or make calm"},
{"r":89,"w":"care for","c":"照顾；喜欢","e":"look after; like"},
{"r":90,"w":"come across","c":"偶然发现；给人…的印象","e":"find by chance; give an impression"},
{"r":91,"w":"count on","c":"依靠，指望","e":"rely on someone or something"},
{"r":92,"w":"deal with","c":"处理，应对","e":"take action to handle"},
{"r":93,"w":"depend on","c":"取决于；依靠","e":"be determined by; rely on"},
{"r":94,"w":"dress up","c":"盛装打扮","e":"wear formal or fancy clothes"},
{"r":95,"w":"fall apart","c":"崩溃，瓦解","e":"break into pieces; collapse"},
{"r":96,"w":"get over","c":"克服；从…中恢复","e":"recover from; overcome"},
{"r":97,"w":"hand in","c":"上交，提交","e":"submit something to a person in authority"},
{"r":98,"w":"hand out","c":"分发","e":"distribute to people"},
{"r":99,"w":"set aside","c":"留出；搁置","e":"reserve; put away for later"},
{"r":100,"w":"watch out","c":"小心，当心","e":"be careful of danger"}
];
