/* Common English phrasal verbs — curated seeds + ECDICT (skywind3000/ECDICT, MIT/open). { r:rank, w:phrase, c:Chinese, e:English def }. */
window.PHRASAL = [
{"r": 1, "w": "give up", "c": "放弃；戒掉", "e": "stop trying to do something; quit a habit"},
{"r": 2, "w": "find out", "c": "查明，发现", "e": "discover information"},
{"r": 3, "w": "look for", "c": "寻找", "e": "try to find something or someone"},
{"r": 4, "w": "go on", "c": "继续；发生", "e": "continue; happen"},
{"r": 5, "w": "come back", "c": "回来", "e": "return to a place"},
{"r": 6, "w": "pick up", "c": "捡起；（开车）接某人；学会", "e": "lift; collect someone; learn casually"},
{"r": 7, "w": "turn on", "c": "打开（电器、灯）", "e": "start a device or light working"},
{"r": 8, "w": "turn off", "c": "关闭（电器、灯）", "e": "stop a device or light working"},
{"r": 9, "w": "get up", "c": "起床；站起来", "e": "rise from bed; stand up"},
{"r": 10, "w": "put on", "c": "穿上；戴上", "e": "dress in; wear"},
{"r": 11, "w": "take off", "c": "脱下；（飞机）起飞", "e": "remove clothing; (of a plane) leave the ground"},
{"r": 12, "w": "wake up", "c": "醒来；叫醒", "e": "stop sleeping; rouse someone"},
{"r": 13, "w": "grow up", "c": "长大，成长", "e": "become an adult"},
{"r": 14, "w": "set up", "c": "建立；设置，搭建", "e": "establish; arrange or assemble"},
{"r": 15, "w": "carry on", "c": "继续", "e": "continue doing something"},
{"r": 16, "w": "break down", "c": "（机器）故障；（情绪）崩溃", "e": "stop working; lose emotional control"},
{"r": 17, "w": "work out", "c": "锻炼；解决；想出", "e": "exercise; solve; figure out"},
{"r": 18, "w": "look after", "c": "照顾", "e": "take care of someone or something"},
{"r": 19, "w": "look forward to", "c": "期待", "e": "anticipate with pleasure"},
{"r": 20, "w": "give in", "c": "屈服，让步", "e": "stop resisting; yield"},
{"r": 21, "w": "go out", "c": "出去（社交）；（火、灯）熄灭", "e": "leave home for fun; (of fire/light) stop burning"},
{"r": 22, "w": "come in", "c": "进来", "e": "enter a place"},
{"r": 23, "w": "get back", "c": "返回；取回", "e": "return; recover something"},
{"r": 24, "w": "take care of", "c": "照顾；处理", "e": "look after; handle"},
{"r": 25, "w": "put off", "c": "推迟", "e": "postpone"},
{"r": 26, "w": "call off", "c": "取消", "e": "cancel something planned"},
{"r": 27, "w": "run out of", "c": "用完，耗尽", "e": "have no more of something left"},
{"r": 28, "w": "bring up", "c": "抚养；提出（话题）", "e": "raise a child; mention a topic"},
{"r": 29, "w": "check out", "c": "查看；结账退房", "e": "examine; pay and leave a hotel"},
{"r": 30, "w": "check in", "c": "登记入住；办理登机", "e": "register at a hotel or airport"},
{"r": 31, "w": "fill out", "c": "填写（表格）", "e": "complete a form"},
{"r": 32, "w": "hold on", "c": "等一下；坚持", "e": "wait; persevere"},
{"r": 33, "w": "hang up", "c": "挂断电话", "e": "end a phone call"},
{"r": 34, "w": "get along", "c": "和睦相处", "e": "have a friendly relationship"},
{"r": 35, "w": "get on", "c": "上（车、飞机）；进展", "e": "board a vehicle; make progress"},
{"r": 36, "w": "get off", "c": "下（车）", "e": "leave a vehicle"},
{"r": 37, "w": "show up", "c": "出现，露面", "e": "appear; arrive"},
{"r": 38, "w": "turn up", "c": "出现；调高（音量）", "e": "appear unexpectedly; increase volume"},
{"r": 39, "w": "turn down", "c": "拒绝；调低（音量）", "e": "reject; lower volume"},
{"r": 40, "w": "put up with", "c": "容忍，忍受", "e": "tolerate something unpleasant"},
{"r": 41, "w": "look up", "c": "查阅；向上看", "e": "search for information; raise the eyes"},
{"r": 42, "w": "look down on", "c": "看不起，轻视", "e": "regard as inferior"},
{"r": 43, "w": "point out", "c": "指出", "e": "draw attention to a fact"},
{"r": 44, "w": "figure out", "c": "弄清楚，想出", "e": "understand or solve by thinking"},
{"r": 45, "w": "come up with", "c": "想出，提出", "e": "produce an idea or plan"},
{"r": 46, "w": "end up", "c": "最终成为，结果是", "e": "eventually be or do something"},
{"r": 47, "w": "set off", "c": "出发；引发，触发", "e": "start a journey; trigger something"},
{"r": 48, "w": "take over", "c": "接管，接手", "e": "take control of something"},
{"r": 49, "w": "take up", "c": "开始从事；占用（时间、空间）", "e": "start a hobby; occupy time or space"},
{"r": 50, "w": "give back", "c": "归还", "e": "return something to its owner"},
{"r": 51, "w": "throw away", "c": "扔掉，丢弃", "e": "discard"},
{"r": 52, "w": "put away", "c": "收起来，放好", "e": "store something in its place"},
{"r": 53, "w": "put down", "c": "放下；镇压；贬低", "e": "set down; suppress; criticize"},
{"r": 54, "w": "break up", "c": "分手；解散，拆散", "e": "end a relationship; disperse"},
{"r": 55, "w": "make up", "c": "编造；和好；化妆", "e": "invent; reconcile; apply cosmetics"},
{"r": 56, "w": "catch up", "c": "赶上", "e": "reach the same level or point"},
{"r": 57, "w": "cut down on", "c": "减少", "e": "reduce the amount of something"},
{"r": 58, "w": "cut off", "c": "切断；隔绝", "e": "disconnect; isolate"},
{"r": 59, "w": "drop off", "c": "（开车）送某人；睡着", "e": "deliver someone; fall asleep"},
{"r": 60, "w": "get rid of", "c": "摆脱，去掉", "e": "remove or dispose of"},
{"r": 61, "w": "go back", "c": "回去，返回", "e": "return to a place or topic"},
{"r": 62, "w": "go ahead", "c": "继续，开始（吧）", "e": "proceed; begin"},
{"r": 63, "w": "hold up", "c": "举起；耽误；持械抢劫", "e": "raise; delay; rob"},
{"r": 64, "w": "keep on", "c": "继续", "e": "continue doing something"},
{"r": 65, "w": "keep up with", "c": "跟上", "e": "maintain the same pace as"},
{"r": 66, "w": "let down", "c": "使失望", "e": "fail to meet someone's hopes"},
{"r": 67, "w": "move on", "c": "继续前进；翻篇", "e": "progress to something new"},
{"r": 68, "w": "pass away", "c": "去世", "e": "die (polite term)"},
{"r": 69, "w": "pay back", "c": "偿还；报复", "e": "repay; take revenge"},
{"r": 70, "w": "run into", "c": "偶遇；撞上", "e": "meet by chance; collide with"},
{"r": 71, "w": "set out", "c": "出发；着手", "e": "begin a journey; start a task"},
{"r": 72, "w": "sort out", "c": "解决；整理", "e": "resolve; organize"},
{"r": 73, "w": "stand out", "c": "突出，显眼", "e": "be clearly noticeable"},
{"r": 74, "w": "stand up", "c": "站起来", "e": "rise to one's feet"},
{"r": 75, "w": "take back", "c": "收回（话）；退回", "e": "retract a statement; return goods"},
{"r": 76, "w": "take down", "c": "记下；拆下", "e": "write down; dismantle"},
{"r": 77, "w": "try on", "c": "试穿", "e": "put on clothing to test the fit"},
{"r": 78, "w": "turn into", "c": "变成", "e": "become something different"},
{"r": 79, "w": "turn out", "c": "结果是，原来是", "e": "prove to be the case"},
{"r": 80, "w": "warm up", "c": "热身；变暖", "e": "prepare with light exercise; become warmer"},
{"r": 81, "w": "work on", "c": "致力于，改进", "e": "try to improve or repair"},
{"r": 82, "w": "account for", "c": "解释；（数量上）占", "e": "explain; make up a proportion of"},
{"r": 83, "w": "back up", "c": "支持；备份；倒车", "e": "support; make a copy; reverse a vehicle"},
{"r": 84, "w": "blow up", "c": "爆炸；充气；放大", "e": "explode; inflate; enlarge"},
{"r": 85, "w": "bring back", "c": "带回；使想起", "e": "return; evoke a memory"},
{"r": 86, "w": "bring about", "c": "带来，导致", "e": "cause something to happen"},
{"r": 87, "w": "call back", "c": "回电话", "e": "return a phone call"},
{"r": 88, "w": "calm down", "c": "冷静下来", "e": "become or make calm"},
{"r": 89, "w": "care for", "c": "照顾；喜欢", "e": "look after; like"},
{"r": 90, "w": "come across", "c": "偶然发现；给人…的印象", "e": "find by chance; give an impression"},
{"r": 91, "w": "count on", "c": "依靠，指望", "e": "rely on someone or something"},
{"r": 92, "w": "deal with", "c": "处理，应对", "e": "take action to handle"},
{"r": 93, "w": "depend on", "c": "取决于；依靠", "e": "be determined by; rely on"},
{"r": 94, "w": "dress up", "c": "盛装打扮", "e": "wear formal or fancy clothes"},
{"r": 95, "w": "fall apart", "c": "崩溃，瓦解", "e": "break into pieces; collapse"},
{"r": 96, "w": "get over", "c": "克服；从…中恢复", "e": "recover from; overcome"},
{"r": 97, "w": "hand in", "c": "上交，提交", "e": "submit something to a person in authority"},
{"r": 98, "w": "hand out", "c": "分发", "e": "distribute to people"},
{"r": 99, "w": "set aside", "c": "留出；搁置", "e": "reserve; put away for later"},
{"r": 100, "w": "watch out", "c": "小心，当心", "e": "be careful of danger"},
{"r": 101, "w": "be about", "c": "从事于", "e": ""},
{"r": 102, "w": "be about to", "c": "即将", "e": ""},
{"r": 103, "w": "be ahead", "c": "赚钱", "e": ""},
{"r": 104, "w": "be along", "c": "来到", "e": ""},
{"r": 105, "w": "be along to", "c": "来到…", "e": ""},
{"r": 106, "w": "be around", "c": "在旁边,在附近", "e": ""},
{"r": 107, "w": "be back", "c": "回来，放回; 拖欠", "e": ""},
{"r": 108, "w": "be down for", "c": "被列入名单", "e": ""},
{"r": 109, "w": "be down on", "c": "对...有怨气", "e": ""},
{"r": 110, "w": "be in", "c": "到达，执政; 在家; 搞", "e": ""},
{"r": 111, "w": "be in at", "c": "参与,参加", "e": ""},
{"r": 112, "w": "be in for", "c": "必定遭到, 参加", "e": ""},
{"r": 113, "w": "be in on", "c": "参预", "e": ""},
{"r": 114, "w": "be off", "c": "离开,取消,竣工,变坏", "e": ""},
{"r": 115, "w": "be off with", "c": "和…断绝关系", "e": ""},
{"r": 116, "w": "be on", "c": "已经开始了, 接受打赌; 上映", "e": ""},
{"r": 117, "w": "be on to", "c": "意识到, 找...岔子", "e": ""},
{"r": 118, "w": "be out for", "c": "力图要", "e": ""},
{"r": 119, "w": "be out to", "c": "企图,决心,很想…", "e": ""},
{"r": 120, "w": "be over", "c": "完了, 结束", "e": ""},
{"r": 121, "w": "be through", "c": "完成,做完;弃绝,嫌弃;完蛋", "e": ""},
{"r": 122, "w": "be through with", "c": "完成, 弃绝", "e": ""},
{"r": 123, "w": "be up", "c": "起床", "e": ""},
{"r": 124, "w": "be up on", "c": "精通, 熟悉", "e": ""},
{"r": 125, "w": "be up to", "c": "胜任,达到,由…负责", "e": ""},
{"r": 126, "w": "be up with", "c": "出了问题,没有希望", "e": ""},
{"r": 127, "w": "have down", "c": "请…到(乡下或南方)作客", "e": ""},
{"r": 128, "w": "have on", "c": "穿着, 戴着, 在手头, 使上钩", "e": ""},
{"r": 129, "w": "do away with", "c": "废除, 弄死", "e": ""},
{"r": 130, "w": "do down", "c": "胜过, 欺骗", "e": ""},
{"r": 131, "w": "do in", "c": "杀害; 搞垮; 损坏; 累垮", "e": ""},
{"r": 132, "w": "do out", "c": "打扫, 收拾", "e": ""},
{"r": 133, "w": "do over", "c": "重做", "e": ""},
{"r": 134, "w": "do up", "c": "修缮, 包扎, 整理", "e": ""},
{"r": 135, "w": "say over", "c": "背诵", "e": ""},
{"r": 136, "w": "go about", "c": "从事, 走动, 传开", "e": ""},
{"r": 137, "w": "go across", "c": "穿过, 横过", "e": ""},
{"r": 138, "w": "go ahead with", "c": "继续进行", "e": ""},
{"r": 139, "w": "go along", "c": "前进, 进行", "e": ""},
{"r": 140, "w": "go along with", "c": "陪...一起去, 赞同, 附和", "e": ""},
{"r": 141, "w": "go around", "c": "参观; 转动; 走访; 相处", "e": ""},
{"r": 142, "w": "go away", "c": "走开", "e": ""},
{"r": 143, "w": "go away with", "c": "带走", "e": ""},
{"r": 144, "w": "go back from", "c": "不守,不履行,违背", "e": ""},
{"r": 145, "w": "go back on", "c": "违约, 背弃", "e": ""},
{"r": 146, "w": "go back to", "c": "回去", "e": ""},
{"r": 147, "w": "go behind", "c": "探究, 进一步斟酌", "e": ""},
{"r": 148, "w": "go down", "c": "下去, 下沉, 坠落, 被接受, 咽下, 平静下来, 下降, 传下去", "e": ""},
{"r": 149, "w": "go down on", "c": "（粗俚）口交", "e": ""},
{"r": 150, "w": "go down to", "c": "延续至", "e": ""},
{"r": 151, "w": "go down with", "c": "因…而病倒,患…", "e": ""},
{"r": 152, "w": "go forth", "c": "向前去, 被发表", "e": ""},
{"r": 153, "w": "go forward", "c": "前进, 发生", "e": ""},
{"r": 154, "w": "go in", "c": "走进, 放得进, 参加", "e": ""},
{"r": 155, "w": "go in at", "c": "痛打", "e": ""},
{"r": 156, "w": "go in for", "c": "参加, 追求, 从事, 赞成", "e": ""},
{"r": 157, "w": "go in with", "c": "与…合伙,与…分担费用,参加", "e": ""},
{"r": 158, "w": "go off", "c": "离开, 去世, 消失, 爆炸, 被发射, 变质, 进行, 睡去, 卖掉", "e": ""},
{"r": 159, "w": "go off into", "c": "开始, 爆发出", "e": ""},
{"r": 160, "w": "go off with", "c": "拿去, 抢走", "e": ""},
{"r": 161, "w": "go on for", "c": "接近,快到", "e": ""},
{"r": 162, "w": "go on to", "c": "转入", "e": ""},
{"r": 163, "w": "go on with", "c": "暂时使用", "e": ""},
{"r": 164, "w": "go out for", "c": "努力争取,力争", "e": ""},
{"r": 165, "w": "go out of", "c": "从…出来，离开", "e": ""},
{"r": 166, "w": "go over", "c": "转变, 仔细检查, 润色, 复习", "e": ""},
{"r": 167, "w": "go round", "c": "到处走动, 顺便去, 流传", "e": ""},
{"r": 168, "w": "go through", "c": "经历, 经受, 仔细检查, 搜查, 参加, 履行, 被通过, 用完", "e": ""},
{"r": 169, "w": "go through with", "c": "完成", "e": ""},
{"r": 170, "w": "go together", "c": "互相协调, 相配, 恋爱", "e": ""},
{"r": 171, "w": "go under", "c": "死, 失败, 屈服, 破产", "e": ""},
{"r": 172, "w": "go up", "c": "上升, 兴建", "e": ""},
{"r": 173, "w": "go up to", "c": "入…， 进…", "e": ""},
{"r": 174, "w": "get about", "c": "走动, 旅行, 传开, 积极参加社会活动", "e": ""},
{"r": 175, "w": "get across", "c": "通过, 被理解", "e": ""},
{"r": 176, "w": "get ahead", "c": "领先, 走在前面, 进步, 获得成功", "e": ""},
{"r": 177, "w": "get ahead of", "c": "胜过, 超过", "e": ""},
{"r": 178, "w": "get along with", "c": "进展, 走开", "e": ""},
{"r": 179, "w": "get around", "c": "病后能够走动, (非正式)旅行, 传开来", "e": ""},
{"r": 180, "w": "get around to", "c": "设法找到足够的时间去做（某事）; 说服", "e": ""},
{"r": 181, "w": "get away", "c": "离开, 逃脱, 起跑, 出发", "e": ""},
{"r": 182, "w": "get away from", "c": "离开,摆脱,脱离", "e": ""},
{"r": 183, "w": "get back at", "c": "报复,对…进行报复", "e": ""},
{"r": 184, "w": "get back to", "c": "回到…,继续…", "e": ""},
{"r": 185, "w": "get behind", "c": "落后, 支持, 拖欠, 识破", "e": ""},
{"r": 186, "w": "get down", "c": "下来, 吞下, 写下, 使沮丧", "e": ""},
{"r": 187, "w": "get down on", "c": "开始不喜欢", "e": ""},
{"r": 188, "w": "get down to", "c": "开始认真考虑", "e": ""},
{"r": 189, "w": "get in", "c": "进入, 到达, 收获, 插入, 陷入", "e": ""},
{"r": 190, "w": "get in on", "c": "参加,参与,干预", "e": ""},
{"r": 191, "w": "get on for", "c": "接近", "e": ""},
{"r": 192, "w": "get on with", "c": "继续（干某事）; 和…友好相处", "e": ""},
{"r": 193, "w": "get out", "c": "出去, 离开, 逃脱, 摆脱, 泄露, 说出, 出版, 弄出来", "e": ""},
{"r": 194, "w": "get out of", "c": "离开,摆脱", "e": ""},
{"r": 195, "w": "get round", "c": "避免, 说服, 走动, 传开来", "e": ""},
{"r": 196, "w": "get round to", "c": "设法找到足够的时间去做（某事）; 说服", "e": ""},
{"r": 197, "w": "get through", "c": "做完, 通过, 度过", "e": ""},
{"r": 198, "w": "get through to", "c": "打通…电话;使自己被…理解,把自己的意思对…讲明白", "e": ""},
{"r": 199, "w": "get through with", "c": "完成,做完,结束", "e": ""},
{"r": 200, "w": "get together", "c": "聚集, 收集, 积累", "e": ""},
{"r": 201, "w": "get under", "c": "抑制, 控制, 镇压", "e": ""},
{"r": 202, "w": "get up to", "c": "到达,赶上;学到,读到;从事,干", "e": ""},
{"r": 203, "w": "make away", "c": "逃走, 离开", "e": ""},
{"r": 204, "w": "make in", "c": "向...进入, 干涉别人, 加入纷争", "e": ""},
{"r": 205, "w": "make off", "c": "离开", "e": ""},
{"r": 206, "w": "make out of", "c": "用...制造, 理解, 了解", "e": ""},
{"r": 207, "w": "make through", "c": "使…通过使…度过", "e": ""},
{"r": 208, "w": "make through with", "c": "完成", "e": ""},
{"r": 209, "w": "make up for", "c": "补偿,弥补", "e": ""},
{"r": 210, "w": "make up of", "c": "构成，组成", "e": ""},
{"r": 211, "w": "make up to", "c": "接近, 奉承", "e": ""},
{"r": 212, "w": "make up with", "c": "与…和解", "e": ""},
{"r": 213, "w": "know about", "c": "知道,了解,听说过…", "e": ""},
{"r": 214, "w": "know apart", "c": "能够区别", "e": ""},
{"r": 215, "w": "see about", "c": "查询, 留意于, 料理", "e": ""},
{"r": 216, "w": "see off", "c": "送行，送别; 把（某人）赶走; 欢送", "e": ""},
{"r": 217, "w": "see out", "c": "送某人出门;看完,坚持到底", "e": ""},
{"r": 218, "w": "see over", "c": "察看", "e": ""},
{"r": 219, "w": "see round", "c": "巡视,视察,察看", "e": ""},
{"r": 220, "w": "see through", "c": "看穿, 识破", "e": ""},
{"r": 221, "w": "time off", "c": "休假，放假", "e": ""},
{"r": 222, "w": "up in", "c": "熟悉, 精通", "e": ""},
{"r": 223, "w": "up on", "c": "熟悉, 精通", "e": ""},
{"r": 224, "w": "take along", "c": "随身携带,带去", "e": ""},
{"r": 225, "w": "take apart", "c": "拆开", "e": ""},
{"r": 226, "w": "take away", "c": "取走", "e": ""},
{"r": 227, "w": "take on", "c": "呈现, 具有, 雇用, 接纳, 承担, 同...较量, 流行, 盛气凌人", "e": ""},
{"r": 228, "w": "think about", "c": "考虑, 回想", "e": ""},
{"r": 229, "w": "think back", "c": "回想", "e": ""},
{"r": 230, "w": "think on", "c": "考虑", "e": ""},
{"r": 231, "w": "think out", "c": "彻底思考, 设计出", "e": ""},
{"r": 232, "w": "think over", "c": "仔细考虑", "e": ""},
{"r": 233, "w": "think through", "c": "彻底地全面考虑", "e": ""},
{"r": 234, "w": "think up", "c": "想出, 发明", "e": ""},
{"r": 235, "w": "come about", "c": "发生, 改变方向", "e": ""},
{"r": 236, "w": "come along with", "c": "随同", "e": ""},
{"r": 237, "w": "come apart", "c": "分开, 分裂", "e": ""},
{"r": 238, "w": "come around", "c": "来, 前来, 过访, 顺便来访, 笼络, 诱骗", "e": ""},
{"r": 239, "w": "come around to", "c": "转而接受,重新着手…", "e": ""},
{"r": 240, "w": "come away", "c": "脱开", "e": ""},
{"r": 241, "w": "come down", "c": "下来, 下跌, 落泊, 流传下来, 捐钱, 反对", "e": ""},
{"r": 242, "w": "come down on", "c": "惩罚, 索取", "e": ""},
{"r": 243, "w": "come down to", "c": "流传下来;压缩为,归结为,简化为", "e": ""},
{"r": 244, "w": "come down with", "c": "被传染上,因…而病倒", "e": ""},
{"r": 245, "w": "come forth", "c": "出来, 涌现, 被公布", "e": ""},
{"r": 246, "w": "come forward", "c": "站出来, 自告奋勇, 主动响应", "e": ""},
{"r": 247, "w": "come in for", "c": "遭到, 受到", "e": ""},
{"r": 248, "w": "come in on", "c": "参加,加入", "e": ""},
{"r": 249, "w": "come in with", "c": "参加,加入", "e": ""},
{"r": 250, "w": "come off", "c": "发生, 举行, 表现, 结果", "e": ""},
{"r": 251, "w": "come on", "c": "偶遇, 进步, 发生, 开始, 出场, 快来", "e": ""},
{"r": 252, "w": "come out", "c": "到边远地区来, 出现, 露出, 出版, 罢工, 结果是, 褪去, 被解出, 宣布", "e": ""},
{"r": 253, "w": "come out in", "c": "出", "e": ""},
{"r": 254, "w": "come out of", "c": "由...产生", "e": ""},
{"r": 255, "w": "come out with", "c": "发表, 出版, 说出, 提出, 把...投入市场销售", "e": ""},
{"r": 256, "w": "come round", "c": "顺便来访, 绕道而来, 转向, 改主意, 苏醒, 平息", "e": ""},
{"r": 257, "w": "come through", "c": "经历...仍活着, 安然度过, 胜利, 表现", "e": ""},
{"r": 258, "w": "come together", "c": "聚会, 相见; 会面; 汇集", "e": ""},
{"r": 259, "w": "come under", "c": "归入, 遭受", "e": ""},
{"r": 260, "w": "come up to", "c": "达到, 等于", "e": ""},
{"r": 261, "w": "give away", "c": "分发, 放弃, 泄露, 出卖, 丧失", "e": ""},
{"r": 262, "w": "give forth", "c": "发出, 发表", "e": ""},
{"r": 263, "w": "give off", "c": "发出", "e": ""},
{"r": 264, "w": "give on", "c": "(门 / 窗)向着(街 / 园)", "e": ""},
{"r": 265, "w": "give out", "c": "分发, 发出, 发表, 用尽, 精疲力竭", "e": ""},
{"r": 266, "w": "give over", "c": "交(托), 停止, 留出, 把...留作特定用途, 放弃", "e": ""},
{"r": 267, "w": "give up on", "c": "不再相信，不再信任", "e": ""},
{"r": 268, "w": "give up to", "c": "陷入", "e": ""},
{"r": 269, "w": "look about", "c": "四处寻找, 考虑, 察看", "e": ""},
{"r": 270, "w": "look ahead", "c": "向前看, 着眼未来", "e": ""},
{"r": 271, "w": "look ahead to", "c": "向前看,展望,考虑", "e": ""},
{"r": 272, "w": "look around", "c": "四下观望; （作出选择前）进行调查; 骋目四顾; 四顾", "e": ""},
{"r": 273, "w": "look around for", "c": "到处寻找", "e": ""},
{"r": 274, "w": "look away", "c": "不再看（某人或某物）", "e": ""},
{"r": 275, "w": "look back on", "c": "回头看,回顾,追忆", "e": ""},
{"r": 276, "w": "look down", "c": "向下看, 俯视", "e": ""},
{"r": 277, "w": "look down at", "c": "向下看,俯视", "e": ""},
{"r": 278, "w": "look on", "c": "观看, 旁观, 看待", "e": ""},
{"r": 279, "w": "look on to", "c": "向外眺望,俯视,朝向,对着", "e": ""},
{"r": 280, "w": "look out", "c": "面朝, 留神, 找出", "e": ""},
{"r": 281, "w": "look out for", "c": "当心…,留神…,提防…", "e": ""},
{"r": 282, "w": "look out of", "c": "从…向外看", "e": ""},
{"r": 283, "w": "look out on", "c": "面临", "e": ""},
{"r": 284, "w": "look over", "c": "从...上面看, 察看, 检查, 原谅", "e": ""},
{"r": 285, "w": "look round", "c": "环顾, 观光, (事先)进行全面考虑", "e": ""},
{"r": 286, "w": "look round at", "c": "回过头来看着", "e": ""},
{"r": 287, "w": "look round for", "c": "到处寻找", "e": ""},
{"r": 288, "w": "look through", "c": "看穿, 审核, 浏览, 透过...看去, 从...中显露", "e": ""},
{"r": 289, "w": "want in", "c": "想要进来", "e": ""},
{"r": 290, "w": "want off", "c": "想要走掉", "e": ""},
{"r": 291, "w": "want out", "c": "想要出去", "e": ""},
{"r": 292, "w": "want out of", "c": "想从…离出去,想摆脱…", "e": ""},
{"r": 293, "w": "well away", "c": "进展顺利, 已有了好的开端, 微醉", "e": ""},
{"r": 294, "w": "well off", "c": "富裕的, 处境好的", "e": ""},
{"r": 295, "w": "well out of", "c": "幸运地摆脱", "e": ""},
{"r": 296, "w": "well over", "c": "溢出, 泛滥", "e": ""},
{"r": 297, "w": "well up", "c": "涌出", "e": ""},
{"r": 298, "w": "well up for", "c": "对…有充分准备,对…满有把握", "e": ""},
{"r": 299, "w": "well up in", "c": "对...有详细了解", "e": ""},
{"r": 300, "w": "down on", "c": "瞧不起, 歧视, 对…有偏见", "e": ""},
{"r": 301, "w": "down under", "c": "在 / 向地球另一边", "e": ""},
{"r": 302, "w": "tell apart", "c": "分辨", "e": ""},
{"r": 303, "w": "tell off", "c": "分派出, 责备", "e": ""},
{"r": 304, "w": "tell on", "c": "告发; 产生（坏的）影响", "e": ""},
{"r": 305, "w": "back away", "c": "逐渐后退", "e": ""},
{"r": 306, "w": "back away from", "c": "从…躲开", "e": ""},
{"r": 307, "w": "back down", "c": "放弃要求, 取消前言", "e": ""},
{"r": 308, "w": "back in", "c": "无意中获得,偶然取得", "e": ""},
{"r": 309, "w": "back off", "c": "后退", "e": ""},
{"r": 310, "w": "back on", "c": "背向", "e": ""},
{"r": 311, "w": "back on to", "c": "背对着;与…相连", "e": ""},
{"r": 312, "w": "back out of", "c": "退出,不履行", "e": ""},
{"r": 313, "w": "even off", "c": "变平; （使）平稳, （使）均衡", "e": ""},
{"r": 314, "w": "even out", "c": "使平坦", "e": ""},
{"r": 315, "w": "even up", "c": "（使）相等; 匀; 取齐; 找齐", "e": ""},
{"r": 316, "w": "even up on", "c": "报复某人,报答某人", "e": ""},
{"r": 317, "w": "still down", "c": "静下来,停下来", "e": ""},
{"r": 318, "w": "put about", "c": "转向, 散布, 使烦恼", "e": ""},
{"r": 319, "w": "put across", "c": "做成, 使被接受, 欺骗", "e": ""},
{"r": 320, "w": "put apart", "c": "留开, 拨开", "e": ""},
{"r": 321, "w": "put aside", "c": "撇开, 储存...备用", "e": ""},
{"r": 322, "w": "put back", "c": "放回原处, 向后移, 推迟, 倒退, 使后退", "e": ""},
{"r": 323, "w": "put behind", "c": "推迟", "e": ""},
{"r": 324, "w": "put down to", "c": "归因于", "e": ""},
{"r": 325, "w": "put forth", "c": "放出, 发表, 颁布, 提出, 发挥, 起航", "e": ""},
{"r": 326, "w": "put in for", "c": "申请", "e": ""},
{"r": 327, "w": "put over", "c": "使转向, 推迟, 拖延, 使被接受, 驶过", "e": ""},
{"r": 328, "w": "put through", "c": "搞成, 接通", "e": ""},
{"r": 329, "w": "put together", "c": "把...加起来, 装配, 整理", "e": ""},
{"r": 330, "w": "put under", "c": "杀死, 埋葬", "e": ""},
{"r": 331, "w": "work away", "c": "不停地连续工作", "e": ""},
{"r": 332, "w": "work in", "c": "(使)渐渐进入, 插进", "e": ""},
{"r": 333, "w": "work in with", "c": "与...相配合", "e": ""},
{"r": 334, "w": "work over", "c": "彻底检查, 研究, 重做, 殴打", "e": ""},
{"r": 335, "w": "work round to", "c": "慢慢找到时间做某事,转向某种想法", "e": ""},
{"r": 336, "w": "work together", "c": "同…在同一处工作; 同事; 搭档; 合作", "e": ""},
{"r": 337, "w": "work up", "c": "逐步建立, 逐步引起, 整理, 逐步发展", "e": ""},
{"r": 338, "w": "work up to", "c": "逐步发展, 逐渐形成", "e": ""},
{"r": 339, "w": "own up", "c": "坦白", "e": ""},
{"r": 340, "w": "own up to", "c": "对某人坦白交待,向某人承认", "e": ""},
{"r": 341, "w": "last out", "c": "持续", "e": ""},
{"r": 342, "w": "last through", "c": "度过,熬过", "e": ""},
{"r": 343, "w": "call about", "c": "来打听…,打电话询问", "e": ""},
{"r": 344, "w": "call away", "c": "叫走, 转移", "e": ""},
{"r": 345, "w": "call down", "c": "叫...下来, 祈求到, 招致, 责骂", "e": ""},
{"r": 346, "w": "call forth", "c": "引起, 使产生, 使起作用", "e": ""},
{"r": 347, "w": "call on", "c": "号召, 呼吁, 约请, 访问", "e": ""},
{"r": 348, "w": "call out", "c": "召唤...行动, 唤起, 大声叫唤", "e": ""},
{"r": 349, "w": "call over", "c": "点名", "e": ""},
{"r": 350, "w": "call round", "c": "访问,拜访", "e": ""},
{"r": 351, "w": "call together", "c": "召集", "e": ""},
{"r": 352, "w": "call up", "c": "召集, 使想起, 提出, 打电话给", "e": ""},
{"r": 353, "w": "leave about", "c": "乱放", "e": ""},
{"r": 354, "w": "leave aside", "c": "不管,不考虑,把…搁到一边", "e": ""},
{"r": 355, "w": "leave behind", "c": "不带, 留下, 遗留, 超过", "e": ""},
{"r": 356, "w": "leave off", "c": "停止, 不再穿", "e": ""},
{"r": 357, "w": "leave out", "c": "省去, 遗漏, 不考虑", "e": ""},
{"r": 358, "w": "leave over", "c": "剩下, 留下", "e": ""},
{"r": 359, "w": "try back", "c": "重新回到", "e": ""},
{"r": 360, "w": "try out", "c": "试验, 提炼", "e": ""},
{"r": 361, "w": "try up", "c": "校准, 为...最后加工", "e": ""},
{"r": 362, "w": "ask about", "c": "打听,询问", "e": ""},
{"r": 363, "w": "ask around", "c": "到处打听", "e": ""},
{"r": 364, "w": "ask in", "c": "请（某人）进来", "e": ""},
{"r": 365, "w": "ask off", "c": "请假", "e": ""},
{"r": 366, "w": "ask out", "c": "请（某人）外出", "e": ""},
{"r": 367, "w": "ask over", "c": "请（某人）来自己家", "e": ""},
{"r": 368, "w": "ask round", "c": "邀请(某人)来家(常指短时间的)：；(多方)打听, 询问:", "e": ""},
{"r": 369, "w": "feel about", "c": "到处摸索;同情,体谅", "e": ""},
{"r": 370, "w": "feel out", "c": "试探出...的意见", "e": ""},
{"r": 371, "w": "feel up", "c": "对妇女动手动脚", "e": ""},
{"r": 372, "w": "feel up to", "c": "觉得能担当", "e": ""},
{"r": 373, "w": "number off", "c": "报数", "e": ""},
{"r": 374, "w": "show around", "c": "到处看看", "e": ""},
{"r": 375, "w": "show in", "c": "领进来,引进", "e": ""},
{"r": 376, "w": "show off", "c": "炫耀, 卖弄, 使显眼", "e": ""},
{"r": 377, "w": "show out", "c": "送出（客人）", "e": ""},
{"r": 378, "w": "show through", "c": "显现,显露,透露;隐约显露,能够看见", "e": ""},
{"r": 379, "w": "house up", "c": "躲藏", "e": ""},
{"r": 380, "w": "keep apart", "c": "（使）分开", "e": ""},
{"r": 381, "w": "keep away", "c": "防范", "e": ""},
{"r": 382, "w": "keep away from", "c": "离开,避开,不接近,戒除…", "e": ""},
{"r": 383, "w": "keep back", "c": "落在后面, 阻止, 隐瞒, 留下", "e": ""},
{"r": 384, "w": "keep down", "c": "卧下, 镇压, 控制, 缩减, 保留", "e": ""},
{"r": 385, "w": "keep in", "c": "抑制, 隐瞒, 隐藏, 继续燃烧", "e": ""},
{"r": 386, "w": "keep in with", "c": "不断讨好", "e": ""},
{"r": 387, "w": "keep off", "c": "让开, 不接近", "e": ""},
{"r": 388, "w": "keep on at", "c": "纠缠, 使烦恼", "e": ""},
{"r": 389, "w": "keep out", "c": "使在外", "e": ""},
{"r": 390, "w": "keep out of", "c": "置身于外", "e": ""},
{"r": 391, "w": "keep under", "c": "压制, 控制", "e": ""},
{"r": 392, "w": "let in", "c": "放进, 招致, 嵌入", "e": ""},
{"r": 393, "w": "let in for", "c": "使陷入, 惹起(麻烦等)", "e": ""},
{"r": 394, "w": "let up", "c": "减小, 停止", "e": ""},
{"r": 395, "w": "hand back", "c": "交还", "e": ""},
{"r": 396, "w": "hand off", "c": "用手推开某人", "e": ""},
{"r": 397, "w": "hand on", "c": "把...传下去, 传递下去, 发放", "e": ""},
{"r": 398, "w": "hand over", "c": "移交", "e": ""},
{"r": 399, "w": "hand up", "c": "上交; 呈上; 把…扶上去", "e": ""},
{"r": 400, "w": "begin on", "c": "开始,着手,动手", "e": ""},
{"r": 401, "w": "help forward", "c": "使人进步,促进", "e": ""},
{"r": 402, "w": "help in", "c": "搀扶着进入; 帮助干…，在…方面帮助", "e": ""},
{"r": 403, "w": "help on", "c": "帮助穿上; 鼓励，促进", "e": ""},
{"r": 404, "w": "help out", "c": "帮助, 帮助…出来", "e": ""},
{"r": 405, "w": "talk about", "c": "讨论, 谈论; 考虑（做…）; 唠; 话", "e": ""},
{"r": 406, "w": "talk away", "c": "不断地谈, 在谈话中度过", "e": ""},
{"r": 407, "w": "talk back", "c": "顶嘴, 反驳", "e": ""},
{"r": 408, "w": "talk down", "c": "大声说话盖住（某人）, 不给（某人）说话机会; 以高人一等的口气对 ... 讲话", "e": ""},
{"r": 409, "w": "talk out", "c": "把...谈透, 通过商谈消除分歧, 响亮地说", "e": ""},
{"r": 410, "w": "talk out of", "c": "劝服（某人）不做（某事）", "e": ""},
{"r": 411, "w": "talk round", "c": "说服, 兜圈子谈", "e": ""},
{"r": 412, "w": "talk up", "c": "大声讲, 大胆讲, 赞扬", "e": ""},
{"r": 413, "w": "turn about", "c": "转身, 反复思考", "e": ""},
{"r": 414, "w": "turn around", "c": "（使）转身; （使）好转; 改变意见; 使变得完全不同", "e": ""},
{"r": 415, "w": "turn aside", "c": "避开, 转过脸, 挡开, 使转变方向", "e": ""},
{"r": 416, "w": "turn away", "c": "不准...入内, 走开, 转过脸, 解雇, 避开", "e": ""},
{"r": 417, "w": "turn away from", "c": "厌恶", "e": ""},
{"r": 418, "w": "turn back", "c": "往回走, 翻回到, 重新翻到, 折转", "e": ""},
{"r": 419, "w": "turn back to", "c": "翻回到, 重新提到", "e": ""},
{"r": 420, "w": "turn out of", "c": "把…逐出…", "e": ""},
{"r": 421, "w": "start aside", "c": "跳开", "e": ""},
{"r": 422, "w": "start back", "c": "畏缩", "e": ""},
{"r": 423, "w": "start in", "c": "开始", "e": ""},
{"r": 424, "w": "start off", "c": "出发, 开始", "e": ""},
{"r": 425, "w": "start on", "c": "开始", "e": ""},
{"r": 426, "w": "start out", "c": "出发, 动身", "e": ""},
{"r": 427, "w": "start over", "c": "重新开始", "e": ""},
{"r": 428, "w": "start up", "c": "突然站起, 突然出现, 发动, 开动", "e": ""},
{"r": 429, "w": "start up in", "c": "开始从事,恢复", "e": ""},
{"r": 430, "w": "point off", "c": "给…加小数点", "e": ""},
{"r": 431, "w": "point up", "c": "强调, （使）特别注意; 清楚表明", "e": ""},
{"r": 432, "w": "hold down", "c": "压制, 抑制, 缩减, 牵制, 垂下", "e": ""},
{"r": 433, "w": "hold forth", "c": "滔滔地说, 提供", "e": ""},
{"r": 434, "w": "hold in", "c": "约束, 抑制", "e": ""},
{"r": 435, "w": "hold off", "c": "不接近, 拖延, 不使接近", "e": ""},
{"r": 436, "w": "hold on to", "c": "坚持", "e": ""},
{"r": 437, "w": "hold together", "c": "使结合, 团结", "e": ""},
{"r": 438, "w": "follow about", "c": "跟在某人身边形影不离", "e": ""},
{"r": 439, "w": "follow on", "c": "继续下去", "e": ""},
{"r": 440, "w": "follow out", "c": "把...查到底, 贯彻, 执行", "e": ""},
{"r": 441, "w": "follow through", "c": "坚持到底", "e": ""},
{"r": 442, "w": "follow up on", "c": "追踪; 继续采用", "e": ""},
{"r": 443, "w": "end around", "c": "首尾循环的", "e": ""},
{"r": 444, "w": "end in", "c": "以...为结果", "e": ""},
{"r": 445, "w": "end off", "c": "结束", "e": ""},
{"r": 446, "w": "end up with", "c": "以…作为结局,以…而告终", "e": ""},
{"r": 447, "w": "right along", "c": "继续地", "e": ""},
{"r": 448, "w": "right away", "c": "立刻", "e": ""},
{"r": 449, "w": "right back", "c": "右后卫", "e": ""},
{"r": 450, "w": "right down", "c": "非常,无比;十足地,地地道道地", "e": ""},
{"r": 451, "w": "right off", "c": "立刻", "e": ""},
{"r": 452, "w": "right on", "c": "对啊, (美)(非正式)你说得对啊, 老于世故的, 知情的", "e": ""},
{"r": 453, "w": "right out", "c": "坦率地,明白地;彻底地", "e": ""},
{"r": 454, "w": "right round", "c": "就在(...)周围, 就在(...)附近, 整整一圈地, 完全朝着相反方向", "e": ""},
{"r": 455, "w": "bring along", "c": "带来,随身携带", "e": ""},
{"r": 456, "w": "bring around", "c": "使信服", "e": ""},
{"r": 457, "w": "bring down on", "c": "招致", "e": ""},
{"r": 458, "w": "bring forth", "c": "使产生", "e": ""},
{"r": 459, "w": "bring in", "c": "提出, 挣得, 引进", "e": ""},
{"r": 460, "w": "bring off", "c": "救出, 完成", "e": ""},
{"r": 461, "w": "bring on", "c": "引起, 导致, 使发展", "e": ""},
{"r": 462, "w": "bring through", "c": "救活", "e": ""},
{"r": 463, "w": "bring under", "c": "制服", "e": ""},
{"r": 464, "w": "hear about", "c": "听说,听到过", "e": ""},
{"r": 465, "w": "hear out", "c": "听完", "e": ""},
{"r": 466, "w": "play about", "c": "随便摆弄,到处乱搞", "e": ""},
{"r": 467, "w": "play along", "c": "等待回音或决定; 合作; （使）沿…闪动; 荡漾", "e": ""},
{"r": 468, "w": "play along with", "c": "参与, 对...假表同意", "e": ""},
{"r": 469, "w": "play around", "c": "玩耍", "e": ""},
{"r": 470, "w": "play away", "c": "在外比赛, 输掉, 浪费掉(时间等)", "e": ""},
{"r": 471, "w": "play back", "c": "把(球)打回对方, 播放(唱片、磁带等)", "e": ""},
{"r": 472, "w": "play down", "c": "对...不重视, 降低, 贬低, 屈尊随群", "e": ""},
{"r": 473, "w": "play off", "c": "使出丑, 延长比赛以破平局, 使相斗, (用欺骗手段)使...脱手", "e": ""},
{"r": 474, "w": "play on", "c": "继续比赛, 利用", "e": ""},
{"r": 475, "w": "play out", "c": "把戏演完, 使耗尽, 使筋疲力尽, 放出, 用完, 使破产, 宣泄, 结束", "e": ""},
{"r": 476, "w": "play up", "c": "加油, (比赛时)拼命, 开始奏乐, 强调, 给...制造麻烦, 出故障", "e": ""},
{"r": 477, "w": "play up to", "c": "支持, 给...当配角, 配合好, 戏弄, 奉承", "e": ""},
{"r": 478, "w": "run about", "c": "跑来跑去,到处乱跑", "e": ""},
{"r": 479, "w": "run across", "c": "偶遇, 跑着穿过", "e": ""},
{"r": 480, "w": "run along", "c": "离开", "e": ""},
{"r": 481, "w": "run around", "c": "和...一起走动", "e": ""},
{"r": 482, "w": "run around with", "c": "与…一起到处乱跑;与…一起鬼混作乐", "e": ""},
{"r": 483, "w": "run away from", "c": "逃避", "e": ""},
{"r": 484, "w": "run back", "c": "倒回;流回,赶回;回落,回跌", "e": ""},
{"r": 485, "w": "run in", "c": "跑进, 顺便探访, 插入, 拘留, 试车, 接排", "e": ""},
{"r": 486, "w": "run on", "c": "连续, 连写, 流逝, 涉及", "e": ""},
{"r": 487, "w": "run out on", "c": "抛弃,遗弃,不再支持", "e": ""},
{"r": 488, "w": "run over with", "c": "充满,洋溢着", "e": ""},
{"r": 489, "w": "run through", "c": "跑着穿过, 刺, 戳, 排练, 挥霍, 贯穿", "e": ""},
{"r": 490, "w": "run up to", "c": "跑到, 达到, 积累到", "e": ""},
{"r": 491, "w": "going away", "c": "出发度蜜月，（体育比赛）领先甚多", "e": ""},
{"r": 492, "w": "going down", "c": "下钻", "e": ""},
{"r": 493, "w": "going forward", "c": "向前", "e": ""},
{"r": 494, "w": "going on", "c": "接近, 快到; 发生", "e": ""},
{"r": 495, "w": "move about", "c": "走来走去, 经常搬家", "e": ""},
{"r": 496, "w": "move along", "c": "继续向前或后移动, 往里走", "e": ""},
{"r": 497, "w": "move around", "c": "走来走去", "e": ""},
{"r": 498, "w": "move away", "c": "离开; 搬到别处去住; 改变（见解）; 挪开", "e": ""},
{"r": 499, "w": "move away from", "c": "离开", "e": ""},
{"r": 500, "w": "move back", "c": "退缩", "e": ""},
{"r": 501, "w": "move forward", "c": "前进", "e": ""},
{"r": 502, "w": "move in", "c": "生活于, 迁入", "e": ""},
{"r": 503, "w": "move in on", "c": "潜近..., 企图夺取(某物), 企图从(某人)处夺取东西", "e": ""},
{"r": 504, "w": "move in to", "c": "进入,驶入,迁入,搬进", "e": ""},
{"r": 505, "w": "move off", "c": "离开, 死, 畅销", "e": ""},
{"r": 506, "w": "move on to", "c": "转换(话题)", "e": ""},
{"r": 507, "w": "move out", "c": "搬出, 出发", "e": ""},
{"r": 508, "w": "move out of", "c": "迁出,离开", "e": ""},
{"r": 509, "w": "move over", "c": "移动一下", "e": ""},
{"r": 510, "w": "move through", "c": "穿过", "e": ""},
{"r": 511, "w": "head back", "c": "向后前进,倒车", "e": ""},
{"r": 512, "w": "head off", "c": "阻止, 拦截", "e": ""},
{"r": 513, "w": "head on", "c": "迎面地", "e": ""},
{"r": 514, "w": "head out", "c": "离去，出发，启程", "e": ""},
{"r": 515, "w": "head over", "c": "驶往,朝…方向前进,前往", "e": ""},
{"r": 516, "w": "head up", "c": "加盖子于", "e": ""},
{"r": 517, "w": "live down", "c": "通过行动使人们原谅", "e": ""},
{"r": 518, "w": "live in", "c": "住进", "e": ""},
{"r": 519, "w": "live off", "c": "以...为食料, 靠...生活", "e": ""},
{"r": 520, "w": "live on", "c": "继续生活, 以...为主食, 靠...生活", "e": ""},
{"r": 521, "w": "live out", "c": "活过(某一段时间), 住在外面", "e": ""},
{"r": 522, "w": "live over", "c": "重温; 重新过（某种日子）; 住在高于…的地方", "e": ""},
{"r": 523, "w": "live through", "c": "度过, 经受过", "e": ""},
{"r": 524, "w": "live together", "c": "住在一起, （通常指异性）同居; 相处", "e": ""},
{"r": 525, "w": "live up to", "c": "实践, 做到", "e": ""},
{"r": 526, "w": "write about", "c": "写…的事, 写到…, 把（某事）作为写作的主题", "e": ""},
{"r": 527, "w": "write away", "c": "写信（索要）; 连续写作", "e": ""},
{"r": 528, "w": "write away for", "c": "函购,写信索取…", "e": ""},
{"r": 529, "w": "write in for", "c": "向商行写信提要求 / 意见", "e": ""},
{"r": 530, "w": "write off for", "c": "写信寄出, 给商行写信(购物)", "e": ""},
{"r": 531, "w": "write on", "c": "写, 记述", "e": ""},
{"r": 532, "w": "believe in", "c": "信仰, 信任", "e": ""},
{"r": 533, "w": "set ahead", "c": "提前; 拨快", "e": ""},
{"r": 534, "w": "set apart", "c": "使分离, 留出", "e": ""},
{"r": 535, "w": "set apart from", "c": "使不同于", "e": ""},
{"r": 536, "w": "set back", "c": "阻碍, 使受挫折, 往回拨", "e": ""},
{"r": 537, "w": "set forward", "c": "促进, 提出, 拨快, 出发", "e": ""},
{"r": 538, "w": "set in", "c": "开始, 到来, 上涨, 插入, 流行", "e": ""},
{"r": 539, "w": "set off for", "c": "动身前往,朝…出发", "e": ""},
{"r": 540, "w": "set on", "c": "攻击, 前进, 怂恿, 使开始", "e": ""},
{"r": 541, "w": "set over", "c": "置于...上, 指派...管理, 移交", "e": ""},
{"r": 542, "w": "set up for", "c": "自以为", "e": ""},
{"r": 543, "w": "set up with", "c": "向…提供", "e": ""},
{"r": 544, "w": "happen along", "c": "碰巧出现,正好到来", "e": ""},
{"r": 545, "w": "happen in", "c": "偶然来到;发生在…", "e": ""},
{"r": 546, "w": "happen in with", "c": "偶然遇见,和…邂逅", "e": ""},
{"r": 547, "w": "happen on", "c": "偶然遇见,碰到", "e": ""},
{"r": 548, "w": "change about", "c": "见异思迁", "e": ""},
{"r": 549, "w": "change back", "c": "恢复到原来的样子、特性等; 换上原来的衣服", "e": ""},
{"r": 550, "w": "change down", "c": "放慢车速", "e": ""},
{"r": 551, "w": "change over", "c": "（使）改变, （使）变换; 调换; 掉期", "e": ""},
{"r": 552, "w": "change round", "c": "改变;转向", "e": ""},
{"r": 553, "w": "change up", "c": "加快车速", "e": ""},
{"r": 554, "w": "water back", "c": "贮水器，加热水池，加热管道", "e": ""},
{"r": 555, "w": "water down", "c": "掺水于; 用水把…冲淡; 削弱; 使缓和", "e": ""},
{"r": 556, "w": "interest in", "c": "对…有兴趣", "e": ""},
{"r": 557, "w": "book down", "c": "把…登记下来", "e": ""},
{"r": 558, "w": "book in", "c": "登记住入,签到", "e": ""},
{"r": 559, "w": "book up", "c": "预订, 预订座位", "e": ""},
{"r": 560, "w": "lot on", "c": "期待", "e": ""},
{"r": 561, "w": "form up", "c": "排好队列", "e": ""},
{"r": 562, "w": "study out", "c": "解决, 设计, 拟定", "e": ""},
{"r": 563, "w": "study up", "c": "钻研", "e": ""},
{"r": 564, "w": "study up on", "c": "对...进行仔细的研究", "e": ""},
{"r": 565, "w": "level down", "c": "拉平,降低", "e": ""},
{"r": 566, "w": "level off", "c": "平整, 变平, 稳定", "e": ""},
{"r": 567, "w": "level out", "c": "把...弄平, 整平, 持平, 达到平衡, 稳定, (飞机)水平飞行", "e": ""},
{"r": 568, "w": "issue forth", "c": "出来；出去：", "e": ""},
{"r": 569, "w": "issue in", "c": "导致", "e": ""},
{"r": 570, "w": "issue out", "c": "流出,冒出,涌出,传出", "e": ""},
{"r": 571, "w": "black out", "c": "使停刊, 熄灭灯火", "e": ""},
{"r": 572, "w": "black up", "c": "弄黑脸和手", "e": ""},
{"r": 573, "w": "allow in", "c": "准许进入", "e": ""},
{"r": 574, "w": "meet up", "c": "偶然地碰到", "e": ""},
{"r": 575, "w": "meet up with", "c": "偶遇", "e": ""},
{"r": 576, "w": "lead away", "c": "使盲从", "e": ""},
{"r": 577, "w": "lead back", "c": "(牌)回出", "e": ""},
{"r": 578, "w": "lead in", "c": "引入线, 介绍, 开场白", "e": ""},
{"r": 579, "w": "lead off", "c": "开始", "e": ""},
{"r": 580, "w": "lead on", "c": "劝诱, 哄骗; 带领…继续前进; 走在前面", "e": ""},
{"r": 581, "w": "lead out", "c": "开始", "e": ""},
{"r": 582, "w": "lead up", "c": "抢先", "e": ""},
{"r": 583, "w": "lead up to", "c": "带到, 导致, 作为...的准备", "e": ""},
{"r": 584, "w": "sit about", "c": "坐着不干, 袖手旁观", "e": ""},
{"r": 585, "w": "sit around", "c": "坐着不干, 袖手旁观", "e": ""},
{"r": 586, "w": "sit back", "c": "不采取行动, 向后靠着坐", "e": ""},
{"r": 587, "w": "sit down", "c": "坐下, 占据, 参加静坐罢工(或示威)", "e": ""},
{"r": 588, "w": "sit down to", "c": "坐下来做…", "e": ""},
{"r": 589, "w": "sit in", "c": "代人暂时照料, 参加静坐罢工", "e": ""},
{"r": 590, "w": "sit in on", "c": "列席, 旁听", "e": ""},
{"r": 591, "w": "sit out", "c": "袖手旁观, 比...坐得久, 坐到结束, 坐在户外", "e": ""},
{"r": 592, "w": "sit over", "c": "坐在...左手, 靠边坐让出地盘", "e": ""},
{"r": 593, "w": "sit through", "c": "坐着捱到结束, 耐着性子看完", "e": ""},
{"r": 594, "w": "sit under", "c": "听...讲授", "e": ""},
{"r": 595, "w": "sit up", "c": "坐起, 端坐, 熬夜, 诧异", "e": ""},
{"r": 596, "w": "game on", "c": "比赛开始信号", "e": ""},
{"r": 597, "w": "stand about", "c": "闲站着", "e": ""},
{"r": 598, "w": "stand aside", "c": "站开, 躲开, 避开", "e": ""},
{"r": 599, "w": "stand back", "c": "退后", "e": ""},
{"r": 600, "w": "stand behind", "c": "支持,作后盾", "e": ""},
{"r": 601, "w": "stand in", "c": "代演员站位, 使花费", "e": ""},
{"r": 602, "w": "stand in for", "c": "替代,暂代,代理", "e": ""},
{"r": 603, "w": "stand in with", "c": "与...分担, 与...联合", "e": ""},
{"r": 604, "w": "stand on", "c": "站立在...上", "e": ""},
{"r": 605, "w": "stand up to", "c": "经得起..., 勇敢地面对, 抵抗", "e": ""},
{"r": 606, "w": "stand up with", "c": "给...当傧相", "e": ""},
{"r": 607, "w": "body forth", "c": "象征", "e": ""},
{"r": 608, "w": "line out", "c": "划出, 标出, 排...成行, 领读", "e": ""},
{"r": 609, "w": "line through", "c": "划掉, 勾销", "e": ""},
{"r": 610, "w": "line up", "c": "整队, 排列起", "e": ""},
{"r": 611, "w": "report back", "c": "带回…的报告, 汇报", "e": ""},
{"r": 612, "w": "report on", "c": "报道…,作有关…的报道", "e": ""},
{"r": 613, "w": "face about", "c": "转过身, 改主意", "e": ""},
{"r": 614, "w": "face away", "c": "把脸转到一边", "e": ""},
{"r": 615, "w": "face down", "c": "压倒, 降服", "e": ""},
{"r": 616, "w": "face off", "c": "和...对抗, (冰球赛中)开球, 把...坚持到底", "e": ""},
{"r": 617, "w": "face on", "c": "俯视,俯瞰", "e": ""},
{"r": 618, "w": "face out", "c": "勇敢地应对", "e": ""},
{"r": 619, "w": "face round", "c": "转过身, 改主意", "e": ""},
{"r": 620, "w": "face up to", "c": "勇敢地面对", "e": ""},
{"r": 621, "w": "carry along", "c": "说服;鼓励,支持", "e": ""},
{"r": 622, "w": "carry away", "c": "运走, 使失去自制力", "e": ""},
{"r": 623, "w": "carry back", "c": "运回, 拿回, 使回忆起", "e": ""},
{"r": 624, "w": "carry on with", "c": "与...调情", "e": ""},
{"r": 625, "w": "lose out", "c": "(比赛)输掉, 失败", "e": ""},
{"r": 626, "w": "rate up", "c": "向...征收较高额保险费", "e": ""},
{"r": 627, "w": "learn about", "c": "学习,听说,得悉,了解", "e": ""},
{"r": 628, "w": "learn off", "c": "牢记,背熟", "e": ""},
{"r": 629, "w": "offer up", "c": "献上", "e": ""},
{"r": 630, "w": "team up", "c": "合作, 协作", "e": ""},
{"r": 631, "w": "team up with", "c": "与…合作,与…齐心协力", "e": ""},
{"r": 632, "w": "reason about", "c": "对…进行推理", "e": ""},
{"r": 633, "w": "reason out", "c": "通过推理得出结论", "e": ""},
{"r": 634, "w": "reason out of", "c": "劝说...排除", "e": ""},
{"r": 635, "w": "view away", "c": "看见…从隐匿处跳出来", "e": ""},
{"r": 636, "w": "kid around", "c": "（美）开玩笑", "e": ""},
{"r": 637, "w": "low aside", "c": "低声独白", "e": ""},
{"r": 638, "w": "low down", "c": "内幕；实情", "e": ""},
{"r": 639, "w": "understand about", "c": "懂得,了解", "e": ""},
{"r": 640, "w": "read about", "c": "阅读有关…的细节", "e": ""},
{"r": 641, "w": "read back", "c": "重复", "e": ""},
{"r": 642, "w": "read on", "c": "继续读", "e": ""},
{"r": 643, "w": "read over", "c": "把...读一遍", "e": ""},
{"r": 644, "w": "read up", "c": "攻读", "e": ""},
{"r": 645, "w": "read up on", "c": "研究,专攻…", "e": ""},
{"r": 646, "w": "watch out for", "c": "戒备, 提防, 密切注意", "e": ""},
{"r": 647, "w": "figure down", "c": "推算出,弄清", "e": ""},
{"r": 648, "w": "figure in", "c": "包括进", "e": ""},
{"r": 649, "w": "figure on", "c": "信赖, 指望, 计划, 打算", "e": ""},
{"r": 650, "w": "centre forward", "c": "中锋", "e": ""},
{"r": 651, "w": "centre on", "c": "集中在...上", "e": ""},
{"r": 652, "w": "stop away from", "c": "离开,走出,退出", "e": ""},
{"r": 653, "w": "stop down", "c": "不增加, 缩小光圈", "e": ""},
{"r": 654, "w": "stop in", "c": "顺便访问", "e": ""},
{"r": 655, "w": "stop out", "c": "覆盖...使其不受腐蚀", "e": ""},
{"r": 656, "w": "stop up", "c": "塞住", "e": ""},
{"r": 657, "w": "add on", "c": "（在计算或目录的末尾额外）加上, 附加", "e": ""},
{"r": 658, "w": "add together", "c": "加起来, 总计; 相加", "e": ""},
{"r": 659, "w": "add up", "c": "合计", "e": ""},
{"r": 660, "w": "add up to", "c": "合计达", "e": ""},
{"r": 661, "w": "fall about", "c": "禁不住笑", "e": ""},
{"r": 662, "w": "fall across", "c": "偶然遇到", "e": ""},
{"r": 663, "w": "fall away", "c": "消瘦, 背离, 离开, 消失, 倾斜", "e": ""},
{"r": 664, "w": "fall back on", "c": "求助于, 退到, 回头再说", "e": ""},
{"r": 665, "w": "fall back to", "c": "落回到", "e": ""},
{"r": 666, "w": "fall behind", "c": "落在后面, 拖欠", "e": ""},
{"r": 667, "w": "fall behind in", "c": "在...方面落后", "e": ""},
{"r": 668, "w": "fall down", "c": "倒塌, 跌倒; 失败; 趴架; 栽倒", "e": ""},
{"r": 669, "w": "fall down on", "c": "失败", "e": ""},
{"r": 670, "w": "fall in for", "c": "得到,受到", "e": ""},
{"r": 671, "w": "fall in with", "c": "偶遇, 同意", "e": ""},
{"r": 672, "w": "fall off", "c": "从...跌下, 下降, 减少, 衰退, 离开", "e": ""},
{"r": 673, "w": "fall on", "c": "落在…之上;攻击,袭击", "e": ""},
{"r": 674, "w": "fall out of", "c": "放弃, 中止", "e": ""},
{"r": 675, "w": "fall out with", "c": "与…闹翻", "e": ""},
{"r": 676, "w": "fall over", "c": "被…绊倒; 意外地从…上跌落; 落在…之外; 迫不及待做某事", "e": ""},
{"r": 677, "w": "fall through", "c": "失败, 失约", "e": ""},
{"r": 678, "w": "fall under", "c": "受到, 被归入", "e": ""},
{"r": 679, "w": "speak about", "c": "谈论,讲起,说到", "e": ""},
{"r": 680, "w": "speak on", "c": "说下去", "e": ""},
{"r": 681, "w": "speak out", "c": "大胆地说, 大声地说", "e": ""},
{"r": 682, "w": "speak up", "c": "更大声地说, 大胆说出, 无保留地说出", "e": ""},
{"r": 683, "w": "control on", "c": "对…的控制", "e": ""},
{"r": 684, "w": "cost down", "c": "降价; 降低成本", "e": ""},
{"r": 685, "w": "remain on", "c": "停留在…之上", "e": ""},
{"r": 686, "w": "remain up", "c": "一直不睡,熬夜", "e": ""},
{"r": 687, "w": "grow away from", "c": "脱离,与…格格不入", "e": ""},
{"r": 688, "w": "grow back", "c": "重新长出", "e": ""},
{"r": 689, "w": "grow on", "c": "引起...爱好, 加深影响", "e": ""},
{"r": 690, "w": "grow out", "c": "长出来,向外增大,膨胀", "e": ""},
{"r": 691, "w": "grow out of", "c": "长得与...不相称, 因长大而丢弃", "e": ""},
{"r": 692, "w": "grow over", "c": "覆盖…", "e": ""},
{"r": 693, "w": "open on", "c": "通往...", "e": ""},
{"r": 694, "w": "open out", "c": "展开, 开发, 改善, 增加, 展现, 揭示, 直言, 畅淡", "e": ""},
{"r": 695, "w": "type in", "c": "在已打好的材料上加入; 输入（在网上）", "e": ""},
{"r": 696, "w": "research on", "c": "研究， 探讨…", "e": ""},
{"r": 697, "w": "walk about", "c": "踱来踱去, 散步", "e": ""},
{"r": 698, "w": "walk around", "c": "绕…而走", "e": ""},
{"r": 699, "w": "walk away", "c": "走开", "e": ""},
{"r": 700, "w": "walk away from", "c": "从...旁边走开, 轻易地胜过", "e": ""},
{"r": 701, "w": "walk away with", "c": "轻易取得", "e": ""},
{"r": 702, "w": "walk off", "c": "不通知就离开, 用散步消除", "e": ""},
{"r": 703, "w": "walk off with", "c": "轻易赢得, 偷走", "e": ""},
{"r": 704, "w": "walk out of", "c": "从……走出", "e": ""},
{"r": 705, "w": "walk out with", "c": "追求…,和某人一起出去幽会", "e": ""},
{"r": 706, "w": "walk through", "c": "轻松地初排(戏), 草率地处理", "e": ""},
{"r": 707, "w": "walk up", "c": "沿...走, 走上", "e": ""},
{"r": 708, "w": "walk up to", "c": "走近, 走向", "e": ""},
{"r": 709, "w": "win back", "c": "重新获得, 夺回", "e": ""},
{"r": 710, "w": "win on", "c": "影响", "e": ""},
{"r": 711, "w": "win out", "c": "获胜,完成,摆脱", "e": ""},
{"r": 712, "w": "win through", "c": "历尽千辛万苦获得成功,终于获胜", "e": ""},
{"r": 713, "w": "win up", "c": "上马, 攀登", "e": ""},
{"r": 714, "w": "send along", "c": "发送, 派遣", "e": ""},
{"r": 715, "w": "send away", "c": "发送, 打发走, 解雇", "e": ""},
{"r": 716, "w": "send away for", "c": "函购某物", "e": ""},
{"r": 717, "w": "send back", "c": "退还", "e": ""},
{"r": 718, "w": "send down", "c": "使下降, 把...向下发送", "e": ""},
{"r": 719, "w": "send forth", "c": "寄发, 发出, 放出, 长出", "e": ""},
{"r": 720, "w": "send forward", "c": "派遣", "e": ""},
{"r": 721, "w": "send in", "c": "递送, 命(或请)...进来", "e": ""},
{"r": 722, "w": "send off", "c": "寄出, 派遣, 给...送行", "e": ""},
{"r": 723, "w": "send off for", "c": "函购某物", "e": ""},
{"r": 724, "w": "send on", "c": "先送, 先遣, 转送", "e": ""},
{"r": 725, "w": "send out", "c": "发送, 派遣, 放出", "e": ""},
{"r": 726, "w": "send over", "c": "发送", "e": ""},
{"r": 727, "w": "send round", "c": "传阅, 发送, 派遣", "e": ""},
{"r": 728, "w": "send through", "c": "送过去,传送,报告,通知", "e": ""},
{"r": 729, "w": "send up", "c": "发出, 射出, 呈交, 使上升", "e": ""},
{"r": 730, "w": "force back", "c": "抑制, 强忍", "e": ""},
{"r": 731, "w": "force out", "c": "把…赶走; 挤掉; 迫使离开; 屈服", "e": ""},
{"r": 732, "w": "force up", "c": "迫使提高", "e": ""},
{"r": 733, "w": "air out", "c": "通通风, 晾一晾; 出气", "e": ""},
{"r": 734, "w": "act out", "c": "将...表演出来, 将...付诸行动", "e": ""},
{"r": 735, "w": "act up", "c": "运作不正常, 调皮", "e": ""},
{"r": 736, "w": "act up to", "c": "按...办事, 实践", "e": ""},
{"r": 737, "w": "decide on", "c": "决定,选定,确定…", "e": ""},
{"r": 738, "w": "foot up", "c": "结算", "e": ""},
{"r": 739, "w": "foot up to", "c": "总计,累计", "e": ""},
{"r": 740, "w": "mind out", "c": "注意,当心", "e": ""},
{"r": 741, "w": "clear away", "c": "清除, 消失", "e": ""},
{"r": 742, "w": "clear up", "c": "整理, 消除, 放晴", "e": ""},
{"r": 743, "w": "major in", "c": "主修, 专攻", "e": ""},
{"r": 744, "w": "paper over", "c": "用纸覆盖;弥补,掩盖", "e": ""},
{"r": 745, "w": "paper round", "c": "送报, 送报路线", "e": ""},
{"r": 746, "w": "wait about", "c": "等在附近", "e": ""},
{"r": 747, "w": "wait around", "c": "在附近等候", "e": ""},
{"r": 748, "w": "wait behind", "c": "在其他人走后留下来", "e": ""},
{"r": 749, "w": "wait in", "c": "在家里等", "e": ""},
{"r": 750, "w": "wait on", "c": "服侍, 招待, 拜访, 焦急地等待", "e": ""},
{"r": 751, "w": "wait out", "c": "等到...结束", "e": ""},
{"r": 752, "w": "wait up", "c": "(为...而)等候着不睡", "e": ""},
{"r": 753, "w": "wait up for", "c": "等候着不睡", "e": ""},
{"r": 754, "w": "agree about", "c": "对…取得一致意见", "e": ""},
{"r": 755, "w": "agree in", "c": "在…意见一致", "e": ""},
{"r": 756, "w": "agree on", "c": "就…取得一致意见,商定", "e": ""},
{"r": 757, "w": "serve on", "c": "为成员", "e": ""},
{"r": 758, "w": "serve out", "c": "分发,分配", "e": ""},
{"r": 759, "w": "serve round", "c": "分发", "e": ""},
{"r": 760, "w": "serve under", "c": "在手下任职", "e": ""},
{"r": 761, "w": "serve up", "c": "端上桌; 上菜; 提供; 发送", "e": ""},
{"r": 762, "w": "die away", "c": "熄灭, 平息, 消失", "e": ""},
{"r": 763, "w": "die back", "c": "（植物）枯死但根部还活着; 顶梢枯死", "e": ""},
{"r": 764, "w": "die down", "c": "枯萎, 凋谢", "e": ""},
{"r": 765, "w": "die off", "c": "相继死去直至死光, 消亡, 逐个死亡", "e": ""},
{"r": 766, "w": "die out", "c": "熄灭, 平息, 消失", "e": ""},
{"r": 767, "w": "reach down", "c": "伸手取下…", "e": ""},
{"r": 768, "w": "reach out", "c": "（使）伸出", "e": ""},
{"r": 769, "w": "reach out for", "c": "伸手去拿...", "e": ""},
{"r": 770, "w": "reach up", "c": "举手,伸脖子", "e": ""},
{"r": 771, "w": "bank on", "c": "指望, 依赖", "e": ""},
{"r": 772, "w": "bank up", "c": "堆积, 筑堤", "e": ""},
{"r": 773, "w": "build in", "c": "嵌入, 插入", "e": ""},
{"r": 774, "w": "build on", "c": "在原有的建筑物上增建; 以…为基础; 依赖; 一心指望", "e": ""},
{"r": 775, "w": "stay ahead of", "c": "领先", "e": ""},
{"r": 776, "w": "stay away", "c": "外出", "e": ""},
{"r": 777, "w": "stay away from", "c": "离开,不接近…", "e": ""},
{"r": 778, "w": "stay down", "c": "停留在下面,卧倒", "e": ""},
{"r": 779, "w": "stay off", "c": "不要上（路）; 远离（某地）", "e": ""},
{"r": 780, "w": "stay on", "c": "继续停留", "e": ""},
{"r": 781, "w": "stay out", "c": "呆在户外", "e": ""},
{"r": 782, "w": "stay over", "c": "过夜", "e": ""},
{"r": 783, "w": "stay together", "c": "在一起（歌曲名）", "e": ""},
{"r": 784, "w": "stay up", "c": "不睡觉", "e": ""},
{"r": 785, "w": "plan ahead", "c": "提前计划", "e": ""},
{"r": 786, "w": "plan on", "c": "打算", "e": ""},
{"r": 787, "w": "plan out", "c": "提出,规划出,设计出,部署", "e": ""},
{"r": 788, "w": "cut about", "c": "乱砍, 乱跑", "e": ""},
{"r": 789, "w": "cut across", "c": "抄近路通过", "e": ""},
{"r": 790, "w": "cut away", "c": "切掉, 砍掉", "e": ""},
{"r": 791, "w": "cut back", "c": "修剪, 削减, 急转向, 倒叙", "e": ""},
{"r": 792, "w": "cut back on", "c": "削减", "e": ""},
{"r": 793, "w": "cut in on", "c": "打断", "e": ""},
{"r": 794, "w": "cut on", "c": "很快向前走", "e": ""},
{"r": 795, "w": "cut out for", "c": "生来就合适,天生合适…", "e": ""},
{"r": 796, "w": "cut over", "c": "采伐; 接入", "e": ""},
{"r": 797, "w": "cut round", "c": "卖弄", "e": ""},
{"r": 798, "w": "cut through", "c": "抄近路走过, 刺穿", "e": ""},
{"r": 799, "w": "cut under", "c": "卖得比...便宜", "e": ""},
{"r": 800, "w": "cut up", "c": "切碎, 抨击, 摧毁, 使伤心, 胡闹", "e": ""},
{"r": 801, "w": "building up", "c": "堆焊", "e": ""},
{"r": 802, "w": "kill down", "c": "枪杀时在场,比赛结束时在场", "e": ""},
{"r": 803, "w": "kill off", "c": "消灭", "e": ""},
{"r": 804, "w": "draw ahead", "c": "赶到前面,超到前面", "e": ""},
{"r": 805, "w": "draw apart", "c": "分手,反目,不和", "e": ""},
{"r": 806, "w": "draw away", "c": "拉开, 引开, 离开", "e": ""},
{"r": 807, "w": "draw down", "c": "招致,惹起;挣得,领取;消耗,耗尽", "e": ""},
{"r": 808, "w": "draw forth", "c": "引起, 博得", "e": ""},
{"r": 809, "w": "draw in", "c": "收缩, 引诱, 接近黄昏, 紧缩开支", "e": ""},
{"r": 810, "w": "draw off", "c": "脱去, 撤退", "e": ""},
{"r": 811, "w": "draw on", "c": "戴上, 吸收, 利用, 向...提取, 引诱, 招致, 临近", "e": ""},
{"r": 812, "w": "draw out", "c": "拉长, 抽出, 引出, 拟订", "e": ""},
{"r": 813, "w": "draw round", "c": "围在周围", "e": ""},
{"r": 814, "w": "draw together", "c": "团结起来", "e": ""},
{"r": 815, "w": "draw up", "c": "草拟, 停住, 逼近, 拉起, 整队", "e": ""},
{"r": 816, "w": "raise up", "c": "举起", "e": ""},
{"r": 817, "w": "care about", "c": "担心", "e": ""},
{"r": 818, "w": "pass along", "c": "沿…向前走; 传送, 传递", "e": ""},
{"r": 819, "w": "pass around", "c": "分, 分发, 传送", "e": ""},
{"r": 820, "w": "pass down", "c": "把…一代传一代，使流传", "e": ""},
{"r": 821, "w": "pass on", "c": "传授, 传递", "e": ""},
{"r": 822, "w": "pass out", "c": "分发, 昏倒, 死, 完成学业, 离去", "e": ""},
{"r": 823, "w": "pass over", "c": "忽略, 省略, 不加考虑, 转交", "e": ""},
{"r": 824, "w": "pass through", "c": "通过..., 透过..., 穿过..., 流过...", "e": ""},
{"r": 825, "w": "pass up", "c": "拒绝, 把...向上递", "e": ""},
{"r": 826, "w": "sell on", "c": "使人想买", "e": ""},
{"r": 827, "w": "sell up", "c": "卖完, 为还债而变卖", "e": ""},
{"r": 828, "w": "better off", "c": "比较富裕; 情况好转", "e": ""},
{"r": 829, "w": "practice on", "c": "以…作为实验对象;利用.欺骗", "e": ""},
{"r": 830, "w": "ground on", "c": "基于", "e": ""},
{"r": 831, "w": "light on", "c": "飞临,栖息于;偶然碰见,无意中发现", "e": ""},
{"r": 832, "w": "light out", "c": "匆匆离去", "e": ""},
{"r": 833, "w": "voice over", "c": "旁白", "e": ""},
{"r": 834, "w": "pull about", "c": "把...拖来拖去, 粗暴对待", "e": ""},
{"r": 835, "w": "pull along", "c": "沿…拉", "e": ""},
{"r": 836, "w": "pull apart", "c": "把...撕开, 批评", "e": ""},
{"r": 837, "w": "pull away", "c": "脱身, 离开", "e": ""},
{"r": 838, "w": "pull away from", "c": "从…挣脱,从…开出", "e": ""},
{"r": 839, "w": "pull in", "c": "进站, 靠岸", "e": ""},
{"r": 840, "w": "pull off", "c": "脱, 努力实现, 赢得", "e": ""},
{"r": 841, "w": "pull on", "c": "穿, 戴, 用力拉", "e": ""},
{"r": 842, "w": "pull out", "c": "拔出, 离开, (使)渡过难关, (使)恢复健康", "e": ""},
{"r": 843, "w": "pull over", "c": "靠岸, 开到路边", "e": ""},
{"r": 844, "w": "pull round", "c": "复原", "e": ""},
{"r": 845, "w": "pull through", "c": "(使)渡过难关, (使)恢复健康", "e": ""},
{"r": 846, "w": "pull together", "c": "齐心协力", "e": ""},
{"r": 847, "w": "pull up", "c": "拔起, 停下, 阻止", "e": ""},
{"r": 848, "w": "pull up to", "c": "追赶上", "e": ""},
{"r": 849, "w": "land on", "c": "猛烈抨击", "e": ""},
{"r": 850, "w": "land up", "c": "到达; 处于", "e": ""},
{"r": 851, "w": "free up", "c": "开放 （市场、经济或体制）; 释放", "e": ""},
{"r": 852, "w": "explain away", "c": "通过解释消除", "e": ""},
{"r": 853, "w": "support in", "c": "在…方面支持", "e": ""},
{"r": 854, "w": "lie about", "c": "懒散, 无所事事", "e": ""},
{"r": 855, "w": "lie around", "c": "到处散放, 闲着不干事", "e": ""},
{"r": 856, "w": "lie back", "c": "倚靠", "e": ""},
{"r": 857, "w": "lie down", "c": "躺下", "e": ""},
{"r": 858, "w": "lie in", "c": "在于..., 分娩, 睡懒觉", "e": ""},
{"r": 859, "w": "lie off", "c": "暂停工作", "e": ""},
{"r": 860, "w": "lie on", "c": "依赖, 压迫, 是...的责任", "e": ""},
{"r": 861, "w": "lie over", "c": "等待以后处理, 逾期不付", "e": ""},
{"r": 862, "w": "lie under", "c": "蒙受", "e": ""},
{"r": 863, "w": "lie up", "c": "隐藏, 卧床, 停止使用", "e": ""},
{"r": 864, "w": "range over", "c": "包括,涉及;在…徘徊", "e": ""},
{"r": 865, "w": "trade in for", "c": "以折价交换…", "e": ""},
{"r": 866, "w": "trade on", "c": "利用", "e": ""},
{"r": 867, "w": "trade out", "c": "出卖", "e": ""},
{"r": 868, "w": "trade up", "c": "买进更高价的东西", "e": ""},
{"r": 869, "w": "drive around", "c": "开车四处转 / 兜风", "e": ""},
{"r": 870, "w": "drive away", "c": "驱车离开; 把…驱开, 赶走; 祛", "e": ""},
{"r": 871, "w": "drive away at", "c": "努力做", "e": ""},
{"r": 872, "w": "drive back", "c": "驾车返回, 驱车返回; 迫使后退; 逐退; 却", "e": ""},
{"r": 873, "w": "drive down", "c": "压低", "e": ""},
{"r": 874, "w": "drive in", "c": "驶进; 打入; 强行灌输; 敲进", "e": ""},
{"r": 875, "w": "drive off", "c": "驾车离去; 驶去; 赶走; 击退", "e": ""},
{"r": 876, "w": "drive on", "c": "继续开车; 煽动; 鼓励; 撞在…上", "e": ""},
{"r": 877, "w": "drive out", "c": "开车出去; 驱逐, 驱散; 撵; 祛除", "e": ""},
{"r": 878, "w": "drive out of", "c": "驱逐出", "e": ""},
{"r": 879, "w": "true up", "c": "校准, 装准", "e": ""},
{"r": 880, "w": "club together", "c": "合伙凑钱", "e": ""},
{"r": 881, "w": "break apart", "c": "分裂; 解体", "e": ""},
{"r": 882, "w": "break away", "c": "突然离开, 脱离, 放弃", "e": ""},
{"r": 883, "w": "break away from", "c": "摆脱,脱离", "e": ""},
{"r": 884, "w": "break down into", "c": "把…分解成", "e": ""},
{"r": 885, "w": "break forth", "c": "喷发, 突发", "e": ""},
{"r": 886, "w": "break in", "c": "训练, 使经使用逐渐合用, 闯入, 打断", "e": ""},
{"r": 887, "w": "break in on", "c": "打断, 打扰", "e": ""},
{"r": 888, "w": "break off", "c": "折断, 突然停止, 脱落, 断绝, 暂停", "e": ""},
{"r": 889, "w": "break out in", "c": "突然发出,迸发出,突发", "e": ""},
{"r": 890, "w": "break out into", "c": "长出;突然发出,迸发出", "e": ""},
{"r": 891, "w": "break over", "c": "吞没,淹没;浪潮般向…袭来", "e": ""},
{"r": 892, "w": "break up into", "c": "把…分解成", "e": ""},
{"r": 893, "w": "short on", "c": "在某方面有欠缺", "e": ""},
{"r": 894, "w": "join in", "c": "参加, 加入", "e": ""},
{"r": 895, "w": "join on", "c": "联接在…,安装在…", "e": ""},
{"r": 896, "w": "join up", "c": "参军, 联合起来", "e": ""},
{"r": 897, "w": "base on", "c": "基于", "e": ""},
{"r": 898, "w": "pick apart", "c": "把...撕碎, 把...驳得体无完肤, 严厉批评", "e": ""},
{"r": 899, "w": "pick off", "c": "摘掉, 拔去, 截取", "e": ""},
{"r": 900, "w": "pick out", "c": "挑选", "e": ""},
{"r": 901, "w": "pick over", "c": "分档挑选", "e": ""},
{"r": 902, "w": "pick up on", "c": "注意到, 接近, 理解, 与...熟悉起来", "e": ""},
{"r": 903, "w": "pick up with", "c": "结识,认识…", "e": ""},
{"r": 904, "w": "wear away", "c": "磨损, 流逝, 消磨, 虚度", "e": ""},
{"r": 905, "w": "wear down", "c": "磨损, 损耗, 使疲劳, 使厌烦, 克服", "e": ""},
{"r": 906, "w": "wear off", "c": "逐渐减弱, 消失, 磨损, 耗损", "e": ""},
{"r": 907, "w": "wear on", "c": "缓缓消逝, 时间消逝, 消磨, 使恼火, 骚扰", "e": ""},
{"r": 908, "w": "wear out", "c": "穿破, 用坏, 疲劳, 经受住, 消磨", "e": ""},
{"r": 909, "w": "wear through", "c": "穿破, 用坏, 用旧, 耗损", "e": ""},
{"r": 910, "w": "space out", "c": "隔开", "e": ""},
{"r": 911, "w": "increase in", "c": "在...方面增加", "e": ""},
{"r": 912, "w": "cover in", "c": "封盖", "e": ""},
{"r": 913, "w": "cover over", "c": "遮没", "e": ""},
{"r": 914, "w": "cover up", "c": "掩盖", "e": ""},
{"r": 915, "w": "cover up for", "c": "包庇", "e": ""},
{"r": 916, "w": "center around", "c": "集中围绕", "e": ""},
{"r": 917, "w": "center back", "c": "排球队或手球队站在后排中间的后卫", "e": ""},
{"r": 918, "w": "center forward", "c": "排球; 足球; 水球; 曲棍球队的中前锋", "e": ""},
{"r": 919, "w": "center on", "c": "以…为中心; 重点在于…, 主要与…有关", "e": ""},
{"r": 920, "w": "couple in", "c": "耦合，接入", "e": ""},
{"r": 921, "w": "couple on", "c": "结合到", "e": ""},
{"r": 922, "w": "couple up", "c": "把…耦联起来", "e": ""},
{"r": 923, "w": "hit back", "c": "反击,击退", "e": ""},
{"r": 924, "w": "hit off", "c": "把...打掉, 适合", "e": ""},
{"r": 925, "w": "hit on", "c": "忽然想到,碰巧遇见,到达", "e": ""},
{"r": 926, "w": "hit out", "c": "猛打", "e": ""},
{"r": 927, "w": "hit out at", "c": "向…扑去,勐烈攻击", "e": ""},
{"r": 928, "w": "hit up", "c": "请求", "e": ""},
{"r": 929, "w": "rule over", "c": "统治, 支配", "e": ""},
{"r": 930, "w": "eat away", "c": "连续不断地吃; 侵蚀; 腐蚀; 咬坏", "e": ""},
{"r": 931, "w": "eat in", "c": "在家吃饭; 在学校就餐", "e": ""},
{"r": 932, "w": "eat off", "c": "吃掉", "e": ""},
{"r": 933, "w": "eat on", "c": "伊顿（姓氏））", "e": ""},
{"r": 934, "w": "eat out", "c": "上馆子吃饭, 锈坏, 过度消耗(牧草等), 责骂", "e": ""},
{"r": 935, "w": "eat up", "c": "吃光, 耗尽, 吞灭", "e": ""},
{"r": 936, "w": "eat up with", "c": "使沉迷于, 使纠缠于", "e": ""},
{"r": 937, "w": "teach up", "c": "大麻中毒;喝醉酒", "e": ""},
{"r": 938, "w": "pound out", "c": "连续猛击而产生", "e": ""},
{"r": 939, "w": "pound up", "c": "捣碎：", "e": ""},
{"r": 940, "w": "phone in", "c": "打电话告知", "e": ""},
{"r": 941, "w": "phone up", "c": "给…打电话", "e": ""},
{"r": 942, "w": "bed down", "c": "安排(人 / 动物)舒服地睡觉, 使自己舒服地睡觉", "e": ""},
{"r": 943, "w": "bed out", "c": "栽种,移栽", "e": ""},
{"r": 944, "w": "piece out", "c": "把…拼凑起来", "e": ""},
{"r": 945, "w": "piece together", "c": "拼凑", "e": ""},
{"r": 946, "w": "piece up", "c": "修补, 分赃", "e": ""},
{"r": 947, "w": "detail off", "c": "派遣,指派", "e": ""},
{"r": 948, "w": "single out", "c": "挑选; 抉", "e": ""},
{"r": 949, "w": "doctor up", "c": "掺假", "e": ""},
{"r": 950, "w": "date back", "c": "回溯至", "e": ""},
{"r": 951, "w": "date back to", "c": "始于,可以追溯到…", "e": ""},
{"r": 952, "w": "wall in", "c": "筑墙围住", "e": ""},
{"r": 953, "w": "wall off", "c": "杜绝,隔开", "e": ""},
{"r": 954, "w": "wall up", "c": "堵塞", "e": ""},
{"r": 955, "w": "catch on", "c": "变得流行, 理解, 明白", "e": ""},
{"r": 956, "w": "catch on to", "c": "理解", "e": ""},
{"r": 957, "w": "catch up on", "c": "补做(工作)", "e": ""},
{"r": 958, "w": "catch up with", "c": "赶上", "e": ""},
{"r": 959, "w": "wish away", "c": "希望消失", "e": ""},
{"r": 960, "w": "wish on", "c": "把...强加于", "e": ""},
{"r": 961, "w": "scheme out", "c": "设计出", "e": ""},
{"r": 962, "w": "step along", "c": "走开", "e": ""},
{"r": 963, "w": "step aside", "c": "避开", "e": ""},
{"r": 964, "w": "step back", "c": "后退，退居不重要的部位; 退坡儿; 退后; 却", "e": ""},
{"r": 965, "w": "step down", "c": "走下, 逐步减低, 辞职, 下台", "e": ""},
{"r": 966, "w": "step forward", "c": "向前走; 站出来; 迈步", "e": ""},
{"r": 967, "w": "step in", "c": "走进, 干涉, 作短时间的非正式访问", "e": ""},
{"r": 968, "w": "step off", "c": "结婚, 死", "e": ""},
{"r": 969, "w": "step on", "c": "踩上..., 踏上...", "e": ""},
{"r": 970, "w": "step out on", "c": "不忠实于", "e": ""},
{"r": 971, "w": "step up", "c": "走近, 逐步增加, 提升, 提高", "e": ""},
{"r": 972, "w": "seek out", "c": "搜出, 挑出", "e": ""},
{"r": 973, "w": "seek through", "c": "搜遍", "e": ""},
{"r": 974, "w": "film over", "c": "（使）变朦胧", "e": ""},
{"r": 975, "w": "deal out", "c": "分配, 分给", "e": ""},
{"r": 976, "w": "source in", "c": "源盘", "e": ""},
{"r": 977, "w": "firm up", "c": "（使）更结实; （使）更坚硬; 把…安排得更稳妥; 使稳定", "e": ""},
{"r": 978, "w": "listen up", "c": "听好了", "e": ""},
{"r": 979, "w": "board around", "c": "吃轮伙", "e": ""},
{"r": 980, "w": "board in", "c": "在寄宿处膳宿,用木板围起来", "e": ""},
{"r": 981, "w": "board out", "c": "在外面用膳", "e": ""},
{"r": 982, "w": "board up", "c": "用木板封住, 用木板隔断", "e": ""},
{"r": 983, "w": "chance on", "c": "偶然发现", "e": ""},
{"r": 984, "w": "fail in", "c": "在…失败;缺乏…", "e": ""},
{"r": 985, "w": "realize on", "c": "从…赚得", "e": ""},
{"r": 986, "w": "share in", "c": "分享, 分担", "e": ""},
{"r": 987, "w": "share out", "c": "分给", "e": ""},
{"r": 988, "w": "plant in", "c": "栽进,插进,刺进,扎进", "e": ""},
{"r": 989, "w": "plant out", "c": "把...移植户外, 以一定行距移植(秧苗)", "e": ""},
{"r": 990, "w": "used in", "c": "用于；适用于", "e": ""},
{"r": 991, "w": "colour up", "c": "羞得脸红", "e": ""},
{"r": 992, "w": "rise up", "c": "起义", "e": ""},
{"r": 993, "w": "close about", "c": "围住, 包围", "e": ""},
{"r": 994, "w": "close behind", "c": "紧跟在…的后面", "e": ""},
{"r": 995, "w": "close down", "c": "关闭, 歇业, 停止播音", "e": ""},
{"r": 996, "w": "close in", "c": "包围, 封锁, (白昼)渐短", "e": ""},
{"r": 997, "w": "close in on", "c": "包围,逼近", "e": ""},
{"r": 998, "w": "close off", "c": "隔绝, 封锁, 结帐", "e": ""},
{"r": 999, "w": "close on", "c": "接近", "e": ""},
{"r": 1000, "w": "close over", "c": "淹没, 封盖, 遮蔽", "e": ""}
];
