/* Common English phrasal verbs — curated seeds + ECDICT (skywind3000/ECDICT, MIT/open). { r:rank, w:phrase, c:Chinese, e:English def }. */
window.PHRASAL = [
{"r": 1, "w": "give up", "c": "放弃；戒掉", "e": "stop trying to do something; quit a habit"},
{"r": 2, "w": "find out", "c": "查明，发现", "e": "discover information"},
{"r": 3, "w": "look for", "c": "寻找", "e": "try to find something or someone"},
{"r": 4, "w": "go on", "c": "继续；发生", "e": "continue; happen"},
{"r": 5, "w": "come back", "c": "回来", "e": "return to a place"},
{"r": 6, "w": "pick up", "c": "捡起；（开车）接某人；学会", "e": "lift; collect someone; learn casually"},
{"r": 7, "w": "turn on", "c": "打开（电器、灯）", "e": "start a device or light working"},
{"r": 8, "w": "turn off", "c": "关闭（电器、灯）", "e": "stop a device or light working"},
{"r": 9, "w": "get up", "c": "起床；站起来", "e": "rise from bed; stand up"},
{"r": 10, "w": "put on", "c": "穿上；戴上", "e": "dress in; wear"},
{"r": 11, "w": "take off", "c": "脱下；（飞机）起飞", "e": "remove clothing; (of a plane) leave the ground"},
{"r": 12, "w": "wake up", "c": "醒来；叫醒", "e": "stop sleeping; rouse someone"},
{"r": 13, "w": "grow up", "c": "长大，成长", "e": "become an adult"},
{"r": 14, "w": "set up", "c": "建立；设置，搭建", "e": "establish; arrange or assemble"},
{"r": 15, "w": "carry on", "c": "继续", "e": "continue doing something"},
{"r": 16, "w": "break down", "c": "（机器）故障；（情绪）崩溃", "e": "stop working; lose emotional control"},
{"r": 17, "w": "work out", "c": "锻炼；解决；想出", "e": "exercise; solve; figure out"},
{"r": 18, "w": "look after", "c": "照顾", "e": "take care of someone or something"},
{"r": 19, "w": "look forward to", "c": "期待", "e": "anticipate with pleasure"},
{"r": 20, "w": "give in", "c": "屈服，让步", "e": "stop resisting; yield"},
{"r": 21, "w": "go out", "c": "出去（社交）；（火、灯）熄灭", "e": "leave home for fun; (of fire/light) stop burning"},
{"r": 22, "w": "come in", "c": "进来", "e": "enter a place"},
{"r": 23, "w": "get back", "c": "返回；取回", "e": "return; recover something"},
{"r": 24, "w": "take care of", "c": "照顾；处理", "e": "look after; handle"},
{"r": 25, "w": "put off", "c": "推迟", "e": "postpone"},
{"r": 26, "w": "call off", "c": "取消", "e": "cancel something planned"},
{"r": 27, "w": "run out of", "c": "用完，耗尽", "e": "have no more of something left"},
{"r": 28, "w": "bring up", "c": "抚养；提出（话题）", "e": "raise a child; mention a topic"},
{"r": 29, "w": "check out", "c": "查看；结账退房", "e": "examine; pay and leave a hotel"},
{"r": 30, "w": "check in", "c": "登记入住；办理登机", "e": "register at a hotel or airport"},
{"r": 31, "w": "fill out", "c": "填写（表格）", "e": "complete a form"},
{"r": 32, "w": "hold on", "c": "等一下；坚持", "e": "wait; persevere"},
{"r": 33, "w": "hang up", "c": "挂断电话", "e": "end a phone call"},
{"r": 34, "w": "get along", "c": "和睦相处", "e": "have a friendly relationship"},
{"r": 35, "w": "get on", "c": "上（车、飞机）；进展", "e": "board a vehicle; make progress"},
{"r": 36, "w": "get off", "c": "下（车）", "e": "leave a vehicle"},
{"r": 37, "w": "show up", "c": "出现，露面", "e": "appear; arrive"},
{"r": 38, "w": "turn up", "c": "出现；调高（音量）", "e": "appear unexpectedly; increase volume"},
{"r": 39, "w": "turn down", "c": "拒绝；调低（音量）", "e": "reject; lower volume"},
{"r": 40, "w": "put up with", "c": "容忍，忍受", "e": "tolerate something unpleasant"},
{"r": 41, "w": "look up", "c": "查阅；向上看", "e": "search for information; raise the eyes"},
{"r": 42, "w": "look down on", "c": "看不起，轻视", "e": "regard as inferior"},
{"r": 43, "w": "point out", "c": "指出", "e": "draw attention to a fact"},
{"r": 44, "w": "figure out", "c": "弄清楚，想出", "e": "understand or solve by thinking"},
{"r": 45, "w": "come up with", "c": "想出，提出", "e": "produce an idea or plan"},
{"r": 46, "w": "end up", "c": "最终成为，结果是", "e": "eventually be or do something"},
{"r": 47, "w": "set off", "c": "出发；引发，触发", "e": "start a journey; trigger something"},
{"r": 48, "w": "take over", "c": "接管，接手", "e": "take control of something"},
{"r": 49, "w": "take up", "c": "开始从事；占用（时间、空间）", "e": "start a hobby; occupy time or space"},
{"r": 50, "w": "give back", "c": "归还", "e": "return something to its owner"},
{"r": 51, "w": "throw away", "c": "扔掉，丢弃", "e": "discard"},
{"r": 52, "w": "put away", "c": "收起来，放好", "e": "store something in its place"},
{"r": 53, "w": "put down", "c": "放下；镇压；贬低", "e": "set down; suppress; criticize"},
{"r": 54, "w": "break up", "c": "分手；解散，拆散", "e": "end a relationship; disperse"},
{"r": 55, "w": "make up", "c": "编造；和好；化妆", "e": "invent; reconcile; apply cosmetics"},
{"r": 56, "w": "catch up", "c": "赶上", "e": "reach the same level or point"},
{"r": 57, "w": "cut down on", "c": "减少", "e": "reduce the amount of something"},
{"r": 58, "w": "cut off", "c": "切断；隔绝", "e": "disconnect; isolate"},
{"r": 59, "w": "drop off", "c": "（开车）送某人；睡着", "e": "deliver someone; fall asleep"},
{"r": 60, "w": "get rid of", "c": "摆脱，去掉", "e": "remove or dispose of"},
{"r": 61, "w": "go back", "c": "回去，返回", "e": "return to a place or topic"},
{"r": 62, "w": "go ahead", "c": "继续，开始（吧）", "e": "proceed; begin"},
{"r": 63, "w": "hold up", "c": "举起；耽误；持械抢劫", "e": "raise; delay; rob"},
{"r": 64, "w": "keep on", "c": "继续", "e": "continue doing something"},
{"r": 65, "w": "keep up with", "c": "跟上", "e": "maintain the same pace as"},
{"r": 66, "w": "let down", "c": "使失望", "e": "fail to meet someone's hopes"},
{"r": 67, "w": "move on", "c": "继续前进；翻篇", "e": "progress to something new"},
{"r": 68, "w": "pass away", "c": "去世", "e": "die (polite term)"},
{"r": 69, "w": "pay back", "c": "偿还；报复", "e": "repay; take revenge"},
{"r": 70, "w": "run into", "c": "偶遇；撞上", "e": "meet by chance; collide with"},
{"r": 71, "w": "set out", "c": "出发；着手", "e": "begin a journey; start a task"},
{"r": 72, "w": "sort out", "c": "解决；整理", "e": "resolve; organize"},
{"r": 73, "w": "stand out", "c": "突出，显眼", "e": "be clearly noticeable"},
{"r": 74, "w": "stand up", "c": "站起来", "e": "rise to one's feet"},
{"r": 75, "w": "take back", "c": "收回（话）；退回", "e": "retract a statement; return goods"},
{"r": 76, "w": "take down", "c": "记下；拆下", "e": "write down; dismantle"},
{"r": 77, "w": "try on", "c": "试穿", "e": "put on clothing to test the fit"},
{"r": 78, "w": "turn into", "c": "变成", "e": "become something different"},
{"r": 79, "w": "turn out", "c": "结果是，原来是", "e": "prove to be the case"},
{"r": 80, "w": "warm up", "c": "热身；变暖", "e": "prepare with light exercise; become warmer"},
{"r": 81, "w": "work on", "c": "致力于，改进", "e": "try to improve or repair"},
{"r": 82, "w": "account for", "c": "解释；（数量上）占", "e": "explain; make up a proportion of"},
{"r": 83, "w": "back up", "c": "支持；备份；倒车", "e": "support; make a copy; reverse a vehicle"},
{"r": 84, "w": "blow up", "c": "爆炸；充气；放大", "e": "explode; inflate; enlarge"},
{"r": 85, "w": "bring back", "c": "带回；使想起", "e": "return; evoke a memory"},
{"r": 86, "w": "bring about", "c": "带来，导致", "e": "cause something to happen"},
{"r": 87, "w": "call back", "c": "回电话", "e": "return a phone call"},
{"r": 88, "w": "calm down", "c": "冷静下来", "e": "become or make calm"},
{"r": 89, "w": "care for", "c": "照顾；喜欢", "e": "look after; like"},
{"r": 90, "w": "come across", "c": "偶然发现；给人…的印象", "e": "find by chance; give an impression"},
{"r": 91, "w": "count on", "c": "依靠，指望", "e": "rely on someone or something"},
{"r": 92, "w": "deal with", "c": "处理，应对", "e": "take action to handle"},
{"r": 93, "w": "depend on", "c": "取决于；依靠", "e": "be determined by; rely on"},
{"r": 94, "w": "dress up", "c": "盛装打扮", "e": "wear formal or fancy clothes"},
{"r": 95, "w": "fall apart", "c": "崩溃，瓦解", "e": "break into pieces; collapse"},
{"r": 96, "w": "get over", "c": "克服；从…中恢复", "e": "recover from; overcome"},
{"r": 97, "w": "hand in", "c": "上交，提交", "e": "submit something to a person in authority"},
{"r": 98, "w": "hand out", "c": "分发", "e": "distribute to people"},
{"r": 99, "w": "set aside", "c": "留出；搁置", "e": "reserve; put away for later"},
{"r": 100, "w": "watch out", "c": "小心，当心", "e": "be careful of danger"},
{"r": 101, "w": "be about", "c": "从事于", "e": ""},
{"r": 102, "w": "be about to", "c": "即将", "e": ""},
{"r": 103, "w": "be ahead", "c": "赚钱", "e": ""},
{"r": 104, "w": "be along", "c": "来到", "e": ""},
{"r": 105, "w": "be along to", "c": "来到…", "e": ""},
{"r": 106, "w": "be around", "c": "在旁边,在附近", "e": ""},
{"r": 107, "w": "be back", "c": "回来，放回; 拖欠", "e": ""},
{"r": 108, "w": "be down for", "c": "被列入名单", "e": ""},
{"r": 109, "w": "be down on", "c": "对...有怨气", "e": ""},
{"r": 110, "w": "be in", "c": "到达，执政; 在家; 搞", "e": ""},
{"r": 111, "w": "be in at", "c": "参与,参加", "e": ""},
{"r": 112, "w": "be in for", "c": "必定遭到, 参加", "e": ""},
{"r": 113, "w": "be in on", "c": "参预", "e": ""},
{"r": 114, "w": "be off", "c": "离开,取消,竣工,变坏", "e": ""},
{"r": 115, "w": "be off with", "c": "和…断绝关系", "e": ""},
{"r": 116, "w": "be on", "c": "已经开始了, 接受打赌; 上映", "e": ""},
{"r": 117, "w": "be on to", "c": "意识到, 找...岔子", "e": ""},
{"r": 118, "w": "be out for", "c": "力图要", "e": ""},
{"r": 119, "w": "be out to", "c": "企图,决心,很想…", "e": ""},
{"r": 120, "w": "be over", "c": "完了, 结束", "e": ""},
{"r": 121, "w": "be through", "c": "完成,做完;弃绝,嫌弃;完蛋", "e": ""},
{"r": 122, "w": "be through with", "c": "完成, 弃绝", "e": ""},
{"r": 123, "w": "be up", "c": "起床", "e": ""},
{"r": 124, "w": "be up on", "c": "精通, 熟悉", "e": ""},
{"r": 125, "w": "be up to", "c": "胜任,达到,由…负责", "e": ""},
{"r": 126, "w": "be up with", "c": "出了问题,没有希望", "e": ""},
{"r": 127, "w": "have down", "c": "请…到(乡下或南方)作客", "e": ""},
{"r": 128, "w": "have on", "c": "穿着, 戴着, 在手头, 使上钩", "e": ""},
{"r": 129, "w": "do away with", "c": "废除, 弄死", "e": ""},
{"r": 130, "w": "do down", "c": "胜过, 欺骗", "e": ""},
{"r": 131, "w": "do in", "c": "杀害; 搞垮; 损坏; 累垮", "e": ""},
{"r": 132, "w": "do out", "c": "打扫, 收拾", "e": ""},
{"r": 133, "w": "do over", "c": "重做", "e": ""},
{"r": 134, "w": "do up", "c": "修缮, 包扎, 整理", "e": ""},
{"r": 135, "w": "say about", "c": "[法] 估计, 大约, 未定的数量", "e": ""},
{"r": 136, "w": "say over", "c": "背诵", "e": ""},
{"r": 137, "w": "go about", "c": "从事, 走动, 传开", "e": ""},
{"r": 138, "w": "go across", "c": "穿过, 横过", "e": ""},
{"r": 139, "w": "go ahead with", "c": "继续进行", "e": ""},
{"r": 140, "w": "go along", "c": "前进, 进行", "e": ""},
{"r": 141, "w": "go along with", "c": "陪...一起去, 赞同, 附和", "e": ""},
{"r": 142, "w": "go around", "c": "参观; 转动; 走访; 相处", "e": ""},
{"r": 143, "w": "go away", "c": "走开", "e": ""},
{"r": 144, "w": "go away with", "c": "带走", "e": ""},
{"r": 145, "w": "go back from", "c": "不守,不履行,违背", "e": ""},
{"r": 146, "w": "go back on", "c": "违约, 背弃", "e": ""},
{"r": 147, "w": "go back to", "c": "回去", "e": ""},
{"r": 148, "w": "go behind", "c": "探究, 进一步斟酌", "e": ""},
{"r": 149, "w": "go down", "c": "下去, 下沉, 坠落, 被接受, 咽下, 平静下来, 下降, 传下去", "e": ""},
{"r": 150, "w": "go down on", "c": "（粗俚）口交", "e": ""},
{"r": 151, "w": "go down to", "c": "延续至", "e": ""},
{"r": 152, "w": "go down with", "c": "因…而病倒,患…", "e": ""},
{"r": 153, "w": "go forth", "c": "向前去, 被发表", "e": ""},
{"r": 154, "w": "go forward", "c": "前进, 发生", "e": ""},
{"r": 155, "w": "go in", "c": "走进, 放得进, 参加", "e": ""},
{"r": 156, "w": "go in at", "c": "痛打", "e": ""},
{"r": 157, "w": "go in for", "c": "参加, 追求, 从事, 赞成", "e": ""},
{"r": 158, "w": "go in with", "c": "与…合伙,与…分担费用,参加", "e": ""},
{"r": 159, "w": "go off", "c": "离开, 去世, 消失, 爆炸, 被发射, 变质, 进行, 睡去, 卖掉", "e": ""},
{"r": 160, "w": "go off into", "c": "开始, 爆发出", "e": ""},
{"r": 161, "w": "go off with", "c": "拿去, 抢走", "e": ""},
{"r": 162, "w": "go on for", "c": "接近,快到", "e": ""},
{"r": 163, "w": "go on to", "c": "转入", "e": ""},
{"r": 164, "w": "go on with", "c": "暂时使用", "e": ""},
{"r": 165, "w": "go out for", "c": "努力争取,力争", "e": ""},
{"r": 166, "w": "go out of", "c": "从…出来，离开", "e": ""},
{"r": 167, "w": "go over", "c": "转变, 仔细检查, 润色, 复习", "e": ""},
{"r": 168, "w": "go round", "c": "到处走动, 顺便去, 流传", "e": ""},
{"r": 169, "w": "go through", "c": "经历, 经受, 仔细检查, 搜查, 参加, 履行, 被通过, 用完", "e": ""},
{"r": 170, "w": "go through with", "c": "完成", "e": ""},
{"r": 171, "w": "go together", "c": "互相协调, 相配, 恋爱", "e": ""},
{"r": 172, "w": "go under", "c": "死, 失败, 屈服, 破产", "e": ""},
{"r": 173, "w": "go up", "c": "上升, 兴建", "e": ""},
{"r": 174, "w": "go up to", "c": "入…， 进…", "e": ""},
{"r": 175, "w": "get about", "c": "走动, 旅行, 传开, 积极参加社会活动", "e": ""},
{"r": 176, "w": "get across", "c": "通过, 被理解", "e": ""},
{"r": 177, "w": "get ahead", "c": "领先, 走在前面, 进步, 获得成功", "e": ""},
{"r": 178, "w": "get ahead of", "c": "胜过, 超过", "e": ""},
{"r": 179, "w": "get along with", "c": "进展, 走开", "e": ""},
{"r": 180, "w": "get around", "c": "病后能够走动, (非正式)旅行, 传开来", "e": ""},
{"r": 181, "w": "get around to", "c": "设法找到足够的时间去做（某事）; 说服", "e": ""},
{"r": 182, "w": "get away", "c": "离开, 逃脱, 起跑, 出发", "e": ""},
{"r": 183, "w": "get away from", "c": "离开,摆脱,脱离", "e": ""},
{"r": 184, "w": "get away with", "c": "na. 拿走；避开责备[惩罚]；〈俚〉卷(款)潜逃；吃掉，喝掉", "e": ""},
{"r": 185, "w": "get back at", "c": "报复,对…进行报复", "e": ""},
{"r": 186, "w": "get back to", "c": "回到…,继续…", "e": ""},
{"r": 187, "w": "get behind", "c": "落后, 支持, 拖欠, 识破", "e": ""},
{"r": 188, "w": "get down", "c": "下来, 吞下, 写下, 使沮丧", "e": ""},
{"r": 189, "w": "get down on", "c": "开始不喜欢", "e": ""},
{"r": 190, "w": "get down to", "c": "开始认真考虑", "e": ""},
{"r": 191, "w": "get in", "c": "进入, 到达, 收获, 插入, 陷入", "e": ""},
{"r": 192, "w": "get in on", "c": "参加,参与,干预", "e": ""},
{"r": 193, "w": "get on for", "c": "接近", "e": ""},
{"r": 194, "w": "get on with", "c": "继续（干某事）; 和…友好相处", "e": ""},
{"r": 195, "w": "get out", "c": "出去, 离开, 逃脱, 摆脱, 泄露, 说出, 出版, 弄出来", "e": ""},
{"r": 196, "w": "get out of", "c": "离开,摆脱", "e": ""},
{"r": 197, "w": "get round", "c": "避免, 说服, 走动, 传开来", "e": ""},
{"r": 198, "w": "get round to", "c": "设法找到足够的时间去做（某事）; 说服", "e": ""},
{"r": 199, "w": "get through", "c": "做完, 通过, 度过", "e": ""},
{"r": 200, "w": "get through to", "c": "打通…电话;使自己被…理解,把自己的意思对…讲明白", "e": ""},
{"r": 201, "w": "get through with", "c": "完成,做完,结束", "e": ""},
{"r": 202, "w": "get together", "c": "聚集, 收集, 积累", "e": ""},
{"r": 203, "w": "get under", "c": "抑制, 控制, 镇压", "e": ""},
{"r": 204, "w": "get up to", "c": "到达,赶上;学到,读到;从事,干", "e": ""},
{"r": 205, "w": "make away", "c": "逃走, 离开", "e": ""},
{"r": 206, "w": "make away with", "c": "带...而逃走, 摆脱, 杀死, 浪费 / [法] 杀掉, 摧毁, 用完", "e": ""},
{"r": 207, "w": "make down", "c": "改小 / [经] 清算, 改小, 准备", "e": ""},
{"r": 208, "w": "make in", "c": "向...进入, 干涉别人, 加入纷争", "e": ""},
{"r": 209, "w": "make off", "c": "离开", "e": ""},
{"r": 210, "w": "make off with", "c": "带...而逃 / [法] 偷", "e": ""},
{"r": 211, "w": "make out", "c": "书写, 填写, 拼凑, 说明, 理解, 辨认出, 设法应付, 进展 / [法] 开出, 写出, 看出", "e": ""},
{"r": 212, "w": "make out of", "c": "用...制造, 理解, 了解", "e": ""},
{"r": 213, "w": "make over", "c": "转让, 移交, 改造 / [经] 把(财产)转让, 移交", "e": ""},
{"r": 214, "w": "make through", "c": "n. 使…通过使…度过", "e": ""},
{"r": 215, "w": "make through with", "c": "完成", "e": ""},
{"r": 216, "w": "make up for", "c": "补偿,弥补", "e": ""},
{"r": 217, "w": "make up of", "c": "构成，组成", "e": ""},
{"r": 218, "w": "make up to", "c": "接近, 奉承", "e": ""},
{"r": 219, "w": "make up with", "c": "与…和解", "e": ""},
{"r": 220, "w": "know about", "c": "知道,了解,听说过…", "e": ""},
{"r": 221, "w": "know apart", "c": "能够区别", "e": ""},
{"r": 222, "w": "see about", "c": "查询, 留意于, 料理", "e": ""},
{"r": 223, "w": "see off", "c": "送行，送别; 把（某人）赶走; 欢送", "e": ""},
{"r": 224, "w": "see out", "c": "送某人出门;看完,坚持到底", "e": ""},
{"r": 225, "w": "see over", "c": "察看", "e": ""},
{"r": 226, "w": "see round", "c": "巡视,视察,察看", "e": ""},
{"r": 227, "w": "see through", "c": "看穿, 识破", "e": ""},
{"r": 228, "w": "take along", "c": "随身携带,带去", "e": ""},
{"r": 229, "w": "take apart", "c": "拆开", "e": ""},
{"r": 230, "w": "take away", "c": "取走", "e": ""},
{"r": 231, "w": "take in", "c": "接受, 接待, 吸收, 改小, 理解, 注意到, 包括, 轻信, 欺骗, 观看, 拘留 / [法] 收容, 了解, 接受", "e": ""},
{"r": 232, "w": "take on", "c": "呈现, 具有, 雇用, 接纳, 承担, 同...较量, 流行, 盛气凌人", "e": ""},
{"r": 233, "w": "take out", "c": "拿出, 取出, 去掉, 扣除, 发泄, 抵充, 取得, 出发 / [化] 取出", "e": ""},
{"r": 234, "w": "take up with", "c": "与...亲密交往, 致力于 / [法] 忍受, 接受, 采用", "e": ""},
{"r": 235, "w": "think about", "c": "考虑, 回想", "e": ""},
{"r": 236, "w": "think back", "c": "回想", "e": ""},
{"r": 237, "w": "think on", "c": "考虑", "e": ""},
{"r": 238, "w": "think out", "c": "彻底思考, 设计出", "e": ""},
{"r": 239, "w": "think over", "c": "仔细考虑", "e": ""},
{"r": 240, "w": "think through", "c": "彻底地全面考虑", "e": ""},
{"r": 241, "w": "think up", "c": "想出, 发明", "e": ""},
{"r": 242, "w": "come about", "c": "发生, 改变方向", "e": ""},
{"r": 243, "w": "come along", "c": "出现, 进步 / [电] 伸线器", "e": ""},
{"r": 244, "w": "come along with", "c": "随同", "e": ""},
{"r": 245, "w": "come apart", "c": "分开, 分裂", "e": ""},
{"r": 246, "w": "come around", "c": "来, 前来, 过访, 顺便来访, 笼络, 诱骗", "e": ""},
{"r": 247, "w": "come around to", "c": "转而接受,重新着手…", "e": ""},
{"r": 248, "w": "come away", "c": "脱开", "e": ""},
{"r": 249, "w": "come down", "c": "下来, 下跌, 落泊, 流传下来, 捐钱, 反对", "e": ""},
{"r": 250, "w": "come down on", "c": "惩罚, 索取", "e": ""},
{"r": 251, "w": "come down to", "c": "流传下来;压缩为,归结为,简化为", "e": ""},
{"r": 252, "w": "come down with", "c": "被传染上,因…而病倒", "e": ""},
{"r": 253, "w": "come forth", "c": "出来, 涌现, 被公布", "e": ""},
{"r": 254, "w": "come forward", "c": "站出来, 自告奋勇, 主动响应", "e": ""},
{"r": 255, "w": "come in for", "c": "遭到, 受到", "e": ""},
{"r": 256, "w": "come in on", "c": "参加,加入", "e": ""},
{"r": 257, "w": "come in with", "c": "参加,加入", "e": ""},
{"r": 258, "w": "come off", "c": "发生, 举行, 表现, 结果", "e": ""},
{"r": 259, "w": "come on", "c": "偶遇, 进步, 发生, 开始, 出场, 快来", "e": ""},
{"r": 260, "w": "come out", "c": "到边远地区来, 出现, 露出, 出版, 罢工, 结果是, 褪去, 被解出, 宣布", "e": ""},
{"r": 261, "w": "come out in", "c": "出", "e": ""},
{"r": 262, "w": "come out of", "c": "由...产生", "e": ""},
{"r": 263, "w": "come out with", "c": "发表, 出版, 说出, 提出, 把...投入市场销售", "e": ""},
{"r": 264, "w": "come over", "c": "过来 / [建] 馏出", "e": ""},
{"r": 265, "w": "come round", "c": "顺便来访, 绕道而来, 转向, 改主意, 苏醒, 平息", "e": ""},
{"r": 266, "w": "come through", "c": "经历...仍活着, 安然度过, 胜利, 表现", "e": ""},
{"r": 267, "w": "come together", "c": "聚会, 相见; 会面; 汇集", "e": ""},
{"r": 268, "w": "come under", "c": "归入, 遭受", "e": ""},
{"r": 269, "w": "come up", "c": "走上前来, 发芽, 发生, 被提到, 流行 / [建] 按照指标达到质量标准", "e": ""},
{"r": 270, "w": "come up to", "c": "达到, 等于", "e": ""},
{"r": 271, "w": "tell apart", "c": "分辨", "e": ""},
{"r": 272, "w": "tell off", "c": "分派出, 责备", "e": ""},
{"r": 273, "w": "tell on", "c": "告发; 产生（坏的）影响", "e": ""},
{"r": 274, "w": "put about", "c": "转向, 散布, 使烦恼", "e": ""},
{"r": 275, "w": "put across", "c": "做成, 使被接受, 欺骗", "e": ""},
{"r": 276, "w": "put apart", "c": "留开, 拨开", "e": ""},
{"r": 277, "w": "put aside", "c": "撇开, 储存...备用", "e": ""},
{"r": 278, "w": "put back", "c": "放回原处, 向后移, 推迟, 倒退, 使后退", "e": ""},
{"r": 279, "w": "put behind", "c": "推迟", "e": ""},
{"r": 280, "w": "put down to", "c": "归因于", "e": ""},
{"r": 281, "w": "put forth", "c": "放出, 发表, 颁布, 提出, 发挥, 起航", "e": ""},
{"r": 282, "w": "put forward", "c": "放出, 拿出, 提出, 推举出 / [法] 放出, 提出", "e": ""},
{"r": 283, "w": "put in", "c": "放进, 提出, 提交, 选举, 插入, 种植, 进港, 进入 / [经] 提出", "e": ""},
{"r": 284, "w": "put in for", "c": "申请", "e": ""},
{"r": 285, "w": "put out", "c": "放出, 伸出, 生产, 出版, 发布, 熄灭, 消除, 使困扰, 使脱臼, 把...杀出局, 出航 / [化] 关; 停止", "e": ""},
{"r": 286, "w": "put over", "c": "使转向, 推迟, 拖延, 使被接受, 驶过", "e": ""},
{"r": 287, "w": "put through", "c": "搞成, 接通", "e": ""},
{"r": 288, "w": "put together", "c": "把...加起来, 装配, 整理", "e": ""},
{"r": 289, "w": "put under", "c": "杀死, 埋葬", "e": ""},
{"r": 290, "w": "put up", "c": "举起, 抬起, 进行, 推举, 参加竞选, 提供, 建造, 接待, 包装, 公布, 上演 / [化] 搭架", "e": ""},
{"r": 291, "w": "ask about", "c": "打听,询问", "e": ""},
{"r": 292, "w": "ask around", "c": "到处打听", "e": ""},
{"r": 293, "w": "ask in", "c": "请（某人）进来", "e": ""},
{"r": 294, "w": "ask off", "c": "请假", "e": ""},
{"r": 295, "w": "ask out", "c": "请（某人）外出", "e": ""},
{"r": 296, "w": "ask over", "c": "请（某人）来自己家", "e": ""},
{"r": 297, "w": "ask round", "c": "邀请(某人)来家(常指短时间的)：；(多方)打听, 询问:", "e": ""},
{"r": 298, "w": "feel about", "c": "到处摸索;同情,体谅", "e": ""},
{"r": 299, "w": "feel out", "c": "试探出...的意见", "e": ""},
{"r": 300, "w": "feel up", "c": "对妇女动手动脚", "e": ""},
{"r": 301, "w": "feel up to", "c": "觉得能担当", "e": ""},
{"r": 302, "w": "let in", "c": "放进, 招致, 嵌入", "e": ""},
{"r": 303, "w": "let in for", "c": "使陷入, 惹起(麻烦等)", "e": ""},
{"r": 304, "w": "let off", "c": "放出, 饶恕 / [机] 放出", "e": ""},
{"r": 305, "w": "let on", "c": "<非正>泄密, 透露, 假装", "e": ""},
{"r": 306, "w": "let out", "c": "放掉, 泄露, 放大, 出租 / [经] 出租", "e": ""},
{"r": 307, "w": "let up", "c": "减小, 停止", "e": ""},
{"r": 308, "w": "begin on", "c": "开始,着手,动手", "e": ""},
{"r": 309, "w": "follow about", "c": "跟在某人身边形影不离", "e": ""},
{"r": 310, "w": "follow on", "c": "继续下去", "e": ""},
{"r": 311, "w": "follow out", "c": "把...查到底, 贯彻, 执行", "e": ""},
{"r": 312, "w": "follow through", "c": "坚持到底", "e": ""},
{"r": 313, "w": "follow up", "c": "穷追, 把...探究到底 / [法] 追查, 追问, 追究", "e": ""},
{"r": 314, "w": "follow up on", "c": "追踪; 继续采用", "e": ""},
{"r": 315, "w": "bring along", "c": "带来,随身携带", "e": ""},
{"r": 316, "w": "bring around", "c": "使信服", "e": ""},
{"r": 317, "w": "bring down", "c": "打倒, 击落, 击败, 降低 / [经] 结转, 转下", "e": ""},
{"r": 318, "w": "bring down on", "c": "招致", "e": ""},
{"r": 319, "w": "bring forth", "c": "使产生", "e": ""},
{"r": 320, "w": "bring forward", "c": "提出, 提前 / [经] 结转", "e": ""},
{"r": 321, "w": "bring in", "c": "提出, 挣得, 引进", "e": ""},
{"r": 322, "w": "bring off", "c": "救出, 完成", "e": ""},
{"r": 323, "w": "bring on", "c": "引起, 导致, 使发展", "e": ""},
{"r": 324, "w": "bring out", "c": "使显示, 出版, 说出 / [经] 包销人公开出售新证券", "e": ""},
{"r": 325, "w": "bring over", "c": "使转变, 把...带来 / [经] 转入(下页,次页)", "e": ""},
{"r": 326, "w": "bring round", "c": "把（某人或某物）带到约好的地点; 劝说（某人）改变主意[意见]; 说服（某人）; 使恢复知觉", "e": ""},
{"r": 327, "w": "bring through", "c": "救活", "e": ""},
{"r": 328, "w": "bring together", "c": "使相合[连接]; 使相识; 使坐在一起; 使会面", "e": ""},
{"r": 329, "w": "bring under", "c": "制服", "e": ""},
{"r": 330, "w": "hear about", "c": "听说,听到过", "e": ""},
{"r": 331, "w": "hear out", "c": "听完", "e": ""},
{"r": 332, "w": "write about", "c": "写…的事, 写到…, 把（某事）作为写作的主题", "e": ""},
{"r": 333, "w": "write away", "c": "写信（索要）; 连续写作", "e": ""},
{"r": 334, "w": "write away for", "c": "函购,写信索取…", "e": ""},
{"r": 335, "w": "write back", "c": "[法] 注销, 红字冲账", "e": ""},
{"r": 336, "w": "write down", "c": "写下, 写文章贬低, 降低地位, 减低帐面价值 / [法] 记录, 记下, 以文字诋毁", "e": ""},
{"r": 337, "w": "write in", "c": "把...写入, 发信(索取) / [经] 写入", "e": ""},
{"r": 338, "w": "write in for", "c": "向商行写信提要求 / 意见", "e": ""},
{"r": 339, "w": "write off", "c": "一口气写成, 写信索取, 注销, 勾销, 取消 / [化] 注销", "e": ""},
{"r": 340, "w": "write off for", "c": "写信寄出, 给商行写信(购物)", "e": ""},
{"r": 341, "w": "write on", "c": "写, 记述", "e": ""},
{"r": 342, "w": "write out", "c": "写出 / [法] 誊写, 全部写出", "e": ""},
{"r": 343, "w": "write up", "c": "详细记叙, 补写...到最近日期, 写文章赞扬 / [法] 记述, 详细记载, 补写", "e": ""},
{"r": 344, "w": "believe in", "c": "信仰, 信任", "e": ""},
{"r": 345, "w": "happen along", "c": "碰巧出现,正好到来", "e": ""},
{"r": 346, "w": "happen in", "c": "偶然来到;发生在…", "e": ""},
{"r": 347, "w": "happen in with", "c": "偶然遇见,和…邂逅", "e": ""},
{"r": 348, "w": "happen on", "c": "偶然遇见,碰到", "e": ""},
{"r": 349, "w": "allow in", "c": "准许进入", "e": ""},
{"r": 350, "w": "sit about", "c": "坐着不干, 袖手旁观", "e": ""},
{"r": 351, "w": "sit around", "c": "坐着不干, 袖手旁观", "e": ""},
{"r": 352, "w": "sit back", "c": "不采取行动, 向后靠着坐", "e": ""},
{"r": 353, "w": "sit down", "c": "坐下, 占据, 参加静坐罢工(或示威)", "e": ""},
{"r": 354, "w": "sit down to", "c": "坐下来做…", "e": ""},
{"r": 355, "w": "sit in", "c": "代人暂时照料, 参加静坐罢工", "e": ""},
{"r": 356, "w": "sit in on", "c": "列席, 旁听", "e": ""},
{"r": 357, "w": "sit on", "c": "为...的一员, 开会讨论, 审理, 拖延, 管教 / [法] 调查, 询问, 占有一席次", "e": ""},
{"r": 358, "w": "sit out", "c": "袖手旁观, 比...坐得久, 坐到结束, 坐在户外", "e": ""},
{"r": 359, "w": "sit over", "c": "坐在...左手, 靠边坐让出地盘", "e": ""},
{"r": 360, "w": "sit through", "c": "坐着捱到结束, 耐着性子看完", "e": ""},
{"r": 361, "w": "sit under", "c": "听...讲授", "e": ""},
{"r": 362, "w": "sit up", "c": "坐起, 端坐, 熬夜, 诧异", "e": ""},
{"r": 363, "w": "lose out", "c": "(比赛)输掉, 失败", "e": ""},
{"r": 364, "w": "learn about", "c": "学习,听说,得悉,了解", "e": ""},
{"r": 365, "w": "learn off", "c": "牢记,背熟", "e": ""},
{"r": 366, "w": "understand about", "c": "懂得,了解", "e": ""},
{"r": 367, "w": "read about", "c": "阅读有关…的细节", "e": ""},
{"r": 368, "w": "read back", "c": "重复", "e": ""},
{"r": 369, "w": "read in", "c": "[计] 读入", "e": ""},
{"r": 370, "w": "read off", "c": "[经] 读出, 从...读取", "e": ""},
{"r": 371, "w": "read on", "c": "继续读", "e": ""},
{"r": 372, "w": "read out", "c": "宣告开除, 把...读出 / [经] 读出, 宣读", "e": ""},
{"r": 373, "w": "read over", "c": "把...读一遍", "e": ""},
{"r": 374, "w": "read through", "c": "把...从头看到尾 / [化] 连读", "e": ""},
{"r": 375, "w": "read up", "c": "攻读", "e": ""},
{"r": 376, "w": "read up on", "c": "研究,专攻…", "e": ""},
{"r": 377, "w": "add in", "c": "把...包括在内 / [计] 添加", "e": ""},
{"r": 378, "w": "add on", "c": "（在计算或目录的末尾额外）加上, 附加", "e": ""},
{"r": 379, "w": "add together", "c": "加起来, 总计; 相加", "e": ""},
{"r": 380, "w": "add up", "c": "合计", "e": ""},
{"r": 381, "w": "add up to", "c": "合计达", "e": ""},
{"r": 382, "w": "speak about", "c": "谈论,讲起,说到", "e": ""},
{"r": 383, "w": "speak on", "c": "说下去", "e": ""},
{"r": 384, "w": "speak out", "c": "大胆地说, 大声地说", "e": ""},
{"r": 385, "w": "speak up", "c": "更大声地说, 大胆说出, 无保留地说出", "e": ""},
{"r": 386, "w": "remain down", "c": "[网络] 保持下来", "e": ""},
{"r": 387, "w": "remain on", "c": "停留在…之上", "e": ""},
{"r": 388, "w": "remain up", "c": "一直不睡,熬夜", "e": ""},
{"r": 389, "w": "buy back", "c": "[经] 产品返销, 补进", "e": ""},
{"r": 390, "w": "buy forward", "c": "[经] 买入期货", "e": ""},
{"r": 391, "w": "buy in", "c": "买进 / [经] 买进(股票)", "e": ""},
{"r": 392, "w": "buy off", "c": "收买 / [经] 买通", "e": ""},
{"r": 393, "w": "buy out", "c": "出钱使放弃地位 / [经] 买下, 买妥, 买下...的全部产权", "e": ""},
{"r": 394, "w": "buy over", "c": "收买, 贿赂 / [经] 收买, 贿赂", "e": ""},
{"r": 395, "w": "buy up", "c": "全买 / [经] 囤积, 收买(公司等), 全买", "e": ""},
{"r": 396, "w": "grow away from", "c": "脱离,与…格格不入", "e": ""},
{"r": 397, "w": "grow back", "c": "重新长出", "e": ""},
{"r": 398, "w": "grow on", "c": "引起...爱好, 加深影响", "e": ""},
{"r": 399, "w": "grow out", "c": "长出来,向外增大,膨胀", "e": ""},
{"r": 400, "w": "grow out of", "c": "长得与...不相称, 因长大而丢弃", "e": ""},
{"r": 401, "w": "grow over", "c": "覆盖…", "e": ""},
{"r": 402, "w": "win back", "c": "重新获得, 夺回", "e": ""},
{"r": 403, "w": "win on", "c": "影响", "e": ""},
{"r": 404, "w": "win out", "c": "获胜,完成,摆脱", "e": ""},
{"r": 405, "w": "win over", "c": "[法] 争取到, 胜诉", "e": ""},
{"r": 406, "w": "win through", "c": "历尽千辛万苦获得成功,终于获胜", "e": ""},
{"r": 407, "w": "win up", "c": "上马, 攀登", "e": ""},
{"r": 408, "w": "send along", "c": "发送, 派遣", "e": ""},
{"r": 409, "w": "send around", "c": "[网络] 分发；发送；散发", "e": ""},
{"r": 410, "w": "send away", "c": "发送, 打发走, 解雇", "e": ""},
{"r": 411, "w": "send away for", "c": "函购某物", "e": ""},
{"r": 412, "w": "send back", "c": "退还", "e": ""},
{"r": 413, "w": "send down", "c": "使下降, 把...向下发送", "e": ""},
{"r": 414, "w": "send forth", "c": "寄发, 发出, 放出, 长出", "e": ""},
{"r": 415, "w": "send forward", "c": "派遣", "e": ""},
{"r": 416, "w": "send in", "c": "递送, 命(或请)...进来", "e": ""},
{"r": 417, "w": "send off", "c": "寄出, 派遣, 给...送行", "e": ""},
{"r": 418, "w": "send off for", "c": "函购某物", "e": ""},
{"r": 419, "w": "send on", "c": "先送, 先遣, 转送", "e": ""},
{"r": 420, "w": "send out", "c": "发送, 派遣, 放出", "e": ""},
{"r": 421, "w": "send over", "c": "发送", "e": ""},
{"r": 422, "w": "send round", "c": "传阅, 发送, 派遣", "e": ""},
{"r": 423, "w": "send through", "c": "送过去,传送,报告,通知", "e": ""},
{"r": 424, "w": "send up", "c": "发出, 射出, 呈交, 使上升", "e": ""},
{"r": 425, "w": "decide on", "c": "决定,选定,确定…", "e": ""},
{"r": 426, "w": "agree about", "c": "对…取得一致意见", "e": ""},
{"r": 427, "w": "agree in", "c": "在…意见一致", "e": ""},
{"r": 428, "w": "agree on", "c": "就…取得一致意见,商定", "e": ""},
{"r": 429, "w": "serve on", "c": "为成员", "e": ""},
{"r": 430, "w": "serve out", "c": "分发,分配", "e": ""},
{"r": 431, "w": "serve round", "c": "分发", "e": ""},
{"r": 432, "w": "serve under", "c": "在手下任职", "e": ""},
{"r": 433, "w": "serve up", "c": "端上桌; 上菜; 提供; 发送", "e": ""},
{"r": 434, "w": "die away", "c": "熄灭, 平息, 消失", "e": ""},
{"r": 435, "w": "die back", "c": "（植物）枯死但根部还活着; 顶梢枯死", "e": ""},
{"r": 436, "w": "die down", "c": "枯萎, 凋谢", "e": ""},
{"r": 437, "w": "die off", "c": "相继死去直至死光, 消亡, 逐个死亡", "e": ""},
{"r": 438, "w": "die out", "c": "熄灭, 平息, 消失", "e": ""},
{"r": 439, "w": "build in", "c": "嵌入, 插入", "e": ""},
{"r": 440, "w": "build on", "c": "在原有的建筑物上增建; 以…为基础; 依赖; 一心指望", "e": ""},
{"r": 441, "w": "build up", "c": "树立, 增进, 增大, 堵塞 / [化] 提升力", "e": ""},
{"r": 442, "w": "involve in", "c": "使参与[陷入，牵扯到]; 婵媛", "e": ""},
{"r": 443, "w": "draw ahead", "c": "赶到前面,超到前面", "e": ""},
{"r": 444, "w": "draw apart", "c": "分手,反目,不和", "e": ""},
{"r": 445, "w": "draw away", "c": "拉开, 引开, 离开", "e": ""},
{"r": 446, "w": "draw back", "c": "收回, 退却, 缩回 / [经] 退钱, 退税", "e": ""},
{"r": 447, "w": "draw down", "c": "招致,惹起;挣得,领取;消耗,耗尽", "e": ""},
{"r": 448, "w": "draw forth", "c": "引起, 博得", "e": ""},
{"r": 449, "w": "draw in", "c": "收缩, 引诱, 接近黄昏, 紧缩开支", "e": ""},
{"r": 450, "w": "draw off", "c": "脱去, 撤退", "e": ""},
{"r": 451, "w": "draw on", "c": "戴上, 吸收, 利用, 向...提取, 引诱, 招致, 临近", "e": ""},
{"r": 452, "w": "draw out", "c": "拉长, 抽出, 引出, 拟订", "e": ""},
{"r": 453, "w": "draw round", "c": "围在周围", "e": ""},
{"r": 454, "w": "draw together", "c": "团结起来", "e": ""},
{"r": 455, "w": "draw up", "c": "草拟, 停住, 逼近, 拉起, 整队", "e": ""},
{"r": 456, "w": "sell off", "c": "廉价卖清 / [经] 廉价出清(存货),(证券的)跌价", "e": ""},
{"r": 457, "w": "sell on", "c": "使人想买", "e": ""},
{"r": 458, "w": "sell out", "c": "卖完, 出卖, 背叛 / [经] 卖完, 出售货物, 商品售缺", "e": ""},
{"r": 459, "w": "sell up", "c": "卖完, 为还债而变卖", "e": ""},
{"r": 460, "w": "pull about", "c": "把...拖来拖去, 粗暴对待", "e": ""},
{"r": 461, "w": "pull ahead", "c": "[体]奋力赶到前面", "e": ""},
{"r": 462, "w": "pull along", "c": "沿…拉", "e": ""},
{"r": 463, "w": "pull apart", "c": "把...撕开, 批评", "e": ""},
{"r": 464, "w": "pull away", "c": "脱身, 离开", "e": ""},
{"r": 465, "w": "pull away from", "c": "从…挣脱,从…开出", "e": ""},
{"r": 466, "w": "pull back", "c": "[计] 退回, 退却", "e": ""},
{"r": 467, "w": "pull down", "c": "摧毁, 推翻, 使降低, 使下跌, 使身体变差, 使萎靡, 获取 / [机] 胀陷, 上模剥砂", "e": ""},
{"r": 468, "w": "pull in", "c": "进站, 靠岸", "e": ""},
{"r": 469, "w": "pull off", "c": "脱, 努力实现, 赢得", "e": ""},
{"r": 470, "w": "pull on", "c": "穿, 戴, 用力拉", "e": ""},
{"r": 471, "w": "pull out", "c": "拔出, 离开, (使)渡过难关, (使)恢复健康", "e": ""},
{"r": 472, "w": "pull over", "c": "靠岸, 开到路边", "e": ""},
{"r": 473, "w": "pull round", "c": "复原", "e": ""},
{"r": 474, "w": "pull through", "c": "(使)渡过难关, (使)恢复健康", "e": ""},
{"r": 475, "w": "pull together", "c": "齐心协力", "e": ""},
{"r": 476, "w": "pull up", "c": "拔起, 停下, 阻止", "e": ""},
{"r": 477, "w": "pull up to", "c": "v. 追赶上", "e": ""},
{"r": 478, "w": "explain away", "c": "通过解释消除", "e": ""},
{"r": 479, "w": "join in", "c": "参加, 加入", "e": ""},
{"r": 480, "w": "join on", "c": "联接在…,安装在…", "e": ""},
{"r": 481, "w": "join up", "c": "参军, 联合起来", "e": ""},
{"r": 482, "w": "eat away", "c": "连续不断地吃; 侵蚀; 腐蚀; 咬坏", "e": ""},
{"r": 483, "w": "eat in", "c": "在家吃饭; 在学校就餐", "e": ""},
{"r": 484, "w": "eat off", "c": "吃掉", "e": ""},
{"r": 485, "w": "eat on", "c": "n. 伊顿（姓氏））", "e": ""},
{"r": 486, "w": "eat out", "c": "上馆子吃饭, 锈坏, 过度消耗(牧草等), 责骂", "e": ""},
{"r": 487, "w": "eat up", "c": "吃光, 耗尽, 吞灭", "e": ""},
{"r": 488, "w": "eat up with", "c": "使沉迷于, 使纠缠于", "e": ""},
{"r": 489, "w": "teach up", "c": "大麻中毒;喝醉酒", "e": ""},
{"r": 490, "w": "seek out", "c": "搜出, 挑出", "e": ""},
{"r": 491, "w": "seek through", "c": "搜遍", "e": ""},
{"r": 492, "w": "choose up", "c": "<口>（临时性非正式比赛中）选定对阵双方的球员, 把人分成两队进行比赛[游戏]", "e": ""},
{"r": 493, "w": "listen in", "c": "收听, 监听, 偷听 / [法] 收听, 监听, 偷听", "e": ""},
{"r": 494, "w": "listen up", "c": "听好了", "e": ""},
{"r": 495, "w": "fail in", "c": "在…失败;缺乏…", "e": ""},
{"r": 496, "w": "realize on", "c": "从…赚得", "e": ""},
{"r": 497, "w": "prove out", "c": "结果证明属实", "e": ""},
{"r": 498, "w": "prove up", "c": "提出证明, 证明已具备受领资格", "e": ""},
{"r": 499, "w": "argue about", "c": "争论…,辩论…", "e": ""},
{"r": 500, "w": "argue away", "c": "把...辩解过去", "e": ""},
{"r": 501, "w": "argue out", "c": "把…辩论清楚", "e": ""},
{"r": 502, "w": "argue over", "c": "争论…,辩论…", "e": ""},
{"r": 503, "w": "throw about", "c": "到处扔, 舞动", "e": ""},
{"r": 504, "w": "throw aside", "c": "扔到一边,丢弃", "e": ""},
{"r": 505, "w": "throw back", "c": "扔回, 阻止, 被迫依靠, 反射", "e": ""},
{"r": 506, "w": "throw down", "c": "扔下, 使卧倒", "e": ""},
{"r": 507, "w": "throw in", "c": "扔进, 接合, 啮合, 入伙, 参加合伙经营", "e": ""},
{"r": 508, "w": "throw off", "c": "扔开, 摆脱, 匆匆脱下", "e": ""},
{"r": 509, "w": "throw on", "c": "匆匆穿上", "e": ""},
{"r": 510, "w": "throw out", "c": "伸出, 扔掉, 说出, 解雇, 拒绝, 显示, 散发出, 放出, 派出, 使延伸, 打扰, 使出局 / [法] 否决, 发表, 拒绝", "e": ""},
{"r": 511, "w": "throw over", "c": "抛弃, 使覆盖 / [法] 放弃, 遗弃, 拒绝", "e": ""},
{"r": 512, "w": "throw together", "c": "匆匆拼凑", "e": ""},
{"r": 513, "w": "throw up", "c": "呕吐, 猛地举起, 放弃, 产生, 使显眼", "e": ""},
{"r": 514, "w": "fill away", "c": "乘风前进", "e": ""},
{"r": 515, "w": "fill down", "c": "[计] 向下填充", "e": ""},
{"r": 516, "w": "fill in", "c": "填充, 填写, 填满, 替代", "e": ""},
{"r": 517, "w": "fill in for", "c": "临时代替", "e": ""},
{"r": 518, "w": "fill up", "c": "填补, 装满, 装满油 / [计] 向上填充", "e": ""},
{"r": 519, "w": "enter on", "c": "正式开始, 着手, 开始考虑, 占有", "e": ""},
{"r": 520, "w": "enter up", "c": "登记,记录", "e": ""},
{"r": 521, "w": "arrive in", "c": "到达,抵达,来到", "e": ""},
{"r": 522, "w": "refer back", "c": "把…转回,重提", "e": ""},
{"r": 523, "w": "refer back to", "c": "重新提及…,把…交还给…", "e": ""},
{"r": 524, "w": "manage about", "c": "设法应付,处理,解决", "e": ""},
{"r": 525, "w": "manage on", "c": "靠…维持", "e": ""},
{"r": 526, "w": "determine on", "c": "决定,确定", "e": ""},
{"r": 527, "w": "lay about", "c": "流浪汉", "e": ""},
{"r": 528, "w": "lay aside", "c": "搁置, 积蓄", "e": ""},
{"r": 529, "w": "lay away", "c": "积蓄, 埋葬", "e": ""},
{"r": 530, "w": "lay back", "c": "使向后，放回，送回", "e": ""},
{"r": 531, "w": "lay down", "c": "放下 / [法] 规定, 制定, 立法", "e": ""},
{"r": 532, "w": "lay in", "c": "贮藏 / [经] 贮存", "e": ""},
{"r": 533, "w": "lay off", "c": "把(衣服等)放在一边, 解雇, 停止工作, 休息, 划出 / [机] 停工, 下料", "e": ""},
{"r": 534, "w": "lay on", "c": "涂抹, 猛攻, 加...于人 / [经] 抽, 征(税等)", "e": ""},
{"r": 535, "w": "lay out", "c": "摆开, 展示, 布置, 安排, 投资 / [经] 花钱, 投资, 布局", "e": ""},
{"r": 536, "w": "lay over", "c": "覆盖, 胜过, 使延期", "e": ""},
{"r": 537, "w": "lay up", "c": "贮存, 搁置, 卧床 / [经] 贮存, 储蓄, 暂停使用", "e": ""},
{"r": 538, "w": "forget about", "c": "忘记,忘却", "e": ""},
{"r": 539, "w": "peter out", "c": "逐渐消失, 耗尽", "e": ""},
{"r": 540, "w": "suffer through", "c": "受尽,遭受…", "e": ""},
{"r": 541, "w": "tend on", "c": "招待, 照料", "e": ""},
{"r": 542, "w": "tend out on", "c": "到场,参加;专心于,注意…", "e": ""},
{"r": 543, "w": "exist in", "c": "存在于…中", "e": ""},
{"r": 544, "w": "reflect back", "c": "反射,折射;真实地反映", "e": ""},
{"r": 545, "w": "reflect on", "c": "深思, 反省, 导致, 招致非议", "e": ""},
{"r": 546, "w": "improve away", "c": "改良祛除", "e": ""},
{"r": 547, "w": "improve on", "c": "改进", "e": ""},
{"r": 548, "w": "operate on", "c": "对...施手术", "e": ""},
{"r": 549, "w": "sing along", "c": "n. 歌咏会；歌唱聚会", "e": ""},
{"r": 550, "w": "sing away", "c": "不停地唱;以唱歌来消除", "e": ""},
{"r": 551, "w": "sing on", "c": "唱下去", "e": ""},
{"r": 552, "w": "sing out", "c": "[法] 向法院或警方自供, 告密", "e": ""},
{"r": 553, "w": "sing up", "c": "更用力地唱", "e": ""},
{"r": 554, "w": "extend out", "c": "向外扩展", "e": ""},
{"r": 555, "w": "extend over", "c": "涉及,波及", "e": ""},
{"r": 556, "w": "arise out of", "c": "由…而引起,由…产生,起因于", "e": ""},
{"r": 557, "w": "attend on", "c": "照顾", "e": ""},
{"r": 558, "w": "stare down", "c": "盯得局促不安：盯视或仿佛盯视而导致动摇或屈服", "e": ""},
{"r": 559, "w": "confirm in", "c": "使更坚定", "e": ""},
{"r": 560, "w": "confirm on", "c": "确认 / [计] 确认", "e": ""},
{"r": 561, "w": "marry off", "c": "嫁出,使完婚", "e": ""},
{"r": 562, "w": "marry up", "c": "结婚,结合,配合", "e": ""},
{"r": 563, "w": "deliver over", "c": "[经] 交付", "e": ""},
{"r": 564, "w": "deliver up", "c": "[法] 让与", "e": ""},
{"r": 565, "w": "observe on", "c": "评论", "e": ""},
{"r": 566, "w": "count down", "c": "倒读数, 用倒数方式计算 / [经] 倒数, 递减计算", "e": ""},
{"r": 567, "w": "count in", "c": "把...计算在内", "e": ""},
{"r": 568, "w": "count off", "c": "报数", "e": ""},
{"r": 569, "w": "count out", "c": "点数, 拳击中判输", "e": ""},
{"r": 570, "w": "count up", "c": "把...加起来, 共计", "e": ""},
{"r": 571, "w": "count up to", "c": "共计", "e": ""},
{"r": 572, "w": "insist on", "c": "坚持, 坚决要求", "e": ""},
{"r": 573, "w": "engage in", "c": "使从事于, 参加", "e": ""},
{"r": 574, "w": "burn away", "c": "继续燃烧, 烧掉", "e": ""},
{"r": 575, "w": "burn down", "c": "烧成平地, 火力减弱 / [机] 烧去, 火力衰退", "e": ""},
{"r": 576, "w": "burn in", "c": "留下不可磨灭的印象", "e": ""},
{"r": 577, "w": "burn off", "c": "[化] 烧尽", "e": ""},
{"r": 578, "w": "burn out", "c": "烧坏, 烧掉, 烧尽 / [机] 烧光", "e": ""},
{"r": 579, "w": "burn together", "c": "[机] 烧结", "e": ""},
{"r": 580, "w": "burn up", "c": "烧起来, 烧掉, 发怒", "e": ""},
{"r": 581, "w": "belong in", "c": "应该在…,住在…", "e": ""},
{"r": 582, "w": "belong together", "c": "属于一个整体,属于同类", "e": ""},
{"r": 583, "w": "participate in", "c": "参加, 参与, 分享", "e": ""},
{"r": 584, "w": "consist in", "c": "存在于", "e": ""},
{"r": 585, "w": "invite out", "c": "请（某人）出去", "e": ""},
{"r": 586, "w": "warn off", "c": "让不去,让别做", "e": ""},
{"r": 587, "w": "impose on", "c": "利用, 欺骗, 施加影响于", "e": ""},
{"r": 588, "w": "declare off", "c": "宣布取消 / [法] 宣告作罢, 取消", "e": ""},
{"r": 589, "w": "declare on", "c": "v. 宣布", "e": ""},
{"r": 590, "w": "declare over", "c": "宣布结束", "e": ""},
{"r": 591, "w": "divide up", "c": "划分,分配,瓜分", "e": ""},
{"r": 592, "w": "climb down", "c": "爬下, 让步, 屈服", "e": ""},
{"r": 593, "w": "climb on", "c": "爬到…上; 趁势, 效法他人的成功做法", "e": ""},
{"r": 594, "w": "climb up", "c": "爬上", "e": ""},
{"r": 595, "w": "expand on", "c": "详述", "e": ""},
{"r": 596, "w": "locate in", "c": "在某一点设置; 在…定居", "e": ""},
{"r": 597, "w": "inform on", "c": "告密,告发,出卖", "e": ""},
{"r": 598, "w": "advise about", "c": "就…对某人提出劝告", "e": ""},
{"r": 599, "w": "advise on", "c": "就…对某人提出劝告", "e": ""},
{"r": 600, "w": "rely on", "c": "依赖, 依靠", "e": ""},
{"r": 601, "w": "succeed in", "c": "在...方面成功", "e": ""},
{"r": 602, "w": "steal away", "c": "溜掉", "e": ""},
{"r": 603, "w": "steal on", "c": "悄悄地到来,不知不觉地到来,潜入,袭来", "e": ""},
{"r": 604, "w": "steal over", "c": "悄悄地到来,不知不觉地到来,逐渐弥漫", "e": ""},
{"r": 605, "w": "fix on", "c": "确定, 决定", "e": ""},
{"r": 606, "w": "fix over", "c": "修理", "e": ""},
{"r": 607, "w": "fix up", "c": "修理好, 安排好", "e": ""},
{"r": 608, "w": "complain about", "c": "抱怨", "e": ""},
{"r": 609, "w": "bind down", "c": "捆,绑,束缚", "e": ""},
{"r": 610, "w": "bind off", "c": "收针：编织时收针; 拷边", "e": ""},
{"r": 611, "w": "bind on", "c": "对…有约束力", "e": ""},
{"r": 612, "w": "bind over", "c": "在法庭发誓", "e": ""},
{"r": 613, "w": "bind together", "c": "把…束缚在一起,使…结合在一起", "e": ""},
{"r": 614, "w": "bind up", "c": "包扎;装订", "e": ""},
{"r": 615, "w": "invest in", "c": "投资于, 买进", "e": ""},
{"r": 616, "w": "compete in", "c": "v. 参加…比赛（竞赛）", "e": ""},
{"r": 617, "w": "proceed on", "c": "继续;按照…行事", "e": ""},
{"r": 618, "w": "bother about", "c": "烦恼", "e": ""},
{"r": 619, "w": "analyse away", "c": "把…分解掉", "e": ""},
{"r": 620, "w": "calculate on", "c": "指望", "e": ""},
{"r": 621, "w": "resolve on", "c": "决心…,决定…", "e": ""},
{"r": 622, "w": "bend down", "c": "弯腰,俯身", "e": ""},
{"r": 623, "w": "bend over", "c": "俯身于…", "e": ""},
{"r": 624, "w": "reckon in", "c": "把…算进去", "e": ""},
{"r": 625, "w": "reckon on", "c": "指望, 依赖", "e": ""},
{"r": 626, "w": "reckon up", "c": "合计,累计,统计", "e": ""},
{"r": 627, "w": "bob about", "c": "[网络] 鲍勃关于", "e": ""},
{"r": 628, "w": "bob around", "c": "飘忽游荡", "e": ""},
{"r": 629, "w": "bob under", "c": "[网络] 鲍勃下", "e": ""},
{"r": 630, "w": "bob up", "c": "突然出现", "e": ""},
{"r": 631, "w": "breathe in", "c": "吸入", "e": ""},
{"r": 632, "w": "breathe out", "c": "呼出", "e": ""},
{"r": 633, "w": "pray down", "c": "求神降伏", "e": ""},
{"r": 634, "w": "pray out", "c": "求神降伏", "e": ""},
{"r": 635, "w": "dig down", "c": "挖下, 掘倒, 掏腰包", "e": ""},
{"r": 636, "w": "dig in", "c": "掘土以掺进", "e": ""},
{"r": 637, "w": "dig out", "c": "掘出, 发现", "e": ""},
{"r": 638, "w": "dig up", "c": "掘起, 挖出, 发现, 开垦", "e": ""},
{"r": 639, "w": "behave about", "c": "处理,处置…", "e": ""},
{"r": 640, "w": "weigh down", "c": "使负重, 使下垂, 使下沉; 坠", "e": ""},
{"r": 641, "w": "weigh in", "c": "称重量, 参加 / [法] 参加, 介入", "e": ""},
{"r": 642, "w": "weigh in with", "c": "有把握地提出 / [法] 成功地提出", "e": ""},
{"r": 643, "w": "weigh on", "c": "重压于", "e": ""},
{"r": 644, "w": "weigh out", "c": "称出", "e": ""},
{"r": 645, "w": "weigh up", "c": "估量", "e": ""},
{"r": 646, "w": "negotiate about", "c": "谈判, 协商", "e": ""},
{"r": 647, "w": "negotiate over", "c": "就…进行谈判,谈判…", "e": ""},
{"r": 648, "w": "differ in", "c": "在…方面不同", "e": ""},
{"r": 649, "w": "snap back", "c": "很快恢复", "e": ""},
{"r": 650, "w": "snap off", "c": "折断; 啪地关灯", "e": ""},
{"r": 651, "w": "snap out", "c": "急促地说,厉声地说", "e": ""},
{"r": 652, "w": "snap up", "c": "抢购", "e": ""},
{"r": 653, "w": "found on", "c": "基于, 使有根据", "e": ""},
{"r": 654, "w": "found out", "c": "搜索; 发现; 找出; 把…揭发出来", "e": ""},
{"r": 655, "w": "yell out", "c": "大声叫喊,大声嚷嚷,叫喊着说", "e": ""},
{"r": 656, "w": "yell together for", "c": "一起为…高喊加油", "e": ""},
{"r": 657, "w": "yell up", "c": "大声叫喊,大声嚷嚷,喊…过来", "e": ""},
{"r": 658, "w": "react on", "c": "起作用于", "e": ""},
{"r": 659, "w": "disagree about", "c": "不同意,对…持有异议", "e": ""},
{"r": 660, "w": "exceed in", "c": "在...方面超过", "e": ""},
{"r": 661, "w": "practise on", "c": "利用", "e": ""},
{"r": 662, "w": "freeze down", "c": "[网络] 冻结", "e": ""},
{"r": 663, "w": "freeze off", "c": "拒绝…, 拒绝接受", "e": ""},
{"r": 664, "w": "freeze out", "c": "（用竞争等）排斥", "e": ""},
{"r": 665, "w": "freeze over", "c": "使被冰覆盖", "e": ""},
{"r": 666, "w": "freeze up", "c": "冻结, 变呆板 / [经] 冻结", "e": ""},
{"r": 667, "w": "rid up", "c": "除去,扫除,收拾干净", "e": ""},
{"r": 668, "w": "fade away", "c": "逐渐消失", "e": ""},
{"r": 669, "w": "fade down", "c": "使渐弱,调弱,调低", "e": ""},
{"r": 670, "w": "fade in", "c": "(使)淡入, (使)渐显 / [电] 化入, 渐强", "e": ""},
{"r": 671, "w": "fade out", "c": "淡出, 渐弱 / [电] 化出, 渐弱", "e": ""},
{"r": 672, "w": "seize on", "c": "抓住, 占有", "e": ""},
{"r": 673, "w": "seize up", "c": "中止", "e": ""},
{"r": 674, "w": "wander about", "c": "漫步, 徘徊", "e": ""},
{"r": 675, "w": "wander through", "c": "沿着…游荡,徘徊穿过…,漫游…", "e": ""},
{"r": 676, "w": "sue out", "c": "向法院请求得到 / [法] 经向法院请求而得到", "e": ""},
{"r": 677, "w": "swear in", "c": "使宣誓就职 / [法] 使宣誓就职", "e": ""},
{"r": 678, "w": "swear off", "c": "发誓戒除 / [法] 立誓弃绝", "e": ""},
{"r": 679, "w": "swear on", "c": "凭...发誓", "e": ""},
{"r": 680, "w": "swear out", "c": "通过宣誓控告使法院发出拘捕证 / [法] 由宣誓而得到, 通过宣誓控告使法院发出", "e": ""},
{"r": 681, "w": "render back", "c": "报答, 归还", "e": ""},
{"r": 682, "w": "render down", "c": "熬浓,煮浓;归纳", "e": ""},
{"r": 683, "w": "render up", "c": "放弃, 让与", "e": ""},
{"r": 684, "w": "knit together", "c": "把…联系在一起,汇集", "e": ""},
{"r": 685, "w": "knit up", "c": "织补, 结束", "e": ""},
{"r": 686, "w": "beg off", "c": "请求免除", "e": ""},
{"r": 687, "w": "suck around", "c": "老是围着...打转", "e": ""},
{"r": 688, "w": "suck down", "c": "吸到里面去", "e": ""},
{"r": 689, "w": "suck in", "c": "吸收, 吞没 / [法] 欺骗, 失望, 失败", "e": ""},
{"r": 690, "w": "suck off", "c": "拍...马屁", "e": ""},
{"r": 691, "w": "suck out", "c": "吸出; 拔", "e": ""},
{"r": 692, "w": "suck up", "c": "吸收", "e": ""},
{"r": 693, "w": "suck up to", "c": "讨好,拍…的马屁", "e": ""},
{"r": 694, "w": "interfere in", "c": "干预,干涉,介入", "e": ""},
{"r": 695, "w": "persist in", "c": "坚持, 固执于", "e": ""},
{"r": 696, "w": "carve out", "c": "开辟", "e": ""},
{"r": 697, "w": "carve up", "c": "瓜分, 划分", "e": ""},
{"r": 698, "w": "opt in", "c": "决定参加", "e": ""},
{"r": 699, "w": "opt out", "c": "[计]撤退", "e": ""},
{"r": 700, "w": "endorse off", "c": "在…背书以支取部分票面金额", "e": ""},
{"r": 701, "w": "endorse over", "c": "背书...转让权利 / [法] 背书...转让权利", "e": ""},
{"r": 702, "w": "blend in", "c": "（使）（与…）和谐或协调", "e": ""},
{"r": 703, "w": "blend in with", "c": "与…调和", "e": ""},
{"r": 704, "w": "flip off", "c": "撢去,拂去,轻轻擦去", "e": ""},
{"r": 705, "w": "flip out", "c": "精神失常, 发疯", "e": ""},
{"r": 706, "w": "flip over", "c": "突然翻转", "e": ""},
{"r": 707, "w": "flip through", "c": "浏览,翻阅", "e": ""},
{"r": 708, "w": "edit out", "c": "编辑中删除", "e": ""},
{"r": 709, "w": "vanish away", "c": "消失,化为乌有,不见踪影", "e": ""},
{"r": 710, "w": "intervene in", "c": "插手,干预,调停", "e": ""},
{"r": 711, "w": "descend on", "c": "袭击", "e": ""},
{"r": 712, "w": "enroll in", "c": "登记,报名参加", "e": ""},
{"r": 713, "w": "specialize in", "c": "专门研究...", "e": ""},
{"r": 714, "w": "tighten up", "c": "使紧密, 加强; 收紧", "e": ""},
{"r": 715, "w": "enquire about", "c": "询问,打听", "e": ""},
{"r": 716, "w": "enquire out", "c": "盘问出,打听出,调查出", "e": ""},
{"r": 717, "w": "heal over", "c": "(伤口)愈合, 痊愈", "e": ""},
{"r": 718, "w": "heal up", "c": "愈合", "e": ""},
{"r": 719, "w": "originate in", "c": "归因于…, 产生于…; 起源", "e": ""},
{"r": 720, "w": "drown out", "c": "淹没, 压过", "e": ""},
{"r": 721, "w": "embark on", "c": "从事, 着手", "e": ""},
{"r": 722, "w": "summon up", "c": "振作, 鼓起", "e": ""},
{"r": 723, "w": "dip down", "c": "沉落,急降,迅速潜入水下", "e": ""},
{"r": 724, "w": "sneak away", "c": "溜号", "e": ""},
{"r": 725, "w": "sneak in", "c": "偷偷地走进 / [法] 潜行进入", "e": ""},
{"r": 726, "w": "sneak off", "c": "蹽；溜；开小差", "e": ""},
{"r": 727, "w": "sneak out", "c": "偷偷地走出", "e": ""},
{"r": 728, "w": "sneak out of", "c": "偷偷地逃避 / [法] 偷偷地逃避", "e": ""},
{"r": 729, "w": "sneak up", "c": "悄悄来临", "e": ""},
{"r": 730, "w": "sneak up on", "c": "不知不觉地来到,潜上", "e": ""},
{"r": 731, "w": "blink away", "c": "眨眼以除去", "e": ""},
{"r": 732, "w": "thrive on", "c": "靠吃…而繁衍兴旺", "e": ""},
{"r": 733, "w": "chew on", "c": "寻思,细想,仔细考虑", "e": ""},
{"r": 734, "w": "chew out", "c": "严厉责备", "e": ""},
{"r": 735, "w": "chew over", "c": "细想, 仔细考虑", "e": ""},
{"r": 736, "w": "chew up", "c": "充分咀嚼; 弄坏; 罚; 申斥", "e": ""},
{"r": 737, "w": "merge in", "c": "并入,吸收,消失在…", "e": ""},
{"r": 738, "w": "prevail on", "c": "说服, 诱使", "e": ""},
{"r": 739, "w": "prevail over", "c": "胜过", "e": ""},
{"r": 740, "w": "confer on", "c": "授予,赋予;商讨,商议,讨论", "e": ""},
{"r": 741, "w": "speculate in", "c": "做…投机生意", "e": ""},
{"r": 742, "w": "speculate on", "c": "考虑, 推测", "e": ""},
{"r": 743, "w": "preach down", "c": "贬损", "e": ""},
{"r": 744, "w": "preach up", "c": "宣扬", "e": ""},
{"r": 745, "w": "soften up", "c": "使软化", "e": ""},
{"r": 746, "w": "straighten out", "c": "改正, 清理, 澄清", "e": ""},
{"r": 747, "w": "straighten up", "c": "挺直, 改正, 清理, 澄清", "e": ""},
{"r": 748, "w": "kneel down", "c": "跪下", "e": ""},
{"r": 749, "w": "pronounce on", "c": "对…发表意见,对…表态", "e": ""},
{"r": 750, "w": "penetrate through", "c": "穿透", "e": ""},
{"r": 751, "w": "fuck about", "c": "胡闹, 摆弄", "e": ""},
{"r": 752, "w": "fuck around", "c": "胡闹, 摆弄; 瞎摆弄", "e": ""},
{"r": 753, "w": "fuck away", "c": "v. 滚开", "e": ""},
{"r": 754, "w": "fuck off", "c": "走开, 滚; 滚开", "e": ""},
{"r": 755, "w": "fuck up", "c": "弄糟, 毁坏", "e": ""},
{"r": 756, "w": "frighten away", "c": "吓跑, 吓走", "e": ""},
{"r": 757, "w": "frighten off", "c": "吓走（某人）", "e": ""},
{"r": 758, "w": "choke back", "c": "抑制", "e": ""},
{"r": 759, "w": "choke down", "c": "硬咽, 抑制", "e": ""},
{"r": 760, "w": "choke off", "c": "中止做; 使放弃做; 批评; 责备", "e": ""},
{"r": 761, "w": "choke out", "c": "闭死", "e": ""},
{"r": 762, "w": "choke up", "c": "塞住, 噎住, 阻塞", "e": ""},
{"r": 763, "w": "enlist in", "c": "热心参加", "e": ""},
{"r": 764, "w": "enlist under", "c": "支持, 加入", "e": ""},
{"r": 765, "w": "reside in", "c": "存在", "e": ""},
{"r": 766, "w": "rattle around in", "c": "在里面随心所欲,佔着茅坑不拉屎", "e": ""},
{"r": 767, "w": "rattle away", "c": "喋喋不休,絮絮叨叨;嘎嗒嘎嗒响个不停", "e": ""},
{"r": 768, "w": "rattle down", "c": "[网络] 拨浪鼓下来", "e": ""},
{"r": 769, "w": "rattle off", "c": "adv. 急促背诵地", "e": ""},
{"r": 770, "w": "rattle on", "c": "v. 喋喋不休地说; 开连珠炮", "e": ""},
{"r": 771, "w": "exclaim over", "c": "感叹", "e": ""},
{"r": 772, "w": "indulge in", "c": "沉湎于", "e": ""},
{"r": 773, "w": "linger about", "c": "徘徊,闲荡,缠绵不去", "e": ""},
{"r": 774, "w": "linger on", "c": "停留,存留,逗留,拖延", "e": ""},
{"r": 775, "w": "linger out", "c": "慢慢地捱过,苟延残喘", "e": ""},
{"r": 776, "w": "linger over", "c": "慢慢地进行", "e": ""},
{"r": 777, "w": "ponder on", "c": "考虑,思考,思索", "e": ""},
{"r": 778, "w": "ponder over", "c": "考虑,思考,思索", "e": ""},
{"r": 779, "w": "simmer down", "c": "被煮浓, 息怒", "e": ""},
{"r": 780, "w": "simmer down to", "c": "浓缩为,归结为…", "e": ""},
{"r": 781, "w": "simmer over", "c": "沸腾,爆发", "e": ""},
{"r": 782, "w": "congratulate on", "c": "祝贺", "e": ""},
{"r": 783, "w": "loosen up", "c": "信口开河, 慷慨解囊, 松弛下来, 活动肌肉, 做准备动作", "e": ""},
{"r": 784, "w": "roam about", "c": "漫游", "e": ""},
{"r": 785, "w": "enlarge on", "c": "详述", "e": ""},
{"r": 786, "w": "collaborate on", "c": "在……方面合作", "e": ""},
{"r": 787, "w": "preside over", "c": "负责, 主持", "e": ""},
{"r": 788, "w": "sew on", "c": "缝上去", "e": ""},
{"r": 789, "w": "sew together", "c": "缝接", "e": ""},
{"r": 790, "w": "sew up", "c": "缝合, 缝入, 解决, 决定", "e": ""},
{"r": 791, "w": "refine on", "c": "提鍊,改善,改进,精益求精;超过,优于", "e": ""},
{"r": 792, "w": "broaden out", "c": "1。（路、河等）变宽; 2。拓展; 扩大; （使）数目增加", "e": ""},
{"r": 793, "w": "inquire about", "c": "询问,了解,打听", "e": ""},
{"r": 794, "w": "mourn over", "c": "哀悼", "e": ""},
{"r": 795, "w": "pierce through", "c": "突破, 刺入", "e": ""},
{"r": 796, "w": "dodge about", "c": "东躲西闪", "e": ""},
{"r": 797, "w": "harden off", "c": "锻鍊;使耐寒", "e": ""},
{"r": 798, "w": "excel in", "c": "在...方面擅长", "e": ""},
{"r": 799, "w": "fasten down", "c": "扎紧,扎牢,钉牢;确定,使下定决心", "e": ""},
{"r": 800, "w": "fasten off", "c": "扣紧,结牢,缝牢", "e": ""},
{"r": 801, "w": "fasten on", "c": "把...强加于, 纠缠, 集中于", "e": ""},
{"r": 802, "w": "fasten up", "c": "拴紧,钉紧,扎牢", "e": ""},
{"r": 803, "w": "dwell on", "c": "细想, 详述", "e": ""},
{"r": 804, "w": "batter away at", "c": "勐烈敲打…", "e": ""},
{"r": 805, "w": "batter down", "c": "撞倒,冲垮,摧毁", "e": ""},
{"r": 806, "w": "batter up", "c": "毁坏,撞坏", "e": ""},
{"r": 807, "w": "sob out", "c": "哭诉", "e": ""},
{"r": 808, "w": "dine forth", "c": "上外面吃饭,在外面用膳", "e": ""},
{"r": 809, "w": "dine in", "c": "在家吃饭", "e": ""},
{"r": 810, "w": "dine out", "c": "外出吃饭", "e": ""},
{"r": 811, "w": "revolve about", "c": "围绕", "e": ""},
{"r": 812, "w": "revolve around", "c": "旋转, 绕转; 环绕", "e": ""},
{"r": 813, "w": "flatten out", "c": "变平, 转为水平飞行", "e": ""},
{"r": 814, "w": "topple down", "c": "倒塌", "e": ""},
{"r": 815, "w": "topple over", "c": "倒下, 倒塌", "e": ""},
{"r": 816, "w": "conjure away", "c": "用魔法驱除", "e": ""},
{"r": 817, "w": "conjure up", "c": "用魔法使出现", "e": ""},
{"r": 818, "w": "wade across", "c": "跋涉通过,趟水穿过", "e": ""},
{"r": 819, "w": "wade in", "c": "介入, 猛烈攻击, 插手", "e": ""},
{"r": 820, "w": "wade through", "c": "跋涉通过,趟水穿过,吃力地通过,费力地读完", "e": ""},
{"r": 821, "w": "abound in", "c": "v. 富于; 盛产", "e": ""},
{"r": 822, "w": "brighten up", "c": "使愉快,使生辉", "e": ""},
{"r": 823, "w": "confide in", "c": "信任", "e": ""},
{"r": 824, "w": "capitalize on", "c": "利用", "e": ""},
{"r": 825, "w": "sift through", "c": "被筛下, 通过", "e": ""},
{"r": 826, "w": "piss about", "c": "胡闹,吊儿郎当", "e": ""},
{"r": 827, "w": "piss around", "c": "吵闹, 胡闹, 工作吊儿郎当", "e": ""},
{"r": 828, "w": "piss away", "c": "挥霍,浪费", "e": ""},
{"r": 829, "w": "piss down", "c": "[俚语]下大雨：", "e": ""},
{"r": 830, "w": "piss off", "c": "走开,滚蛋;惹恼,喝醉,精疲力竭", "e": ""},
{"r": 831, "w": "piss on", "c": "故意对...表示不敬, 亵渎", "e": ""},
{"r": 832, "w": "darken up", "c": "阴暗下来", "e": ""},
{"r": 833, "w": "radiate out", "c": "辐射,向週围扩张", "e": ""},
{"r": 834, "w": "grate on", "c": "激怒, 刺激", "e": ""},
{"r": 835, "w": "skim off", "c": "把…撇去; <非正>提取精华", "e": ""},
{"r": 836, "w": "skim over", "c": "掠过, 滑过, 浏览", "e": ""},
{"r": 837, "w": "skim through", "c": "浏览", "e": ""},
{"r": 838, "w": "rejoice in", "c": "享有…,因…感到高兴", "e": ""},
{"r": 839, "w": "rejoice over", "c": "对…感到高兴", "e": ""},
{"r": 840, "w": "lighten out", "c": "v. 闪现出", "e": ""},
{"r": 841, "w": "lighten up", "c": "别那么严肃; 别抱怨; 别担忧; 使生动活泼", "e": ""},
{"r": 842, "w": "seep in", "c": "[化] 漏入; 渗入", "e": ""},
{"r": 843, "w": "smuggle out", "c": "[法] 掩盖, 回避, 逃避", "e": ""},
{"r": 844, "w": "nestle down", "c": "舒服地躺下,歇息", "e": ""},
{"r": 845, "w": "nestle up", "c": "偎依,挨靠着", "e": ""},
{"r": 846, "w": "veer out", "c": "放松", "e": ""},
{"r": 847, "w": "vomit up", "c": "呕吐", "e": ""},
{"r": 848, "w": "sag down", "c": "使下凹 / 使下垂", "e": ""},
{"r": 849, "w": "thrash about", "c": "剧烈移动", "e": ""},
{"r": 850, "w": "thrash out", "c": "研究解决", "e": ""},
{"r": 851, "w": "fell down", "c": "倒下，跪拜", "e": ""},
{"r": 852, "w": "fell off", "c": "跌落", "e": ""},
{"r": 853, "w": "fend off", "c": "挡开", "e": ""},
{"r": 854, "w": "concur in", "c": "赞成", "e": ""},
{"r": 855, "w": "concur on", "c": "在…方面意见一致", "e": ""},
{"r": 856, "w": "scurry away", "c": "匆匆跑开", "e": ""},
{"r": 857, "w": "scurry off", "c": "[法] 窜逃, 匆忙逃开", "e": ""},
{"r": 858, "w": "bestow on", "c": "v. 赠与", "e": ""},
{"r": 859, "w": "scour about", "c": "寻找,搜索,查看", "e": ""},
{"r": 860, "w": "scour away", "c": "清洗,洗涤,冲刷掉…", "e": ""},
{"r": 861, "w": "scour off", "c": "擦掉, 洗去", "e": ""},
{"r": 862, "w": "scour out", "c": "冲刷成", "e": ""},
{"r": 863, "w": "ascend in", "c": "乘坐…上升", "e": ""},
{"r": 864, "w": "amplify on", "c": "详述,进一步阐述", "e": ""},
{"r": 865, "w": "perk up", "c": "(使)振作, (使)活跃起来", "e": ""},
{"r": 866, "w": "permeate through", "c": "渗透入", "e": ""},
{"r": 867, "w": "bash in", "c": "v. 打坏", "e": ""},
{"r": 868, "w": "browse on", "c": "v. 放牧,吃草", "e": ""},
{"r": 869, "w": "intrude on", "c": "[网络] 侵犯；间接地侵犯；干涉", "e": ""},
{"r": 870, "w": "grieve over", "c": "哀悼", "e": ""},
{"r": 871, "w": "predominate over", "c": "占优势", "e": ""},
{"r": 872, "w": "blurt out", "c": "因为高兴或紧张而不假思索地脱口而出; 直言不讳", "e": ""},
{"r": 873, "w": "holler out", "c": "[网络] 呃出来", "e": ""},
{"r": 874, "w": "infiltrate through", "c": "渗透入", "e": ""},
{"r": 875, "w": "spew out", "c": "（使）喷涌出", "e": ""},
{"r": 876, "w": "bellow off", "c": "高声驱赶,呵斥得某人哑口无言", "e": ""},
{"r": 877, "w": "bellow out", "c": "吼出,喊出,大声发出", "e": ""},
{"r": 878, "w": "stash away", "c": "n. 隐藏处; 藏起, 隐藏（某物）", "e": ""},
{"r": 879, "w": "dwindle away", "c": "减少, 缩小", "e": ""},
{"r": 880, "w": "dwindle down", "c": "逐渐减少；逐渐变小, 缩小：", "e": ""},
{"r": 881, "w": "snarl up", "c": "使缠结：；使(交通等)堵塞：", "e": ""},
{"r": 882, "w": "gulp back", "c": "咽回去,忍住", "e": ""},
{"r": 883, "w": "gulp down", "c": "一口吞下,狼吞虎咽地吃", "e": ""},
{"r": 884, "w": "rummage up", "c": "搜查出", "e": ""},
{"r": 885, "w": "doze away", "c": "在瞌睡中度过…", "e": ""},
{"r": 886, "w": "doze off", "c": "不知不觉地睡着了", "e": ""},
{"r": 887, "w": "whack off", "c": "用力敲掉", "e": ""},
{"r": 888, "w": "whack out", "c": "用力演奏,大力制造", "e": ""},
{"r": 889, "w": "whack up", "c": "均分,瓜分;增加", "e": ""},
{"r": 890, "w": "impinge on", "c": "撞击, 侵犯, 紧密接触", "e": ""},
{"r": 891, "w": "alight on", "c": "碰到,碰巧遇到", "e": ""},
{"r": 892, "w": "evict out of", "c": "驱逐出", "e": ""},
{"r": 893, "w": "bask in", "c": "沐浴于,沉湎于…", "e": ""},
{"r": 894, "w": "dribble away", "c": "逐渐消磨, 逐渐消失", "e": ""},
{"r": 895, "w": "wither up", "c": "枯萎", "e": ""},
{"r": 896, "w": "crumple up", "c": "起皱, 打垮, 使崩溃", "e": ""},
{"r": 897, "w": "prick down", "c": "选择", "e": ""},
{"r": 898, "w": "prick off", "c": "挑选出", "e": ""},
{"r": 899, "w": "prick on", "c": "驱使", "e": ""},
{"r": 900, "w": "prick out", "c": "挑选出,移植,用针刺出", "e": ""},
{"r": 901, "w": "prick up", "c": "竖起, 粗涂, (风)加剧", "e": ""},
{"r": 902, "w": "restart up", "c": "[计] 再启动", "e": ""},
{"r": 903, "w": "rationalize away", "c": "[网络] 合理化", "e": ""},
{"r": 904, "w": "devolve on", "c": "移交", "e": ""},
{"r": 905, "w": "stow away", "c": "偷乘", "e": ""},
{"r": 906, "w": "stow down", "c": "装入,装载", "e": ""},
{"r": 907, "w": "meditate on", "c": "沉思", "e": ""},
{"r": 908, "w": "gnaw off", "c": "咬掉", "e": ""},
{"r": 909, "w": "bleach out", "c": "漂白, 褪色", "e": ""},
{"r": 910, "w": "scoot about", "c": "到处跑动", "e": ""},
{"r": 911, "w": "err in", "c": "犯错误, 弄错", "e": ""},
{"r": 912, "w": "cull out", "c": "选出 / 拔出", "e": ""},
{"r": 913, "w": "pare away", "c": "修掉, 减少", "e": ""},
{"r": 914, "w": "pare down", "c": "缩减", "e": ""},
{"r": 915, "w": "pare off", "c": "修掉", "e": ""},
{"r": 916, "w": "tote up", "c": "[网络] 手提包", "e": ""},
{"r": 917, "w": "encroach on", "c": "侵犯, 蚕食", "e": ""},
{"r": 918, "w": "muddle along", "c": "混日子, 得过且过", "e": ""},
{"r": 919, "w": "muddle away", "c": "挥霍,虚度", "e": ""},
{"r": 920, "w": "muddle on", "c": "混日子, 得过且过", "e": ""},
{"r": 921, "w": "muddle through", "c": "终于对付过去, 终于应付过去", "e": ""},
{"r": 922, "w": "muddle together", "c": "把…搞乱", "e": ""},
{"r": 923, "w": "muddle up", "c": "把…搞乱", "e": ""},
{"r": 924, "w": "persevere in", "c": "坚持", "e": ""},
{"r": 925, "w": "rationalise away", "c": "[网络] 合理化", "e": ""},
{"r": 926, "w": "hark back", "c": "回想; 回到原题", "e": ""},
{"r": 927, "w": "hark back to", "c": "回溯到,追溯到,引用", "e": ""},
{"r": 928, "w": "slacken off", "c": "松懈下来; 变迟缓; 松驰; 减弱", "e": ""},
{"r": 929, "w": "usurp on", "c": "侵占", "e": ""},
{"r": 930, "w": "snip off", "c": "剪[绞]掉", "e": ""},
{"r": 931, "w": "dabble in", "c": "涉猎", "e": ""},
{"r": 932, "w": "blacken out", "c": "[网络] 无法记起", "e": ""},
{"r": 933, "w": "crystallize out", "c": "[建] 结晶出来", "e": ""},
{"r": 934, "w": "plunk down", "c": "突然落下, 付给", "e": ""},
{"r": 935, "w": "wallow in", "c": "沉湎于", "e": ""},
{"r": 936, "w": "tied up", "c": "a. 忙得不可开交的；不得闲的；正在使用的", "e": ""},
{"r": 937, "w": "whittle away", "c": "削减, 减少, 降低（…的大小、重要性或价值）", "e": ""},
{"r": 938, "w": "whittle down", "c": "削减", "e": ""},
{"r": 939, "w": "fatten out", "c": "长肥, 长胖：；[口语]充实(文章、作品等)：", "e": ""},
{"r": 940, "w": "fatten up", "c": "使肥胖; 长膘", "e": ""},
{"r": 941, "w": "babble out", "c": "（因多说话而）吐露（或泄露）秘密", "e": ""},
{"r": 942, "w": "renege on", "c": "[网络] 食言；违背；违约", "e": ""},
{"r": 943, "w": "partake in", "c": "参与, 参加, 分享", "e": ""},
{"r": 944, "w": "hunker down", "c": "沉潜待发", "e": ""},
{"r": 945, "w": "drool over", "c": "痴情地看, 迷恋地看", "e": ""},
{"r": 946, "w": "recline on", "c": "依赖", "e": ""},
{"r": 947, "w": "scrabble about for", "c": "到处摸索", "e": ""},
{"r": 948, "w": "scrabble up", "c": "拼凑成", "e": ""},
{"r": 949, "w": "shrivel up", "c": "v. (使)皱缩；(使)干瘪；(使)枯萎；(使)无能为力", "e": ""},
{"r": 950, "w": "rant out", "c": "大声地说", "e": ""},
{"r": 951, "w": "waken up", "c": "醒来", "e": ""},
{"r": 952, "w": "meddle in", "c": "干涉,插手,介入", "e": ""},
{"r": 953, "w": "raze out", "c": "v. 削去", "e": ""},
{"r": 954, "w": "loll around", "c": "懒洋洋地坐着（或躺着、站着）, 无所事事", "e": ""},
{"r": 955, "w": "loll out", "c": "伸出", "e": ""},
{"r": 956, "w": "subsist on", "c": "靠...生存", "e": ""},
{"r": 957, "w": "sidle up", "c": "悄悄贴近", "e": ""},
{"r": 958, "w": "lob along", "c": "沉重(或笨拙)地走动", "e": ""},
{"r": 959, "w": "botch up", "c": "<口>（由于不注意、不小心等）搞坏, 弄糟", "e": ""},
{"r": 960, "w": "scrunch up", "c": "n. 喀嚓声; 把…揉成小团; 扭曲（面部）", "e": ""},
{"r": 961, "w": "abut on", "c": "与…毗邻,紧靠…", "e": ""},
{"r": 962, "w": "hew off", "c": "砍掉", "e": ""},
{"r": 963, "w": "hew out", "c": "开辟", "e": ""},
{"r": 964, "w": "freshen up", "c": "(使)精神饱满, 梳洗一番", "e": ""},
{"r": 965, "w": "pucker up", "c": "使缩拢", "e": ""},
{"r": 966, "w": "offered down", "c": "[经] 开价跌落, 出价下降", "e": ""},
{"r": 967, "w": "mete out", "c": "给予; 给予惩罚; 责罚; 使受苦", "e": ""},
{"r": 968, "w": "teem in", "c": "大量存在于：", "e": ""},
{"r": 969, "w": "innovate in", "c": "对...革新", "e": ""},
{"r": 970, "w": "regale on", "c": "享用, 吃喝", "e": ""},
{"r": 971, "w": "enjoin on", "c": "嘱咐, 命令", "e": ""},
{"r": 972, "w": "stopped up", "c": "na. 没有睡；熬夜；塞住(洞口)；同“stop” / [网络] 塞住了", "e": ""},
{"r": 973, "w": "psych out", "c": "吓坏, 装疯以逃避", "e": ""},
{"r": 974, "w": "psych up", "c": "使兴奋起来, 使（为比赛、表演等）作好精神准备", "e": ""},
{"r": 975, "w": "exult in", "c": "狂喜", "e": ""},
{"r": 976, "w": "exult over", "c": "狂喜", "e": ""},
{"r": 977, "w": "coughing up", "c": "[网络] 咳嗽", "e": ""},
{"r": 978, "w": "loiter about", "c": "消磨时间", "e": ""},
{"r": 979, "w": "loiter away", "c": "消磨", "e": ""},
{"r": 980, "w": "dawdle away", "c": "浪费(时间等)", "e": ""},
{"r": 981, "w": "suss out", "c": "弄清楚", "e": ""},
{"r": 982, "w": "dote on", "c": "过分喜爱,溺爱", "e": ""},
{"r": 983, "w": "lop off", "c": "砍掉", "e": ""},
{"r": 984, "w": "laze away", "c": "混日子", "e": ""},
{"r": 985, "w": "tamp down", "c": "vt. 敲下、舂紧; 敲定; 夯实, 压实", "e": ""},
{"r": 986, "w": "snooze away", "c": "消磨", "e": ""},
{"r": 987, "w": "skimp over", "c": "[网络] sk p过去", "e": ""},
{"r": 988, "w": "bluster out", "c": "v. 咆哮", "e": ""},
{"r": 989, "w": "swill down", "c": "n. 泔脚饲料; 猪食; <非正>（谈话或写作中的）无意义的话; 废话", "e": ""},
{"r": 990, "w": "swill out", "c": "冲洗掉", "e": ""},
{"r": 991, "w": "smarten up", "c": "(使)变漂亮, (使)变潇洒, (使)变时髦", "e": ""},
{"r": 992, "w": "fritter away", "c": "消磨", "e": ""},
{"r": 993, "w": "winnow out", "c": "淘汰 / 排除", "e": ""},
{"r": 994, "w": "played out", "c": "[体]使筋疲力尽", "e": ""},
{"r": 995, "w": "ruminate over", "c": "反复思考", "e": ""},
{"r": 996, "w": "yap away", "c": "(狗)狂吠, 不停地叫：；不停地唠唠叨叨；没完没了地废话：", "e": ""},
{"r": 997, "w": "eke out", "c": "弥补...的不足, 竭力维持", "e": ""},
{"r": 998, "w": "editorialize on", "c": "发表社论", "e": ""},
{"r": 999, "w": "browned off", "c": "a. 厌烦的；沮丧的", "e": ""},
{"r": 1000, "w": "thresh about", "c": "un. 脱粒；打(谷)；挥舞", "e": ""}
];
