/* English proverbs (LLMProverbMT + IdiomKB). { r, w, c:Chinese, e:English }. */
window.PROVERBS = [
{"r": 1, "w": "you only get what you give", "c": "有付出才有收获", "e": ""},
{"r": 2, "w": "you get what you pay for", "c": "一分钱，一分货", "e": ""},
{"r": 3, "w": "use it or lose it", "c": "用进废退", "e": ""},
{"r": 4, "w": "you only go around once", "c": "人生苦短", "e": ""},
{"r": 5, "w": "this too shall pass", "c": "一切终将过去", "e": ""},
{"r": 6, "w": "you make the bed you lie in", "c": "自食其果", "e": ""},
{"r": 7, "w": "a bird in the hand", "c": "双鸟在林，不如一鸟在手", "e": ""},
{"r": 8, "w": "never put off until tomorrow what you can do today", "c": "今日事，今日畢", "e": ""},
{"r": 9, "w": "murder will out", "c": "天网恢恢，疏而不漏", "e": ""},
{"r": 10, "w": "cross that bridge when you come to it", "c": "遇到问题时再解决，不必预先担心或担忧", "e": "to deal with a problem or difficult situation only when it arises, rather than worrying about it in advance"},
{"r": 11, "w": "come hell or high water", "c": "不管发生什么事，无论遇到什么困难", "e": "no matter what happens or what difficulties are encountered; regardless of the obstacles or challenges that may arise"},
{"r": 12, "w": "have a lot on one's plate", "c": "手头很忙，有很多事情要处理", "e": "to have a lot of tasks, responsibilities, or problems to deal with"},
{"r": 13, "w": "have too much on one's plate", "c": "任务过多或负担过重", "e": "to have too many tasks or responsibilities to deal with"},
{"r": 14, "w": "turn over a new leaf", "c": "改过自新；重新开始；改变行为方式", "e": "to make a fresh start or change one's behavior or attitude for the better"},
{"r": 15, "w": "have a mountain to climb", "c": "面临很大的困难或挑战", "e": "to face a difficult or challenging task or situation"},
{"r": 16, "w": "give it to me straight", "c": "直截了当地告诉我", "e": "to be honest and direct with someone"},
{"r": 17, "w": "keep body and soul together", "c": "维持基本生活需要；维持生计", "e": "To earn enough money to live and survive"},
{"r": 18, "w": "make heavy weather of something", "c": "在做某事时过于复杂化或困难化", "e": "to make a task or situation more difficult, complicated, or time-consuming than necessary"},
{"r": 19, "w": "business before pleasure", "c": "先苦后甜", "e": ""},
{"r": 20, "w": "make a clean breast of", "c": "坦白承认，公开透露", "e": "to confess or make a full and honest disclosure"},
{"r": 21, "w": "a cat may look at a king", "c": "人人平等", "e": ""},
{"r": 22, "w": "give someone a bloody nose", "c": "给某人一个惨败，让某人吃亏，让某人受伤", "e": "to defeat or physically harm someone in a confrontation"},
{"r": 23, "w": "a golden key can open any door", "c": "有钱能使鬼推磨", "e": ""},
{"r": 24, "w": "come out in the wash", "c": "最终达到公正或解决问题", "e": "to be resolved or come to light over time through natural processes or events"},
{"r": 25, "w": "talk nineteen to the dozen", "c": "口若悬河，滔滔不绝", "e": "to talk rapidly, incessantly, or without pause"},
{"r": 26, "w": "be sick and tired of", "c": "对...感到厌烦；对...烦透了", "e": "to be extremely annoyed or fed up with"},
{"r": 27, "w": "do something at the drop of a hat", "c": "毫不犹豫迅速行动", "e": "to do something immediately or without hesitation"},
{"r": 28, "w": "have a chip on your shoulder", "c": "心怀不满或愤怒，对某人或某事抱有敌意或敌视的态度", "e": "to have a persistent feeling of resentment or anger, often from a perceived injustice or unfair treatment"},
{"r": 29, "w": "be glad to see the back of", "c": "庆幸某人离开或离开某个烦人的事情", "e": "to be happy or relieved when someone or something leaves or is gone"},
{"r": 30, "w": "be glad to see the back of someone", "c": "对某人的离开感到高兴", "e": "To be pleased when someone leaves because you did not like them"},
{"r": 31, "w": "not be short of a bob or two", "c": "没有短钱；相当有钱", "e": "to have plenty of money or wealth"},
{"r": 32, "w": "give the kiss of life", "c": "救命，使某人/某事恢复活力或重新启动", "e": "to revive or bring something back to life"},
{"r": 33, "w": "as luck would have it", "c": "碰巧的是；恰巧", "e": "by chance or fortunate circumstances"},
{"r": 34, "w": "be part of the furniture", "c": "成为家具的一部分；变得无足轻重或习以为常", "e": "to have been in a place for so long that one is considered a permanent fixture, often overlooked or ignored"},
{"r": 35, "w": "come out of your shell", "c": "走出你的舒适区，变得更加社交和活跃", "e": "to become more outgoing or sociable, to overcome shyness or reserve"},
{"r": 36, "w": "make head or tail of", "c": "弄清楚或理解", "e": "to understand or comprehend something"},
{"r": 37, "w": "light at the end of the tunnel", "c": "隧道尽头的光明", "e": "hope or relief, especially after a long and difficult time or situation"},
{"r": 38, "w": "bite the hand that feed", "c": "恩将仇报；忘恩负义", "e": "to harm or betray someone who has helped or supported you"},
{"r": 39, "w": "time and tide wait for no man", "c": "时不我待", "e": ""},
{"r": 40, "w": "make a virtue of necessity", "c": "将无奈变为美德", "e": "to make the best of a difficult situation"},
{"r": 41, "w": "come out of the closet", "c": "公开自己的真实身份或性取向", "e": "to reveal or acknowledge one's true identity or beliefs, especially regarding homosexuality"},
{"r": 42, "w": "fall off the back of a lorry", "c": "非法获得或购买廉价货物", "e": "to have acquired something illegally or dishonestly"},
{"r": 43, "w": "better the devil you know", "c": "宁可选择已知的困难或问题，也不愿意冒险去面对未知的情况", "e": "to choose or accept something familiar, even if it is not ideal, over something unfamiliar or unknown"},
{"r": 44, "w": "give the devil his due", "c": "公平地承认或赞赏恶人的优点或成就", "e": "acknowledge and give credit to someone, even if they are disliked or considered to be a bad person"},
{"r": 45, "w": "be left holding the baby", "c": "承担责任或后果，通常是因为其他人拒绝或无法承担", "e": "to be left with the responsibility or consequences of something, especially when it is undesired or burdensome"},
{"r": 46, "w": "make money hand over fist", "c": "大把赚钱", "e": "To make a large amount of money quickly and easily"},
{"r": 47, "w": "set a thief to catch a thief", "c": "用贼去捉贼", "e": "to use a person with questionable character or expertise to apprehend or expose another person with similar qualities or skills"},
{"r": 48, "w": "keep the wolf from the door", "c": "勉力维持生计；勉力糊口", "e": "to have enough money or resources to prevent hunger or poverty"},
{"r": 49, "w": "have a card up your sleeve", "c": "暗中保留一张杀手锏，以便在关键时刻使用", "e": "to have a secret plan or advantage that can be used if needed"},
{"r": 50, "w": "have a whale of a time", "c": "玩得非常开心，享受得不亦乐乎", "e": "To have a great and enjoyable time; to have a lot of fun"},
{"r": 51, "w": "keep me in the loop", "c": "让我了解最新情况", "e": "to keep someone informed or involved in a particular situation or project"},
{"r": 52, "w": "spare the rod and spoil the child", "c": "孩子不打不成器", "e": ""},
{"r": 53, "w": "turn up like a bad penny", "c": "不请自来；一直出现不受欢迎的人或事物", "e": "to unexpectedly appear, especially in an unwanted or negative way"},
{"r": 54, "w": "make a monkey of someone", "c": "让某人出丑，使其成为笑柄", "e": "to make someone look foolish or ridiculous"},
{"r": 55, "w": "make a monkey out of", "c": "让某人感到非常愚蠢或尴尬，以至于成为笑柄", "e": "to make a fool out of someone, to embarrass or humiliate someone"},
{"r": 56, "w": "the fox may grow grey but never good", "c": "本性难移", "e": ""},
{"r": 57, "w": "bite off more than can chew", "c": "贪多嚼不烂/心有余而力不足", "e": "to take on more responsibilities or tasks than one can handle"},
{"r": 58, "w": "bite off more than you can chew", "c": "承担比自己能力范围内更多的责任", "e": "to take on more responsibilities or tasks than one can handle or manage"},
{"r": 59, "w": "have a tiger by the tail", "c": "牵强附会并不请去做一项难以控制的任务或处理棘手的情况", "e": "to be in a situation or have a problem that is challenging or difficult to control"},
{"r": 60, "w": "go down like a lead balloon", "c": "没有引起兴趣或者没有成功", "e": "to be poorly received or unsuccessful, typically due to being unpopular or uninteresting"},
{"r": 61, "w": "rob peter to pay paul", "c": "以不当手段取得资金或资源以解决当前的问题，但同时增加了其他问题或困难", "e": "to take from one source to provide for another, often leading to a never-ending cycle of debts or problems"},
{"r": 62, "w": "too much pudding will choke a dog", "c": "弄巧成拙", "e": ""},
{"r": 63, "w": "sauce for the goose", "c": "一视同仁", "e": ""},
{"r": 64, "w": "all bark and no bite", "c": "纸老虎，嘴上厉害但实际上没什么能耐", "e": "someone who talks tough or acts aggressively, but lacks the courage or ability to follow through with their threats or actions"},
{"r": 65, "w": "bark up the wrong tree", "c": "对一个问题、情况或人的判断完全错误", "e": "to pursue a mistaken or misguided course of action or to blame the wrong person or thing"},
{"r": 66, "w": "have a face like thunder", "c": "脸色阴沉，表情愤怒或生气", "e": "to have a very angry or unhappy expression"},
{"r": 67, "w": "neither a borrower nor a lender be", "c": "救急不救窮，幫困不幫懶", "e": ""},
{"r": 68, "w": "even a blind squirrel can find a nut once in a while", "c": "瞎猫碰上死耗子", "e": ""},
{"r": 69, "w": "have an axe to grind", "c": "有隐私的私人事情要处理或争辩", "e": "to have a hidden personal agenda or motive"},
{"r": 70, "w": "have other fish to fry", "c": "有更重要的事情要做", "e": "to have other more important or pressing matters to attend to"},
{"r": 71, "w": "make a pig of oneself", "c": "大吃大喝", "e": "to eat too much or in a greedy and excessive manner"},
{"r": 72, "w": "save money for a rainy day", "c": "为了不时之需而储蓄金钱", "e": "To save money for a future time when it may be needed or when there may be unexpected expenses."},
{"r": 73, "w": "bat from the pavilion end", "c": "从亭子一侧击球", "e": "No information is available for this specific idiom."},
{"r": 74, "w": "seek and ye shall find", "c": "求则得之", "e": ""},
{"r": 75, "w": "have a bun in the oven", "c": "怀孕", "e": "to be pregnant"},
{"r": 76, "w": "not hurt a fly or flea", "c": "不会伤害一只苍蝇或跳蚤", "e": "To be extremely gentle and harmless"},
{"r": 77, "w": "come out of the woodwork", "c": "从不为人知的地方出现，通常表达负面的意义，意味着在某个事件或情况中突然出现了许多人或事物", "e": "to suddenly appear or emerge, often in large numbers or from unexpected places"},
{"r": 78, "w": "curiosity killed the cat", "c": "好奇害死猫", "e": ""},
{"r": 79, "w": "birds of a feather flock together", "c": "物以类聚，人以群分", "e": ""},
{"r": 80, "w": "help a lame dog over a stile", "c": "帮助一个需要帮助的人，尽管任务很小或似乎没有太大意义", "e": "to assist someone who is in need, even if their condition or situation is challenging or difficult"},
{"r": 81, "w": "still waters run deep", "c": "静水流深", "e": ""},
{"r": 82, "w": "a fly in the ointment", "c": "破坏完美计划、情况或享受的一件小事物", "e": "something that spoils or ruins a situation or plan"},
{"r": 83, "w": "too much water drowned the miller", "c": "过犹不及", "e": ""},
{"r": 84, "w": "be joined at the hip", "c": "彼此紧密地联系在一起，无法分开", "e": "to be extremely close or inseparable, often referring to two people who spend a lot of time together and do everything together"},
{"r": 85, "w": "run something up the flagpole", "c": "试探性地提出或公开一个想法或计划，以观察反应或获取意见", "e": "to test or try out an idea, suggestion, or proposal to see if it is well-received or popular"},
{"r": 86, "w": "never the twain shall meet", "c": "东西终不相能；两种截然不同的事物永远无法相遇", "e": "Two things or groups are so different that they cannot coexist or come together"},
{"r": 87, "w": "there is nothing new under the sun", "c": "太阳底下无新事", "e": ""},
{"r": 88, "w": "home is where the heart is", "c": "此心安处是吾乡", "e": ""},
{"r": 89, "w": "age is just a number", "c": "年龄只是数字", "e": ""},
{"r": 90, "w": "an ounce of prevention is better than a pound of cure", "c": "惩创于已然，不如防患于未然", "e": ""},
{"r": 91, "w": "a little knowledge is a dangerous thing", "c": "一知半解,自欺欺人", "e": ""},
{"r": 92, "w": "knowledge is power", "c": "知识就是力量", "e": ""},
{"r": 93, "w": "to err is human", "c": "人非圣贤孰能无过", "e": ""},
{"r": 94, "w": "fair exchange is no robbery", "c": "礼尚往来", "e": ""},
{"r": 95, "w": "a good deed is its own reward", "c": "赠人玫瑰，手有余香", "e": ""},
{"r": 96, "w": "a friend in need is a friend indeed", "c": "患难见真情", "e": ""},
{"r": 97, "w": "where there is a will", "c": "有志者事竟成", "e": ""},
{"r": 98, "w": "no man is an island", "c": "没有人是一座孤岛", "e": ""},
{"r": 99, "w": "necessity is the mother of invention", "c": "需求创造价值", "e": ""},
{"r": 100, "w": "money is the root of all evil", "c": "钱是万恶之源", "e": ""},
{"r": 101, "w": "every man is the architect of his own fortune", "c": "自己的命运自己掌握", "e": ""},
{"r": 102, "w": "patience is a virtue", "c": "耐心是一种美德", "e": ""},
{"r": 103, "w": "talk is cheap", "c": "開空頭支票", "e": ""},
{"r": 104, "w": "procrastination is the thief of time", "c": "拖延就是浪费时间", "e": ""},
{"r": 105, "w": "health is your first wealth", "c": "健康就是财富", "e": ""},
{"r": 106, "w": "the first step is always the hardest", "c": "万事开头难", "e": ""},
{"r": 107, "w": "prevention is better than cure", "c": "防患于未然", "e": ""},
{"r": 108, "w": "time is a great healer", "c": "时间是治愈创伤的良药", "e": ""},
{"r": 109, "w": "comparison is the thief of joy", "c": "攀比是偷走快乐的贼", "e": ""},
{"r": 110, "w": "a contented mind is a perpetual feast", "c": "知足常乐", "e": ""},
{"r": 111, "w": "no one is born a master", "c": "天生我材必有用", "e": ""},
{"r": 112, "w": "less is more", "c": "舍，得", "e": ""},
{"r": 113, "w": "honesty is the best policy", "c": "做人诚信为本", "e": ""},
{"r": 114, "w": "silence is consent", "c": "默认", "e": ""},
{"r": 115, "w": "it is easy to be wise after the event", "c": "事后诸葛亮", "e": ""},
{"r": 116, "w": "experience is the best teacher", "c": "前车之鉴，后事之师", "e": ""},
{"r": 117, "w": "something is better than nothing", "c": "聊胜于无", "e": ""},
{"r": 118, "w": "ignorance is bliss", "c": "无知便是福", "e": ""},
{"r": 119, "w": "the enemy of my enemy is my friend", "c": "敌人的敌人就是朋友", "e": ""},
{"r": 120, "w": "brevity is the soul of wit", "c": "言简意赅", "e": ""},
{"r": 121, "w": "hunger is the best spice", "c": "饥不择食", "e": ""},
{"r": 122, "w": "beauty is only skin deep", "c": "美貌只是皮囊", "e": ""},
{"r": 123, "w": "love is blind", "c": "爱情是盲目的", "e": ""},
{"r": 124, "w": "all publicity is good publicity", "c": "任何宣传都是好的宣传", "e": ""},
{"r": 125, "w": "beauty is in the eye of the beholder", "c": "情人眼里出西施", "e": ""},
{"r": 126, "w": "enough is as good as a feast", "c": "凡事适可而止", "e": ""},
{"r": 127, "w": "what you see is what you get", "c": "所见即所得", "e": ""},
{"r": 128, "w": "a revolution is not a dinner party", "c": "革命不是请客吃饭", "e": ""},
{"r": 129, "w": "a little learning is a dangerous thing", "c": "知之甚少则危险", "e": "having a small amount of knowledge about something can lead to overconfidence and mistakes"},
{"r": 130, "w": "a miss is as good as a mile", "c": "差之毫厘，失之千里", "e": "Even a small mistake or failure has the same result as a larger one; being close to success or achieving a goal is not the same as actually succeeding."},
{"r": 131, "w": "a penny saved is a penny earned", "c": "省下来的一分钱就是挣来的一分钱", "e": "Saving money is the same as earning money; it is wise to save money."},
{"r": 132, "w": "all is fair in love and war", "c": "爱情和战争中，一切皆公平", "e": "any type of behavior is acceptable or justified when dealing with love or war"},
{"r": 133, "w": "art is long and life is short", "c": "艺术是无限长久的，而生命则短暂有限", "e": "the time we have in life is limited, but the impact of great works of art can last forever"},
{"r": 134, "w": "discretion is the better part of valour", "c": "谨慎是勇敢的重要组成部分", "e": "to act with caution and prudence is often the wisest course of action, especially in dangerous or risky situations"},
{"r": 135, "w": "everything in the garden is rosy", "c": "一切都很美好，没有问题或困难", "e": "everything is going well; everything is in a positive or ideal state"},
{"r": 136, "w": "experience is the mother of wisdom", "c": "经验是智慧之母", "e": "a person gains wisdom through their experiences"},
{"r": 137, "w": "it is written all over your face", "c": "这清楚地写在你的脸上", "e": "to be very obvious or evident, often through one's facial expression"},
{"r": 138, "w": "laughter is the best medicine", "c": "笑是最好的良药", "e": "laughter and humor can have a positive and healing effect on a person's physical and emotional well-being"},
{"r": 139, "w": "poverty is not a crime", "c": "贫穷并不是一种犯罪", "e": "Being poor is not a punishable offense or something to be ashamed of"},
{"r": 140, "w": "strike while the iron is hot", "c": "趁热打铁", "e": "to take advantage of an opportunity at the right moment"},
{"r": 141, "w": "tell it like it is", "c": "直言不讳地说出真相", "e": "to speak openly and honestly; to state the truth without sugarcoating or exaggeration"},
{"r": 142, "w": "the best is yet to come", "c": "最好的还在后面", "e": "better things are still to come in the future"},
{"r": 143, "w": "the boot is on the other foot", "c": "情况发生了逆转", "e": "the situation has changed, with the person who was in a position of power or advantage now in a position of disadvantage or vulnerability"},
{"r": 144, "w": "the customer is always right", "c": "顾客永远是对的", "e": "an ideology or belief that prioritizes catering to the needs and demands of customers, even if they may be unreasonable or incorrect"},
{"r": 145, "w": "the joke is on someone", "c": "戏谑的对象是某人", "e": "to be the target or subject of a joke or prank"},
{"r": 146, "w": "until one is blue in the face", "c": "不管说多少次，都不会改变事实或说服对方", "e": "to do something excessively or for a long time without achieving the desired outcome"},
{"r": 147, "w": "variety is the spice of life", "c": "多样化使生活更有趣、更充实", "e": "Having a diverse range of experiences or activities makes life more enjoyable or interesting"},
{"r": 148, "w": "your guess is as good as mine", "c": "我猜也不知道", "e": "Used when one does not know the answer to a question and is implying that nobody else knows either"},
{"r": 149, "w": "bring a knife to a gunfight", "c": "缺乏必要准备或能力与强大的对手竞争", "e": "to enter into a situation ill-prepared or at a disadvantage"},
{"r": 150, "w": "know which way the wind is blowing", "c": "理解当前形势或态势并做出相应的反应", "e": "to understand the current trends, opinions, or circumstances in order to be able to act appropriately or make advantageous decisions"},
{"r": 151, "w": "turnabout is fair play", "c": "以其人之道，还治其人之身", "e": ""},
{"r": 152, "w": "to thine own self be true", "c": "忠於自己", "e": ""},
{"r": 153, "w": "a problem shared is a problem halved", "c": "众人拾柴火焰高", "e": ""},
{"r": 154, "w": "a sorrow shared is a sorrow halved", "c": "快樂因分享而加倍，悲傷因分擔而减半", "e": ""},
{"r": 155, "w": "keep your nose to the grindstone", "c": "勤奋工作；专注于工作或任务", "e": "to work hard and diligently; to stay focused on tasks and not be easily distracted"},
{"r": 156, "w": "make a mountain out of a molehill", "c": "小题大做，把小事看得很严重", "e": "exaggerating or making a big deal out of something small or unimportant"},
{"r": 157, "w": "he who denied it supplied it", "c": "恶人先告状", "e": ""},
{"r": 158, "w": "failure to prepare is preparing to fail", "c": "没准备好，就准备失败", "e": ""},
{"r": 159, "w": "take time by the forelock", "c": "打铁趁热", "e": ""},
{"r": 160, "w": "ne'er cast a clout til may be out", "c": "春捂秋冻", "e": ""},
{"r": 161, "w": "forewarned is forearmed", "c": "有备则无患", "e": ""},
{"r": 162, "w": "when all is said and done", "c": "话虽如此，事实上", "e": "after considering all the facts or events; ultimately; in the final analysis"},
{"r": 163, "w": "the chickens come home to roost", "c": "罪有应得", "e": ""},
{"r": 164, "w": "well begun is half done", "c": "良好的开端是成功的一半", "e": ""},
{"r": 165, "w": "early to bed, early to rise, makes a man healthy, wealthy and wise", "c": "早睡早起身体好", "e": ""},
{"r": 166, "w": "the early bird gets the worm", "c": "早起的鸟儿有虫吃", "e": ""},
{"r": 167, "w": "you can't step in the same river twice", "c": "一个人不可能两次踏入同一条河流", "e": ""},
{"r": 168, "w": "a promise made is a promise kept", "c": "一言既出，驷马难追", "e": ""},
{"r": 169, "w": "it never rains but it pours", "c": "屋漏偏逢连夜雨", "e": ""},
{"r": 170, "w": "history repeats itself", "c": "重蹈覆辙", "e": ""},
{"r": 171, "w": "on the internet nobody knows you're a dog", "c": "在網際網路上，沒人知道你是一隻狗", "e": ""},
{"r": 172, "w": "no good deed ever goes unpunished", "c": "好心没好报", "e": ""},
{"r": 173, "w": "a leopard cannot change its spots", "c": "江山易改，本性难移", "e": ""},
{"r": 174, "w": "the pen is mightier than the sword", "c": "言大于剑", "e": ""},
{"r": 175, "w": "you win some, you lose some", "c": "胜败仍兵家常事", "e": ""},
{"r": 176, "w": "two wrongs don't make a right", "c": "冤冤相报何时了", "e": ""},
{"r": 177, "w": "it takes all sorts", "c": "林子大了，什么鸟都有", "e": ""},
{"r": 178, "w": "fine feathers make fine birds", "c": "人要衣装,佛要金装", "e": ""},
{"r": 179, "w": "one man's meat is another man's poison", "c": "甲之蜜糖，乙之砒霜", "e": ""},
{"r": 180, "w": "the best laid plans of mice and men often go awry", "c": "计划赶不上变化", "e": ""},
{"r": 181, "w": "that's the way it goes", "c": "無能為力", "e": ""},
{"r": 182, "w": "different strokes for different folks", "c": "萝卜青菜各有所爱", "e": ""},
{"r": 183, "w": "good artists copy, great artists steal", "c": "优秀艺术家模仿，伟大艺术家窃取", "e": ""},
{"r": 184, "w": "all's fair in love and war", "c": "在情场和战场上可以不择手段", "e": ""},
{"r": 185, "w": "when it rains, it pours", "c": "屋漏偏逢连夜雨", "e": ""},
{"r": 186, "w": "old habits die hard", "c": "江山易改本性难移", "e": ""},
{"r": 187, "w": "the road to hell is paved with good intentions", "c": "黄泉路上徒有好意多", "e": ""},
{"r": 188, "w": "great minds think alike", "c": "英雄所见略同", "e": ""},
{"r": 189, "w": "it takes all kinds", "c": "一种米养百样人", "e": ""},
{"r": 190, "w": "rules are made to be broken", "c": "制定规则是为了被打破的", "e": ""},
{"r": 191, "w": "if wishes were horses, beggars would ride", "c": "天上不会掉馅饼", "e": ""},
{"r": 192, "w": "people who live in glass houses shouldn't throw stones", "c": "莫揭他人短", "e": ""},
{"r": 193, "w": "speak of the devil and he appears", "c": "说曹操，曹操就到", "e": ""},
{"r": 194, "w": "he who digs a pit for others falls in himself", "c": "害人先害己", "e": ""},
{"r": 195, "w": "there are two sides to every story", "c": "凡事有两面", "e": ""},
{"r": 196, "w": "he that mischief hatches, mischief catches", "c": "害人者终将害己", "e": ""},
{"r": 197, "w": "little pitchers have big ears", "c": "隔牆有耳", "e": ""},
{"r": 198, "w": "scientia potentia est", "c": "知識就是力量", "e": ""},
{"r": 199, "w": "many hands make light work", "c": "人多好办事", "e": ""},
{"r": 200, "w": "like mother, like daughter", "c": "有其母必有其女", "e": ""},
{"r": 201, "w": "bad news travels fast", "c": "坏事传千里", "e": ""},
{"r": 202, "w": "the course of true love never did run smooth", "c": "真爱无坦途", "e": ""},
{"r": 203, "w": "eat, drink and be merry for tomorrow we die", "c": "人生苦短，及时行乐", "e": ""},
{"r": 204, "w": "the wolf may lose his teeth but never his nature", "c": "江山易改本性难移", "e": ""},
{"r": 205, "w": "it's an ill bird that fouls its own nest", "c": "家丑不可外扬", "e": ""},
{"r": 206, "w": "when the cat's away the mice will play", "c": "山中无老虎，猴子称大王", "e": ""},
{"r": 207, "w": "there is strength in numbers", "c": "众志成城", "e": ""},
{"r": 208, "w": "practice makes perfect", "c": "熟能生巧", "e": ""},
{"r": 209, "w": "what doesn't kill you makes you stronger", "c": "艰难困苦，玉汝于成", "e": ""},
{"r": 210, "w": "wherever you go, there you are", "c": "逃的了一时，逃不了一世", "e": ""},
{"r": 211, "w": "every silver lining has a cloud", "c": "黑暗中总有一线光明", "e": ""},
{"r": 212, "w": "two's company and three is none", "c": "两人成伴，三人不欢", "e": ""},
{"r": 213, "w": "you can't unring a bell", "c": "覆水难收", "e": ""},
{"r": 214, "w": "play stupid games, win stupid prizes", "c": "自作自受", "e": ""},
{"r": 215, "w": "one bad turn deserves another", "c": "恶有恶报", "e": ""},
{"r": 216, "w": "once bitten, twice shy", "c": "一朝被蛇咬，十年怕井绳", "e": ""},
{"r": 217, "w": "garbage in, garbage out", "c": "垃圾进，垃圾出", "e": ""},
{"r": 218, "w": "you're never too old to learn", "c": "活到老，学到老", "e": ""},
{"r": 219, "w": "as you make your bed, so you must lie in it", "c": "自食其果", "e": ""},
{"r": 220, "w": "when the cat's away", "c": "山中无老虎，猴子称大王", "e": ""},
{"r": 221, "w": "in the land of the blind, the one-eyed man is king", "c": "矮子里面挑将军", "e": ""},
{"r": 222, "w": "a new broom sweeps clean", "c": "新官上任三把火", "e": ""},
{"r": 223, "w": "every stick has two ends", "c": "河有两岸，事有两面", "e": ""},
{"r": 224, "w": "the grass is always greener on the other side", "c": "外国的月亮比较圆", "e": ""},
{"r": 225, "w": "money can't buy happiness", "c": "金錢買不到幸福", "e": ""},
{"r": 226, "w": "you can't take it with you", "c": "浮生若梦", "e": ""},
{"r": 227, "w": "it takes two to make a quarrel", "c": "一個巴掌拍不響", "e": ""},
{"r": 228, "w": "nothing ventured, nothing gained", "c": "不入虎穴，焉得虎子", "e": ""},
{"r": 229, "w": "faint heart never won fair lady", "c": "一分耕耘才有一分收获", "e": ""},
{"r": 230, "w": "no guts, no glory", "c": "若要功夫深，铁杵磨成针", "e": ""},
{"r": 231, "w": "clogs to clogs in three generations", "c": "富不过三代", "e": ""},
{"r": 232, "w": "heaven helps those who help themselves", "c": "天道酬勤", "e": ""},
{"r": 233, "w": "slow and steady wins the race", "c": "从容不迫，胜券在握", "e": ""},
{"r": 234, "w": "when the going gets tough, the tough get going", "c": "艱難之路，唯勇者行", "e": ""},
{"r": 235, "w": "charity begins at home", "c": "博爱始于家门", "e": ""},
{"r": 236, "w": "tomorrow never comes", "c": "我生待明日,万事成蹉跎", "e": ""},
{"r": 237, "w": "a buck's a buck", "c": "一分钱也是钱", "e": ""},
{"r": 238, "w": "a journey of a thousand miles begins with a single step", "c": "千里之行始于足下", "e": ""},
{"r": 239, "w": "when in rome, do as the romans do", "c": "入乡随俗", "e": ""},
{"r": 240, "w": "if the mountain won't come to muhammad", "c": "山不过来，我就过去", "e": ""},
{"r": 241, "w": "there is no such thing as bad weather, only bad clothing", "c": "沒有所謂的壞天氣只有軟弱的人", "e": ""},
{"r": 242, "w": "faith will move mountains", "c": "精诚所至，金石为开", "e": ""},
{"r": 243, "w": "squeaky wheel gets the grease", "c": "早起的鳥兒有蟲吃", "e": ""},
{"r": 244, "w": "the more you know, the higher you go", "c": "学习使人进步", "e": ""},
{"r": 245, "w": "when life gives you lemons, make lemonade", "c": "随遇而安，苦中作乐", "e": ""},
{"r": 246, "w": "the wheel turns", "c": "时移世易", "e": ""},
{"r": 247, "w": "don't count your chickens before they're hatched", "c": "别高兴地太早", "e": ""},
{"r": 248, "w": "everything happens for a reason", "c": "万事皆有因", "e": ""},
{"r": 249, "w": "eat to live, not live to eat", "c": "吃饭是为了活着，但活着不是为了吃饭", "e": ""},
{"r": 250, "w": "man proposes, god disposes", "c": "謀事在人，成事在天", "e": ""},
{"r": 251, "w": "self-praise is no recommendation", "c": "自夸不足为自荐", "e": ""},
{"r": 252, "w": "what's done is done", "c": "木已成舟, 覆水难收", "e": ""},
{"r": 253, "w": "you can't be half pregnant", "c": "非黑即白", "e": ""},
{"r": 254, "w": "give them an inch and they'll take an ell", "c": "得寸進尺", "e": ""},
{"r": 255, "w": "there's no accounting for taste", "c": "各花入各眼", "e": ""},
{"r": 256, "w": "haste makes waste", "c": "欲速則不達", "e": ""},
{"r": 257, "w": "there's no i in team", "c": "團隊裏沒有個我", "e": ""},
{"r": 258, "w": "he who hesitates is lost", "c": "举棋不定，坐失良机", "e": ""},
{"r": 259, "w": "little strokes fell great oaks", "c": "水滴石穿", "e": ""},
{"r": 260, "w": "there's no time like the present", "c": "择日不如撞日", "e": ""},
{"r": 261, "w": "eye for an eye, a tooth for a tooth", "c": "以眼還眼，以牙還牙", "e": ""},
{"r": 262, "w": "if you find yourself in a hole, the first thing to do is stop digging", "c": "及时止损", "e": ""},
{"r": 263, "w": "don't get mad, get even", "c": "持其志，无暴其气", "e": ""},
{"r": 264, "w": "fall seven times, stand up eight", "c": "跌倒了就站起来", "e": ""},
{"r": 265, "w": "work smarter, not harder", "c": "事半功倍", "e": ""},
{"r": 266, "w": "cobbler, keep to your last", "c": "不要班门弄斧", "e": ""},
{"r": 267, "w": "there's no point crying over spilt milk", "c": "覆水难收，事成定局", "e": ""},
{"r": 268, "w": "cross my heart and hope to die, stick a needle in my eye", "c": "撒谎不得好死", "e": ""},
{"r": 269, "w": "time heals all wounds", "c": "时间是治愈一切的良药", "e": ""},
{"r": 270, "w": "pressure makes diamonds", "c": "没有压力就没有动力", "e": ""},
{"r": 271, "w": "fortune favors the bold", "c": "天助勇者", "e": ""},
{"r": 272, "w": "one nail drives out another", "c": "长江后浪拍前浪", "e": ""},
{"r": 273, "w": "fool me once, shame on you; fool me twice, shame on me", "c": "騙我一次，你可恥. 騙我兩次，只能怪我自己", "e": ""},
{"r": 274, "w": "opportunity knocks at every man's door", "c": "风水轮流转", "e": ""},
{"r": 275, "w": "familiarity breeds contempt", "c": "親不敬，熟生蔑", "e": ""},
{"r": 276, "w": "man plans and god laughs", "c": "计划赶不上变化", "e": ""},
{"r": 277, "w": "pride comes before a fall", "c": "骄兵必败", "e": ""},
{"r": 278, "w": "the darkest hour is just before the dawn", "c": "黑暗即將過去，黎明就在眼前", "e": ""},
{"r": 279, "w": "a bad workman always blames his tools", "c": "不会撑船怪河弯", "e": ""},
{"r": 280, "w": "a smooth sea never made a skilled sailor", "c": "不经历风雨怎能见彩虹", "e": ""},
{"r": 281, "w": "fine words butter no parsnips", "c": "花言巧语没有用", "e": ""},
{"r": 282, "w": "needs must when the devil drives", "c": "形势所迫不得不为", "e": ""},
{"r": 283, "w": "the nut does not fall far from the tree", "c": "有其父必有其子", "e": ""},
{"r": 284, "w": "manners maketh man", "c": "观其待人而知其人", "e": ""},
{"r": 285, "w": "shirtsleeves to shirtsleeves in three generations", "c": "富不过三代", "e": ""},
{"r": 286, "w": "a burnt child dreads the fire", "c": "一朝被蛇咬,十年怕井绳", "e": ""},
{"r": 287, "w": "you can't keep a good man down", "c": "好人自有出头日", "e": ""},
{"r": 288, "w": "it's the thought that counts", "c": "礼轻情意重", "e": ""},
{"r": 289, "w": "one can run but one can't hide", "c": "跑的了和尚跑不了庙", "e": ""},
{"r": 290, "w": "in for an inch, in for a mile", "c": "得寸進尺", "e": ""},
{"r": 291, "w": "might makes right", "c": "强权即公理", "e": ""},
{"r": 292, "w": "you can't teach an old dog new tricks", "c": "江山易改，本性难移", "e": ""},
{"r": 293, "w": "loose lips sink ships", "c": "言多必失", "e": ""},
{"r": 294, "w": "if you lie down with dogs, you get up with fleas", "c": "近朱者赤，近墨者黑", "e": ""},
{"r": 295, "w": "you can't judge a book by its cover", "c": "不要以貌取人", "e": ""},
{"r": 296, "w": "you can lead a horse to water, but you can't make it drink", "c": "强扭的瓜不甜", "e": ""},
{"r": 297, "w": "if you fly with the crows, you get shot with the crows", "c": "同流合污", "e": ""},
{"r": 298, "w": "good work ain't cheap, cheap work ain't good", "c": "便宜没好货", "e": ""},
{"r": 299, "w": "genius is one percent inspiration, ninety-nine percent perspiration", "c": "天才是1%的天分加上99%的努力", "e": ""},
{"r": 300, "w": "rules are rules", "c": "规则就是规则", "e": ""},
{"r": 301, "w": "short reckonings make long friends", "c": "亲兄弟明算账", "e": ""},
{"r": 302, "w": "in vino veritas", "c": "酒后吐真言", "e": ""},
{"r": 303, "w": "you pays your money and you takes your choice", "c": "自己選擇自己承擔後果", "e": ""},
{"r": 304, "w": "uneasy lies the head that wears a crown", "c": "高处不胜寒", "e": ""},
{"r": 305, "w": "mess with the bull and you get the horns", "c": "没事别惹事", "e": ""},
{"r": 306, "w": "what the eye doesn't see, the heart doesn't grieve over", "c": "眼不见为净", "e": ""},
{"r": 307, "w": "he who laughs last laughs best", "c": "笑到最后，笑得最好", "e": ""},
{"r": 308, "w": "the cow knows not the worth of its tail till it loses it", "c": "失去才知道珍惜", "e": ""},
{"r": 309, "w": "words cut deep", "c": "口是伤人斧，言是割舌刀", "e": ""},
{"r": 310, "w": "keep your friends close, and your enemies closer", "c": "要親近朋友，但要更親近你的敵人", "e": ""},
{"r": 311, "w": "too many cooks spoil the broth", "c": "人多手杂", "e": ""},
{"r": 312, "w": "don't put all your eggs in one basket", "c": "把雞蛋放在同一個籃子裡", "e": ""},
{"r": 313, "w": "more haste, less speed", "c": "欲速则不达", "e": ""},
{"r": 314, "w": "extraordinary claims require extraordinary evidence", "c": "超凡主張須有超凡證據", "e": ""},
{"r": 315, "w": "when you find yourself in a hole, the first thing to do is stop digging", "c": "及时止损", "e": ""},
{"r": 316, "w": "fools rush in where angels fear to tread", "c": "智者裹足不前，愚者铤而走险", "e": ""},
{"r": 317, "w": "success depends on your backbone, not your wishbone", "c": "一分耕耘，一分收获", "e": ""},
{"r": 318, "w": "lucky at cards, unlucky in love", "c": "赌场得意,情场失意", "e": ""},
{"r": 319, "w": "opportunity seldom knocks twice", "c": "过了这个村就没这个店", "e": ""},
{"r": 320, "w": "necessity knows no law", "c": "铤而走险", "e": ""},
{"r": 321, "w": "where you stand depends on where you sit", "c": "位置决定立场", "e": ""},
{"r": 322, "w": "a fault confessed is half redressed", "c": "浪子回头金不换", "e": ""},
{"r": 323, "w": "there are two sides to every question", "c": "公说公有理，婆说婆有理", "e": ""},
{"r": 324, "w": "a lie has no legs", "c": "谎言站不长", "e": ""},
{"r": 325, "w": "the end justifies the means", "c": "为达目的，不择手段", "e": ""},
{"r": 326, "w": "desperate times call for desperate measures", "c": "非常時期要用非常手段", "e": ""},
{"r": 327, "w": "one swallow does not a summer make", "c": "一隻燕子飛來了，並不代表夏天已經來臨", "e": ""},
{"r": 328, "w": "life is like a box of chocolates", "c": "世事无常", "e": ""},
{"r": 329, "w": "as the twig is bent, so is the tree inclined", "c": "作为嫩枝时被弄弯，长成小树时就会倾斜", "e": ""},
{"r": 330, "w": "a danger foreseen is half avoided", "c": "防患于未然", "e": ""},
{"r": 331, "w": "you can't make a silk purse of a sow's ear", "c": "朽木不可雕也", "e": ""},
{"r": 332, "w": "crime doesn't pay", "c": "天网恢恢，疏而不漏", "e": ""},
{"r": 333, "w": "the fish rots from the head", "c": "上樑不正下樑歪", "e": ""},
{"r": 334, "w": "the apple does not fall far from the tree", "c": "有其父必有其子", "e": ""},
{"r": 335, "w": "physician, heal thyself", "c": "泥菩萨过江，自身难保", "e": ""},
{"r": 336, "w": "forbidden fruit is the sweetest", "c": "禁果分外甜", "e": ""},
{"r": 337, "w": "beggars can't be choosers", "c": "唯命是从", "e": ""},
{"r": 338, "w": "looks can be deceiving", "c": "外表可能会骗人", "e": ""},
{"r": 339, "w": "a man is known by the company he keeps", "c": "观其友知其人", "e": ""},
{"r": 340, "w": "handsome is as handsome does", "c": "相逐心生", "e": ""},
{"r": 341, "w": "hindsight is 20/20", "c": "事后诸葛亮", "e": ""},
{"r": 342, "w": "opportunity makes a thief", "c": "财不露白", "e": ""},
{"r": 343, "w": "you can't put an old head on young shoulders", "c": "姜还是老的辣", "e": ""},
{"r": 344, "w": "love the sinner, hate the sin", "c": "厭惡罪惡本身，關愛犯罪的人", "e": ""},
{"r": 345, "w": "appearances are deceptive", "c": "人不可貌相", "e": ""},
{"r": 346, "w": "better the devil you know than the devil you don't know", "c": "明枪易躲,暗箭难防", "e": ""},
{"r": 347, "w": "there's many a good tune played on an old fiddle", "c": "老当益壮", "e": ""},
{"r": 348, "w": "yesterday is gone", "c": "昨日已逝", "e": ""},
{"r": 349, "w": "good things come to those who wait", "c": "精诚所至，金石为开", "e": ""},
{"r": 350, "w": "location, location, location", "c": "位置,位置,位置", "e": ""},
{"r": 351, "w": "the voice of the people, the voice of god", "c": "人民的利益高于一切", "e": ""},
{"r": 352, "w": "you can't fix stupid", "c": "无药可救", "e": ""},
{"r": 353, "w": "who keeps company with the wolf will learn to howl", "c": "近朱者赤,近墨者黑", "e": ""},
{"r": 354, "w": "every man has a price", "c": "有钱能使鬼推磨", "e": ""},
{"r": 355, "w": "the mills of the gods grind slowly", "c": "天網恢恢，疏而不漏", "e": ""},
{"r": 356, "w": "give him enough rope and he'll hang himself", "c": "授繩與愚，愚能自縛", "e": ""},
{"r": 357, "w": "rome wasn't built in a day", "c": "冰冻三尺非一日之寒，滴水石穿非一日之功", "e": ""},
{"r": 358, "w": "you buy cheap, you get cheap", "c": "一分钱一分货", "e": ""},
{"r": 359, "w": "big things come in small packages", "c": "浓缩的都是精品", "e": ""},
{"r": 360, "w": "mighty oaks from little acorns grow", "c": "合抱之木生於毫末", "e": ""},
{"r": 361, "w": "the real treasure is the friends we made along the way", "c": "人之相識，貴在相知", "e": ""},
{"r": 362, "w": "history is written by the victors", "c": "成王敗寇", "e": ""},
{"r": 363, "w": "in like a lion, out like a lamb", "c": "三月天，孩儿脸，说变就变", "e": ""},
{"r": 364, "w": "if ifs and buts were candy and nuts, we'd all have a merry christmas", "c": "白日做梦", "e": ""},
{"r": 365, "w": "one man's trash is another man's treasure", "c": "彼之砒霜，吾之蜜糖", "e": ""},
{"r": 366, "w": "walls have ears", "c": "隔牆有耳", "e": ""},
{"r": 367, "w": "sow the wind, reap the whirlwind", "c": "恶有恶报", "e": ""},
{"r": 368, "w": "what's done cannot be undone", "c": "木已成舟", "e": ""},
{"r": 369, "w": "it ain't over 'til the fat lady sings", "c": "鹿死誰手尚未可知", "e": ""},
{"r": 370, "w": "in unity, there is strength", "c": "团结就是力量", "e": ""},
{"r": 371, "w": "you can't go home again", "c": "往事只能回味", "e": ""},
{"r": 372, "w": "another day, another dollar", "c": "做一天和尚撞一天钟", "e": ""},
{"r": 373, "w": "that's the way the cookie crumbles", "c": "人生不如意十之八九", "e": ""},
{"r": 374, "w": "all's well that ends well", "c": "皆大欢喜", "e": ""},
{"r": 375, "w": "it takes all kinds to make a world", "c": "世界之大，無奇不有", "e": ""},
{"r": 376, "w": "a fool and his money are soon parted", "c": "愚者与金钱很快就会分手", "e": "Someone who is foolish with their money will quickly lose it."},
{"r": 377, "w": "a house divided against itself cannot stand", "c": "家庭、群体、团队内部不团结，很难成功或持久", "e": "internal conflict within a group or organization will lead to its downfall"},
{"r": 378, "w": "a leopard can't change his spots", "c": "金矿再怎么催也不会变钢铁。形容人的根本性格很难改变", "e": "Someone cannot change their basic nature or character."},
{"r": 379, "w": "a picture is worth a thousand words", "c": "一幅画胜过千言万语", "e": "An image can convey a complex idea or emotion more effectively than a written description."},
{"r": 380, "w": "a stitch in time saves nine", "c": "及时处理问题，可以避免更大的麻烦或损失", "e": "Taking prompt action to solve a problem or address an issue can prevent greater problems or issues in the future."},
{"r": 381, "w": "a watched pot never boils", "c": "过于焦虑等待某事并不会使其更快发生", "e": "when you are waiting for something to happen, it seems to take a very long time"},
{"r": 382, "w": "a woman's work is never done", "c": "婦女的工作永遠完不成", "e": "to suggest that there is always more work or responsibilities for women, emphasizing the perception that women have a larger workload compared to men"},
{"r": 383, "w": "absence makes the heart grow fonder", "c": "物以稀为贵", "e": "the feeling of affection or longing for someone or something increases when they are absent or distant"},
{"r": 384, "w": "all cats are grey in the dark", "c": "暗中看来，所有的猫都是灰色的", "e": "when it is not possible to see or perceive differences, appearances or distinctions become irrelevant"},
{"r": 385, "w": "all in a day's work", "c": "习以为常；不足为奇", "e": "something that is expected or typical; a task or situation that is a normal part of one's job or responsibilities"},
{"r": 386, "w": "all that glitters is not gold", "c": "闪光的不一定都是金子", "e": "to be cautious of appearances, as things may not be as good as they seem"},
{"r": 387, "w": "an englishman's home is his castle", "c": "一个人的家是他的庇护所", "e": "one's home is a private and protected space where they have control and authority"},
{"r": 388, "w": "an apple a day keeps the doctor away", "c": "每天吃一个苹果，远离医生", "e": "Regular consumption of healthy habits can help maintain good health and prevent illnesses."},
{"r": 389, "w": "be a barrel of laughs", "c": "令人开心或有趣的人或事物", "e": "to be humorous or entertaining"},
{"r": 390, "w": "blood is thicker than water", "c": "血浓于水", "e": "Family bonds are stronger than other social relationships"},
{"r": 391, "w": "build castles in the air", "c": "白日做梦、空中楼阁", "e": "to have unrealistic or impractical dreams or plans"},
{"r": 392, "w": "burn candles at both ends", "c": "过度地工作或过度地消耗资源", "e": "to exhaust or deplete one's energy or resources by working or staying up late on both ends of the day"},
{"r": 393, "w": "burn the candle at both ends", "c": "过度努力工作或玩乐，导致身体或精神疲劳", "e": "to work or party late into the night and then get up early in the morning, not allowing enough time for rest"},
{"r": 394, "w": "burn the candle at both the ends", "c": "过度劳累或过度使用自己的资源，通常指同时从事太多的活动或工作", "e": "to overwork or exhaust oneself by doing too much or staying up too late"},
{"r": 395, "w": "can't stand the sight of", "c": "无法忍受看到某人或某物的存在", "e": "strongly dislike or be unable to tolerate someone or something"},
{"r": 396, "w": "cannot stomach someone or something", "c": "无法忍受某人或某事", "e": "to dislike or have an aversion to someone or something"},
{"r": 397, "w": "chickens come home to roost", "c": "恶果自作自受、坏事有报应", "e": "consequences or negative actions will eventually catch up to a person"},
{"r": 398, "w": "children should be seen and not heard", "c": "孩子应该只露面而不发声", "e": "children should be quiet and not speak unless spoken to"},
{"r": 399, "w": "come down on somebody like a ton of bricks", "c": "严厉地批评或责罚某人", "e": "to criticize or punish someone severely"},
{"r": 400, "w": "come up smelling of roses", "c": "无论发生什么事都能成功或正面收场", "e": "to emerge from a difficult situation with success or a positive outcome"},
{"r": 401, "w": "count one's chickens before they hatch", "c": "过早预料成功或结果", "e": "to make plans or have expectations based on a future event that may not actually happen"},
{"r": 402, "w": "devil finds work for idle hands to do", "c": "懒人易遭魔鬼勾引", "e": "Idle people often find themselves involved in mischievous activities or trouble."},
{"r": 403, "w": "don't beat a dead horse", "c": "不要浪费时间或精力在无用的事情上", "e": "to stop wasting time or effort on something that is already resolved or ineffective"},
{"r": 404, "w": "don't bite the hand that feeds you", "c": "不要恩将仇报; 不要伤害帮助你的人", "e": "to not harm or criticize someone who helps or supports you"},
{"r": 405, "w": "don't count your chickens before they hatch", "c": "不要过早地预计或确信某件事情会发生或成功", "e": "to not make plans or be overly confident about a situation that is uncertain or has not yet happened"},
{"r": 406, "w": "don't cry over spilt milk", "c": "别为不能挽回的事后悔或难过", "e": "to not worry or be upset about something that has already happened and cannot be changed"},
{"r": 407, "w": "don't give up the day job", "c": "不要放弃现有工作", "e": "This is not your area of expertise or talent"},
{"r": 408, "w": "don't give up your day job", "c": "别放弃你的正职工作", "e": "to continue with your current profession or occupation because attempting something else may not be successful"},
{"r": 409, "w": "don't look a gift horse in the mouth", "c": "别对送来的礼物过分挑剔，应该心存感激", "e": "to not question or criticize something that is given as a gift or is available for free"},
{"r": 410, "w": "elvis has left the building", "c": "表演结束；该离开了", "e": "It's all over, there's nothing more to see or do"},
{"r": 411, "w": "every dog has his day", "c": "每个人都有自己的得意时刻", "e": "Everyone gets their moment of success or happiness at some point in their life"},
{"r": 412, "w": "every dog has its day", "c": "每个人都会有成功的时刻，不管他们目前处于什么困境或失败", "e": "someone who has been successful or famous in the past but is no longer"},
{"r": 413, "w": "every man has his price", "c": "每个人都有自己的价格", "e": "everyone can be bought or persuaded under the right conditions"},
{"r": 414, "w": "fall head over heels for someone", "c": "完全地、深深地迷恋上某人", "e": "to fall deeply and completely in love with someone"},
{"r": 415, "w": "forbidden fruit is always the sweetest", "c": "被禁止的事物总是最甜美的", "e": "something that is attractive or appealing because it is prohibited or off-limits"},
{"r": 416, "w": "give him an inch and he'll take a mile", "c": "给他一寸，他会得寸进尺", "e": "to give someone a small amount of freedom or leeway and for them to take advantage of it by pushing boundaries and taking much more"},
{"r": 417, "w": "give your eye teeth for something", "c": "非常渴望某物；不惜付出任何代价得到某物", "e": "to be willing to give up something of great value in order to obtain or achieve something else"},
{"r": 418, "w": "good fences make good neighbors", "c": "良好的分界线可以保持友好邻居关系", "e": "To have clear boundaries or limits in a relationship or community results in better and more peaceful relationships"},
{"r": 419, "w": "grass is greener on the other side", "c": "对事物的观念呈现出被过分理想化或不切实际的状态", "e": "to believe that the situation or circumstances of someone else are better or more desirable than one's own"},
{"r": 420, "w": "have a foot in both camps", "c": "在两个阵营都有所涉足或参与的状态", "e": "to be involved or associated with opposing groups or sides; to have conflicting opinions or loyalties"},
{"r": 421, "w": "have ants in your pants", "c": "坐立不安或焦躁不安", "e": "to be restless or fidgety"},
{"r": 422, "w": "have bigger fish to fry", "c": "有更重要的事情要做；有更紧迫的问题需要解决", "e": "to have more important or pressing matters to attend to"},
{"r": 423, "w": "have friends in high places", "c": "与有权势或有影响力的人保持友好关系", "e": "Have powerful or influential connections"},
{"r": 424, "w": "have never had it so good", "c": "过得从未如此美好", "e": "to be experiencing a period of great success or good fortune"},
{"r": 425, "w": "have someone by the short and curlies", "c": "完全掌握某人，使某人陷入无法逃脱的困境或境地", "e": "to have complete control or power over someone, often with the ability to manipulate or coerce them"},
{"r": 426, "w": "have someone's guts for garters", "c": "极度生气或愤怒，想要严厉惩罚某人", "e": "to be extremely angry with someone and want to punish them severely"},
{"r": 427, "w": "have the hots for someone", "c": "对某人有强烈的欲望或爱慕", "e": "to feel a strong sexual or romantic attraction towards someone"},
{"r": 428, "w": "have time on your hands", "c": "时间多得没有事可干", "e": "having extra time available; not being busy or occupied"},
{"r": 429, "w": "have your head in the clouds", "c": "沉迷于幻想或不切实际的想法，不注重眼前的现实", "e": "to be daydreaming or not paying attention; to be unrealistic or impractical"},
{"r": 430, "w": "he has bigger fish to fry", "c": "他有更重要的事情要处理", "e": "to have more important or pressing matters to attend to; to be preoccupied with other tasks or concerns"},
{"r": 431, "w": "i can't be doing with it", "c": "我受不了它", "e": "to have no tolerance or patience for something"},
{"r": 432, "w": "i can't put a name to someone", "c": "我无法想起某人的名字", "e": "to be unable to remember or recall someone's name"},
{"r": 433, "w": "idle hands are the devil's tools", "c": "虚度光阴容易做坏事", "e": "being idle or having nothing to do can lead to mischief or trouble"},
{"r": 434, "w": "if it's the last thing i do", "c": "无论如何，即使是最后一件事我也要做到", "e": "to express a strong determination to do something, even if it is the final thing one accomplishes or the very last effort one makes"},
{"r": 435, "w": "it has someone's name on it", "c": "这是为某人准备的；适合某人", "e": "it is specifically intended for or destined for someone"},
{"r": 436, "w": "it is a poor workman who blames his tools", "c": "埋怨工具不好的人是差劲的工人", "e": "An incompetent person will often make excuses or shift blame onto their tools or equipment rather than admitting their own lack of skill."},
{"r": 437, "w": "it is always darkest before the dawn", "c": "黎明前总是最黑暗的", "e": "difficult times often come right before things get better"},
{"r": 438, "w": "it takes one to know one", "c": "看过光自己也以为别人都是同样的人", "e": "someone who possesses a certain negative quality or behavior can easily recognize that same quality or behavior in others"},
{"r": 439, "w": "keep up with the joneses", "c": "攀比，竭力迎合别人的标准或生活方式", "e": "to strive to match or exceed the lifestyle or possessions of one's neighbors or peers"},
{"r": 440, "w": "keep your friends close and your enemies closer", "c": "与朋友保持亲近，与敌人保持更亲近", "e": "Be vigilant and maintain a close watch on people who may pose a threat to you, as they may be harder to defeat if you underestimate them."},
{"r": 441, "w": "kill the goose that lays the golden egg", "c": "杀鸡取卵", "e": "to destroy a valuable or profitable resource out of greed or short-sightedness"},
{"r": 442, "w": "kill the goose that lays the golden eggs", "c": "杀了下金蛋的鹅", "e": "to destroy a valuable or beneficial resource or opportunity in pursuit of immediate gain"},
{"r": 443, "w": "lock the stable door after the horse has bolted", "c": "亡羊补牢", "e": "to take precautions or preventive measures after damage has already been done"},
{"r": 444, "w": "make a pig's ear of", "c": "把事情搞得一团糟", "e": "to completely mess up or botch something"},
{"r": 445, "w": "make hay while the sun shines", "c": "趁着有机会或有利条件做事", "e": "to take advantage of an opportunity while it is available"},
{"r": 446, "w": "man cannot live by bread alone", "c": "不能只靠满足基本需要来过好生活；需要其他事物或经验来达到幸福和满足", "e": "Contrary to the popular belief that physical needs are the only requirements for survival, humans also need intellectual, emotional, and spiritual nourishment."},
{"r": 447, "w": "man's home is his castle", "c": "一个人的家就是他的堡垒", "e": "to emphasize the belief that a person's home is their own private space and they have control over it"},
{"r": 448, "w": "money doesn't grow on trees", "c": "金钱不会从树上长出来", "e": "money is not easily obtained or readily available"},
{"r": 449, "w": "not have a cat in hell's chance", "c": "没有一点成功的机会或可能性", "e": "To have no chance at all; to have no hope of success"},
{"r": 450, "w": "not have a snowball's chance in hell", "c": "毫無成功機會；毫無可能成功之可能性", "e": "to have no chance at all, to have no possibility of success"},
{"r": 451, "w": "not know you are born", "c": "不知道自己幸福在哪里", "e": "to be ignorant or unappreciative of how fortunate one is"},
{"r": 452, "w": "not to be sneezed at", "c": "不可小视的；不容忽视的", "e": "worthy of attention or consideration; not to be disregarded or underestimated"},
{"r": 453, "w": "nothing is certain but death and taxes", "c": "死亡和税费是确凿无疑的事情，其他一切都是不确定的", "e": "there are only two things that are inevitable or guaranteed in life"},
{"r": 454, "w": "one cannot love and be wise", "c": "一心不能二用", "e": "one cannot be in love and think logically or make rational decisions"},
{"r": 455, "w": "one good turn deserves another", "c": "以德报德；善有善报", "e": "an act of kindness should be reciprocated with another act of kindness"},
{"r": 456, "w": "possession is nine points of the law", "c": "拥有物品的人通常在法律纠纷中占据优势地位", "e": "Whoever physically possesses an item is presumed to be the rightful owner"},
{"r": 457, "w": "rome was not built in one day", "c": "罗马不是一天建成的", "e": "It takes time and effort to accomplish something big or significant."},
{"r": 458, "w": "run with the hare and hunt with the hounds", "c": "左右为难；两面讨好", "e": "to support or be involved with two opposing sides or ideas at the same time"},
{"r": 459, "w": "stand up and be counted", "c": "挺身而出，勇于表明自己的立场，尤其是在困难或危险的情况下", "e": "to publicly express one's opinion or beliefs, especially in a situation where it is important or necessary to do so"},
{"r": 460, "w": "sure as eggs is eggs", "c": "肯定，毫无疑问", "e": "absolutely certain or true, without a doubt"},
{"r": 461, "w": "tell tales out of school", "c": "泄露秘密", "e": "to disclose private or confidential information or secrets"},
{"r": 462, "w": "that makes two of us", "c": "我也是一个（同样的情况或意见）", "e": "the same is true for me; I feel the same way"},
{"r": 463, "w": "the ball is in somebody's court", "c": "這取決於某人的決定或行動", "e": "the responsibility or decision is now someone else's to handle"},
{"r": 464, "w": "the ball is in someone's court", "c": "握在某人手上，由某人来决定或采取行动", "e": "the responsibility or decision is now in someone else's hands"},
{"r": 465, "w": "the bigger they are the harder they fall", "c": "越大越容易摔倒", "e": "Used to express that powerful or influential people are more vulnerable to a great downfall or failure."},
{"r": 466, "w": "the devil is in the details", "c": "细节决定成败", "e": "Difficulties or problems are often hidden in the small details, so it is important to pay close attention to them."},
{"r": 467, "w": "the grass is always greener", "c": "眼红别人的事物，总认为自己没有的东西更好", "e": "the belief that other people's situation or possessions are always better than one's own"},
{"r": 468, "w": "the squeaky wheel gets the grease", "c": "喧哗的轮子得到了油脂", "e": "the person who complains the loudest or most frequently is the one who receives the most attention or assistance"},
{"r": 469, "w": "the wheels have come off", "c": "情况发生了意想不到的错误或失败", "e": "Things have gone wrong; a plan or situation has failed"},
{"r": 470, "w": "there are clouds on the horizon", "c": "有不好的迹象或问题即将发生", "e": "there are signs of trouble or a problem approaching in the future"},
{"r": 471, "w": "there are other fish in the sea", "c": "世界上还有其他的机会或选择", "e": "\"there are other options or opportunities available\" (usually in the context of relationships or opportunities)"},
{"r": 472, "w": "there is honor among thieves", "c": "盗贼中也有诚实人", "e": "even dishonest or corrupt individuals can still have a code of conduct or a sense of loyalty"},
{"r": 473, "w": "til the cows come home", "c": "无限期地、无休止地、很久地、永远地", "e": "for a very long time, indefinitely"},
{"r": 474, "w": "till the cows come home", "c": "一直到非常晚的时间点", "e": "for a very long time; indefinitely"},
{"r": 475, "w": "time flies when you're having fun", "c": "快乐的时候时间过得飞快", "e": "time seems to pass quickly when you are enjoying yourself"},
{"r": 476, "w": "two heads are better than one", "c": "两人共同思考比一个人更好", "e": "It is beneficial to have the input or assistance of another person when trying to solve a problem or make a decision."},
{"r": 477, "w": "until the cows come home", "c": "直到很晚（常指深夜或凌晨），很久很久", "e": "for a very long time; indefinitely"},
{"r": 478, "w": "we'll cross that bridge when we come to it", "c": "过河拆桥；来日方长，一切都会水落石出", "e": "We will deal with that problem when it happens, not before then"},
{"r": 479, "w": "what goes around comes around", "c": "因果报应", "e": "the consequences of your actions will come back to you at some point in the future"},
{"r": 480, "w": "when push comes to shove", "c": "当情况变得紧要时，当无法避免时", "e": "when a situation becomes difficult or when action needs to be taken"},
{"r": 481, "w": "when the chips are down", "c": "在最困难的时刻或最关键的时候", "e": "when a situation becomes difficult or challenging; when one is facing adversity or a crisis"},
{"r": 482, "w": "who pays the piper calls the tune", "c": "谁付钱就有权决定", "e": "the person who provides the money for something gets to make the decisions and control how it is done"},
{"r": 483, "w": "work your fingers to the bone", "c": "辛勤工作或努力到筋疲力尽", "e": "to work extremely hard or tirelessly"},
{"r": 484, "w": "you are what you eat", "c": "吃什么长什么", "e": "Your physical health and well-being are influenced by your diet and the food you consume."},
{"r": 485, "w": "you can't have your cake and eat it", "c": "鱼与熊掌不可兼得", "e": "you can't have everything your way; you can't have two desirable things that are mutually exclusive"},
{"r": 486, "w": "you can't have your cake and eat it too", "c": "不可以两全其美", "e": "you can't have the best of both worlds; you can't have it both ways; you can't have or do two desirable things at the same time"},
{"r": 487, "w": "you can't make an omelet without breaking some eggs", "c": "没有付出牺牲就无法取得成果", "e": "you can't achieve something great without sacrificing or experiencing some difficulties"},
{"r": 488, "w": "you can't win them all", "c": "你不能事事都胜利", "e": "to accept that you cannot always succeed or be victorious in every situation"},
{"r": 489, "w": "you could have knocked me down with a feather", "c": "真让我吃惊，以至于差点被吓倒", "e": "to express utter astonishment or surprise"},
{"r": 490, "w": "you gotta be kidding me", "c": "你一定是在开玩笑", "e": "expression of disbelief or surprise, often in response to something that is difficult to believe or understand"},
{"r": 491, "w": "you've got to be kidding", "c": "你一定是在开玩笑", "e": "expressing disbelief or incredulity about something"}
];
