/* English sayings & expressions (IdiomKB). { r, w, c:Chinese, e:English }. */
window.SAYINGS = [
{"r": 1, "w": "on the up and up", "c": "合法和正直的，没有任何欺骗或不诚实的行为", "e": "honest; trustworthy; legitimate"},
{"r": 2, "w": "get out of bed on the wrong side", "c": "心情不好，开始一天时情绪低落或者发脾气", "e": "to start the day in a bad mood or be irritable"},
{"r": 3, "w": "get out of the wrong side of the bed", "c": "心情糟糕或易怒，通常会影响整天的状态", "e": "to wake up in a bad mood or be irritable for no apparent reason"},
{"r": 4, "w": "not to put too fine a point on it", "c": "无需过分解释或强调，因为事实已经非常明显", "e": "to speak directly and honestly without sugarcoating or beating around the bush"},
{"r": 5, "w": "go in one ear and out the other", "c": "一耳朵进，一耳朵出，形容听了却不记住或不理解", "e": "to be quickly forgotten or not understood"},
{"r": 6, "w": "white as a sheet", "c": "惊慌、害怕、或病得面无血色的样子", "e": "extremely pale, usually due to fear, shock, or illness"},
{"r": 7, "w": "water under the bridge", "c": "过去的事情；已经发生的无法改变的事情", "e": "something that happened in the past and is no longer important or relevant"},
{"r": 8, "w": "cold day in hell", "c": "极为罕见的事件或情况不太可能发生", "e": "Something that is highly unlikely to happen"},
{"r": 9, "w": "for the hell of it", "c": "出于兴趣或无聊而去做某事，没有明确的目的或动机", "e": "doing something without any particular reason or purpose, purely for the sake of enjoyment or amusement"},
{"r": 10, "w": "as right as rain", "c": "健康或状态良好，没有问题", "e": "in perfect or excellent condition; feeling or doing well"},
{"r": 11, "w": "a lot on my plate", "c": "任务繁重，忙得不可开交", "e": "having many tasks or responsibilities to deal with"},
{"r": 12, "w": "a lot on your plate", "c": "应付或处理的事情太多，无法集中注意力或完成所有任务", "e": "Having a lot of tasks or responsibilities to deal with"},
{"r": 13, "w": "step up the plate", "c": "挺身而出，承担责任", "e": "to take on a challenge or responsibility"},
{"r": 14, "w": "from the bottom of my heart", "c": "真诚地，由衷地，从内心深处", "e": "to say or do something with genuine sincerity or deep feeling"},
{"r": 15, "w": "get to the bottom", "c": "查明真相；弄清事情的原委", "e": "to discover the truth or underlying cause of something"},
{"r": 16, "w": "get to the bottom of", "c": "彻底弄清事情的真相或原因", "e": "to fully understand or uncover the truth about something"},
{"r": 17, "w": "a clean bill of health", "c": "健康证明，表示一个人没有任何健康问题或疾病的证明", "e": "official or formal statement confirming that someone or something is healthy, in good condition, or free from any negative or harmful factors"},
{"r": 18, "w": "make a clean break", "c": "做出干净利落的分手或结束", "e": "to completely sever ties or end a relationship in a decisive and definitive manner"},
{"r": 19, "w": "get it in the neck", "c": "受到责备、惩罚或不公正对待", "e": "to receive severe criticism, punishment, or a negative outcome"},
{"r": 20, "w": "pain in the neck", "c": "讨厌的人或事物", "e": "someone or something that is annoying or bothersome"},
{"r": 21, "w": "stick your neck out", "c": "冒险、冒着危险去做某事；为某事冒风险或冒生命危险；赌上自己的名誉或活命去支持某人或某事", "e": "to take a risk or put oneself in a vulnerable position"},
{"r": 22, "w": "like a chicken with its head cut off", "c": "像鸡头被割掉的样子，手忙脚乱、毫无目的地四处乱跑", "e": "to behave in a frantic, disorganized, or aimless manner"},
{"r": 23, "w": "an open and shut case", "c": "显而易见的事情，没有争议的事情", "e": "a situation or legal matter that is easily and clearly resolved or determined"},
{"r": 24, "w": "put up or shut up", "c": "要么实际行动，要么闭嘴", "e": "to either take action or stop talking about something"},
{"r": 25, "w": "shut the door on", "c": "断绝与某人的关系或机会", "e": "to put an end to; to refuse to consider or accept; to exclude or reject completely"},
{"r": 26, "w": "all over the map", "c": "到处都在", "e": "unorganized or lacking focus; scattered"},
{"r": 27, "w": "paint the town red", "c": "狂欢一场，尽情享乐", "e": "to go out and enjoy oneself by engaging in a lively and extravagant manner, often involving partying and indulgence"},
{"r": 28, "w": "add fuel to the fire", "c": "火上浇油", "e": "to worsen or escalate a situation by saying or doing something that makes it more intense or contentious"},
{"r": 29, "w": "salt of the earth", "c": "人民的脊梁", "e": "someone who is genuine, honest, and trustworthy"},
{"r": 30, "w": "public enemy number one", "c": "公众的头号敌人", "e": "The most wanted or despised person or group in a particular context."},
{"r": 31, "w": "keep a straight face", "c": "面无表情；保持严肃的表情", "e": "to maintain a serious or composed expression, especially in a humorous or difficult situation"},
{"r": 32, "w": "straight from the shoulder", "c": "直截了当地说，坦率地说", "e": "honest and direct; speaking openly and frankly"},
{"r": 33, "w": "make heavy weather of", "c": "把某事看得太严重或复杂化", "e": "to make something more difficult or complicated than necessary"},
{"r": 34, "w": "out of thin air", "c": "毫无根据或依据", "e": "to appear or happen suddenly or seemingly from nothing"},
{"r": 35, "w": "spread yourself too thin", "c": "过分分散注意力或精力，同时承担太多任务或责任", "e": "to take on too many tasks or responsibilities, resulting in being unable to effectively perform any of them"},
{"r": 36, "w": "a breath of fresh air", "c": "一股清新的风", "e": "something or someone that is refreshing and new, providing a different and positive perspective or experience"},
{"r": 37, "w": "in the same breath", "c": "连续地，几乎同时", "e": "to mention or discuss two or more contrasting ideas or topics at the same time"},
{"r": 38, "w": "take a deep breath", "c": "深深呼吸，以缓解情绪或焦虑", "e": "to calm down or relax, especially in a stressful or difficult situation"},
{"r": 39, "w": "nurse someone back to health", "c": "护理某人恢复健康", "e": "to care for and help someone recover from an illness or injury"},
{"r": 40, "w": "go down a storm", "c": "大受欢迎，取得巨大成功", "e": "to be very successful, well received, or enjoyed by others"},
{"r": 41, "w": "beyond a shadow of doubt", "c": "毫无疑问；无可置疑地", "e": "absolutely certain; without any doubt"},
{"r": 42, "w": "for the time being", "c": "暂时地，暂时的状态", "e": "temporarily or for now; until further notice"},
{"r": 43, "w": "have a captain cook", "c": "认真看看或检查某事物的内容或细节，通常是出于好奇心或了解情况的需要", "e": "to have a quick look or glance at something"},
{"r": 44, "w": "fight like cat and dog", "c": "如猫狗一般相互争吵、打斗", "e": "to have frequent and intense arguments; to constantly fight or argue"},
{"r": 45, "w": "play to the gallery", "c": "迎合观众或大众口味；为了赢得观众或大众的喜爱而表演", "e": "to behave or perform in a way that will gain approval or support from a popular audience or majority"},
{"r": 46, "w": "get something off your chest", "c": "吐露心声，说出内心的秘密或烦恼", "e": "to share or confess something that has been troubling or bothering you"},
{"r": 47, "w": "neither here nor there", "c": "无关紧要，毫无意义", "e": "not relevant or important; of no consequence"},
{"r": 48, "w": "through thick and thin", "c": "无论情况如何都坚定不移地支持、陪伴或支援", "e": "in all circumstances, both good and bad"},
{"r": 49, "w": "keep your nose clean", "c": "保持良好的行为；避免麻烦", "e": "to stay out of trouble; to avoid doing anything wrong or illegal"},
{"r": 50, "w": "sick as a dog", "c": "病得像只狗", "e": "to be very sick or ill"},
{"r": 51, "w": "long in the tooth", "c": "年龄太大，已经不再幼稚或有活力的", "e": "old or aged"},
{"r": 52, "w": "in the fast lane", "c": "在快车道上；过着充满刺激和忙碌的生活", "e": "living or behaving in a way that is full of activity, excitement, or risk"},
{"r": 53, "w": "go against the flow", "c": "逆流而上，与主流相悖", "e": "to act or behave in a way that is contrary to the prevailing or expected direction, trend, or opinion"},
{"r": 54, "w": "go with the flow", "c": "随遇而安，顺其自然", "e": "to adapt to a situation or circumstance without resistance or effort"},
{"r": 55, "w": "in the wake of", "c": "在...之后发生的事件或情况的影响下", "e": "following or as a result of something, especially a significant event or occurrence"},
{"r": 56, "w": "wake up on the wrong side of bed", "c": "心情不好，发脾气或焦躁不安", "e": "to be in a bad mood; to start the day off feeling irritable or grouchy"},
{"r": 57, "w": "give someone the slip", "c": "瞒着别人悄悄离开或逃脱", "e": "to escape or elude someone or something"},
{"r": 58, "w": "kick the can down the road", "c": "将问题推迟到将来解决，而不是立即解决", "e": "to postpone a decision or action, especially in a way that shifts the responsibility to someone else or to the future"},
{"r": 59, "w": "tear your hair out", "c": "非常焦虑或生气；非常困难或痛苦而感到无助", "e": "to be extremely frustrated, stressed, or exasperated"},
{"r": 60, "w": "a roof over your head", "c": "提供住所", "e": "having a place to live; having basic shelter and protection"},
{"r": 61, "w": "go through the roof", "c": "十分愤怒、激动或非常高兴", "e": "to become very angry, furious, or extremely upset"},
{"r": 62, "w": "back to the drawing board", "c": "重新开始，重新计划或重新设计以取得更好的结果", "e": "start again from the beginning because a previous attempt has failed or been found to be unworkable"},
{"r": 63, "w": "pour cold water on", "c": "消极或负面地评论或阻碍某人或某物", "e": "to discourage or dampen enthusiasm for something"},
{"r": 64, "w": "be on cloud nine", "c": "极度兴奋或快乐，感觉像在云层中一样高飞", "e": "to be extremely happy or joyful"},
{"r": 65, "w": "sick and tired of something", "c": "厌倦、不再想要、对某事感到厌烦", "e": "to be extremely annoyed or frustrated with something and wanting it to stop"},
{"r": 66, "w": "put one's shoulder to the wheel", "c": "努力工作或尽力完成某项任务", "e": "To work hard and with determination towards a goal; to make a strong effort or contribution"},
{"r": 67, "w": "put your shoulder to the wheel", "c": "全力以赴，特别是在面临困难或挑战时努力工作", "e": "to work hard and make a strong effort to achieve something"},
{"r": 68, "w": "come with the territory", "c": "与这个职位或角色相关", "e": "to be a natural or expected consequence or part of a particular situation or position"},
{"r": 69, "w": "at the drop of a hat", "c": "随时准备做某事", "e": "to do something immediately or without hesitation; very quickly"},
{"r": 70, "w": "pass the hat around", "c": "将帽子传递给大家，以便大家都能为特定目的捐款", "e": "To collect money from a group of people, typically for a shared purpose or cause"},
{"r": 71, "w": "take one's hat off to someone", "c": "钦佩或向某人表示敬意", "e": "to show admiration or respect for someone's achievements or qualities"},
{"r": 72, "w": "talk through one's hat", "c": "胡扯八道，说话没有根据或知识", "e": "to speak nonsense or make false claims"},
{"r": 73, "w": "throw your hat in the ring", "c": "表达对某个竞争或争斗的兴趣或参与的意愿", "e": "to announce or declare one's intention to compete or participate in a contest or competition"},
{"r": 74, "w": "throw your hat into the ring", "c": "表示参与某项挑战或竞争，通常是在政治或职业领域", "e": "to announce or declare oneself as a candidate for a position or competition"},
{"r": 75, "w": "get a taste of your own medicine", "c": "尝到自己的咸淡", "e": "to experience the same negative treatment that one has given to others"},
{"r": 76, "w": "taste of own medicine", "c": "尝试自己以前对他人的待遇", "e": "to experience the same negative treatment or consequence that one has inflicted on others"},
{"r": 77, "w": "cast the first stone", "c": "首先扔石头", "e": "to be judgmental or critical of others, usually without considering one's own faults or mistakes"},
{"r": 78, "w": "cast your mind back", "c": "回想起过去的事情", "e": "to think back or remember something"},
{"r": 79, "w": "wrap your head around something", "c": "理解或接受某件事情，尤其是某事情很困难或复杂", "e": "to understand or comprehend something, especially something complex or difficult to grasp"},
{"r": 80, "w": "on a wing and a prayer", "c": "毫无根据地承担重大任务或挑战，几乎没有希望成功或幸运支持", "e": "trying to achieve something with very little chance or hope of success"},
{"r": 81, "w": "go through the mill", "c": "经历艰难困苦的时期或经历", "e": "to go through a difficult or challenging experience; to face hardships or adversity"},
{"r": 82, "w": "a chip on your shoulder", "c": "怨气，自卑感或敌意，常常准备对挑战或争执做出强烈反应", "e": "to have a grudge or to be easily angered or offended"},
{"r": 83, "w": "any port in a storm", "c": "困境中，抓住任何机会或选择", "e": "to accept any solution or opportunity in a difficult or desperate situation"},
{"r": 84, "w": "put the boot in", "c": "恶意攻击或批评", "e": "to physically or verbally attack someone when they are already in a vulnerable or weakened state"},
{"r": 85, "w": "slip through the net", "c": "逃脱或避开了监管或控制，尤其是通过巧妙或不完整的方式", "e": "to escape or go unnoticed; to be missed or omitted"},
{"r": 86, "w": "draw a line in the sand", "c": "划定底线；宣示原则或立场；做出不可逾越的决定", "e": "to establish a boundary or limit that cannot be crossed or violated"},
{"r": 87, "w": "run into the sand", "c": "失去动力或进展停滞", "e": "to lose momentum or come to a halt; to fail or be abandoned"},
{"r": 88, "w": "licence to print money", "c": "印钞票的许可证", "e": "a business or investment opportunity that yields significant profits with little effort or risk"},
{"r": 89, "w": "let someone down gently", "c": "委婉地让某人失望或拒绝", "e": "To break bad news or disappoint someone in a kind or considerate manner"},
{"r": 90, "w": "under lock and key", "c": "被严密保管，禁止访问或触摸", "e": "to be securely locked or closely guarded; to be kept in a safe or secure place"},
{"r": 91, "w": "before you can say knife", "c": "非常迅速地；立即；瞬间", "e": "very quickly or suddenly"},
{"r": 92, "w": "kiss and make up", "c": "和解并重归于好", "e": "to reconcile or resolve a disagreement or conflict"},
{"r": 93, "w": "i owe you one", "c": "我欠你一个人情", "e": "To owe someone a favor or gratitude"},
{"r": 94, "w": "down to the wire", "c": "到最后一刻；不确定的；紧迫的", "e": "to the very end or last minute"},
{"r": 95, "w": "go down to the wire", "c": "到最后一刻仍然不确定结果或胜负的状态", "e": "to continue until the very last moment or to the end"},
{"r": 96, "w": "wake up and smell the coffee", "c": "清醒一下；认清实际情况", "e": "To become aware of the reality of a situation; to start paying attention to what is happening or what needs to be done"},
{"r": 97, "w": "bury your head in the sand", "c": "将头埋在沙子中", "e": "to ignore or avoid a problem or unpleasant situation; to refuse to confront the truth"},
{"r": 98, "w": "go up in smoke", "c": "付诸东流，化为乌有，或失败", "e": "to be completely destroyed or ruined; to fail utterly or come to nothing"},
{"r": 99, "w": "no smoke without fire", "c": "无风不起浪，没有空穴来风", "e": "there is usually some truth or basis for a rumor or accusation"},
{"r": 100, "w": "take the rough with the smooth", "c": "接受好坏两种情况", "e": "to accept both the good and the bad parts of a situation"},
{"r": 101, "w": "part of the furniture", "c": "已经成为某个地方或组织的一部分，非常熟悉和被接受的人", "e": "to be so familiar or ingrained in a place or situation that one is often overlooked or taken for granted"},
{"r": 102, "w": "the apple of my eye", "c": "掌上明珠；最爱的人", "e": "someone or something that is cherished above all others"},
{"r": 103, "w": "ask for the moon", "c": "索取过多或过分追求不切实际的东西", "e": "to make an unrealistic or excessive request"},
{"r": 104, "w": "no room to swing a cat", "c": "空间很小，没办法转身", "e": "very little space"},
{"r": 105, "w": "not enough room to swing a cat", "c": "空间非常狭窄，无法做出很大的活动", "e": "to describe a very small or cramped space"},
{"r": 106, "w": "turn the other cheek", "c": "转过身去; 对待冒犯或伤害不作回应", "e": "to refrain from seeking revenge or retaliation; to respond to harm or insult with forgiveness or patience"},
{"r": 107, "w": "cream of the crop", "c": "最好的人或事物，精华，精选", "e": "the best or most talented individuals or things in a particular group or category"},
{"r": 108, "w": "go down the pan", "c": "完蛋了；被毁了；没有希望了", "e": "to fail or deteriorate; to be unsuccessful or go to ruin"},
{"r": 109, "w": "call on the carpet", "c": "受到训斥或批评", "e": "to be reprimanded or called out for something"},
{"r": 110, "w": "bring the curtain down", "c": "结束一段时间，尤指一个时期的活动或事件", "e": "to bring an event or performance to an end"},
{"r": 111, "w": "make a fast buck", "c": "快速赚钱", "e": "to make money quickly and easily, often through dishonest or questionable means"},
{"r": 112, "w": "on a full stomach", "c": "饱餐之后", "e": "after eating a meal; when one is not hungry"},
{"r": 113, "w": "ahead of the curve", "c": "在发展或趋势之前，比其他人更早或更有先见之明", "e": "being ahead or more advanced than others in terms of knowledge, skills, or trends"},
{"r": 114, "w": "make an honest buck", "c": "以诚实的方式赚钱", "e": "to earn money in a fair and ethical manner"},
{"r": 115, "w": "turn back the clock", "c": "倒退，回到过去的时期", "e": "to go back in time; to return to a previous state or condition"},
{"r": 116, "w": "in a split second", "c": "在一瞬间；瞬间之间", "e": "very quickly or immediately"},
{"r": 117, "w": "my way or the highway", "c": "要不然就按照我的方式办，要不然就离开", "e": "an uncompromising attitude or approach, typically with little or no regard for others' opinions or preferences"},
{"r": 118, "w": "everything but the kitchen sink", "c": "除了厨房水槽外的一切东西", "e": "including nearly everything possible; with little or no restraint or limitations"},
{"r": 119, "w": "shoot from the hip", "c": "毫不考虑地急匆匆地做决定、发言或采取行动", "e": "to speak or act without careful consideration or planning; to be impulsive or spontaneous"},
{"r": 120, "w": "move heaven and earth", "c": "不遗余力，竭尽全力做某事", "e": "to do everything possible or go to great lengths in order to achieve or accomplish something"},
{"r": 121, "w": "sweep something under the carpet", "c": "避免公开或处理问题，尤其是为了保护某人的形象或避免任何麻烦或困难", "e": "to hide or ignore a problem or issue, usually in order to avoid dealing with it"},
{"r": 122, "w": "bright as a button", "c": "聪明伶俐；机智聪慧", "e": "very intelligent or clever"},
{"r": 123, "w": "right on the button", "c": "正好及时；恰到好处；准确无误", "e": "exactly correct or accurate; precisely on time or at the expected moment"},
{"r": 124, "w": "pick of the bunch", "c": "最好的选择或最优秀的人或物", "e": "the best or most desirable item from a selection"},
{"r": 125, "w": "keep a low profile", "c": "保持低调；不引人注目或扬名立万", "e": "to avoid attracting attention or being noticed, typically in order to avoid trouble or unwanted attention"},
{"r": 126, "w": "bet your bottom dollar", "c": "非常确信；非常相信某事", "e": "to be absolutely certain or confident about something; to be willing to wager everything one has on a particular outcome"},
{"r": 127, "w": "you can bet your life", "c": "你可以肯定", "e": "to be absolutely certain or confident about something"},
{"r": 128, "w": "wipe the floor with", "c": "彻底击败或战胜某人", "e": "to defeat someone decisively or completely"},
{"r": 129, "w": "everybody and his cousin", "c": "几乎每个人都参与其中", "e": "referring to a large number of people or a wide variety of individuals"},
{"r": 130, "w": "turn a blind eye", "c": "睁一只眼闭一只眼", "e": "to ignore or pretend not to see something"},
{"r": 131, "w": "lend me your ear", "c": "听我说，倾听我的意见或请求", "e": "to listen attentively"},
{"r": 132, "w": "run a tight ship", "c": "严管秩序；严格管理", "e": "to have strict control over an organization or situation"},
{"r": 133, "w": "run out of steam", "c": "失去动力或能量，力不从心", "e": "to lose energy, motivation, or momentum; to tire or exhaust"},
{"r": 134, "w": "do me a favour", "c": "帮我个忙", "e": "to ask someone for a favor or assistance"},
{"r": 135, "w": "in the nick of time", "c": "在最后一刻", "e": "at the last possible moment; just in time"},
{"r": 136, "w": "beat about the bush", "c": "绕着弯子说话；含糊其辞或不直接回答问题", "e": "to avoid getting to the point or addressing a matter directly; to speak in a roundabout or evasive manner"},
{"r": 137, "w": "the whole shooting match", "c": "包括所有的事物或人的全部", "e": "everything; the entire thing"},
{"r": 138, "w": "by no stretch of the imagination", "c": "无论如何也不可能", "e": "not at all; not in any possible way; absolutely not"},
{"r": 139, "w": "keep a civil tongue", "c": "保持礼貌和谦和的口舌", "e": "to speak in a polite and respectful manner; to refrain from using offensive or rude language"},
{"r": 140, "w": "on the tip of one's tongue", "c": "一种感觉，当某人准备要说某个事物的名称或细节时，该事物几乎立即就会浮现在他们的脑海中", "e": "Something that is almost remembered but not quite; something that one is very close to saying or recalling"},
{"r": 141, "w": "slip of the tongue", "c": "口误，不小心说错话", "e": "an unintentional error in speaking, typically revealing something that was meant to be concealed"},
{"r": 142, "w": "hand in the till", "c": "趁势牟利或盗窃", "e": "to steal money from one's employer"},
{"r": 143, "w": "as poor as a church mouse", "c": "一贫如洗、一无所有", "e": "to have little or no money or possessions"},
{"r": 144, "w": "play cat and mouse", "c": "玩猫捉老鼠的游戏；斗智斗勇，相互追逐，策略战", "e": "to engage in a game of wits or strategy, typically where one person is teasing or deceiving another"},
{"r": 145, "w": "poor as a church mouse", "c": "非常贫穷，一贫如洗", "e": "to be extremely poor or have no money"},
{"r": 146, "w": "quiet as a mouse", "c": "像老鼠一样安静", "e": "very quiet; making little or no noise"},
{"r": 147, "w": "at a loose end", "c": "无所事事，没有目标或计划", "e": "to have nothing to do or be unsure of what to do"},
{"r": 148, "w": "play fast and loose", "c": "玩弄花招，不守规矩或不诚实对待某人或某事", "e": "to behave in an irresponsible or unpredictable manner"},
{"r": 149, "w": "do the dirty work", "c": "做脏活", "e": "to do the unpleasant or difficult tasks, especially on behalf of someone else"},
{"r": 150, "w": "rub someone the wrong way", "c": "惹恼某人；让某人感到不舒服", "e": "to irritate or annoy someone"},
{"r": 151, "w": "rub someone up the wrong way", "c": "惹人讨厌或惹恼别人", "e": "to irritate or annoy someone, often unintentionally"},
{"r": 152, "w": "rub the wrong way", "c": "使某人不悦或触怒；激怒某人", "e": "to irritate or annoy someone"},
{"r": 153, "w": "sail against the wind", "c": "逆时而行；违抗潮流或逆境而前进", "e": "to go against popular opinion or prevailing trends; to do something difficult or challenging; to face obstacles or resistance in pursuit of a goal"},
{"r": 154, "w": "sail close to the wind", "c": "冒险做某事，鲁莽行动，接近危险的边缘", "e": "to take risks or behave recklessly"},
{"r": 155, "w": "deaf as a post", "c": "聋得像木头一样", "e": "completely unable to hear"},
{"r": 156, "w": "go steady with someone", "c": "与某人交往", "e": "to be in a committed romantic relationship with someone"},
{"r": 157, "w": "all hat and no cattle", "c": "言行不一致，虚有其表", "e": "someone who talks boastfully or confidently about their abilities or accomplishments, but has no substance or evidence to support their claims"},
{"r": 158, "w": "slip of the pen", "c": "似乎是笔记、书法或其他手写文字错误的纯粹技术错误", "e": "an unintentional mistake or error made while writing"},
{"r": 159, "w": "too clever by half", "c": "过于聪明反而给人以不好的印象或引起麻烦", "e": "to be excessively or arrogantly clever, leading to negative consequences"},
{"r": 160, "w": "pull a rabbit out of a hat", "c": "表面上毫不费力地完成令人吃惊的事情", "e": "To produce something unexpectedly and impressively, often in a challenging or difficult situation"},
{"r": 161, "w": "pull a rabbit out of the hat", "c": "突然解决问题或成功做到某事，尤其是在没有预期的情况下", "e": "to do something unexpected or impressive, especially in a difficult or challenging situation"},
{"r": 162, "w": "go through a rough patch", "c": "经历困难时期", "e": "to experience a difficult or challenging period of time"},
{"r": 163, "w": "asleep at the wheel", "c": "在关键时刻疏忽大意或无所作为", "e": "not paying attention or being unaware of what is happening; being negligent or careless"},
{"r": 164, "w": "a new lease of life", "c": "重新获得活力，重新开始", "e": "renewed energy, vitality, or enthusiasm"},
{"r": 165, "w": "every trick in the book", "c": "尽一切办法或手段来达到目的", "e": "all possible methods or strategies; every known or available trick or tactic"},
{"r": 166, "w": "not miss a trick", "c": "观察细致，不放过任何机会或细节", "e": "to be very observant, alert, or attentive; to not overlook or miss any details or opportunities"},
{"r": 167, "w": "trick of the trade", "c": "行业诀窍；专业技能或秘诀", "e": "an expert technique or method that is used in a specific profession or field"},
{"r": 168, "w": "fit like a glove", "c": "非常适合，完全贴合", "e": "to fit perfectly or very well"},
{"r": 169, "w": "a bite to eat", "c": "吃点东西", "e": "a small meal or snack; something to eat"},
{"r": 170, "w": "bite the big one", "c": "彻底失败或挫败", "e": "to die or fail in a significant or dramatic way"},
{"r": 171, "w": "grin and bear it", "c": "勉强忍受或接受不愉快的情况或问题", "e": "to endure a difficult or unpleasant situation with courage and patience"},
{"r": 172, "w": "take with a grain of salt", "c": "以保持怀疑的态度对待，表示不完全相信或接受", "e": "to not completely believe or trust something; to be skeptical or doubtful about something"},
{"r": 173, "w": "paint something with a broad brush", "c": "以一概全，不细节考虑", "e": "to generalize or stereotype something or someone without considering individual differences or nuances"},
{"r": 174, "w": "hit the ground running", "c": "立即从最初开始行动，毫不拖延", "e": "to start a new job or project quickly and energetically; to immediately become fully involved and active"},
{"r": 175, "w": "out of the running", "c": "无望胜出; 不再竞争", "e": "no longer in contention or competition; having no chance of winning or being successful"},
{"r": 176, "w": "keep your powder dry", "c": "保留力量或资源，以备不时之需", "e": "to be prepared and ready for a future opportunity or event; to exercise caution and restraint in order to protect oneself"},
{"r": 177, "w": "give up the ghost", "c": "死亡或停止运作", "e": "to die or stop functioning"},
{"r": 178, "w": "swim against the tide", "c": "逆流而游", "e": "to go against popular opinion or prevailing trends"},
{"r": 179, "w": "swim with the tide", "c": "顺势而为、遵循大势或跟随潮流", "e": "to go along with the majority opinion or prevailing trends; to conform"},
{"r": 180, "w": "as ugly as sin", "c": "非常丑陋，极其难看", "e": "extremely unattractive"},
{"r": 181, "w": "cut from the same cloth", "c": "本质相同", "e": "to have similar characteristics or traits; to be very similar in nature"},
{"r": 182, "w": "cut your coat according to your cloth", "c": "根据自己的经济状况做出合理安排，不超过能力范围", "e": "to live within one's means; to adapt one's lifestyle or expenses to match one's income or resources"},
{"r": 183, "w": "man of the cloth", "c": "教士，特指神职人员", "e": "a clergyman or priest"},
{"r": 184, "w": "give someone enough rope", "c": "给某人自由或机会来自取灭亡；任其自生自灭", "e": "to give someone enough freedom or leeway to make mistakes or reveal their true character, often resulting in their own downfall or failure"},
{"r": 185, "w": "money for old rope", "c": "不劳而获，容易得到的东西或金钱", "e": "Easy money, effortless profit, or a valuable return for minimal effort"},
{"r": 186, "w": "as easy as pie", "c": "非常容易", "e": "extremely easy or simple"},
{"r": 187, "w": "pie in the sky", "c": "空中烤饼；不切实际的幻想或希望", "e": "something that is unrealistic or unlikely to happen"},
{"r": 188, "w": "come rain or shine", "c": "无论天晴还是下雨，永不改变", "e": "regardless of any circumstances or obstacles; in any weather condition"},
{"r": 189, "w": "take a shine to", "c": "对某人或某物很感兴趣或很喜欢", "e": "to become attracted to or develop a liking for someone or something"},
{"r": 190, "w": "smell of the lamp", "c": "努力工作，特别是在艰苦的环境下，以达到目标", "e": "to show signs of great effort or laboriousness in work"},
{"r": 191, "w": "big fish in a small pond", "c": "居于小圈子的重要人物", "e": "an important or influential person in a small or limited arena or group"},
{"r": 192, "w": "little fish in a big pond", "c": "大海捞针；小巫见大巫", "e": "feeling insignificant or unimportant in a large or competitive environment"},
{"r": 193, "w": "silent as the grave", "c": "沉默不语", "e": "completely silent; not making a sound"},
{"r": 194, "w": "sleep like a log", "c": "睡得很沉，一觉到天亮", "e": "to sleep deeply and soundly"},
{"r": 195, "w": "bitter pill to swallow", "c": "令人不愉快但必须接受的现实或情况", "e": "something difficult or unpleasant to accept"},
{"r": 196, "w": "look before you leap", "c": "三思而后行", "e": "to think about the possible consequences or dangers before taking action"},
{"r": 197, "w": "i beg to differ", "c": "我不同意", "e": "to politely disagree with someone's opinion or statement"},
{"r": 198, "w": "out of the closet", "c": "公开承认或表达某个隐藏或秘密的事实或身份", "e": "to openly reveal or acknowledge one's true beliefs, identity, or preferences, especially in regards to sexual orientation"},
{"r": 199, "w": "snake in the grass", "c": "见利忘义，背后搞鬼，暗中挑拨离间", "e": "someone who appears friendly or harmless but is actually treacherous or deceitful"},
{"r": 200, "w": "a flash in the pan", "c": "昙花一现", "e": "something or someone that initially shows great promise but fails to meet expectations in the long run"},
{"r": 201, "w": "flash in the pan", "c": "昙花一现（没有长久效果或持久影响的事物）", "e": "Something that initially shows great promise or potential, but ultimately fails to deliver or live up to expectations"},
{"r": 202, "w": "quick as a flash", "c": "迅速无比；快得像闪电一样", "e": "Extremely quick or fast"},
{"r": 203, "w": "give somebody the elbow", "c": "对某人施加压力，解雇某人", "e": "to reject or dismiss someone, especially in a romantic or personal relationship"},
{"r": 204, "w": "take to something like a duck to water", "c": "自然而然地掌握某事；轻松适应某事", "e": "to learn or adapt to something very quickly and easily"},
{"r": 205, "w": "in no uncertain terms", "c": "毫不含糊地，坦率地", "e": "very clearly and explicitly; without any doubt or ambiguity"},
{"r": 206, "w": "between the devil and the deep blue sea", "c": "进退两难，左右为难", "e": "being in a difficult or impossible situation with two equally undesirable choices or outcomes"},
{"r": 207, "w": "devil of a time", "c": "非常困难或令人苦恼的时刻", "e": "to have a very difficult or challenging experience"},
{"r": 208, "w": "sell your soul to the devil", "c": "出卖灵魂；为了私利而无坚守；对原则和价值观的背叛", "e": "to make a desperate or morally compromising deal or agreement in exchange for personal gain or success"},
{"r": 209, "w": "talk of the devil", "c": "刚说论及某人，某人就来了", "e": "to mention someone who then appears unexpectedly"},
{"r": 210, "w": "fight tooth and nail", "c": "不遗余力地战斗或努力争取某事", "e": "to fight or argue fiercely and with great determination"},
{"r": 211, "w": "laugh like a drain", "c": "笑得很大声或很尽兴", "e": "To laugh very loudly and uncontrollably"},
{"r": 212, "w": "go out on a limb", "c": "冒险或采取行动，尤其是在没有他人支持或保证的情况下", "e": "To take a risk or put oneself in a vulnerable position"},
{"r": 213, "w": "out on a limb", "c": "置身险地，面临孤立的困境", "e": "to be in a risky or vulnerable position"},
{"r": 214, "w": "sing the same tune", "c": "表示具有相同观点或意见", "e": "to have the same opinion or viewpoint as someone else; to agree or be consistent in one's beliefs or statements"},
{"r": 215, "w": "to the tune of", "c": "以...的金额；总共达到...", "e": "to the amount or extent of; in the range of; approximately"},
{"r": 216, "w": "blow one's own horn", "c": "吹嘘自己；自吹自擂", "e": "to boast or brag about one's own achievements or abilities"},
{"r": 217, "w": "to pull the trigger", "c": "做出重要决定或采取行动", "e": "to take decisive action or make a decision, often with significant consequences"},
{"r": 218, "w": "throw the towel in", "c": "放弃或认输", "e": "to give up or surrender; to admit defeat"},
{"r": 219, "w": "as blind as a bat", "c": "非常盲目或视力不好", "e": "to have extremely poor eyesight"},
{"r": 220, "w": "blind as a bat", "c": "眼盲，指一个人非常近视或视力非常差", "e": "having extremely poor or no vision"},
{"r": 221, "w": "like a bat out of hell", "c": "非常快速地行动或移动，如同地狱中的蝙蝠", "e": "to move or act very quickly or recklessly"},
{"r": 222, "w": "not bat an eye", "c": "毫不在意或露出任何情感或反应", "e": "show no reaction or emotion, especially in a situation where one might be expected to"},
{"r": 223, "w": "sweat like a pig", "c": "非常努力工作或运动，以至于流汗如雨", "e": "to perspire heavily"},
{"r": 224, "w": "drunk as a lord", "c": "喝醉得像贵族一样", "e": "extremely intoxicated"},
{"r": 225, "w": "in the driving seat", "c": "处于控制或指挥的位置", "e": "in a position of control or influence"},
{"r": 226, "w": "broad in the beam", "c": "身材丰满的", "e": "having a wide or large bottom or hips"},
{"r": 227, "w": "thumb your nose at", "c": "嘲笑或蔑视某人或某事", "e": "to show contempt or disdain for someone or something"},
{"r": 228, "w": "hit the panic button", "c": "按下恐慌按钮、在担心、害怕或紧张时做出仓促或冲动的举动", "e": "to become very worried or anxious; to react to a situation with excessive fear or alarm"},
{"r": 229, "w": "press the panic button", "c": "按下紧急按钮，表达紧急或惊慌的情绪", "e": "to become extremely anxious or panicked in a challenging or difficult situation"},
{"r": 230, "w": "push the panic button", "c": "触动紧急按钮，感到极度紧张或恐慌", "e": "to react with extreme worry or fear in a situation"},
{"r": 231, "w": "read the riot act", "c": "告诫或训斥某人，通常指严厉地警告某人停止行为", "e": "to reprimand or scold someone severely"},
{"r": 232, "w": "let someone off the hook", "c": "放过某个人，不追究他的过错或责任", "e": "to not hold someone accountable or responsible for something; to release someone from punishment or obligation"},
{"r": 233, "w": "ring off the hook", "c": "电话响个不停", "e": "to have a lot of phone calls or inquiries coming in"},
{"r": 234, "w": "put on a brave face", "c": "装作勇敢；摆出坚定的面孔", "e": "to act courageous or confident in the face of adversity or fear"},
{"r": 235, "w": "fire in the belly", "c": "内心燃起的强烈欲望或动力", "e": "strong determination, passion, or motivation for something"},
{"r": 236, "w": "and all that jazz", "c": "等等类似的东西", "e": "and similar things; and other similar things"},
{"r": 237, "w": "pat on the back", "c": "表示赞赏或鼓励", "e": "to show approval or recognition for someone's achievements or efforts"},
{"r": 238, "w": "born to the purple", "c": "天生神力，或者出生于高贵的家族或阶层", "e": "born into a privileged or high-ranking position"},
{"r": 239, "w": "on the flip side", "c": "从另一面来看", "e": "referring to the opposite or contrasting aspect of a situation or argument"},
{"r": 240, "w": "not worth the candle", "c": "得不偿失，代价不值得", "e": "not worth the effort or cost involved"},
{"r": 241, "w": "take it on the chin", "c": "勇敢地接受困难或失败，没有抱怨或退缩", "e": "to accept or endure adversity or criticism without complaint or becoming discouraged"},
{"r": 242, "w": "vanish into the air", "c": "消失得无影无踪", "e": "to disappear completely and suddenly"},
{"r": 243, "w": "hidden in plain sight", "c": "明明就在眼前却未被察觉或注意到", "e": "something that is very obvious or easily seen, but goes unnoticed or overlooked"},
{"r": 244, "w": "bring up the rear", "c": "走在最后面; 处于最后一位", "e": "to be the last in a group or line"},
{"r": 245, "w": "put the cart before the horse", "c": "本末倒置、弄错顺序", "e": "to do things in the wrong order or with the wrong priorities; to do something before it should be done"},
{"r": 246, "w": "upset the apple cart", "c": "打翻了苹果车；破坏了原本正常的情况或计划", "e": "to disrupt or spoil a plan or situation"},
{"r": 247, "w": "benjamin of the family", "c": "家族的宝贝", "e": "the youngest or most spoiled member of a family"},
{"r": 248, "w": "all greek to me", "c": "对某事一无所知、毫无概念或听不懂", "e": "something that is difficult or impossible to understand or comprehend"},
{"r": 249, "w": "a slap on the wrist", "c": "轻微的惩罚", "e": "a mild or lenient punishment or reprimand"},
{"r": 250, "w": "slap on the wrist", "c": "轻微的惩罚或警告", "e": "to receive a very light or lenient punishment"},
{"r": 251, "w": "its not rocket science", "c": "这不是火箭科学", "e": "something that is not difficult or complicated"},
{"r": 252, "w": "shot across the bow", "c": "向对方发出警告或示威来预示即将发生的冲突或争议", "e": "a warning or threat, especially delivered in a confrontational or assertive manner"},
{"r": 253, "w": "by the grace of god", "c": "靠着上帝的恩典", "e": "with the help or blessings of God; through divine intervention or favor"},
{"r": 254, "w": "laugh up your sleeve", "c": "暗中嘲笑或幸灾乐祸", "e": "to secretly find amusement or satisfaction in someone else's misfortune"},
{"r": 255, "w": "wear heart on sleeve", "c": "表达情感或感受时毫不掩饰或隐藏自己的情感", "e": "to openly and visibly display one's emotions or feelings"},
{"r": 256, "w": "wear your heart on your sleeve", "c": "毫不掩饰地表达自己的情感或感情", "e": "To openly and freely show or display one's emotions or feelings."},
{"r": 257, "w": "as gentle as a lamb", "c": "温顺如羔羊", "e": "to be very calm, kind, or gentle"},
{"r": 258, "w": "before one can say jack robinson", "c": "在即秒之间", "e": "to happen very quickly or suddenly"},
{"r": 259, "w": "before you can say jack robinson", "c": "转瞬间；马上", "e": "something happening quickly or suddenly"},
{"r": 260, "w": "calm before the storm", "c": "暴风雨前的宁静", "e": "the peaceful period right before a chaotic or challenging situation"},
{"r": 261, "w": "the calm before the storm", "c": "风雨前的宁静", "e": "a period of peace or tranquility before a difficult or chaotic period begins"},
{"r": 262, "w": "another nail in one's coffin", "c": "加重某人困境或失败的因素", "e": "a further action or event that brings one closer to ruin or failure; something that worsens the already difficult or negative situation"},
{"r": 263, "w": "hot under the collar", "c": "情绪激动或生气", "e": "to be angry or agitated"},
{"r": 264, "w": "a bull and cow", "c": "争吵或冲突的夫妻", "e": "a couple; a pair"},
{"r": 265, "w": "bull in a china shop", "c": "在不适合自己的环境中举止粗鲁或笨拙", "e": "someone who is clumsy, careless, or inconsiderate in their actions"},
{"r": 266, "w": "as busy as a bee", "c": "非常忙碌", "e": "to be very busy, working quickly and energetically"},
{"r": 267, "w": "out of the loop", "c": "不了解事情的最新情况或没有参与到重要的决策或活动中", "e": "not having information about something"},
{"r": 268, "w": "go off the boil", "c": "失去兴趣或动力", "e": "to lose interest, motivation, or enthusiasm; to become less effective or successful"},
{"r": 269, "w": "make your blood boil", "c": "令人非常生气或愤怒", "e": "to cause extreme anger or frustration"},
{"r": 270, "w": "put a sock in it", "c": "闭嘴或停止说话", "e": "to tell someone to be quiet or stop talking"},
{"r": 271, "w": "set the ball rolling", "c": "开始、引领或启动某个行动或进程", "e": "to initiate or start something; to get a process or activity underway"},
{"r": 272, "w": "draw the short straw", "c": "遭受不利情况或任务", "e": "to be chosen or assigned the least desirable or favorable option or task"},
{"r": 273, "w": "the elephant in the room", "c": "显而易见但却被人们不愿意讨论或面对的问题", "e": "an obvious problem or difficult situation that people do not want to talk about"},
{"r": 274, "w": "born with a silver spoon in mouth", "c": "生来富有，幸福的出生", "e": "to be born into a wealthy or privileged family"},
{"r": 275, "w": "up a blind alley", "c": "走进了一条死胡同，没有出路，没有希望", "e": "to be in a situation that leads nowhere; to be faced with a dead end; to be pursuing a fruitless or pointless endeavor"},
{"r": 276, "w": "work like a charm", "c": "非常有效或顺利地工作", "e": "to work perfectly or effectively; to have the desired or expected result"},
{"r": 277, "w": "share and share alike", "c": "平分成果、财富或责任的原则", "e": "to divide something equally among all parties involved"},
{"r": 278, "w": "not give a damn", "c": "不在乎或不在意", "e": "to not care at all; to have no interest or concern"},
{"r": 279, "w": "no use to man or beast", "c": "毫无用处，对人或动物都没有用", "e": "completely useless or valueless"},
{"r": 280, "w": "drop in the bucket", "c": "沧海一粟，微不足道的贡献", "e": "something that is considered to be small in comparison to the whole or the overall need"},
{"r": 281, "w": "law of the jungle", "c": "丛林法则；弱肉强食", "e": "the principle of survival of the fittest; a situation of fierce competition and chaos where only the strongest or most cunning survive"},
{"r": 282, "w": "a feather in one's cap", "c": "引以为荣的成就或荣誉", "e": "an achievement or accomplishment that one can be proud of"},
{"r": 283, "w": "feather in your cap", "c": "令人骄傲或引以为傲的成就或荣誉", "e": "an accomplishment or achievement that one can be proud of"},
{"r": 284, "w": "dip your toe in the water", "c": "试水一下，初步尝试", "e": "to try or experience something new or unfamiliar, usually in a cautious or limited way"},
{"r": 285, "w": "blow the lid off", "c": "揭露秘密或真相", "e": "to reveal or expose something secret or scandalous"},
{"r": 286, "w": "keep a lid on", "c": "控制或限制某事，使其不被公开或暴露", "e": "to keep something secret or hidden; to maintain control or restraint over something"},
{"r": 287, "w": "bang for the buck", "c": "以较少的投资获得更高的回报", "e": "the value or benefit received from an investment or expenditure, especially in relation to the amount of money spent"},
{"r": 288, "w": "in the blink of an eye", "c": "在眨眼的一瞬间；瞬间", "e": "very quickly; in a very short amount of time; almost instantaneously"},
{"r": 289, "w": "chill to the bone", "c": "寒冷得骨头发寒；寒气透骨", "e": "to feel extremely cold"},
{"r": 290, "w": "the chill wind of something", "c": "某事的冷风", "e": "the unwelcome or unpleasant consequences or effects of something"},
{"r": 291, "w": "lie like a rug", "c": "撒谎，讲假话", "e": "to lie or deceive someone convincingly and without remorse"},
{"r": 292, "w": "sweep something under the rug", "c": "掩盖、隐藏或不公开某事物，尤指某个问题或错误", "e": "to ignore or conceal a problem or issue, typically in order to avoid dealing with it or to maintain a positive image"},
{"r": 293, "w": "power behind the throne", "c": "幕后操纵的力量", "e": "the person or group that has the real power and controls a ruler or leader, especially in a secret or unofficial way"},
{"r": 294, "w": "a pig in a poke", "c": "掩人耳目的买卖或交易，即对商品的真实情况毫无了解", "e": "buying something without inspecting it first"},
{"r": 295, "w": "pig in a poke", "c": "以与实际情况不符的方式出售或购买商品，即没有检查也没有了解就购买商品", "e": "to buy or accept something without knowing its true nature or value"},
{"r": 296, "w": "poke one's nose in", "c": "过多干涉别人的事情或私事", "e": "to interfere or intrude in someone else's business or affairs"},
{"r": 297, "w": "hang by a thread", "c": "岌岌可危；处于极其危险或不确定的情况中", "e": "to be in a precarious or dangerous situation; to be at risk of imminent failure or collapse"},
{"r": 298, "w": "throw caution to the wind", "c": "不顾后果，毫不考虑地冒险或行事", "e": "to take a risk or act recklessly without considering the potential consequences"},
{"r": 299, "w": "trip the light fantastic", "c": "优美而富有节奏地跳舞，常指在晚会或社交场合中尽情狂欢", "e": "to dance or move in a lively and graceful manner"},
{"r": 300, "w": "have a screw loose", "c": "思维或行为上有问题，不正常或疯狂", "e": "to be mentally unstable or eccentric"},
{"r": 301, "w": "you know the drill", "c": "你知道该怎么做了；你明白程序", "e": "you are familiar with the process or routine; you know what needs to be done or how things work"},
{"r": 302, "w": "send up a trial balloon", "c": "放风球", "e": "To test an idea or proposal before fully committing to it"},
{"r": 303, "w": "practise what you preach", "c": "说到做到", "e": "to consistently act in accordance with one's own advice or beliefs"},
{"r": 304, "w": "ace in the hole", "c": "一个秘密的策略、计划或资源，可以在紧急情况下使用", "e": "a secret advantage or resource that can be used in a situation when it is needed"},
{"r": 305, "w": "within an ace of", "c": "接近、差一点就要......", "e": "to be extremely close to or on the verge of something"},
{"r": 306, "w": "bolt from the blue", "c": "突然而来的惊喜或震惊的消息", "e": "an unexpected and surprising event or news"},
{"r": 307, "w": "the fog of war", "c": "战争中的混乱、不确定性和困惑的状态", "e": "the confusion and uncertainty that arises during a war or a chaotic situation"},
{"r": 308, "w": "drive a hard bargain", "c": "以强硬手段进行交易，尤指在谈判中坚持自己的要求，不容易让步", "e": "to negotiate or haggle fiercely or aggressively in order to get the best deal possible"},
{"r": 309, "w": "go under the hammer", "c": "被拍卖", "e": "to be sold at an auction"},
{"r": 310, "w": "on the spur of the moment", "c": "一时冲动地；即时地，毫无准备地", "e": "doing something without planning or thinking ahead; spontaneously"},
{"r": 311, "w": "preach to the choir", "c": "对已经同意的人进行说教", "e": "to try to persuade or convince someone who already agrees with you or supports your cause"},
{"r": 312, "w": "carry a torch for", "c": "暗恋", "e": "to have strong feelings of love or affection for someone, especially when those feelings are not reciprocated"},
{"r": 313, "w": "send someone to coventry", "c": "把某人冷落、孤立或排挤出社交圈，通常是由于某种原因不受欢迎而被忽视或拒绝与之交往", "e": "to deliberately ignore or ostracize someone"},
{"r": 314, "w": "shiver down one's spine", "c": "寒从脊背而过；毛骨悚然", "e": "a sudden feeling of fear or excitement"},
{"r": 315, "w": "in the lap of luxury", "c": "生活在奢华中", "e": "living in conditions of great comfort and luxury"},
{"r": 316, "w": "no peace for the wicked", "c": "只有作恶者才会没有平静", "e": "Constant troubles or difficulties that are believed to be a consequence of one's bad actions or behavior."},
{"r": 317, "w": "no rest for the wicked", "c": "非常忙碌，没有时间休息", "e": "constant work or activity, especially when one is considered guilty or deserving of punishment"},
{"r": 318, "w": "grin like a cheshire cat", "c": "面带贼笑，展示出特别开心或者暗示有某种计谋或秘密", "e": "to have a big, wide, and often mysterious or mischievous smile on one's face"},
{"r": 319, "w": "draw a bead on", "c": "准确地瞄准或锁定目标", "e": "to take aim at or focus on something or someone"},
{"r": 320, "w": "big frog in a small pond", "c": "自誇自大，過於自信，但實際上只在小圈子中有影響力或表現出色", "e": "To be a prominent or important person in a small or limited setting or group, but potentially insignificant or unimportant in a larger or more competitive context"},
{"r": 321, "w": "back to the grind", "c": "回归辛苦工作，通常指假期结束后重新开始日常工作", "e": "returning to work or routine tasks after a period of leisure or relaxation"},
{"r": 322, "w": "grind to a halt", "c": "完全停下来；彻底停顿", "e": "to come to a complete stop, usually after a gradual decrease in speed or progress"},
{"r": 323, "w": "stab in the back", "c": "背后刺一刀", "e": "to betray or deceive someone, especially in a sneaky or underhanded way"},
{"r": 324, "w": "take a stab at", "c": "试着做某事，尝试做某事", "e": "to attempt or try something, often without much certainty or preparation"},
{"r": 325, "w": "a voice crying in the wilderness", "c": "無人聽從的呼聲", "e": "someone who is expressing an unpopular or ignored opinion or viewpoint"},
{"r": 326, "w": "for crying out loud", "c": "一个表示愤怒、惊讶或沮丧的说法", "e": "an expression of frustration or annoyance; used to emphasize a statement or command"},
{"r": 327, "w": "get out of a jam", "c": "摆脱困境，解决棘手的问题", "e": "to find a solution or escape from a difficult or problematic situation"},
{"r": 328, "w": "go on a wild goose chase", "c": "进行一场毫无意义或无法实现的努力或追求", "e": "to pursue a fruitless or unattainable task or quest"},
{"r": 329, "w": "from pillar to post", "c": "四处奔波，来回奔波", "e": "to be constantly moving or shifting from one place or situation to another without making any progress"},
{"r": 330, "w": "go to the mat", "c": "全力以赴；付出最大努力", "e": "to engage in a fierce and determined confrontation or fight, often to defend or support a particular cause or belief"},
{"r": 331, "w": "leave at the altar", "c": "在婚礼当天抛弃伴侣；突然取消婚礼", "e": "to cancel or break off a planned wedding or commitment at the last minute"},
{"r": 332, "w": "die on the vine", "c": "在发展的过程中停滞不前、失败或终止", "e": "to fail or be abandoned before it is completed or successful"},
{"r": 333, "w": "wash dirty linen in public", "c": "公开讨论或揭示私人的不愉快或不光彩的事情", "e": "to discuss private or embarrassing matters in public; to air one's grievances or disputes publicly"},
{"r": 334, "w": "close but no cigar", "c": "差一点点就达成目标，但最终没能成功", "e": "almost successful, but not quite"},
{"r": 335, "w": "smoke like a chimney", "c": "如烟囱般冒烟", "e": "to smoke heavily or excessively"},
{"r": 336, "w": "take a dim view of", "c": "对某事持负面或不支持的态度；对某事不满或不认同", "e": "To have a negative or unfavorable opinion of something or someone"},
{"r": 337, "w": "put someone out to pasture", "c": "让（某人）退休；让（某人）离职", "e": "to retire someone or remove them from their position of authority or responsibility due to age or incompetence"},
{"r": 338, "w": "have someone on toast", "c": "嘲笑或戏弄某人", "e": "to have complete control or power over someone"},
{"r": 339, "w": "par for the course", "c": "常规或平常的事物或行为", "e": "typical; to be expected; nothing out of the ordinary"},
{"r": 340, "w": "the bull in the bowler hat", "c": "难以置信或与众不同的人或事物", "e": "a clumsy or awkward person, typically someone who is imposing or self-important"},
{"r": 341, "w": "prop up the bar", "c": "支撑吧台，常表醉酒或沉迷酒精的行为", "e": "to stand or sit at a bar for an extended period of time, often drinking alcohol"},
{"r": 342, "w": "as high as a kite", "c": "非常兴奋或兴奋的状态", "e": "to be very intoxicated or under the influence of drugs"},
{"r": 343, "w": "high as a kite", "c": "非常兴奋或兴奋到无法自拔的状态", "e": "To be in a state of euphoria or extreme excitement, often due to the influence of drugs or alcohol"},
{"r": 344, "w": "religious about doing something", "c": "对某事非常认真和坚持的；对某事非常有信仰和虔诚的", "e": "to be extremely dedicated and committed to doing something consistently and faithfully"},
{"r": 345, "w": "gum up the works", "c": "阻碍或使事情变得混乱", "e": "to cause problems or disruptions in a process or system"},
{"r": 346, "w": "up a gum tree", "c": "陷入困境或无法解决问题", "e": "in a difficult or awkward situation with no clear or easy way out"},
{"r": 347, "w": "a red rag to a bull", "c": "激怒别人的事物或行为", "e": "something that is certain to provoke or irritate someone"},
{"r": 348, "w": "by a long chalk", "c": "明显地或大幅地胜过其他人或事物；远远优于其他人或事物", "e": "by a considerable amount; by a large margin"},
{"r": 349, "w": "like chalk and cheese", "c": "完全不同的两个事物", "e": "completely different or incompatible"},
{"r": 350, "w": "x marks the spot", "c": "宝贝就在这里", "e": "the exact location or place"},
{"r": 351, "w": "bring home the bacon", "c": "做出贡献或获得成功来维持生计", "e": "to earn a living, especially to provide for one's family and basic needs"},
{"r": 352, "w": "as keen as mustard", "c": "非常热衷、充满热情", "e": "to be very enthusiastic or eager about something"},
{"r": 353, "w": "foam at the mouth", "c": "大发雷霆，十分愤怒或激动，常常用来形容盲目的愤怒或激情", "e": "to express extreme anger, rage, or excitement"},
{"r": 354, "w": "as bald as a cue ball", "c": "非常秃头的意思", "e": "completely bald; having no hair at all"},
{"r": 355, "w": "miles to go before i sleep", "c": "睡觉之前还有很长的路要走", "e": "have a long way to go before achieving a goal or reaching a desired outcome"},
{"r": 356, "w": "beard the lion in his den", "c": "围攻并直面一个非常有权势或有影响力的人或团体", "e": "to confront someone in their own territory or domain"},
{"r": 357, "w": "like a bear with a sore head", "c": "情绪暴躁或易怒的样子", "e": "to be in a very bad mood or irritable"},
{"r": 358, "w": "stick out like a sore thumb", "c": "格格不入，引人注目", "e": "to be very noticeable or different from the surrounding people or things"},
{"r": 359, "w": "by the same token", "c": "出于同样的原因或逻辑", "e": "to indicate that the same logic or reasoning applies to a similar situation or point"},
{"r": 360, "w": "wipe the slate clean", "c": "将一切都忘记，重新开始", "e": "to start fresh, to remove all past mistakes or offenses and begin again with a clean record"},
{"r": 361, "w": "method to my madness", "c": "有目的地做事，尽管看起来不合常理", "e": "an unconventional or seemingly illogical approach or plan that actually has a hidden purpose or systematic logic"},
{"r": 362, "w": "kick up a fuss", "c": "大惊小怪；大惊小怪；大惊小怪", "e": "to make a big commotion or protest about something"},
{"r": 363, "w": "clean as a whistle", "c": "非常干净，一尘不染", "e": "completely clean or pure"},
{"r": 364, "w": "whistle in the dark", "c": "徒劳无益地试图保持镇静或充满信心", "e": "to remain optimistic or hopeful in a difficult or uncertain situation"},
{"r": 365, "w": "pick up the tab", "c": "承担费用或账单", "e": "to pay for something, especially when others were expecting to pay or share the cost"},
{"r": 366, "w": "icing on the cake", "c": "锦上添花", "e": "an additional benefit or pleasant surprise that enhances an already good situation"},
{"r": 367, "w": "the icing on the cake", "c": "锦上添花，意味着某事物的额外的好处或令人满意的东西", "e": "an additional pleasant or desirable feature or event that enhances an already good situation"},
{"r": 368, "w": "a fate worse than death", "c": "比死亡更糟糕的命运", "e": "an extremely bad or undesirable outcome or situation"},
{"r": 369, "w": "fish for a compliment", "c": "寻求恭维或称赞的赞美（通常是明显的）", "e": "to seek or attempt to elicit praise or admiration from others"},
{"r": 370, "w": "on the crest of a wave", "c": "处于事业或成功的巅峰状态", "e": "experiencing a period of great success or happiness"},
{"r": 371, "w": "cut somebody some slack", "c": "对某人宽容一些，减轻对某人的严厉批评或处罚", "e": "to be lenient or forgiving towards someone; to give someone a break or some leeway"},
{"r": 372, "w": "an axe to grind", "c": "别有目的地做某事，通常是出于个人利益或私人动机", "e": "to have a hidden personal agenda or ulterior motive"},
{"r": 373, "w": "square peg in a round hole", "c": "一个人或事物与其周围环境或情境不相配或不适应", "e": "someone who doesn't fit in a particular situation or environment"},
{"r": 374, "w": "hand something to someone on a silver platter", "c": "毫不费力地提供某物给某人；毫无努力地给某人提供某种机会或好处", "e": "to give or provide something to someone very easily or without any effort or struggle on their part"},
{"r": 375, "w": "on a silver platter", "c": "不费吹灰之力地；一帆风顺地", "e": "to have something handed to you easily or without effort"},
{"r": 376, "w": "a knight in shining armour", "c": "全副武装的骑士，通常指一个英勇和完美的男人", "e": "a person who comes to someone's aid or rescue; a heroic or chivalrous person"},
{"r": 377, "w": "knight in shining armour", "c": "一个勇敢、有魅力且有能力解救别人或提供帮助的人", "e": "someone who comes to the rescue or provides assistance, especially in a chivalrous and heroic manner"},
{"r": 378, "w": "up hill and down dale", "c": "跋山涉水，走遍山岗坡地", "e": "through a difficult or challenging journey or experience"},
{"r": 379, "w": "flat as a pancake", "c": "平坦如饼", "e": "completely level or without any variation"},
{"r": 380, "w": "saving for a rainy day", "c": "未雨绸缪；存钱以备不时之需", "e": "setting aside money or resources for future needs or emergencies"},
{"r": 381, "w": "at the drop of a dime", "c": "立刻或毫不犹豫地做某事", "e": "to do something immediately or without hesitation"},
{"r": 382, "w": "taking something for face value", "c": "只看表面的意思；只根据表面的外貌、外观、形象或事实来判断某物或某人", "e": "accepting something as it appears or is stated, without considering any hidden meanings or ulterior motives"},
{"r": 383, "w": "stubborn as a mule", "c": "像骡子一样固执", "e": "extremely stubborn or obstinate"},
{"r": 384, "w": "as the actress said to the bishop", "c": "如演员对主教所说的那样", "e": "a phrase used to humorously or sarcastically point out a potentially suggestive or double entendre comment"},
{"r": 385, "w": "on the brink of", "c": "在边缘，接近某个非常重要或危险的情况或事件", "e": "about to happen; on the verge of"},
{"r": 386, "w": "by the seat of your pants", "c": "凭直觉或者缺乏有关经验或知识的情况下去做某事", "e": "to do something by instinct or without a plan; to improvise or make decisions as you go along, often based on intuition rather than careful thought"},
{"r": 387, "w": "best thing since sliced bread", "c": "自上次面包切片以来最好的事物", "e": "Something that is considered to be excellent or exceptional; the best or most innovative thing"},
{"r": 388, "w": "the best thing since sliced bread", "c": "自面包切片以来最好的事物；非常好的事物", "e": "something or someone considered to be highly impressive or innovative"},
{"r": 389, "w": "pedal to the metal", "c": "全力以赴；加快速度；不留余地", "e": "to drive or work at full speed or maximum effort"},
{"r": 390, "w": "put the pedal to the metal", "c": "加快速度，尽全力做某事", "e": "to go as fast as possible; to accelerate or increase speed"},
{"r": 391, "w": "nine times out of ten", "c": "十之九都", "e": "almost always or in the majority of cases"},
{"r": 392, "w": "sign of the times", "c": "时代的象征；时代的标志；时代的特征", "e": "an indication or reflection of a particular period or era, typically showing current trends, attitudes, or events"},
{"r": 393, "w": "third times a charm", "c": "第三次才会成功", "e": "the third attempt or effort is likely to be successful or lucky"},
{"r": 394, "w": "champ at the bit", "c": "焦虑不安、渴望迫不及待地想要做某事", "e": "to be impatient or eager to start or do something"},
{"r": 395, "w": "go the whole hog", "c": "全力以赴做某事", "e": "to do something in a thorough or complete way; to give full effort or commitment to something"},
{"r": 396, "w": "high on the hog", "c": "生活得很舒适或享受很多奢侈品", "e": "to live luxuriously or enjoy the best of everything"},
{"r": 397, "w": "neck of the woods", "c": "附近地区或社区", "e": "a particular neighborhood or region; a specific area or vicinity"},
{"r": 398, "w": "out of the woods", "c": "摆脱危险或困境，安全无虞", "e": "to be out of danger or difficulty; to have escaped a challenging situation"},
{"r": 399, "w": "in the wink of an eye", "c": "一眨眼的功夫，非常快速的", "e": "very quickly or almost instantaneously"},
{"r": 400, "w": "nudge nudge wink wink", "c": "暗示、传达或交流隐含的信息或意图", "e": "to make an indirect reference or suggestion, often with a secretive or salacious undertone"},
{"r": 401, "w": "quick as a wink", "c": "非常迅速地；像眨眼一样快速", "e": "very fast or quickly, almost instantaneously"},
{"r": 402, "w": "cock and bull story", "c": "胡扯蛋白的故事", "e": "an unbelievable or far-fetched story that is likely to be untrue"},
{"r": 403, "w": "cock of the walk", "c": "自以为是、狂妄自大的人", "e": "Someone who assumes an air of superiority or dominance; someone who struts or boasts about their accomplishments or position."},
{"r": 404, "w": "on the same wavelength", "c": "在思想、感受或意见上保持一致的状态", "e": "to have a similar way of thinking or understanding"},
{"r": 405, "w": "give it a whirl", "c": "试一试；尝试一下", "e": "to try something, especially if it is new or uncertain; to give something a chance or attempt"},
{"r": 406, "w": "on the back burner", "c": "被搁置或暂时搁置", "e": "to be put aside or delayed, often in favor of more urgent or important matters"},
{"r": 407, "w": "swear like a trooper", "c": "咒骂不停", "e": "to use profane or vulgar language excessively"},
{"r": 408, "w": "cool as a cucumber", "c": "非常冷静和自信", "e": "Calm and composed, especially in stressful situations"},
{"r": 409, "w": "not playing with a full deck", "c": "智商有问题，思路混乱，或者行为怪异", "e": "to be mentally impaired or lacking in intelligence or common sense"},
{"r": 410, "w": "the author of your own misfortune", "c": "自取灾难的罪魁祸首", "e": "to be responsible for causing one's own problems or difficulties"},
{"r": 411, "w": "economical with the truth", "c": "事实择善而去的方式；不完全坦白；故意隐瞒真相", "e": "to be dishonest or not completely truthful"},
{"r": 412, "w": "kick up a stink", "c": "大声抗议、制造麻烦、引起公愤或引起轩然大波", "e": "to create a commotion or uproar; to make a big fuss about something"},
{"r": 413, "w": "by hook or by crook", "c": "不择手段地", "e": "by any means necessary, often including dishonest or unscrupulous methods"},
{"r": 414, "w": "from the cradle to the grave", "c": "从出生到死亡; 终生", "e": "throughout one's entire life"},
{"r": 415, "w": "not bat an eyelid", "c": "面不改色地对待或回应令人吃惊或令人不满意的事情", "e": "to not show any surprise, emotion, or reaction"},
{"r": 416, "w": "sick as a parrot", "c": "非常失望或沮丧", "e": "extremely disappointed or unhappy"},
{"r": 417, "w": "call a spade a spade", "c": "说话直截了当，毫不讳言", "e": "to speak honestly and directly, even if it may be considered blunt or offensive"},
{"r": 418, "w": "fit as a fiddle", "c": "身体健康的，精神状况良好的", "e": "in excellent physical health"},
{"r": 419, "w": "fell off the back of a lorry", "c": "不合法获得的物品", "e": "obtained illegally or through dishonest means; stolen or counterfeit"},
{"r": 420, "w": "blow your own trumpet", "c": "自吹自擂，吹嘘自己的才能或成就", "e": "to boast about oneself or one's achievements"},
{"r": 421, "w": "thin as a rake", "c": "瘦如根麦草", "e": "extremely thin, skinny, or emaciated"},
{"r": 422, "w": "the sound of leather on willow", "c": "打板球的声音", "e": "referring to the sound made when the cricket ball hits the bat in cricket"},
{"r": 423, "w": "bun in the oven", "c": "怀孕", "e": "to be pregnant"},
{"r": 424, "w": "boots on the ground", "c": "面临实际问题或挑战，采取实际行动解决问题", "e": "the presence of military personnel on or near the battlefield; typically used to refer to the need for physical presence or action in a situation"},
{"r": 425, "w": "too big for your boots", "c": "自命不凡，傲慢自大", "e": "to have an exaggerated sense of one's own importance or abilities"},
{"r": 426, "w": "tough as old boots", "c": "非常坚韧或固执的", "e": "extremely tough or resilient"},
{"r": 427, "w": "pot calling the kettle black", "c": "自己也有同样缺点还指责别人缺点", "e": "hypocritical reproach; accusing someone of a fault or action that one is guilty of themselves"},
{"r": 428, "w": "the pot calling the kettle black", "c": "以貌相人，无视自己的相同缺点而批评他人", "e": "to criticize or accuse someone of a fault or wrongdoing that one is also guilty of"},
{"r": 429, "w": "come down the pike", "c": "出现或出现在某人的视野中", "e": "to appear or become noticeable, usually in a significant or important way"},
{"r": 430, "w": "leave someone in the lurch", "c": "将某人撇在一旁; 抛弃某人", "e": "to abandon, betray, or leave someone in a difficult or challenging situation without any assistance or support"},
{"r": 431, "w": "paddle one's own canoe", "c": "独立自主，自力更生", "e": "to be self-reliant and independent; to take care of one's own affairs"},
{"r": 432, "w": "paddle your own canoe", "c": "独立自主地去处理自己的事情", "e": "to be self-reliant; to take responsibility for one's own actions and decisions"},
{"r": 433, "w": "up shit creek without a paddle", "c": "陷入困境且没有任何帮助或解决办法", "e": "To be in a very difficult or challenging situation with no solution or help available"},
{"r": 434, "w": "cuckoo in the nest", "c": "喧宾夺主；闯入他人的圈子或活动中", "e": "an unwanted or intrusive person or thing in a place or situation where they do not belong"},
{"r": 435, "w": "sealed with a kiss", "c": "以一个吻来确认或完成某事", "e": "to be confirmed, finalized, or made official, especially in a romantic or intimate context"},
{"r": 436, "w": "shuffle off this mortal coil", "c": "摆脱这个尘世的束缚；离开人世", "e": "to die"},
{"r": 437, "w": "from stem to stern", "c": "从头到尾；彻底地；完全地", "e": "\"from one end to the other\" or \"thoroughly\""},
{"r": 438, "w": "off the beaten track", "c": "偏僻或少被人所知的地方", "e": "away from the usual or popularly traveled routes; in a remote or less common location"},
{"r": 439, "w": "chill to the marrow", "c": "使人非常恐惧或寒冷到骨子里", "e": "to be extremely cold or frightened"},
{"r": 440, "w": "a thorn in my flesh", "c": "令人痛苦或苦恼的事物或人", "e": "someone or something that causes constant annoyance, frustration, or difficulty"},
{"r": 441, "w": "out of the frying pan and into the fire", "c": "从一种糟糕的情况转到另一种糟糕的情况", "e": "going from a bad or difficult situation to an even worse one"},
{"r": 442, "w": "out of the frying pan into the fire", "c": "从一个困境或麻烦中进入另一个更严重的困境或麻烦；事情变得更糟糕", "e": "to go from a bad or difficult situation to an even worse one"},
{"r": 443, "w": "tip of the iceberg", "c": "冰山一角", "e": "a small, noticeable part or aspect of a larger, more complex issue or problem"},
{"r": 444, "w": "as happy as a clam", "c": "非常开心", "e": "to be very happy or content"},
{"r": 445, "w": "happy as a clam", "c": "非常快乐；非常满足", "e": "extremely happy and content"},
{"r": 446, "w": "like riding a bicycle", "c": "像骑自行车一样", "e": "something that you can do easily or effortlessly, even after a long period of not doing it"},
{"r": 447, "w": "all hell broke loose", "c": "局势变得混乱或失控", "e": "chaos or extreme disorder ensued"},
{"r": 448, "w": "put someone on a pedestal", "c": "把某人捧在鼻孔里; 过分崇拜或推崇某人", "e": "To greatly admire or idealize someone, often to the point of placing them above criticism or fault"},
{"r": 449, "w": "arrow in the quiver", "c": "预先准备好的计划或手段", "e": "an additional resource or option available for future use"},
{"r": 450, "w": "strain at the leash", "c": "迫不及待；急切地想要做某事", "e": "to eagerly or impatiently desire to do something or be free to do something"},
{"r": 451, "w": "easy as falling off a log", "c": "十拿九稳、易如反掌", "e": "extremely easy or effortless"},
{"r": 452, "w": "hitch one's wagon to a star", "c": "把希望寄托在别人或别的事物上来取得成功或获得幸福", "e": "to strive for ambitious goals and align oneself with successful or influential people"},
{"r": 453, "w": "just what the doctor ordered", "c": "非常适合或正是需要的东西", "e": "exactly what is needed or desired in a particular situation"},
{"r": 454, "w": "woman of ill repute", "c": "声誉不佳的女性", "e": "a woman who is considered to have a bad reputation, often associated with engaging in promiscuous or immoral behavior"},
{"r": 455, "w": "beat a hasty retreat", "c": "匆忙逃离，急忙撤退", "e": "to quickly leave a place or situation in order to avoid something unpleasant or dangerous"},
{"r": 456, "w": "fall on stony ground", "c": "无人理解或接受，无法产生任何影响", "e": "to be received with little or no interest or enthusiasm"},
{"r": 457, "w": "work like a beaver", "c": "努力工作，非常努力，尤其是在完成任务或目标方面", "e": "to work very hard and diligently"},
{"r": 458, "w": "wither on the vine", "c": "在葡萄藤上枯萎，形容某事由于缺乏支持或关注而失败", "e": "to fail, decline, or deteriorate due to neglect or lack of attention"},
{"r": 459, "w": "tar with the same brush", "c": "用同一把毛刷涂抹沥青", "e": "to consider or treat everyone in a particular group as having the same negative characteristics or faults"},
{"r": 460, "w": "up with the lark", "c": "起得很早；习惯于早起", "e": "to wake up or be active early in the morning"},
{"r": 461, "w": "snug as a bug in a rug", "c": "温暖舒适，安全舒适", "e": "very comfortable and cozy"},
{"r": 462, "w": "birds of a feather", "c": "品位或兴趣相似的人们聚集在一起", "e": "people who are similar in character, interests, or background"},
{"r": 463, "w": "to get bent out of shape", "c": "变得非常生气或心烦意乱", "e": "to become overly upset, angry, or annoyed"},
{"r": 464, "w": "soaked to the bone", "c": "全身湿透", "e": "completely wet"},
{"r": 465, "w": "about as useful as a chocolate teapot", "c": "一点用处都没有", "e": "completely useless or ineffective"},
{"r": 466, "w": "snake in one's bosom", "c": "身边的危险或背叛者", "e": "someone who pretends to be supportive or friendly but is actually deceitful or treacherous"},
{"r": 467, "w": "nothing to sneeze at", "c": "不可小视；值得重视", "e": "something that is significant or important; not to be underestimated"},
{"r": 468, "w": "err on the side of", "c": "站在...的一边，选择更安全或保守的做法", "e": "to choose a more cautious or safe option in a situation"},
{"r": 469, "w": "mecca for someone or something", "c": "某人或某事物的朝圣地", "e": "a place or destination that is highly revered or sought after by someone or something"},
{"r": 470, "w": "creme de la creme", "c": "最优秀、最出色的人或事物", "e": "the best of the best; the top or highest quality"},
{"r": 471, "w": "bear the brunt of", "c": "承受...的主要冲击或责任", "e": "to be the one who experiences the worst or most severe part of something, especially criticism or blame"},
{"r": 472, "w": "stand in a good stead", "c": "对某人或某事非常有帮助或有益", "e": "to be of great benefit or advantage to someone in the future"},
{"r": 473, "w": "stand someone in good stead", "c": "对某人非常有好处，特别是在将来的时候", "e": "to be of great benefit or advantage to someone in the future"},
{"r": 474, "w": "flog a dead horse", "c": "白费力气，做徒劳无益的事情", "e": "to persistently pursue or continue with a task or argument that is futile or pointless"},
{"r": 475, "w": "skating on thin ice", "c": "冒险，进行一项危险或不确定的行动", "e": "taking a risky or dangerous course of action; pushing the limits or boundaries"},
{"r": 476, "w": "chalk something up to inexperience", "c": "归咎于经验不足", "e": "to attribute something to a lack of experience or knowledge"},
{"r": 477, "w": "crux of the matter", "c": "问题的关键", "e": "the most important or crucial part of a problem, issue, or situation"},
{"r": 478, "w": "hide light under a bushel", "c": "掩饰或让自己的才能或优点不为人所知", "e": "to hide one's talents or achievements"},
{"r": 479, "w": "put your oar in", "c": "插手或干预他人的事务", "e": "to interfere or meddle in a situation or conversation, often unwelcome or without invitation"},
{"r": 480, "w": "grouse about someone or something", "c": "抱怨某人或某事", "e": "To complain or grumble about someone or something"},
{"r": 481, "w": "on a hiding to nothing", "c": "没有任何可能成功的事情，而只会遭受失败和困扰", "e": "engaging in a task or endeavor that is bound to fail or have no chance of success"},
{"r": 482, "w": "neither fish nor fowl", "c": "既非鱼亦非禽；不属于任何一种类别；有些人或物难分类", "e": "something or someone that does not belong to any specific group or category"},
{"r": 483, "w": "tempest in a teapot", "c": "一场小题大做的争吵或争议", "e": "an overblown or exaggerated response or concern to a small or unimportant issue or problem"},
{"r": 484, "w": "fit to be tied", "c": "非常生气或激动，情绪无法控制", "e": "extremely angry or agitated"},
{"r": 485, "w": "take up the gauntlet", "c": "接受挑战；勇敢应对困难", "e": "to accept a challenge or invitation, especially in a determined or defiant manner"},
{"r": 486, "w": "throw down the gauntlet", "c": "接受挑战", "e": "to issue a challenge"},
{"r": 487, "w": "spanner in the works", "c": "干扰或阻碍计划或进程的人或事物", "e": "an unexpected or disruptive obstacle or problem"},
{"r": 488, "w": "sign on the dotted line", "c": "在指定的地方签字，表示同意或接受某个协议或合同", "e": "to formally agree or commit to something, especially by signing a contract or agreement"},
{"r": 489, "w": "take the gilt off the gingerbread", "c": "把事物的吸引力或乐趣削弱或破坏", "e": "to reveal the negative or less appealing aspects of something that initially seemed appealing or attractive"},
{"r": 490, "w": "memory like a sieve", "c": "记忆像筛子一样", "e": "having a poor or unreliable memory"},
{"r": 491, "w": "fish in troubled waters", "c": "趁混乱时期进行活动；趁乱捞取利益", "e": "To take advantage of a chaotic or tense situation for personal gain"},
{"r": 492, "w": "pour oil on troubled waters", "c": "平息争端或冲突，使局势平和", "e": "to calm or soothe a tense or difficult situation"},
{"r": 493, "w": "up to the hilt", "c": "完全、彻底地", "e": "completely or fully involved or committed to something"},
{"r": 494, "w": "put on the ritz", "c": "摆阔贵族派头；摆出一副富丽堂皇的样子", "e": "to dress or behave in an elegant or extravagant manner"},
{"r": 495, "w": "zenith of career or life", "c": "职业或生活的巅峰，达到最高点", "e": "the peak or highest point of one's career or life"},
{"r": 496, "w": "high man on the totem pole", "c": "天梯上的高位者", "e": "the person with the highest rank or authority in a group or organization"},
{"r": 497, "w": "low man on the totem pole", "c": "底层的人或职位", "e": "the person with the least authority or status in a group or organization"},
{"r": 498, "w": "meat and two veg", "c": "非常基本或平凡的食物或事物；普通或无聊之物", "e": "\"meat and two veg\" is a vulgar slang phrase that refers to a traditional British meal consisting of a main course of meat with two accompanying vegetables. However, it is often used as a euphemism to refer to male genitalia."},
{"r": 499, "w": "play hardball with someone", "c": "对某人采取强硬手段", "e": "to be tough, aggressive, or uncompromising in dealing with someone in a competitive situation"},
{"r": 500, "w": "cog in the machine", "c": "机器中的一只齿轮", "e": "an unimportant or insignificant person in a larger system or organization"},
{"r": 501, "w": "hear it on the grapevine", "c": "\"从传言中听到\" (从他人的传闻中得知某事情)", "e": "to learn or receive information from unofficial or informal sources"},
{"r": 502, "w": "hear on the grapevine", "c": "通过非正式渠道、传闻或谣言听到一件事情", "e": "to hear rumors or information indirectly or through gossip"},
{"r": 503, "w": "a bit of fluff", "c": "一个没用的人或物，特别是指与某人有短暂而不重要的感情关系的人", "e": "a person, especially a woman, who is considered to be attractive but not very intelligent or interesting"},
{"r": 504, "w": "fall by the wayside", "c": "失去兴趣、放弃或失败，不能坚持到底", "e": "to fail to continue or succeed in something"},
{"r": 505, "w": "a storm in a teacup", "c": "小题大做；无风起浪", "e": "an overreaction to a small or insignificant issue"},
{"r": 506, "w": "let the genie out of the bottle", "c": "放出无法收回的问题或后果", "e": "to do something that cannot be reversed; to reveal or unleash something powerful or uncontrollable"},
{"r": 507, "w": "every nook and cranny", "c": "每个角落和缝隙", "e": "every small or hidden place, every part or corner; everywhere"},
{"r": 508, "w": "put a damper on", "c": "扫兴；使兴致低落", "e": "to discourage, hinder, or spoil something, usually by suppressing enthusiasm or excitement"},
{"r": 509, "w": "bounce off the walls", "c": "非常兴奋或过分兴奋", "e": "to be extremely excited, hyperactive, or restless"},
{"r": 510, "w": "all over bar the shouting", "c": "胜券在握；胜利在望", "e": "all the essential or important parts or elements are completed or settled"},
{"r": 511, "w": "a sledgehammer to crack a nut", "c": "用大砲打蚊子", "e": "using excessive force or taking extreme measures to solve a relatively small problem"},
{"r": 512, "w": "use a sledgehammer to crack a nut", "c": "用重武器对付简单的问题或情况", "e": "to use excessive or unnecessary force to solve a simple or straightforward problem"},
{"r": 513, "w": "dyed in the wool", "c": "坚定不移的，根深蒂固的", "e": "firm or steadfast in one's beliefs or opinions, especially when it comes to a particular topic or ideology"},
{"r": 514, "w": "a needle in a haystack", "c": "大海捞针", "e": "something that is very difficult or impossible to find or locate"},
{"r": 515, "w": "dog in the manger", "c": "自己不想要或者不需要，但是也不供给别人使用的东西", "e": "someone who selfishly prevents others from using or enjoying something that they themselves have no use for"},
{"r": 516, "w": "saved by the bell", "c": "乘时救援", "e": "to be rescued or helped at the last possible moment"},
{"r": 517, "w": "all dressed up and nowhere to go", "c": "打扮得漂漂亮亮却无处可去", "e": "being prepared for a special event or occasion, but having no opportunity or purpose to use it"},
{"r": 518, "w": "look like mutton dressed as lamb", "c": "穿着装扮不合适年龄的人", "e": "to look older or inappropriate in one's appearance or clothing"},
{"r": 519, "w": "mutton dressed as lamb", "c": "年长的人穿着过于年轻化，或不适合自己的衣物", "e": "refers to an older woman who is dressed in a style more suitable for a younger woman, usually implying that she is trying too hard to appear younger or more attractive than she actually is"},
{"r": 520, "w": "grist to the mill", "c": "给磨坊带来了磨粉的原料或利益，引申为给某事物带来好处或利益", "e": "valuable or useful material or information that can be used to one's advantage"},
{"r": 521, "w": "joined at the hip", "c": "紧密结合或密切相关", "e": "extremely close or inseparable"},
{"r": 522, "w": "mind your own beeswax", "c": "管好自己的事情；別插手别人的事情", "e": "to mind your own business; to not interfere in other people's affairs"},
{"r": 523, "w": "nutty as a fruitcake", "c": "疯疯癫癫的", "e": "to be crazy or eccentric"},
{"r": 524, "w": "toot one's own horn", "c": "自吹自擂，自夸，吹嘘自己的成就或能力", "e": "to boast or brag about one's own achievements or abilities"},
{"r": 525, "w": "caught in a time warp", "c": "被困在过去的时空中；停滞不前；无法适应现代化", "e": "stuck or trapped in a place or situation that seems to be from a different era or time period"},
{"r": 526, "w": "caught in the crossfire", "c": "陷入两边争斗或争论之中", "e": "being involved in a conflict or disagreement between two or more parties, often resulting in being unfairly blamed or affected"},
{"r": 527, "w": "from a to z", "c": "从头到尾地、完整地", "e": "to encompass or cover everything; from beginning to end"},
{"r": 528, "w": "cruising for a bruising", "c": "寻找麻烦或争吵", "e": "seeking trouble or provoking a confrontation"},
{"r": 529, "w": "separate the wheat from the chaff", "c": "把好的和坏的分离开来；筛出可取的或有价值的东西，并丢弃不好的或无价值的东西", "e": "to distinguish the valuable or important from the worthless or unimportant"},
{"r": 530, "w": "to the nth degree", "c": "到了极点、极度、极端的程度", "e": "to the highest or greatest extent possible"},
{"r": 531, "w": "it is a deal", "c": "这是一笔交易", "e": "an agreement or arrangement has been made and is agreed upon"},
{"r": 532, "w": "one's word is law", "c": "某人的话就是法律，必须遵守或依从某人的命令或决定", "e": "to have absolute authority or control; to be in a position of power where one's decisions or commands must be obeyed"},
{"r": 533, "w": "poverty is no sin", "c": "贫穷并非罪过", "e": "Being poor is not a moral fault or a shameful thing"},
{"r": 534, "w": "the bottom line is", "c": "最重要的是；归根结底", "e": "the most important or fundamental aspect or point"},
{"r": 535, "w": "the die is cast", "c": "决定已被做出，无法更改", "e": "the decision is made and cannot be changed; the future or outcome is determined and cannot be altered"},
{"r": 536, "w": "the jury is out", "c": "还没有定论或决定", "e": "the judgment or decision is still pending; it is unclear or undecided"},
{"r": 537, "w": "the rest is history", "c": "其余的事情都是众所周知的", "e": "referring to a well-known or well-documented event or outcome that is considered common knowledge"},
{"r": 538, "w": "your name is mud", "c": "你声名狼藉、遭到普遍唾弃", "e": "to have a bad reputation; to be disliked or discredited"},
{"r": 539, "w": "your number is up", "c": "你的时间到了；你的命运即将结束", "e": "to be about to die or experience something negative or unfortunate"},
{"r": 540, "w": "go for the jugular", "c": "直截了当地攻击或利用对方最脆弱的部分来取得胜利", "e": "to attack or confront someone or something in a direct and ruthless manner"},
{"r": 541, "w": "as mad as a hatter", "c": "疯疯癫癫的，疯狂的", "e": "to be crazy or insane"},
{"r": 542, "w": "something nasty in the woodshed", "c": "某种不愉快或不为人知的秘密或不良行为", "e": "a dark or scandalous secret"},
{"r": 543, "w": "throw the baby out with the bathwater", "c": "过度舍弃，抛弃中间或有价值的东西，只保留不值得或无用的东西", "e": "to get rid of something valuable or important while trying to eliminate something undesirable"},
{"r": 544, "w": "as bald as a coot", "c": "非常秃头的人", "e": "completely bald"},
{"r": 545, "w": "call off the dogs", "c": "停止攻击或追捕，取消或终止对某人或某事的追究或抨击", "e": "to stop pursuing or attacking someone; to end or cancel a search, investigation, or aggressive behavior towards someone or something"},
{"r": 546, "w": "go to the dogs", "c": "走向没落；变得越来越糟糕", "e": "to deteriorate or decline, especially in terms of quality or standards"},
{"r": 547, "w": "dead as a dodo", "c": "完全死去或消失，已经不复存在", "e": "completely extinct or obsolete"},
{"r": 548, "w": "give someone the runaround", "c": "敷衍某人，拖延某人", "e": "to avoid giving someone a direct answer or solution; to intentionally confuse or mislead someone in order to delay or frustrate them"},
{"r": 549, "w": "stick in your craw", "c": "令人感到不舒服、烦恼或难以接受的事情", "e": "to greatly irritate or be a source of ongoing annoyance"},
{"r": 550, "w": "take it on the lam", "c": "逃跑；逃离现场", "e": "to flee or escape, especially from the law or a dangerous situation"},
{"r": 551, "w": "keep your pecker up", "c": "保持乐观，坚持下去", "e": "keep your spirits up; stay positive"},
{"r": 552, "w": "go to hell in a handbasket", "c": "走向毁灭或衰败的状态", "e": "to deteriorate or become worse quickly"},
{"r": 553, "w": "going to hell in a handbasket", "c": "走向毁灭；日趋恶化", "e": "rapidly deteriorating or declining; heading towards a disastrous outcome"},
{"r": 554, "w": "it totally slipped my mind", "c": "完全忘记了", "e": "to completely forget about something"},
{"r": 555, "w": "shipshape and bristol fashion", "c": "整洁有序，一切井然有序", "e": "neat, clean, and organized; in good order"},
{"r": 556, "w": "cut the gordian knot", "c": "化解困境、解决问题的困难，通常是采取一个简单却充分有效的方法", "e": "to solve a difficult problem in a quick and decisive manner"},
{"r": 557, "w": "put the kibosh on", "c": "阻止或终止某事的发生，使其无法继续进行", "e": "to put an end to something or prevent it from happening"},
{"r": 558, "w": "head for the hills", "c": "迅速逃离或离开危险或困境的地方", "e": "to flee or escape quickly; to run away from a dangerous or unpleasant situation"},
{"r": 559, "w": "old as the hills", "c": "非常古老，存在已久", "e": "very old or ancient"},
{"r": 560, "w": "take to the hills", "c": "逃离危险；躲起来；逃亡", "e": "to flee or escape quickly; to run away or hide from a dangerous or threatening situation"},
{"r": 561, "w": "on the qui vive", "c": "警惕地注意，随时准备应对可能的危险或意外情况", "e": "being on high alert or watchful for something"},
{"r": 562, "w": "as nice as ninepence", "c": "非常整洁或有序的", "e": "to be very well-behaved or polite"},
{"r": 563, "w": "a little bird told me", "c": "有人告诉我", "e": "to have learned or obtained information from an unknown or secret source"},
{"r": 564, "w": "dead as a doornail", "c": "死得彻底，毫无生命迹象", "e": "completely lifeless or inanimate; beyond the point of no return; unmistakably and irrevocably dead"},
{"r": 565, "w": "easier said than done", "c": "说起来容易，做起来难", "e": "more difficult to do than to say; easier in theory than in practice"},
{"r": 566, "w": "the tail wagging the dog", "c": "小事烦扰大事", "e": "when a small or secondary part of something dominates or controls the whole"},
{"r": 567, "w": "kill the fatted calf", "c": "盛情款待某人，尤指欢迎热烈地迎接某人的到来", "e": "to celebrate extravagantly, especially after a long absence"},
{"r": 568, "w": "cat got your tongue", "c": "说不出话来，因为紧张或害怕而沉默不语", "e": "to be unable to speak or respond, often due to surprise or embarrassment"},
{"r": 569, "w": "you got me there", "c": "你搞糊涂了我的思维；我无法回答或辩解", "e": "to admit that someone has stumped or confused you; to acknowledge that you don't know the answer or solution to something"},
{"r": 570, "w": "i'll eat my hat", "c": "我将吃掉我的帽子", "e": "an expression of disbelief or doubt, often used when someone makes a statement that seems unlikely or impossible"},
{"r": 571, "w": "a bed of roses", "c": "一切都很容易或很愉快的情况", "e": "an easy or comfortable situation"},
{"r": 572, "w": "a bigger bang for your buck", "c": "用少量的花费获得更多的回报", "e": "getting a greater value, benefit, or outcome in relation to the amount of money or effort invested"},
{"r": 573, "w": "a bunch of fives", "c": "一拳", "e": "a forceful punch or hit with a closed fist"},
{"r": 574, "w": "a dish fit for the gods", "c": "非常美味或诱人的食物", "e": "an exceptionally delicious or impressive dish"},
{"r": 575, "w": "a load of cobblers", "c": "一堆胡言乱语或无意义的话", "e": "nonsense or rubbish; something that is not believable or of poor quality"},
{"r": 576, "w": "a load of codswallop", "c": "完全胡扯的一堆话", "e": "nonsense or something that is completely untrue or unbelievable"},
{"r": 577, "w": "a lost ball in the weeds", "c": "茫然无助；不知所措", "e": "to be in a difficult or hopeless situation with little chance of success or rescue"},
{"r": 578, "w": "a man of few words", "c": "少言寡语的人", "e": "someone who does not talk much, someone who is not very talkative"},
{"r": 579, "w": "a penny for your thoughts", "c": "请让我知道你在想什么", "e": "an expression used to ask someone what they are thinking about or to invite them to share their thoughts or opinions"},
{"r": 580, "w": "a picture paints a thousand words", "c": "一图胜千言", "e": "Visual imagery is often more powerful or effective in conveying a message or expressing a concept than words alone."},
{"r": 581, "w": "a safe pair of hands", "c": "一个可靠的人，能够信任的人", "e": "someone who can be relied upon to do a task or handle a situation competently and responsibly"},
{"r": 582, "w": "a sight for sore eyes", "c": "一见到就让人心情愉快或感到欣慰的人、事或物", "e": "something or someone that is very pleasing, comforting, or refreshing to see"},
{"r": 583, "w": "a snowball's chance in hell", "c": "不可能成功的机会或可能性", "e": "almost no chance at all"},
{"r": 584, "w": "a wolf in sheep's clothing", "c": "伪装的狼，指的是外表善良，内心狡猾的人", "e": "someone who appears harmless or friendly but is actually dangerous or deceitful"},
{"r": 585, "w": "a woman of few words", "c": "说话不多的女人", "e": "someone who speaks very little or is not talkative"},
{"r": 586, "w": "add fuel to the flames", "c": "火上加油；煽风点火", "e": "to make a bad situation worse"},
{"r": 587, "w": "ain't my first rodeo", "c": "这不是我第一次经历，我有经验", "e": "experienced; not easily fooled or taken advantage of"},
{"r": 588, "w": "all bets are off", "c": "一切皆无法预测，没有确定性或保证", "e": "to imply that previously established rules or expectations no longer apply"},
{"r": 589, "w": "all one's eggs in one basket", "c": "把所有的希望或资源都集中在一个地方或一个事物上", "e": "to put all of one's resources or hopes into a single, risky endeavor, rather than diversifying or spreading them out"},
{"r": 590, "w": "all things being equal", "c": "在一切情况都相等的条件下", "e": "assuming that all conditions are the same; in a fair and unbiased situation"},
{"r": 591, "w": "all walks of life", "c": "各行各业的人；来自不同背景或行业的人", "e": "people from all different backgrounds and social statuses"},
{"r": 592, "w": "apple of somebody's eye", "c": "某人心目中的宠儿或宝贝；被某人特别喜爱和关注的人或物", "e": "someone or something that is greatly cherished or loved"},
{"r": 593, "w": "armed to the teeth", "c": "全副武装", "e": "being heavily armed or well-equipped, often to an excessive or extreme degree"},
{"r": 594, "w": "as the crow flies", "c": "直线距离，不计较道路或障碍物的飞行距离", "e": "the shortest or most direct route between two points"},
{"r": 595, "w": "at a loss for words", "c": "无言以对；语塞；不知道说什么好", "e": "unable to speak or express oneself, typically due to shock, surprise, or confusion"},
{"r": 596, "w": "at a snail's pace", "c": "非常缓慢地进行或发展", "e": "to move or progress very slowly"},
{"r": 597, "w": "at sixes and sevens", "c": "混乱、杂乱无章或不协调的状态", "e": "to be in a state of confusion or disorder"},
{"r": 598, "w": "at your mother's knee", "c": "在母亲的膝上", "e": "learning from someone, typically a parent, at a young age; being influenced or shaped by someone's teachings or guidance from a young age"},
{"r": 599, "w": "away with the fairies", "c": "心不在焉；恍惚不实", "e": "to be lost in one's own thoughts or daydreaming; to be absent-minded or not paying attention"},
{"r": 600, "w": "back on one's feet", "c": "恢复健康，重新站起来", "e": "to recover from a difficult situation, typically referring to regaining financial stability or physical well-being"}
];
