/* English slang, hand-curated and tagged by where it is actually used.
   { r, w, c:Chinese, e:English meaning, nat:American|British|Australian|General }

   "General" means current across the main English-speaking countries. The rest
   are strongly associated with one of them — a British speaker understands
   "bail" and an American understands "knackered", but neither would say it.

   Deliberately excluded: vulgar terms, slurs, and words whose meaning flips
   between countries in a way that would embarrass a learner. */
window.SLANG = [
{"r": 1, "w": "knackered", "c": "累坏了，精疲力尽", "e": "extremely tired", "nat": "British"},
{"r": 2, "w": "gutted", "c": "非常失望，心都碎了", "e": "bitterly disappointed", "nat": "British"},
{"r": 3, "w": "chuffed", "c": "非常高兴，得意", "e": "very pleased", "nat": "British"},
{"r": 4, "w": "cheeky", "c": "顽皮的，放肆的；（指饮食）随性来一份", "e": "playfully rude; a casual indulgence", "nat": "British"},
{"r": 5, "w": "dodgy", "c": "靠不住的，可疑的", "e": "unreliable or suspicious", "nat": "British"},
{"r": 6, "w": "faff", "c": "瞎忙，磨蹭", "e": "to waste time on trivial things", "nat": "British"},
{"r": 7, "w": "gobsmacked", "c": "目瞪口呆", "e": "utterly astonished", "nat": "British"},
{"r": 8, "w": "kip", "c": "小睡，打盹", "e": "a short sleep", "nat": "British"},
{"r": 9, "w": "quid", "c": "英镑", "e": "one pound sterling", "nat": "British"},
{"r": 10, "w": "skint", "c": "身无分文", "e": "having no money", "nat": "British"},
{"r": 11, "w": "bloke", "c": "家伙，男人", "e": "a man", "nat": "British"},
{"r": 12, "w": "naff", "c": "土气的，劣质的", "e": "tacky or of poor quality", "nat": "British"},
{"r": 13, "w": "peckish", "c": "有点饿", "e": "slightly hungry", "nat": "British"},
{"r": 14, "w": "posh", "c": "上流的，高档的", "e": "upper-class or luxurious", "nat": "British"},
{"r": 15, "w": "telly", "c": "电视", "e": "television", "nat": "British"},
{"r": 16, "w": "wonky", "c": "歪的，不稳的，出毛病的", "e": "crooked or not working properly", "nat": "British"},
{"r": 17, "w": "brolly", "c": "雨伞", "e": "an umbrella", "nat": "British"},
{"r": 18, "w": "cuppa", "c": "一杯茶", "e": "a cup of tea", "nat": "British"},
{"r": 19, "w": "gaff", "c": "住处，家", "e": "one's home", "nat": "British"},
{"r": 20, "w": "mardy", "c": "闹脾气的，臭脸的", "e": "sulky or bad-tempered", "nat": "British"},
{"r": 21, "w": "nick", "c": "偷；逮捕", "e": "to steal; to arrest", "nat": "British"},
{"r": 22, "w": "sorted", "c": "搞定了，安排好了", "e": "dealt with, arranged", "nat": "British"},
{"r": 23, "w": "plonker", "c": "笨蛋，傻瓜", "e": "a fool", "nat": "British"},
{"r": 24, "w": "blimey", "c": "天哪（表示惊讶）", "e": "an exclamation of surprise", "nat": "British"},
{"r": 25, "w": "bants", "c": "互相调侃，玩笑话", "e": "playful teasing between friends", "nat": "British"},
{"r": 26, "w": "zonked", "c": "累瘫了", "e": "completely worn out", "nat": "British"},
{"r": 27, "w": "take the mickey", "c": "取笑，拿…开玩笑", "e": "to mock or tease someone", "nat": "British"},
{"r": 28, "w": "throw a wobbly", "c": "大发脾气", "e": "to lose one's temper", "nat": "British"},
{"r": 29, "w": "chat up", "c": "搭讪", "e": "to flirt with someone", "nat": "British"},
{"r": 30, "w": "shattered", "c": "累垮了", "e": "exhausted", "nat": "British"},
{"r": 31, "w": "dosh", "c": "钱", "e": "money", "nat": "British"},
{"r": 32, "w": "grub", "c": "食物，吃的", "e": "food", "nat": "British"},
{"r": 33, "w": "lurgy", "c": "小病，感冒", "e": "a minor illness", "nat": "British"},
{"r": 34, "w": "miffed", "c": "有点生气，不高兴", "e": "mildly annoyed", "nat": "British"},
{"r": 35, "w": "pear-shaped", "c": "（事情）搞砸了", "e": "gone badly wrong", "nat": "British"},
{"r": 36, "w": "bloke-ish", "c": "有男人味的，糙的", "e": "typically male in manner", "nat": "British"},
{"r": 37, "w": "waffle", "c": "废话连篇", "e": "to talk at length without saying much", "nat": "British"},
{"r": 38, "w": "whinge", "c": "抱怨，发牢骚", "e": "to complain persistently", "nat": "British"},
{"r": 39, "w": "bung", "c": "随手一扔，塞给", "e": "to put or throw casually", "nat": "British"},
{"r": 40, "w": "gutting", "c": "令人失望的", "e": "deeply disappointing", "nat": "British"},

{"r": 41, "w": "bail", "c": "放鸽子，中途溜走", "e": "to leave abruptly or cancel on someone", "nat": "American"},
{"r": 42, "w": "bucks", "c": "美元", "e": "dollars", "nat": "American"},
{"r": 43, "w": "salty", "c": "恼火的，不服气的", "e": "bitter or annoyed", "nat": "American"},
{"r": 44, "w": "shady", "c": "不可靠的，可疑的", "e": "dishonest or suspicious", "nat": "American"},
{"r": 45, "w": "sketchy", "c": "让人不放心的，可疑的", "e": "unsafe or dubious", "nat": "American"},
{"r": 46, "w": "bummer", "c": "扫兴的事，真倒霉", "e": "a disappointing thing", "nat": "American"},
{"r": 47, "w": "hyped", "c": "兴奋的，期待的", "e": "very excited", "nat": "American"},
{"r": 48, "w": "flake", "c": "放鸽子的人；爽约", "e": "an unreliable person; to cancel on someone", "nat": "American"},
{"r": 49, "w": "bust", "c": "抓获；弄坏；破产的", "e": "to catch or break; broke", "nat": "American"},
{"r": 50, "w": "jazzed", "c": "非常兴奋", "e": "enthusiastic and excited", "nat": "American"},
{"r": 51, "w": "swamped", "c": "忙得不可开交", "e": "overwhelmed with work", "nat": "American"},
{"r": 52, "w": "bail on", "c": "抛下…不管", "e": "to abandon a plan or person", "nat": "American"},
{"r": 53, "w": "psyched", "c": "特别期待，兴奋", "e": "excited and ready", "nat": "American"},
{"r": 54, "w": "bogus", "c": "假的，不合理的", "e": "fake or unfair", "nat": "American"},
{"r": 55, "w": "buck", "c": "一美元", "e": "one dollar", "nat": "American"},
{"r": 56, "w": "cram", "c": "临时抱佛脚，突击复习", "e": "to study intensively at the last minute", "nat": "American"},
{"r": 57, "w": "gig", "c": "临时工作，演出", "e": "a job, especially short-term or a performance", "nat": "American"},
{"r": 58, "w": "hang out", "c": "闲逛，一起消磨时间", "e": "to spend time casually", "nat": "American"},
{"r": 59, "w": "hit up", "c": "联系，找（某人）", "e": "to contact someone", "nat": "American"},
{"r": 60, "w": "kick back", "c": "放松，休息", "e": "to relax", "nat": "American"},
{"r": 61, "w": "lame", "c": "无聊的，逊的", "e": "boring or unimpressive", "nat": "American"},
{"r": 62, "w": "nuts", "c": "疯了的，荒唐的", "e": "crazy", "nat": "American"},
{"r": 63, "w": "pissed off", "c": "生气的，火大", "e": "angry", "nat": "American"},
{"r": 64, "w": "rip off", "c": "宰客，敲竹杠", "e": "to overcharge or cheat", "nat": "American"},
{"r": 65, "w": "screw up", "c": "搞砸", "e": "to make a bad mistake", "nat": "American"},
{"r": 66, "w": "shoot the breeze", "c": "闲聊", "e": "to chat idly", "nat": "American"},
{"r": 67, "w": "spill", "c": "透露内幕，说吧", "e": "to reveal information", "nat": "American"},
{"r": 68, "w": "totaled", "c": "（车）报废了", "e": "completely wrecked", "nat": "American"},
{"r": 69, "w": "veg out", "c": "什么都不干地放松", "e": "to relax doing nothing", "nat": "American"},
{"r": 70, "w": "wasted", "c": "喝多了，烂醉", "e": "very drunk", "nat": "American"},
{"r": 71, "w": "bail out", "c": "解困，救急", "e": "to rescue from trouble", "nat": "American"},
{"r": 72, "w": "ballpark", "c": "大致的范围", "e": "an approximate range", "nat": "American"},
{"r": 73, "w": "cheesy", "c": "俗气的，肉麻的", "e": "corny or tacky", "nat": "American"},
{"r": 74, "w": "flunk", "c": "考砸，挂科", "e": "to fail an exam or course", "nat": "American"},
{"r": 75, "w": "goof", "c": "犯傻，出错", "e": "to make a silly mistake", "nat": "American"},
{"r": 76, "w": "grand", "c": "一千美元", "e": "a thousand dollars", "nat": "American"},
{"r": 77, "w": "hassle", "c": "麻烦事；找麻烦", "e": "a nuisance; to bother someone", "nat": "American"},
{"r": 78, "w": "jonesing", "c": "特别想要，渴望", "e": "craving something badly", "nat": "American"},
{"r": 79, "w": "knock it off", "c": "别闹了，住手", "e": "stop that", "nat": "American"},
{"r": 80, "w": "no-brainer", "c": "显而易见的选择", "e": "an obvious decision", "nat": "American"},

{"r": 81, "w": "arvo", "c": "下午", "e": "afternoon", "nat": "Australian"},
{"r": 82, "w": "barbie", "c": "烧烤", "e": "a barbecue", "nat": "Australian"},
{"r": 83, "w": "bogan", "c": "土包子，粗人", "e": "an unsophisticated person", "nat": "Australian"},
{"r": 84, "w": "brekkie", "c": "早餐", "e": "breakfast", "nat": "Australian"},
{"r": 85, "w": "chockers", "c": "满满当当的", "e": "completely full", "nat": "Australian"},
{"r": 86, "w": "esky", "c": "保温箱，冰桶", "e": "a portable cooler", "nat": "Australian"},
{"r": 87, "w": "fair dinkum", "c": "真的，货真价实", "e": "genuine, true", "nat": "Australian"},
{"r": 88, "w": "footy", "c": "橄榄球，足球", "e": "football", "nat": "Australian"},
{"r": 89, "w": "g'day", "c": "你好", "e": "hello", "nat": "Australian"},
{"r": 90, "w": "heaps", "c": "很多，非常", "e": "lots; very", "nat": "Australian"},
{"r": 91, "w": "mozzie", "c": "蚊子", "e": "a mosquito", "nat": "Australian"},
{"r": 92, "w": "ripper", "c": "棒极了", "e": "excellent", "nat": "Australian"},
{"r": 93, "w": "servo", "c": "加油站", "e": "a petrol station", "nat": "Australian"},
{"r": 94, "w": "sickie", "c": "请病假（尤指装病）", "e": "a day off work claiming illness", "nat": "Australian"},
{"r": 95, "w": "snag", "c": "香肠", "e": "a sausage", "nat": "Australian"},
{"r": 96, "w": "stubby", "c": "小瓶啤酒", "e": "a short bottle of beer", "nat": "Australian"},
{"r": 97, "w": "sunnies", "c": "太阳镜", "e": "sunglasses", "nat": "Australian"},
{"r": 98, "w": "thongs", "c": "人字拖", "e": "flip-flops", "nat": "Australian"},
{"r": 99, "w": "ute", "c": "皮卡车", "e": "a utility vehicle or pickup", "nat": "Australian"},
{"r": 100, "w": "no worries", "c": "没问题，别客气", "e": "it's fine, no problem", "nat": "Australian"},
{"r": 101, "w": "spit the dummy", "c": "耍脾气，闹别扭", "e": "to throw a tantrum", "nat": "Australian"},
{"r": 102, "w": "chuck a sickie", "c": "装病请假", "e": "to take a day off pretending to be ill", "nat": "Australian"},
{"r": 103, "w": "bottle-o", "c": "酒类商店", "e": "a liquor shop", "nat": "Australian"},
{"r": 104, "w": "doona", "c": "羽绒被", "e": "a duvet", "nat": "Australian"},
{"r": 105, "w": "dunny", "c": "厕所", "e": "a toilet", "nat": "Australian"},
{"r": 106, "w": "maccas", "c": "麦当劳", "e": "McDonald's", "nat": "Australian"},
{"r": 107, "w": "reckon", "c": "觉得，认为", "e": "to think or suppose", "nat": "Australian"},
{"r": 108, "w": "rort", "c": "舞弊，占便宜", "e": "a scam or dishonest scheme", "nat": "Australian"},
{"r": 109, "w": "smoko", "c": "工间休息", "e": "a work break", "nat": "Australian"},
{"r": 110, "w": "tucker", "c": "食物", "e": "food", "nat": "Australian"},
{"r": 111, "w": "yakka", "c": "苦活，劳作", "e": "hard work", "nat": "Australian"},
{"r": 112, "w": "good on ya", "c": "干得好", "e": "well done", "nat": "Australian"},
{"r": 113, "w": "hard yakka", "c": "重体力活", "e": "hard physical work", "nat": "Australian"},
{"r": 114, "w": "she'll be right", "c": "没事的，会好的", "e": "it will turn out fine", "nat": "Australian"},
{"r": 115, "w": "flat out", "c": "忙得不可开交", "e": "extremely busy", "nat": "Australian"},

{"r": 116, "w": "awesome", "c": "太棒了", "e": "excellent", "nat": "General"},
{"r": 117, "w": "cool", "c": "酷，不错；可以", "e": "good, acceptable, stylish", "nat": "General"},
{"r": 118, "w": "buddy", "c": "伙伴，哥们儿", "e": "a friend", "nat": "General"},
{"r": 119, "w": "cash", "c": "现金，钱", "e": "money", "nat": "General"},
{"r": 120, "w": "crash", "c": "倒头就睡；借宿", "e": "to fall asleep; to stay overnight", "nat": "General"},
{"r": 121, "w": "mess up", "c": "弄糟，搞错", "e": "to do something badly", "nat": "General"},
{"r": 122, "w": "hit the road", "c": "出发，上路", "e": "to set off on a journey", "nat": "General"},
{"r": 123, "w": "wrap up", "c": "收尾，结束", "e": "to finish something off", "nat": "General"},
{"r": 124, "w": "broke", "c": "没钱的，破产的", "e": "having no money", "nat": "General"},
{"r": 125, "w": "chill", "c": "放松；冷静点", "e": "to relax; calm down", "nat": "General"},
{"r": 126, "w": "creepy", "c": "让人发毛的", "e": "unsettling or disturbing", "nat": "General"},
{"r": 127, "w": "freak out", "c": "吓坏了，慌了", "e": "to panic or overreact", "nat": "General"},
{"r": 128, "w": "geek", "c": "书呆子；发烧友", "e": "an enthusiast, especially technical", "nat": "General"},
{"r": 129, "w": "get it", "c": "懂了，明白", "e": "to understand", "nat": "General"},
{"r": 130, "w": "guts", "c": "胆量，勇气", "e": "courage", "nat": "General"},
{"r": 131, "w": "hang on", "c": "等一下", "e": "to wait", "nat": "General"},
{"r": 132, "w": "make it", "c": "赶上；成功", "e": "to arrive in time; to succeed", "nat": "General"},
{"r": 133, "w": "nail it", "c": "做得漂亮，一举拿下", "e": "to do something perfectly", "nat": "General"},
{"r": 134, "w": "pain", "c": "麻烦的人或事", "e": "an annoyance", "nat": "General"},
{"r": 135, "w": "pick up", "c": "学会；接（人）", "e": "to learn casually; to collect someone", "nat": "General"},
{"r": 136, "w": "pull off", "c": "成功办成（难事）", "e": "to manage something difficult", "nat": "General"},
{"r": 137, "w": "rip", "c": "撕；宰人的价格", "e": "to tear; an unfair price", "nat": "General"},
{"r": 138, "w": "sick of", "c": "受够了", "e": "tired of something", "nat": "General"},
{"r": 139, "w": "stuff", "c": "东西，玩意儿", "e": "things in general", "nat": "General"},
{"r": 140, "w": "take it easy", "c": "别急，放轻松", "e": "relax", "nat": "General"},
{"r": 141, "w": "tricky", "c": "棘手的", "e": "difficult to handle", "nat": "General"},
{"r": 142, "w": "weird", "c": "奇怪的", "e": "strange", "nat": "General"},
{"r": 143, "w": "wrecked", "c": "累垮的；毁了的", "e": "exhausted; ruined", "nat": "General"},
{"r": 144, "w": "come on", "c": "拜托，得了吧", "e": "an urging or disbelieving exclamation", "nat": "General"},
{"r": 145, "w": "big deal", "c": "了不起的事（常反讽）", "e": "something important, often said ironically", "nat": "General"},
{"r": 146, "w": "hang in there", "c": "坚持住", "e": "keep going despite difficulty", "nat": "General"},
{"r": 147, "w": "get away with", "c": "侥幸逃脱惩罚", "e": "to escape consequences", "nat": "General"},
{"r": 148, "w": "look out", "c": "小心", "e": "watch out", "nat": "General"},
{"r": 149, "w": "showing off", "c": "炫耀", "e": "displaying ability to impress", "nat": "General"},
{"r": 150, "w": "way too", "c": "太…了", "e": "excessively", "nat": "General"}
];
