/* English slang & colloquialisms (ECDICT). { r, w, c:Chinese, e:English }. */
window.SLANG = [
{"r": 1, "w": "molly", "c": "懦夫；娘娘腔的男人", "e": "n popular aquarium fish"},
{"r": 2, "w": "fella", "c": "小伙子；伙伴, 伙计", "e": "n a boy or man"},
{"r": 3, "w": "becky", "c": "上挂钩", "e": ""},
{"r": 4, "w": "bagel", "c": "百吉饼（先蒸后烤的发面圈）；（体育比赛中）零蛋", "e": "n. (Yiddish) glazed yeast-raised doughnut-shaped roll with hard crust"},
{"r": 5, "w": "temp", "c": "临时雇员", "e": "n. a worker (especially in an office) hired on a temporary basis"},
{"r": 6, "w": "barney", "c": "大吵大闹；拉曳器", "e": ""},
{"r": 7, "w": "tara", "c": "再会！", "e": "n. a village in eastern Ireland (northwest of Dublin); seat of Irish kings until 6th century"},
{"r": 8, "w": "goldberg", "c": "犹太老板（尤指在黑人聚居区开店或雇用黑人的）", "e": "n. United States cartoonist who drew intricate diagrams of very complicated and impractical contraptions that accomplished little or nothing (1883-1970)"},
{"r": 9, "w": "critter", "c": "家畜；马；牛；人", "e": "n. a regional term for `creature' (especially for domestic animals)"},
{"r": 10, "w": "git", "c": "饭桶", "e": "n a person who is deemed to be despicable or contemptible"},
{"r": 11, "w": "sched", "c": "（无线电）固定播送时间", "e": ""},
{"r": 12, "w": "butch", "c": "充当男性角色的女同性恋者；粗鲁的男人或男孩", "e": "n. (slang) offensive term for a lesbian who is noticeably masculine\\ns. used of men; markedly masculine in appearance or manner\\ns. (of male or female homosexuals) characterized by stereotypically male traits or appearance"},
{"r": 13, "w": "yuk", "c": "引起大笑的趣事；（因有趣而发出的）咯咯大笑", "e": ""},
{"r": 14, "w": "wonk", "c": "书呆子, 死用功的学生", "e": "n an insignificant student who is ridiculed as being affected or boringly studious"},
{"r": 15, "w": "hickey", "c": "器械；唇印；螺纹接合器；弯管器", "e": "n. a temporary red mark on a person's skin resulting from kissing or sucking by their lover"},
{"r": 16, "w": "twat", "c": "笨蛋；阴门；娘们儿", "e": "n a man who is a stupid incompetent fool\\nn obscene terms for female genitals"},
{"r": 17, "w": "boonies", "c": "郊区, 远离城市的原野", "e": ""},
{"r": 18, "w": "repro", "c": "复制品；再生产；繁殖", "e": ""},
{"r": 19, "w": "themself", "c": "他自己；其本身", "e": ""},
{"r": 20, "w": "pooped", "c": "筋疲力竭的", "e": "imp. & p. p. of Poop\\np. p. & a. Having a poop; furnished with a poop.\\np. p. & a. Struck on the poop."},
{"r": 21, "w": "buller", "c": "代理人(或讼师, 学监)的助手", "e": ""},
{"r": 22, "w": "snook", "c": "大拇指按鼻端, 其余四指张开以示轻蔑的手势", "e": "n. large tropical American food and game fishes of coastal and brackish waters; resemble pike"},
{"r": 23, "w": "mosh", "c": "狂舞", "e": "v dance the slam dance"},
{"r": 24, "w": "eff", "c": "弄糟", "e": "v have sexual intercourse with"},
{"r": 25, "w": "ragging", "c": "欺负, 开玩笑, 恶作剧, (学生的)胡闹", "e": "v treat cruelly\\nv cause annoyance in; disturb, especially by minor irritations\\nv play in ragtime\\nv harass with persistent criticism or carping\\nv censure severely or angrily\\nv break into lumps before sorting"},
{"r": 26, "w": "paki", "c": "巴基斯坦佬", "e": ""},
{"r": 27, "w": "sprog", "c": "新飞行员, 新兵, 新手", "e": "n. a new military recruit\\nn. a child"},
{"r": 28, "w": "aeriator", "c": "飞行员, 航空员", "e": ""},
{"r": 29, "w": "baby blues", "c": "1。（某些产妇的）产后伤感, 产后沮丧, 产后忧郁症", "e": ""},
{"r": 30, "w": "back at square one", "c": "回到原来的起点;回复原状", "e": ""},
{"r": 31, "w": "bakehead", "c": "火车司炉", "e": ""},
{"r": 32, "w": "beany", "c": "精神旺盛的, 狂妄的", "e": "n a small skullcap; formerly worn by schoolboys and college freshmen"},
{"r": 33, "w": "beerage", "c": "英国贵族", "e": ""},
{"r": 34, "w": "blubberhead", "c": "愚笨的人, 笨蛋", "e": ""},
{"r": 35, "w": "boatnik", "c": "水上人家, 船户", "e": ""},
{"r": 36, "w": "buns", "c": "人的臀部", "e": "n the fleshy part of the human body that you sit on\\nn small rounded bread either plain or sweet"},
{"r": 37, "w": "cheapie", "c": "便宜货；廉价品", "e": ""},
{"r": 38, "w": "cold fish", "c": "态度冷冰冰的人, 没有热情的人; 冷漠无情的人", "e": ""},
{"r": 39, "w": "con artist", "c": "骗子，以花言巧语骗人的人; 过上了舒适懒散生活的人", "e": ""},
{"r": 40, "w": "conmanship", "c": "骗术, 骗子手法", "e": ""},
{"r": 41, "w": "dipsydoodle", "c": "大幅度波动", "e": ""},
{"r": 42, "w": "do a ton", "c": "以每小时一百英里的高速疾驶", "e": ""},
{"r": 43, "w": "do the ton", "c": "以每小时一百英里的高速疾驶", "e": ""},
{"r": 44, "w": "dogood", "c": "(空想)改良社会的, 不切实际的", "e": ""},
{"r": 45, "w": "doodah", "c": "激动, 惊慌", "e": ""},
{"r": 46, "w": "exworks", "c": "出厂(指出厂价格或价值等)", "e": ""},
{"r": 47, "w": "flamer", "c": "火焰喷射器；公开的同性恋者", "e": ""},
{"r": 48, "w": "get-go", "c": "开端, 开始", "e": "n. the time at which something is supposed to begin"},
{"r": 49, "w": "goldmark", "c": "记录搜索接收机", "e": "n United States inventor (born in Hungary) who made the first TV broadcast in 1940 and invented the long-playing record in 1948 and pioneered videocassette recording (1906-1977)"},
{"r": 50, "w": "gongster", "c": "用锣声指挥交通的警察", "e": ""},
{"r": 51, "w": "gump", "c": "笨蛋, 傻儿", "e": "n. A dolt; a dunce."},
{"r": 52, "w": "gutshot", "c": "胃或腹部受到枪伤或炮击的伤口", "e": ""},
{"r": 53, "w": "hypering", "c": "过增感作用", "e": ""},
{"r": 54, "w": "jama", "c": "睡衣裤", "e": ""},
{"r": 55, "w": "mechs", "c": "机械化部队", "e": ""},
{"r": 56, "w": "mumbo jumbo", "c": "莫名其妙的话, 迷惑人的神秘活动, 巫术; 魔神", "e": ""},
{"r": 57, "w": "nother", "c": "各异的, 不同的", "e": "conj. Neither; nor."},
{"r": 58, "w": "pantata", "c": "要人, 老板, 头子", "e": ""},
{"r": 59, "w": "platformula", "c": "演讲八股", "e": ""},
{"r": 60, "w": "polk", "c": "跳波尔卡舞", "e": "n. 11th President of the United States; his expansionism led to the Mexican War and the annexation of California and much of the southwest (1795-1849)"},
{"r": 61, "w": "pongo", "c": "(非洲)类人猿, 黑猩猩", "e": "n. type genus of the family Pongidae: orangutans"},
{"r": 62, "w": "rats", "c": "胡说；瞎扯", "e": "n any of various long-tailed rodents similar to but larger than a mouse\\nn someone who works (or provides workers) during a strike\\nn a person who is deemed to be despicable or contemptible\\nn one who reveals confidential information in return for money\\nn a pad (usually made of hair) worn as part of a woman's coiffure\\nv desert one's party or group of friends, for example, for one's personal advantage\\nv employ scabs or strike breakers in\\nv take the place of work of someone on strike\\nv give (hair) the appearance of being fuller by using a rat\\nv catch rats, especially with dogs\\nv give away information about somebody"},
{"r": 63, "w": "romanish", "c": "罗马天主教(徒)的", "e": "a. Pertaining to Romanism."},
{"r": 64, "w": "romanism", "c": "天主教", "e": "n the beliefs and practices of the Catholic Church based in Rome"},
{"r": 65, "w": "rubout", "c": "谋杀；抹掉；擦掉", "e": ""},
{"r": 66, "w": "schmear", "c": "事情, 事件, 事物", "e": "n (Yiddish) a batch of things that go together"},
{"r": 67, "w": "sidy", "c": "高视阔步的, 趾高气扬的, 傲慢的", "e": ""},
{"r": 68, "w": "skiv", "c": "一镑(金币)", "e": ""},
{"r": 69, "w": "sloke", "c": "悄悄离去, 溜走", "e": "n. See Sloakan."},
{"r": 70, "w": "slurb", "c": "市郊贫民区", "e": ""},
{"r": 71, "w": "smouse", "c": "犹太人, (南非的)商贩", "e": ""},
{"r": 72, "w": "social climbing", "c": "结交权贵向上爬的做法", "e": ""},
{"r": 73, "w": "stockateer", "c": "推销或强销不可靠股票的经纪人", "e": ""},
{"r": 74, "w": "suicide seat", "c": "自杀座(指汽车驾驶座旁的座椅,因车祸时坐此位者最易伤亡而得名)", "e": ""},
{"r": 75, "w": "suicide squad", "c": "(橄榄球赛中负责开球和踢悬空球的)敢死队", "e": ""},
{"r": 76, "w": "sweal", "c": "烧光, 烧焦,蜡烛融化, 淌蜡", "e": "v. i. To melt and run down, as the tallow of a candle; to waste\\n away without feeding the flame.\\nv. t. To singe; to scorch; to swale; as, to sweal a pig by\\n singeing off the hair."},
{"r": 77, "w": "talking head", "c": "(电视中发言者的)头部特写;接受电视採访者;(电视在播放电影等时头部出现在屏幕上的)旁叙人", "e": ""},
{"r": 78, "w": "throwdown", "c": "拒绝, 败北, 失败", "e": ""},
{"r": 79, "w": "umptyumpth", "c": "很多(的), 几十几(的)(20, 21...99)", "e": ""},
{"r": 80, "w": "upalong", "c": "朝上, 向东方, 从西部", "e": ""},
{"r": 81, "w": "vandook", "c": "步枪", "e": ""}
];
