#!/usr/bin/env python3
"""Regenerate senses.js — Chinese meanings with an English label saying which
sense each one is.

ECDICT gives a flat list: "break" is `n. 休息, 中断, 破裂处 / vt. 打破, 弄坏…`,
and nothing says which Chinese goes with which meaning. Wiktionary's translation
tables do carry that label, so this layers them on top:

    v.  to separate into two or more pieces  ->  打破
    v.  of a bone: to crack                  ->  折, 骨折
    v.  to do that which is forbidden        ->  破戒, 犯戒
    n.  rest or pause, usually from work     ->  休息

Wiktionary covers fewer meanings than ECDICT, so this supplements rather than
replaces it — words.js stays the source of the full list.

Source: kaikki.org's machine-readable Wiktionary extract (CC BY-SA 4.0, the
same licence as Wiktionary itself). The extract is ~3 GB, so it is streamed and
filtered rather than stored.

Usage:
    curl -sL https://kaikki.org/dictionary/English/kaikki.org-dictionary-English.jsonl \\
      | python3 tools/build-senses.py
"""

import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PER_POS = 5             # at most this many labelled senses per word type
MAX_GLOSS = 58          # a sense label longer than this is a definition, not a label

POS_MAP = {
    "noun": "n.", "verb": "v.", "adj": "adj.", "adv": "adv.", "prep": "prep.",
    "conj": "conj.", "pron": "pron.", "det": "art.", "article": "art.",
    "num": "num.", "intj": "interj.",
}
HAN = re.compile(r"[一-鿿]")


def load_vocab_words():
    src = open(os.path.join(REPO, "words.js"), encoding="utf-8").read()
    entries = json.loads(src[src.index("["):].rstrip().rstrip(";"))
    return {e["w"].strip().lower() for e in entries}


def clean_gloss(text):
    """Wiktionary sense labels carry grammar notes we do not need."""
    text = re.sub(r"^\s*(transitive|intransitive|ambitransitive|reflexive|"
                  r"idiomatic|figurative|figuratively|literally|colloquial|"
                  r"informal|slang|archaic|obsolete|dated|rare|chiefly \w+)\s*[:,]\s*",
                  "", str(text or ""), flags=re.I)
    text = re.sub(r"\s+", " ", text).strip(" .;:")
    return text


def chinese_terms(word):
    """Wiktionary writes Han variants as "壞 /坏"; keep them as separate terms."""
    out = []
    for part in re.split(r"[/,、]", str(word or "")):
        part = part.strip()
        if part and HAN.search(part) and len(part) <= 12:
            out.append(part)
    return out


def main():
    wanted = load_vocab_words()
    table = {}
    seen_lines = kept = 0

    for line in sys.stdin:
        seen_lines += 1
        if seen_lines % 200000 == 0:
            print("  %d lines, %d words so far" % (seen_lines, len(table)), file=sys.stderr)
        # Cheap reject before paying for a JSON parse — most entries have no
        # Chinese translations at all.
        if '"lang": "Chinese' not in line:
            continue
        try:
            entry = json.loads(line)
        except ValueError:
            continue
        word = str(entry.get("word", "")).strip().lower()
        if word not in wanted:
            continue
        label = POS_MAP.get(entry.get("pos"))
        if not label:
            continue

        by_gloss = {}
        for tr in entry.get("translations") or []:
            if "Chinese" not in str(tr.get("lang", "")):
                continue
            gloss = clean_gloss(tr.get("sense"))
            if not gloss or len(gloss) > MAX_GLOSS:
                continue
            terms = chinese_terms(tr.get("word"))
            if not terms:
                continue
            by_gloss.setdefault(gloss, [])
            for t in terms:
                if t not in by_gloss[gloss]:
                    by_gloss[gloss].append(t)

        if not by_gloss:
            continue
        rows = table.setdefault(word, [])
        for gloss, terms in list(by_gloss.items())[:PER_POS]:
            if any(r["p"] == label and r["g"] == gloss for r in rows):
                continue
            rows.append({"p": label, "g": gloss, "z": terms[:4]})
            kept += 1

    # Keep the file honest in size: cap each word, ordered by word type.
    order = ["n.", "v.", "adj.", "adv.", "prep.", "conj.", "pron.", "art.", "num.", "interj."]
    for word, rows in table.items():
        rows.sort(key=lambda r: (order.index(r["p"]) if r["p"] in order else 99, r["g"]))
        del rows[8:]

    blob = json.dumps(table, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    out = os.path.join(REPO, "senses.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(
            "/* Chinese meanings labelled with the sense they belong to.\n"
            "   Generated by tools/build-senses.py from Wiktionary via kaikki.org\n"
            "   (CC BY-SA 4.0). Supplements words.js, which keeps the full flat list.\n"
            "   Do not edit by hand. */\n"
            "window.SENSES = " + blob + ";\n")
    print("wrote %s — %d words, %d labelled senses, %.0f KB"
          % (out, len(table), sum(len(v) for v in table.values()),
             os.path.getsize(out) / 1024))


if __name__ == "__main__":
    main()
